### ISSUE TITLE
merge v7 consensus SNV and CNV files

### ISSUE THREAD

**Issue by jharenza** [PediatricOpenTargets/ticket-tracker#100]
#### What data file(s) does this issue pertain to?
```
s3://kf-openaccess-us-east-1-prd-pbta/open-targets/v7/snv-consensus-plus-hotspots.maf.tsv.gz
https://s3.console.aws.amazon.com/s3/object/kf-openaccess-us-east-1-prd-pbta?region=us-east-1&prefix=open-targets/v6/cnv-controlfreec.tsv.gz
https://s3.console.aws.amazon.com/s3/object/kf-openaccess-us-east-1-prd-pbta?region=us-east-1&prefix=open-targets/v6/cnv-cnvkit.seg.gz
```

#### What release are you using?

v6

#### Put your question or report your issue here.
- Merge v6 SNV consensus MAF (above) with consensus MAFs from TARGET panel and WXS generated [here](https://github.com/d3b-center/bixu-tracker/issues/1150#issuecomment-878290815).
- Merge v6 controlfreeC TSV (above) with controlfreeC output from TARGET panel and WXS generated [here](https://github.com/d3b-center/bixu-tracker/issues/1150#issuecomment-878290815) and PNOC samples as discussed [here](https://github.com/PediatricOpenTargets/ticket-tracker/issues/80). 
- Merge v6 CNVkit seg (above) with CNVkit output from TARGET panel and WXS generated [here](https://github.com/d3b-center/bixu-tracker/issues/1150#issuecomment-878290815) and PNOC samples as discussed [here](https://github.com/PediatricOpenTargets/ticket-tracker/issues/80). 
- Generate md5sums
- Upload to v7 folder: s3://kf-openaccess-us-east-1-prd-pbta/open-targets/v7/
- Update md5sum.txt file in v7 folder

cc @zhangb1 @yuankunzhu

**Comment by zhangb1** [comment]
As the discussion here : https://github.com/PediatricOpenTargets/ticket-tracker/issues/80

I will do the SNV consensus MAF merge for all panel and WXS .

the control-freeC and cnvkit merge will be only WXS  including PNOC03 WXS too.

**Comment by zhangb1** [comment]
merged files has been update in the bucket as long as the md5

```
2021-07-14 16:37:18   32601567 cnv-cnvkit.tsv.gz
2021-07-14 16:38:04   40683174 cnv-controlfreec.tsv.gz
2021-07-14 15:11:12   23260112 fusion-arriba.tsv.gz
2021-07-14 15:12:07    4220942 fusion-starfusion.tsv.gz
2021-07-14 15:12:14  190797366 gene-counts-rsem-expected_count-collapsed.rds
2021-07-14 15:14:51  221856478 gene-counts-rsem-expected_count.rds
2021-07-14 15:17:51  172237164 gene-expression-rsem-tpm-collapsed.rds
2021-07-14 15:20:16  201356546 gene-expression-rsem-tpm.rds
2021-07-15 11:41:16        583 md5sum.txt
2021-07-14 15:36:23  590302840 snv-consensus-plus-hotspots.maf.tsv.gz
```

**Comment by kgaonkar6** [comment]
Thanks @zhangb1! Just noticed that the file `cnv-cnvkit.tsv.gz` should be `cnv-cnvkit.seg.gz` could you please update that in the cwl and s3? Thanks!

**Comment by zhangb1** [comment]
> Thanks @zhangb1! Just noticed that the file `cnv-cnvkit.tsv.gz` should be `cnv-cnvkit.seg.gz` could you please update that in the cwl and s3? Thanks!

done, fixed

**Comment by jharenza** [comment]
closing with [PR 61](https://github.com/PediatricOpenTargets/OpenPedCan-analysis/pull/61)
