### ISSUE TITLE
Create merge RNA-Seq files for v7 (v6 + new TARGET RNA)

### ISSUE THREAD

**Issue by jharenza** [PediatricOpenTargets/ticket-tracker#101]
#### What data file(s) does this issue pertain to?
```
https://s3.console.aws.amazon.com/s3/object/kf-openaccess-us-east-1-prd-pbta?region=us-east-1&prefix=open-targets/v6/fusion-arriba.tsv.gz
https://s3.console.aws.amazon.com/s3/object/kf-openaccess-us-east-1-prd-pbta?region=us-east-1&prefix=open-targets/v6/fusion-starfusion.tsv.gz
https://s3.console.aws.amazon.com/s3/object/kf-openaccess-us-east-1-prd-pbta?region=us-east-1&prefix=open-targets/v6/gene-counts-rsem-expected_count-collapsed.rds
https://s3.console.aws.amazon.com/s3/object/kf-openaccess-us-east-1-prd-pbta?region=us-east-1&prefix=open-targets/v6/gene-expression-rsem-tpm-collapsed.rds
```

#### What release are you using?

v6

#### Put your question or report your issue here.
- Merge each v6 arriba and STAR-Fusion files (above) with respective results from TARGET RNA from #9 
- Merge v6 counts with TARGET RNA counts from #9 
- Merge v6 tpm with TARGET RNA tpm from #9 
- Create collapsed counts files
- Create collapsed TPM files
- Generate md5sums
- Upload to v7 folder: s3://kf-openaccess-us-east-1-prd-pbta/open-targets/v7/ the merged fusion and collapsed rna-seq files 
- Update `md5sum.txt` file in v7 folder

cc @zhangb1 @yuankunzhu

**Comment by zhangb1** [comment]
@jharenza @kgaonkar6 

do we have the v6 `gene-expression-rsem-tpm.rds` and `gene-counts-rsem-expected_count.rds` merged files? 

I need to use those to do the merge to v7 then can generate the collapsed file.

**Comment by kgaonkar6** [comment]
Those files ( PBTA + GMKF ) are in v5 s3://kf-openaccess-us-east-1-prd-pbta/open-targets/v5/.

**Comment by kgaonkar6** [comment]
Just wanted to document here that we didn't maintain `gene-expression-rsem-tpm.rds and gene-counts-rsem-expected_count.rds`  files in v6 since we had the collapsed GTEx (TPM, expected_counts) merged to the collapsed files files directly for data release . 

But since we need these files to iterative merging of KFDRC processed RNA-seq files like we should maintain `gene-expression-rsem-tpm.rds` and `gene-counts-rsem-expected_count.rds` for toolkit.

**Comment by zhangb1** [comment]
@kgaonkar6  Thank you . 

@jharenza another questions, 

1. are we skipping the `gene-expression-rsem-fpkm.rds` ? 
2. all the v5/v6 tpm are all stranded? we don't have the  --library difference for previous version? open target RNAseq samples have stranded and ploy-a.  Do we need to distinguish those?

**Comment by jharenza** [comment]
>are we skipping the gene-expression-rsem-fpkm.rds ?
yes for now, since GTEX does not provide FPKM

>all the v5/v6 tpm are all stranded? we don't have the --library difference for previous version? open target RNAseq samples have stranded and ploy-a. Do we need to distinguish those?

we are not distinguishing - adding all in the single file

**Comment by zhangb1** [comment]
the RNA merged files have been upload in the V7 folder:

will create the md5 after DNA files get updated.

s3://kf-openaccess-us-east-1-prd-pbta/open-targets/v7/

```
2021-07-14 15:11:12   23260112 fusion-arriba.tsv.gz
2021-07-14 15:12:07    4220942 fusion-starfusion.tsv.gz
2021-07-14 15:12:14  190797366 gene-counts-rsem-expected_count-collapsed.rds
2021-07-14 15:14:51  221856478 gene-counts-rsem-expected_count.rds
2021-07-14 15:17:51  172237164 gene-expression-rsem-tpm-collapsed.rds
2021-07-14 15:20:16  201356546 gene-expression-rsem-tpm.rds
```

**Comment by jharenza** [comment]
thanks @zhangb1 ! @kgaonkar6 will you check the histologies file and remove any RNA samples not in the tpm file? perhaps you can pull them out into a separate file we can keep in the v7 folder but not in md5sum in case we add any of those samples later

**Comment by kgaonkar6** [comment]
Cool, will do. We will need to add GTEx to these collapsed files for v7 right?

**Comment by jharenza** [comment]
> Cool, will do. We will need to add GTEx to these collapsed files for v7 right?

yes

**Comment by jharenza** [comment]
Adding that GTEX still needs to be added to the RNA-Seq merge and collapsed files as per https://github.com/d3b-center/d3b-bixu-data-assembly/issues/7

**Comment by jharenza** [comment]
closing with [PR 61](https://github.com/PediatricOpenTargets/OpenPedCan-analysis/pull/61)

**Comment by kgaonkar6** [comment]
tagging @runjin326 to this ticket, I believe  v7 was the last time rnaseq files were merged. Can you check s3://kf-openaccess-us-east-1-prd-pbta/open-targets/v7/ ? The rsem files should have tumor from PBTA+GMKF+TARGET and normal from GTEX
