### ISSUE TITLE
Updated analysis: RUVseq evaluation using differentially expressed housekeeping genes

### ISSUE THREAD

**Issue by aadamk** [PediatricOpenTargets/ticket-tracker#103]
#### What analysis module should be updated and why?

[rna-seq-protocol-ruvseq](https://github.com/PediatricOpenTargets/OpenPedCan-analysis/tree/dev/analyses/rna-seq-protocol-ruvseq)

#### What changes need to be made? Please provide enough detail for another participant to make the update.

Re-evaluate DGE analysis using differentially expressed housekeeping genes [identified by DESeq2](https://github.com/PediatricOpenTargets/OpenPedCan-analysis/blob/dev/analyses/rna-seq-protocol-dge/results/deseq2_rle_normalized/stranded_vs_polya_dge_deseq2_nbinom_wald_test_res.csv) as the [negative control gene set for RUVseq](https://github.com/PediatricOpenTargets/OpenPedCan-analysis/blob/d53b626c4eae5dccc4efdfda0432253b53338713/analyses/rna-seq-protocol-ruvseq/01-protocol-ruvseq.R#L229). 

The negative control gene set can be defined as those from DESeq2 linked above with a `BH FDR` < 0.05. 

The underlying assumption that is being evaluated for this analysis is that DEGs identified from first pass DGE analysis are representative of predominantly technical rather than biological variability, as they are identified from comparisons across technical replicates amongst only HRT atlas genes. Therefore, these genes may represent a more appropriate set for correcting for batch effects. 

The expected output would be to evaluate the p-value histograms for the comparisons specified below to compare to the histograms that are currently part of this module. 

#### What input data should be used? Which data were used in the version being updated?

The data driving the comparisons specified in the readme, namely: 

1. RNA-seq libraries with matching sample_ids:
2. Diffuse intrinsic pontine glioma (DIPG) libraries without matching sample_ids
3. Neuroblastoma (NBL) libraries

#### When do you expect the revised analysis will be completed?

By 7/16? 

#### Who will complete the updated analysis?
@logstar 
cc @taylordm @jharenza @afarrel

**Comment by jharenza** [comment]
Thanks for the ticket @aadamk - we will be holding batch correction until after the end of august portal standup deadline (or sooner if we complete all other deliverables), so wanted to note that here.

**Comment by aadamk** [comment]
Got it, thank you.

**Comment by aadamk** [comment]
Closing to clean up batch correction tickets - feel free to re-open if still needed.
