### ISSUE TITLE
v6 `histologies.tsv` has missing `RNA_library` values for some RNA-Seq samples

### ISSUE THREAD

**Issue by logstar** [PediatricOpenTargets/ticket-tracker#104]
#### What data file(s) does this issue pertain to?

`histologies.tsv`

#### What release are you using?

v6

#### Put your question or report your issue here.

v6 `histologies.tsv` has missing `RNA_library` values for some RNA-Seq samples.

```text
> htl_df <- read_tsv(
+   '../../data/histologies.tsv',
+   col_types = cols(.default = col_guess()),
+   guess_max = 100000)
> 
> # cohorts and RNA_library values for RNA-Seq samples without missing values
> htl_df %>%
+   filter(experimental_strategy == 'RNA-Seq') %>%
+   group_by(cohort, RNA_library) %>%
+   summarise(n = n())
# A tibble: 11 x 3
# Groups:   cohort [5]
   cohort RNA_library         n
   <chr>  <chr>           <int>
 1 GMKF   stranded          208
** 2 GMKF   NA                  1**
 3 GTEx   poly-A          17382
 4 PBTA   poly-A             58
 5 PBTA   stranded          977
 6 TARGET poly-A            200
 7 TARGET poly-A stranded   914
 8 TARGET stranded          253
** 9 TARGET NA                720**
10 TCGA   poly-A          10886
11 TCGA   stranded          151
```

I wonder if these missing values will be replaced in future releases.

**Comment by jharenza** [comment]
@bmennis - can you provide a list of sample IDs and rna library types based on your TARGET RNA run?

**Comment by jharenza** [comment]
cc @zhangb1 and @yuankunzhu

**Comment by bmennis** [comment]
I have the list of samples by aliquot ID followed by the infer experiment results for strands 1 and 2, and last the strandedness for the analysis performed.
[target_rnaseq_nq_sample_strand.txt](https://github.com/PediatricOpenTargets/ticket-tracker/files/6843074/target_rnaseq_nq_sample_strand.txt)

**Comment by jharenza** [comment]
thank you @bmennis! cc @kgaonkar6

**Comment by jharenza** [comment]
closing with [PR 61](https://github.com/PediatricOpenTargets/OpenPedCan-analysis/pull/61)
