### ISSUE TITLE
v6 RNA-Seq count matrix has fewer samples than v4

### ISSUE THREAD

**Issue by logstar** [PediatricOpenTargets/ticket-tracker#105]
#### What data file(s) does this issue pertain to?

`gene-counts-rsem-expected_count-collapsed.rds`

#### What release are you using?

v6

#### Put your question or report your issue here.

v6 `gene-counts-rsem-expected_count-collapsed.rds` has 18,626 samples.

```text
> library(tidyverse)
> htl_df <- read_tsv(
+   '../../data/histologies.tsv',
+   col_types = cols(.default = col_guess()),
+   guess_max = 100000)
> 
> cnt_df <- readRDS('../../data/gene-counts-rsem-expected_count-collapsed.rds')
> htl_df %>%
+   filter(experimental_strategy == 'RNA-Seq') %>%
+   group_by(cohort) %>%
+   summarise(n_samples = n(),
+             n_samples_in_count_df = sum(Kids_First_Biospecimen_ID %in%
+                                           colnames(cnt_df)))
# A tibble: 5 x 3
  cohort n_samples n_samples_in_count_df
  <chr>      <int>                 <int>
1 GMKF         209                   209
2 GTEx       17382                 17382
3 PBTA        1035                  1035
4 TARGET      2087                     0
5 TCGA       11037                     0
> ncol(cnt_df)
[1] 18626
```

v4 `gtex_target_tcga-gene-counts-rsem-expected_count-collapsed.rds` and `gene-counts-rsem-expected_count-collapsed.rds` have 19,891 and 1244 samples respectively. From the mapping files shared by @komalsrathi at <https://github.com/PediatricOpenTargets/ticket-tracker/issues/22#issuecomment-854901528>, it seems that the v6 dropped TARGET and TCGA samples.

```text
$ wc -l input/*mapping.txt
   7864 input/gtex_mapping.txt
   1400 input/target_mapping.txt
  10662 input/tcga_mapping.txt
  19926 total
```

I wonder if the dropped samples in v6 will be added back in future releases.

**Comment by jharenza** [comment]
Hi @logstar! Thanks for checking this. The drops are intentional and we will also likely be dropping additional samples from TARGET, as we are trying to match what is available through the GDC. Past iterations included data downloaded locally, so we are trying to get the right selection here which can be reproducibly downloaded by others as well.
