### ISSUE TITLE
Collapse two cerebellum subgroups to one for GTEX, update blood

### ISSUE THREAD

**Issue by jharenza** [PediatricOpenTargets/ticket-tracker#106]
#### What data file(s) does this issue pertain to?
`histologies.tsv`

#### What release are you using?

v6

#### Put your question or report your issue here.
Since GTEX Uberon codes for cerebellum and cerebellum hemisphere are both for "cerebellum", we will Merge cerebellum hemisphere and cerebellum to `Cerebellum`
Change `Whole Blood` to `Blood` annotation for alphabetization

cc @afarrel @kgaonkar6 @sangeetashukla

**Comment by jharenza** [comment]
@afarrel add any other updates we need to fix in the histologies file here, but for uberon-specific notes, please add to #85

**Comment by afarrel** [comment]
[Uberon-map.xlsx](https://github.com/PediatricOpenTargets/ticket-tracker/files/6816221/Uberon-map.xlsx)

This is the original table comparing GTEx Descriptions, UBERON codes, and UBERON descriptions.

**Comment by jharenza** [comment]
I have done this in #85 , so it remains to be done in the histologies file.

**Comment by jharenza** [comment]
closing with [PR 61](https://github.com/PediatricOpenTargets/OpenPedCan-analysis/pull/61)
