### ISSUE TITLE
v6 histologies.tsv mis-matched sample_type and composition TARGET

### ISSUE THREAD

**Issue by kgaonkar6** [PediatricOpenTargets/ticket-tracker#107]
#### What data file(s) does this issue pertain to?
histologies.tsv 

#### What release are you using?

v6

#### Put your question or report your issue here.
Please update/verify the composition column, it seems to be mis-matched. 

```r
> histology %>% group_by(sample_type,composition) %>% tally()
# A tibble: 10 x 3
# Groups:   sample_type [3]
   sample_type composition                n
   <chr>       <chr>                  <int>
 1 Non-Tumor   NA                         1
 2 Normal      Bone Marrow               72 ***
 3 Normal      Not Reported               7
 4 Normal      Peripheral Whole Blood  2841
 5 Normal      Saliva                   329
 6 Normal      Solid Tissue           17195 **
 7 Tumor       Bone Marrow             1618
 8 Tumor       Derived Cell Line         38
 9 Tumor       Peripheral Whole Blood   449*
10 Tumor       Solid Tissue           14035
> 
```

\* 449 sample_type=="Tumor" have composition "Peripheral Whole Blood" 
**  17195 sample_type=="Normal" have composition=="Solid Tissue" 
*** Not sure if Bone Marrow can be considered as Normal as well.

**Comment by jharenza** [comment]
For the bone marrow, FYI- if these are NBL, the way they determine normal vs tumor marrow is if it has >10% tumor, then it is considered tumor, else, marrow.

The bloods are more concerning - those should all have a suffix of *10*. However, if these are only leukemias showing this blood + tumor, then that makes sense- can you check the tumor histologies @kgaonkar6 ?

**Comment by kgaonkar6** [comment]
The tumor with blood composition are leukemia. 
```r
> histology %>% group_by(sample_type,composition, broad_histology) %>% tally() %>% filter(sample_type=="Tumor", composition=="Peripheral Whole Blood") %>% as.data.frame()
  sample_type            composition              broad_histology   n
1       Tumor Peripheral Whole Blood Acute Lymphoblastic Leukemia 133
2       Tumor Peripheral Whole Blood       Acute myeloid leukemia 151
3       Tumor Peripheral Whole Blood       Acute Myeloid Leukemia 165
```

Can you please expand on this?
> The bloods are more concerning - those should all have a suffix of 10.
