### ISSUE TITLE
v6 histologies.tsv: RNA-Seq added as sample_type==Normal

### ISSUE THREAD

**Issue by kgaonkar6** [PediatricOpenTargets/ticket-tracker#108]
#### What data file(s) does this issue pertain to?
histologies.tsv

#### What release are you using?

v6

#### Put your question or report your issue here.
Please verify if the RNA-Seq added as Normal is correct?

```r
> histology  %>% group_by(experimental_strategy, sample_type) %>% tally()
# A tibble: 9 x 3
# Groups:   experimental_strategy [4]
  experimental_strategy sample_type     n
  <chr>                 <chr>       <int>
1 RNA-Seq               Normal      18118 *
2 RNA-Seq               Tumor       13632
3 Targeted Sequencing   Normal        500
4 Targeted Sequencing   Tumor         500
5 WGS                   Non-Tumor       1
6 WGS                   Normal       1136
7 WGS                   Tumor        1276
8 WXS                   Normal        690
9 WXS                   Tumor         732
```
* 18118 RNA-Seq samples have sample_type=="Normal"

**Comment by jharenza** [comment]
Can you check the cohort on this? I think the majority should be GTEX, and there are a handful of TARGET normal RNAs

**Comment by kgaonkar6** [comment]
ah right, majority are GTEx. 
12 are TARGET and 724 are TCGA

```r
   experimental_strategy sample_type cohort     n
   <chr>                 <chr>       <chr>  <int>
 1 RNA-Seq               Normal      GTEx   17382
 2 RNA-Seq               Normal      TARGET    12
 3 RNA-Seq               Normal      TCGA     724

```

**Comment by ewafula** [comment]
@kgaonkar6 , all`Normal` + `Bone Marrow` samples  are a Neuroblastoma TARGET. That is the info provided in the SRA/dbGap data manifest from @afarrel . It is somewhat  counter intuitive that Normals are classified as Neuroblastoma but  @jharenza's point make sense if they are <10% tumors.

**Comment by kgaonkar6** [comment]
Thanks both! Can we do a quick check on the TCGA RNA-Seq which are annotated as "Normal", is that also expected ?

**Comment by jharenza** [comment]
This is expected, as per OGC codes [here](https://ocg.cancer.gov/sites/default/files/OCG-Project-Codes_Tissues-and-Samples_03-02-2021.pdf), the suffixes 10 and 11 are normal blood and tissue, respectively.

```
> hist %>%
+   filter(cohort == "TCGA" & sample_type == "Normal") %>%
+   filter(grepl(pattern = "-11A-|-10A-|-11B-|-10B-|-11R-", Kids_First_Biospecimen_ID)) %>%
+   tally()
# A tibble: 1 x 1
      n
  <int>
1   724
```
