### ISSUE TITLE
v6 histologies.tsv add broad_tumor_descriptor

### ISSUE THREAD

**Issue by kgaonkar6** [PediatricOpenTargets/ticket-tracker#109]
#### What data file(s) does this issue pertain to?
histologies.tsv

#### What release are you using?

v6

#### Put your question or report your issue here.
Add `broad_tumor_descriptor` with values `diagnosis` and `relapse` that will be used as annotation for pedbio and output files.

```r
broad_tumor_descriptor= case_when( tumor_descriptor %in% c("Initial CNS Tumor", "Primary Tumor") ~ "diagnosis",
    tumor_descriptor %in% c("Recurrence", "Progressive", "Progressive Disease Post Mortem") ~ "relapse")
 ```

**Comment by jharenza** [comment]
closing with [PR 61](https://github.com/PediatricOpenTargets/OpenPedCan-analysis/pull/61)
