### ISSUE TITLE
Updated analysis: tumor-gtex-plots - add table of api calls per plot

### ISSUE THREAD

**Issue by jharenza** [PediatricOpenTargets/ticket-tracker#110]
#### What analysis module should be updated and why?
`tumor-gtex-plots`

#### What changes need to be made? Please provide enough detail for another participant to make the update.
- Migrate R Shiny app from DBHI server to `https://d3b-rstudio-connect-public-prd.d3b.io/connect`
- Create an api with _https://www.rplumber.io/_
- In `metadata.tsv`, replace `plot_fname` with `plot_api_call` 
- Archive plot generation/export code from this PR
- We will also have to combine tables, but that, along with a few other updates, I will add to a separate ticket.

#### What input data should be used? Which data were used in the version being updated?
v6

#### When do you expect the revised analysis will be completed?
as soon as possible

#### Who will complete the updated analysis?
@komalsrathi

**Comment by komalsrathi** [comment]
@jharenza can we close as @logstar is tackling this now?
