### ISSUE TITLE
Updated analysis: assess CNV amplification and deep deletion threshold in TARGET and GMKF data

### ISSUE THREAD

**Issue by jharenza** [PediatricOpenTargets/ticket-tracker#113]
#### What analysis module should be updated and why?
focal-cn-preparation

Either before or once v7 is released, assess amplification threshold of TARGET WXS CNVs using MYCN status (molecular_subtype). Typically, MYCN amplification is called when there are 8-10+ copies of the gene and our current amplification thresholds may be a bit low for this. So, assess what is called vs what is subtyped as amplified or non-amplified.

For deep deletions, we can assess CDNK2A for ALL (though this piece will come in v8).

#### What changes need to be made? Please provide enough detail for another participant to make the update.
See above

#### What input data should be used? Which data were used in the version being updated?
Consensus CNV file, histologies file

#### When do you expect the revised analysis will be completed?
1-2 weeks

#### Who will complete the updated analysis?
@kgaonkar6

**Comment by jharenza** [comment]
assigning to @ewafula cc @afarrel 

@ewafula you can make a branch off of this PR to work on this: https://github.com/PediatricOpenTargets/OpenPedCan-analysis/pull/89

**Comment by taylordm** [comment]
Next step: Wait for new CNV method comparison by Alvin, can run multi-CNV on NB data , and do the same comparison with the old CNV calls. In progress with Brian E.

**Comment by jharenza** [comment]
This was addressed in https://github.com/PediatricOpenTargets/OpenPedCan-analysis/pull/264
