### ISSUE TITLE
Updated analysis: copy_number_consensus_call and focal-cn-file-preparation rerun for OT subtyping 

### ISSUE THREAD

**Issue by kgaonkar6** [PediatricOpenTargets/ticket-tracker#114]
#### What analysis module should be updated and why?
We need to rerun focal-cn-file-preparation for subtyping with every new sampleset added for subtyping. 

#### What changes need to be made? Please provide enough detail for another participant to make the update.
For consensus cnv [run_consensus_cal.sh](https://github.com/PediatricOpenTargets/OpenPedCan-analysis/blob/dev/analyses/copy_number_consensus_call/run_consensus_call.sh)
For focal WGS copy number calls [run-prepare-cn-OpenTarget.sh](https://github.com/PediatricOpenTargets/OpenPedCan-analysis/blob/dev/analyses/focal-cn-file-preparation/run-prepare-cn-OpenTarget.sh)
For WXS only use annotated cnvkit calls from the output of the script below
`RUN_ORIGINAL=1 bash analyses/focal-cn-file-preparation/run-prepare-cn-OpenTarget.sh`

#### What input data should be used? Which data were used in the version being updated?
sv-manta.tsv.gz
cnv-cnvkit.seg.gz
cnv-controlfreec.tsv.gz

#### When do you expect the revised analysis will be completed?
1-2 days

**Comment by runjin326** [comment]
@kgaonkar6, I guess this issue would now be taken cared of by bixops team? And for each release, we just need to make sure to run sub typing *after* the focal-cn is complete?

**Comment by kgaonkar6** [comment]
Yes that's right! We will have the most up-to-date focal-cn files in the data download from bix-ops and we will have to rerun subtyping per release.

**Comment by runjin326** [comment]
Closing - this is currently taken cared of by bioengineering team and no longer needs to be run in repo.
