### ISSUE TITLE
Updated analysis: run-gistic for OT subtyping 

### ISSUE THREAD

**Issue by kgaonkar6** [PediatricOpenTargets/ticket-tracker#115]
#### What analysis module should be updated and why?
run-gistic module needs to be updated to run on filenames for OpenPedCan

#### What changes need to be made? Please provide enough detail for another participant to make the update.
Change `pbta-cnv-consensus.seg.gz` to `cnv-consensus.seg.gz`  and `pbta-histologies.tsv` to `histologies.tsv` in [run-gistic-module.sh])https://github.com/PediatricOpenTargets/OpenPedCan-analysis/blob/dev/analyses/run-gistic/run-gistic-module.sh)

#### What input data should be used? Which data were used in the version being updated?
cnv-consensus.seg.gz
histologies.tsv

#### When do you expect the revised analysis will be completed?
1-2 days

**Comment by runjin326** [comment]
@kgaonkar6, I am not that familiar with GISTIC but does it take WXS samples as well? If so, should we then modify the code to take both `cnv-consensus.seg.gz` and `cnv-cnvkit.seg.gz` and generate results for WGS using the consensus and WXS with the cnvkit?

**Comment by kgaonkar6** [comment]
hmm good point , I think GISTIC will run successfully using cnv-consensus.seg.gz and cnv-cnvkit.seg.gz

**Comment by runjin326** [comment]
Ok! I will update to let it take both files then ;) thanks!

**Comment by runjin326** [comment]
Closing with [PR119](https://github.com/PediatricOpenTargets/OpenPedCan-analysis/pull/119) merged.
