### ISSUE TITLE
Updated analysis: tumor-gtex-plots - collapse tables

### ISSUE THREAD

**Issue by jharenza** [PediatricOpenTargets/ticket-tracker#119]
#### What analysis module should be updated and why?
`tumor-gtex-plots`

#### What changes need to be made? Please provide enough detail for another participant to make the update.
FNL would like two long tables for each analysis type (cohort+cancer_group and cancer_group). The tables should look something like this (eg for `cancer_group` table, for which we will use `all_cohorts` as the cohort):

| gene | ENSG_id | cohort      | cancer_group    | x_labels                                            | mean  | median | sd    | efo_code | mondo_code | uberon_code | plot_api |
|------|---------|-------------|-----------------|-----------------------------------------------------|-------|--------|-------|----------|------------|-------------|----------|
| GPC2 |         | all_cohorts | Neuroblastoma   | Neuroblastoma (N = 211)                             | 27.57 | 26.32  | 15.88 |          |            |             | X_api    |
| GPC2 |         | all_cohorts | Neuroblastoma   | Adipose - Subcutaneous (N = 663)                    | 1.76  | 1.66   | 0.82  |          |            |             | X_api    |
| GPC2 |         | all_cohorts | Neuroblastoma   | Adipose - Visceral (Omentum) (N = 541)              | 1.2   | 1.04   | 0.65  |          |            |             | X_api    |
| GPC2 |         | all_cohorts | Neuroblastoma   | Adrenal Gland (N = 258)                             | 0.72  | 0.63   | 0.36  |          |            |             | X_api    |
| GPC2 |         | all_cohorts | Neuroblastoma   | Artery - Aorta (N = 432)                            | 1.45  | 1.3    | 0.74  |          |            |             | X_api    |
| GPC2 |         | all_cohorts | Neuroblastoma   | Artery - Coronary (N = 240)                         | 1.37  | 1.14   | 0.95  |          |            |             | X_api    |
| GPC2 |         | all_cohorts | Neuroblastoma   | Artery - Tibial (N = 663)                           | 0.75  | 0.61   | 0.59  |          |            |             | X_api    |
| GPC2 |         | all_cohorts | Neuroblastoma   | Bladder (N = 21)                                    | 1.98  | 1.85   | 1.25  |          |            |             | X_api    |
| GPC2 |         | all_cohorts | Neuroblastoma   | Brain - Amygdala (N = 152)                          | 2.29  | 2.22   | 0.86  |          |            |             | X_api    |
| GPC2 |         | all_cohorts | Neuroblastoma   | Brain - Anterior cingulate cortex (BA24) (N = 176)  | 1.86  | 1.78   | 0.65  |          |            |             | X_api    |
| GPC2 |         | all_cohorts | Neuroblastoma   | Brain - Caudate (basal ganglia) (N = 246)           | 1.35  | 1.35   | 0.5   |          |            |             | X_api    |
| GPC2 |         | all_cohorts | Neuroblastoma   | Brain - Cerebellar Hemisphere (N = 215)             | 3.12  | 2.79   | 1.83  |          |            |             | X_api    |
| GPC2 |         | all_cohorts | Neuroblastoma   | Brain - Cerebellum (N = 241)                        | 3.27  | 2.77   | 1.98  |          |            |             | X_api    |
| GPC2 |         | all_cohorts | Neuroblastoma   | Brain - Cortex (N = 255)                            | 1.63  | 1.53   | 0.57  |          |            |             | X_api    |
| GPC2 |         | all_cohorts | Neuroblastoma   | Brain - Frontal Cortex (BA9) (N = 209)              | 1.61  | 1.56   | 0.59  |          |            |             | X_api    |
| GPC2 |         | all_cohorts | Neuroblastoma   | Brain - Hippocampus (N = 197)                       | 2.21  | 2.09   | 1     |          |            |             | X_api    |
| GPC2 |         | all_cohorts | Neuroblastoma   | Brain - Hypothalamus (N = 202)                      | 1.58  | 1.45   | 0.83  |          |            |             | X_api    |
| GPC2 |         | all_cohorts | Neuroblastoma   | Brain - Nucleus accumbens (basal ganglia) (N = 246) | 1.36  | 1.28   | 0.69  |          |            |             | X_api    |
| GPC2 |         | all_cohorts | Neuroblastoma   | Brain - Putamen (basal ganglia) (N = 205)           | 1.32  | 1.24   | 0.58  |          |            |             | X_api    |
| GPC2 |         | all_cohorts | Neuroblastoma   | Brain - Spinal cord (cervical c-1) (N = 159)        | 3.34  | 3.2    | 1.52  |          |            |             | X_api    |
| GPC2 |         | all_cohorts | Neuroblastoma   | Brain - Substantia nigra (N = 139)                  | 1.74  | 1.59   | 0.96  |          |            |             | X_api    |
| GPC2 |         | all_cohorts | Neuroblastoma   | Breast - Mammary Tissue (N = 459)                   | 2.27  | 1.88   | 1.62  |          |            |             | X_api    |
| GPC2 |         | all_cohorts | Neuroblastoma   | Cells - Cultured fibroblasts (N = 504)              | 1.3   | 1.21   | 0.6   |          |            |             | X_api    |
| GPC2 |         | all_cohorts | Neuroblastoma   | Cells - EBV-transformed lymphocytes (N = 174)       | 2.61  | 2.33   | 1.56  |          |            |             | X_api    |
| GPC2 |         | all_cohorts | Neuroblastoma   | Cervix - Ectocervix (N = 9)                         | 4.63  | 3.68   | 2.91  |          |            |             | X_api    |
| GPC2 |         | all_cohorts | Neuroblastoma   | Cervix - Endocervix (N = 10)                        | 5.14  | 3.64   | 4.09  |          |            |             | X_api    |
| GPC2 |         | all_cohorts | Neuroblastoma   | Colon - Sigmoid (N = 373)                           | 1.67  | 1.55   | 0.83  |          |            |             | X_api    |
| GPC2 |         | all_cohorts | Neuroblastoma   | Colon - Transverse (N = 406)                        | 2.02  | 1.92   | 0.87  |          |            |             | X_api    |
| GPC2 |         | all_cohorts | Neuroblastoma   | Esophagus - Gastroesophageal Junction (N = 375)     | 1.13  | 0.99   | 0.61  |          |            |             | X_api    |
| GPC2 |         | all_cohorts | Neuroblastoma   | Esophagus - Mucosa (N = 555)                        | 1.16  | 1.04   | 0.59  |          |            |             | X_api    |
| GPC2 |         | all_cohorts | Neuroblastoma   | Esophagus - Muscularis (N = 515)                    | 1.19  | 1.05   | 0.65  |          |            |             | X_api    |
| GPC2 |         | all_cohorts | Neuroblastoma   | Fallopian Tube (N = 9)                              | 3.32  | 2.8    | 1.75  |          |            |             | X_api    |
| GPC2 |         | all_cohorts | Neuroblastoma   | Heart - Atrial Appendage (N = 429)                  | 0.63  | 0.56   | 0.36  |          |            |             | X_api    |
| GPC2 |         | all_cohorts | Neuroblastoma   | Heart - Left Ventricle (N = 432)                    | 0.44  | 0.34   | 0.42  |          |            |             | X_api    |
| GPC2 |         | all_cohorts | Neuroblastoma   | Kidney - Cortex (N = 85)                            | 0.66  | 0.48   | 0.75  |          |            |             | X_api    |
| GPC2 |         | all_cohorts | Neuroblastoma   | Liver (N = 226)                                     | 0.17  | 0.12   | 0.2   |          |            |             | X_api    |
| GPC2 |         | all_cohorts | Neuroblastoma   | Lung (N = 578)                                      | 1.52  | 1.31   | 1.01  |          |            |             | X_api    |
| GPC2 |         | all_cohorts | Neuroblastoma   | Minor Salivary Gland (N = 162)                      | 2.06  | 1.84   | 1.2   |          |            |             | X_api    |
| GPC2 |         | all_cohorts | Neuroblastoma   | Muscle - Skeletal (N = 803)                         | 0.45  | 0.34   | 0.4   |          |            |             | X_api    |
| GPC2 |         | all_cohorts | Neuroblastoma   | Nerve - Tibial (N = 619)                            | 3     | 2.89   | 1.11  |          |            |             | X_api    |
| GPC2 |         | all_cohorts | Neuroblastoma   | Ovary (N = 180)                                     | 5.42  | 4.51   | 3.52  |          |            |             | X_api    |
| GPC2 |         | all_cohorts | Neuroblastoma   | Pancreas (N = 328)                                  | 0.33  | 0.26   | 0.32  |          |            |             | X_api    |
| GPC2 |         | all_cohorts | Neuroblastoma   | Pituitary (N = 283)                                 | 2.24  | 2.04   | 1.12  |          |            |             | X_api    |
| GPC2 |         | all_cohorts | Neuroblastoma   | Prostate (N = 245)                                  | 2.24  | 2.08   | 1.05  |          |            |             | X_api    |
| GPC2 |         | all_cohorts | Neuroblastoma   | Skin - Not Sun Exposed (Suprapubic) (N = 604)       | 13.99 | 13.12  | 6.07  |          |            |             | X_api    |
| GPC2 |         | all_cohorts | Neuroblastoma   | Skin - Sun Exposed (Lower leg) (N = 701)            | 10.98 | 10.5   | 4.54  |          |            |             | X_api    |
| GPC2 |         | all_cohorts | Neuroblastoma   | Small Intestine - Terminal Ileum (N = 187)          | 2.74  | 2.13   | 2     |          |            |             | X_api    |
| GPC2 |         | all_cohorts | Neuroblastoma   | Spleen (N = 241)                                    | 3.1   | 2.8    | 1.43  |          |            |             | X_api    |
| GPC2 |         | all_cohorts | Neuroblastoma   | Stomach (N = 359)                                   | 0.76  | 0.65   | 0.46  |          |            |             | X_api    |
| GPC2 |         | all_cohorts | Neuroblastoma   | Testis (N = 361)                                    | 32.59 | 32.61  | 10.03 |          |            |             | X_api    |
| GPC2 |         | all_cohorts | Neuroblastoma   | Thyroid (N = 653)                                   | 1.07  | 0.95   | 0.6   |          |            |             | X_api    |
| GPC2 |         | all_cohorts | Neuroblastoma   | Uterus (N = 142)                                    | 6.07  | 4.65   | 4.41  |          |            |             | X_api    |
| GPC2 |         | all_cohorts | Neuroblastoma   | Vagina (N = 156)                                    | 3.16  | 2.98   | 1.37  |          |            |             | X_api    |
| GPC2 |         | all_cohorts | Neuroblastoma   | Whole Blood (N = 755)                               | 1.04  | 0.8    | 1.81  |          |            |             | X_api    |
| GPC2 |         | all_cohorts | Medulloblastoma | Medulloblastoma (N = 122)                           | 27.58 | 23.85  | 18.41 |          |            |             | y_api    |
| GPC2 |         | all_cohorts | Medulloblastoma | Adipose - Subcutaneous (N = 663)                    | 1.76  | 1.66   | 0.82  |          |            |             | y_api    |
| GPC2 |         | all_cohorts | Medulloblastoma | Adipose - Visceral (Omentum) (N = 541)              | 1.2   | 1.04   | 0.65  |          |            |             | y_api    |
| GPC2 |         | all_cohorts | Medulloblastoma | Adrenal Gland (N = 258)                             | 0.72  | 0.63   | 0.36  |          |            |             | y_api    |
| GPC2 |         | all_cohorts | Medulloblastoma | Artery - Aorta (N = 432)                            | 1.45  | 1.3    | 0.74  |          |            |             | y_api    |
| GPC2 |         | all_cohorts | Medulloblastoma | Artery - Coronary (N = 240)                         | 1.37  | 1.14   | 0.95  |          |            |             | y_api    |
| GPC2 |         | all_cohorts | Medulloblastoma | Artery - Tibial (N = 663)                           | 0.75  | 0.61   | 0.59  |          |            |             | y_api    |
| GPC2 |         | all_cohorts | Medulloblastoma | Bladder (N = 21)                                    | 1.98  | 1.85   | 1.25  |          |            |             | y_api    |
| GPC2 |         | all_cohorts | Medulloblastoma | Brain - Amygdala (N = 152)                          | 2.29  | 2.22   | 0.86  |          |            |             | y_api    |
| GPC2 |         | all_cohorts | Medulloblastoma | Brain - Anterior cingulate cortex (BA24) (N = 176)  | 1.86  | 1.78   | 0.65  |          |            |             | y_api    |
| GPC2 |         | all_cohorts | Medulloblastoma | Brain - Caudate (basal ganglia) (N = 246)           | 1.35  | 1.35   | 0.5   |          |            |             | y_api    |
| GPC2 |         | all_cohorts | Medulloblastoma | Brain - Cerebellar Hemisphere (N = 215)             | 3.12  | 2.79   | 1.83  |          |            |             | y_api    |
| GPC2 |         | all_cohorts | Medulloblastoma | Brain - Cerebellum (N = 241)                        | 3.27  | 2.77   | 1.98  |          |            |             | y_api    |
| GPC2 |         | all_cohorts | Medulloblastoma | Brain - Cortex (N = 255)                            | 1.63  | 1.53   | 0.57  |          |            |             | y_api    |
| GPC2 |         | all_cohorts | Medulloblastoma | Brain - Frontal Cortex (BA9) (N = 209)              | 1.61  | 1.56   | 0.59  |          |            |             | y_api    |
| GPC2 |         | all_cohorts | Medulloblastoma | Brain - Hippocampus (N = 197)                       | 2.21  | 2.09   | 1     |          |            |             | y_api    |
| GPC2 |         | all_cohorts | Medulloblastoma | Brain - Hypothalamus (N = 202)                      | 1.58  | 1.45   | 0.83  |          |            |             | y_api    |
| GPC2 |         | all_cohorts | Medulloblastoma | Brain - Nucleus accumbens (basal ganglia) (N = 246) | 1.36  | 1.28   | 0.69  |          |            |             | y_api    |
| GPC2 |         | all_cohorts | Medulloblastoma | Brain - Putamen (basal ganglia) (N = 205)           | 1.32  | 1.24   | 0.58  |          |            |             | y_api    |
| GPC2 |         | all_cohorts | Medulloblastoma | Brain - Spinal cord (cervical c-1) (N = 159)        | 3.34  | 3.2    | 1.52  |          |            |             | y_api    |
| GPC2 |         | all_cohorts | Medulloblastoma | Brain - Substantia nigra (N = 139)                  | 1.74  | 1.59   | 0.96  |          |            |             | y_api    |
| GPC2 |         | all_cohorts | Medulloblastoma | Breast - Mammary Tissue (N = 459)                   | 2.27  | 1.88   | 1.62  |          |            |             | y_api    |
| GPC2 |         | all_cohorts | Medulloblastoma | Cells - Cultured fibroblasts (N = 504)              | 1.3   | 1.21   | 0.6   |          |            |             | y_api    |
| GPC2 |         | all_cohorts | Medulloblastoma | Cells - EBV-transformed lymphocytes (N = 174)       | 2.61  | 2.33   | 1.56  |          |            |             | y_api    |
| GPC2 |         | all_cohorts | Medulloblastoma | Cervix - Ectocervix (N = 9)                         | 4.63  | 3.68   | 2.91  |          |            |             | y_api    |
| GPC2 |         | all_cohorts | Medulloblastoma | Cervix - Endocervix (N = 10)                        | 5.14  | 3.64   | 4.09  |          |            |             | y_api    |
| GPC2 |         | all_cohorts | Medulloblastoma | Colon - Sigmoid (N = 373)                           | 1.67  | 1.55   | 0.83  |          |            |             | y_api    |
| GPC2 |         | all_cohorts | Medulloblastoma | Colon - Transverse (N = 406)                        | 2.02  | 1.92   | 0.87  |          |            |             | y_api    |
| GPC2 |         | all_cohorts | Medulloblastoma | Esophagus - Gastroesophageal Junction (N = 375)     | 1.13  | 0.99   | 0.61  |          |            |             | y_api    |
| GPC2 |         | all_cohorts | Medulloblastoma | Esophagus - Mucosa (N = 555)                        | 1.16  | 1.04   | 0.59  |          |            |             | y_api    |
| GPC2 |         | all_cohorts | Medulloblastoma | Esophagus - Muscularis (N = 515)                    | 1.19  | 1.05   | 0.65  |          |            |             | y_api    |
| GPC2 |         | all_cohorts | Medulloblastoma | Fallopian Tube (N = 9)                              | 3.32  | 2.8    | 1.75  |          |            |             | y_api    |
| GPC2 |         | all_cohorts | Medulloblastoma | Heart - Atrial Appendage (N = 429)                  | 0.63  | 0.56   | 0.36  |          |            |             | y_api    |
| GPC2 |         | all_cohorts | Medulloblastoma | Heart - Left Ventricle (N = 432)                    | 0.44  | 0.34   | 0.42  |          |            |             | y_api    |
| GPC2 |         | all_cohorts | Medulloblastoma | Kidney - Cortex (N = 85)                            | 0.66  | 0.48   | 0.75  |          |            |             | y_api    |
| GPC2 |         | all_cohorts | Medulloblastoma | Liver (N = 226)                                     | 0.17  | 0.12   | 0.2   |          |            |             | y_api    |
| GPC2 |         | all_cohorts | Medulloblastoma | Lung (N = 578)                                      | 1.52  | 1.31   | 1.01  |          |            |             | y_api    |
| GPC2 |         | all_cohorts | Medulloblastoma | Minor Salivary Gland (N = 162)                      | 2.06  | 1.84   | 1.2   |          |            |             | y_api    |
| GPC2 |         | all_cohorts | Medulloblastoma | Muscle - Skeletal (N = 803)                         | 0.45  | 0.34   | 0.4   |          |            |             | y_api    |
| GPC2 |         | all_cohorts | Medulloblastoma | Nerve - Tibial (N = 619)                            | 3     | 2.89   | 1.11  |          |            |             | y_api    |
| GPC2 |         | all_cohorts | Medulloblastoma | Ovary (N = 180)                                     | 5.42  | 4.51   | 3.52  |          |            |             | y_api    |
| GPC2 |         | all_cohorts | Medulloblastoma | Pancreas (N = 328)                                  | 0.33  | 0.26   | 0.32  |          |            |             | y_api    |
| GPC2 |         | all_cohorts | Medulloblastoma | Pituitary (N = 283)                                 | 2.24  | 2.04   | 1.12  |          |            |             | y_api    |
| GPC2 |         | all_cohorts | Medulloblastoma | Prostate (N = 245)                                  | 2.24  | 2.08   | 1.05  |          |            |             | y_api    |
| GPC2 |         | all_cohorts | Medulloblastoma | Skin - Not Sun Exposed (Suprapubic) (N = 604)       | 13.99 | 13.12  | 6.07  |          |            |             | y_api    |
| GPC2 |         | all_cohorts | Medulloblastoma | Skin - Sun Exposed (Lower leg) (N = 701)            | 10.98 | 10.5   | 4.54  |          |            |             | y_api    |
| GPC2 |         | all_cohorts | Medulloblastoma | Small Intestine - Terminal Ileum (N = 187)          | 2.74  | 2.13   | 2     |          |            |             | y_api    |
| GPC2 |         | all_cohorts | Medulloblastoma | Spleen (N = 241)                                    | 3.1   | 2.8    | 1.43  |          |            |             | y_api    |
| GPC2 |         | all_cohorts | Medulloblastoma | Stomach (N = 359)                                   | 0.76  | 0.65   | 0.46  |          |            |             | y_api    |
| GPC2 |         | all_cohorts | Medulloblastoma | Testis (N = 361)                                    | 32.59 | 32.61  | 10.03 |          |            |             | y_api    |
| GPC2 |         | all_cohorts | Medulloblastoma | Thyroid (N = 653)                                   | 1.07  | 0.95   | 0.6   |          |            |             | y_api    |
| GPC2 |         | all_cohorts | Medulloblastoma | Uterus (N = 142)                                    | 6.07  | 4.65   | 4.41  |          |            |             | y_api    |
| GPC2 |         | all_cohorts | Medulloblastoma | Vagina (N = 156)                                    | 3.16  | 2.98   | 1.37  |          |            |             | y_api    |
| GPC2 |         | all_cohorts | Medulloblastoma | Whole Blood (N = 755)                               | 1.04  | 0.8    | 1.81  |          |            |             | y_api    |

also pasting an excel example for whichever is easier for you.
[mock_all_cohort_tpm_plot_data.xlsx](https://github.com/PediatricOpenTargets/ticket-tracker/files/6843876/mock_all_cohort_tpm_plot_data.xlsx)

where `ENSG_id`, `efo_code`, `mondo_code`, and `uberon_code` will be added later, after #112 is completed and where `plot_api` is the api link to each plot

#### What input data should be used? Which data were used in the version being updated?
```
gene-expression-rsem-tpm-collapsed.rds 
histologies.tsv
```

#### When do you expect the revised analysis will be completed?
this week?

#### Who will complete the updated analysis?
@komalsrathi

**Comment by komalsrathi** [comment]
@jharenza is this instead of the `metadata.tsv` file?

**Comment by jharenza** [comment]
> @jharenza is this instead of the `metadata.tsv` file or instead of individual tsv files corresponding to the plots? If the latter, then should we keep the `metadata.tsv` file?

This would be instead of all tables - so you would just have two tables at the end, one cohort+cancer_group for all genes and all plots, along with api links and then one cancer_group with cohort being `all_cohorts` for all genes and all plots with api links. They will somehow enable export of the tables from the long format table (guessing based on api link).

**Comment by jharenza** [comment]
closing this, as we do not want to implement
