### ISSUE TITLE
Proposed Analysis: cluster TCGA/GTEX/TARGET RNA-Seq +/- batch correction

### ISSUE THREAD

**Issue by jharenza** [PediatricOpenTargets/ticket-tracker#12]
#### What are the scientific goals of the analysis?
To determine whether these three datasets, while all polyA, need batch correction by dataset.

#### What methods do you plan to use to accomplish the scientific goals?
Plot either uMAP or tSNE by dataset to determine whether they cluster by dataset. If they do, perform batch correction and re-plot.

#### What input data are required for this analysis?
TPM for GTEX, TCGA, TARGET

#### How long do you expect is needed to complete the analysis? Will it be a multi-step analysis?
0.5 day

#### Who will complete the analysis (please add a GitHub handle here if relevant)?
@komalsrathi 

#### What relevant scientific literature relates to this analysis?
NA

Note: these files aren't in the release yet (per #11), so this does not need to be a module

**Comment by komalsrathi** [comment]
@jharenza I'll be adding these to the batch correction module (won't push the combined uncorrected + corrected matrices to github but only to s3 bucket as they are large) but for your reference these are the plots that will be generated and pushed as part of the module:

1. `GTEx + TARGET NBL`:

UMAP (t-SNE is taking a lot of time, so I can add those later) of top 10% most variable + house keeping genes. Points are colored by `group` and shape is `batch`:

[gtex-target-nbl-gene-expression-rsem-tpm-collapsed.polya_umap.pdf](https://github.com/PediatricOpenTargets/ticket-tracker/files/6503785/gtex-target-nbl-gene-expression-rsem-tpm-collapsed.polya_umap.pdf)

Density plots only of house keeping genes:

[gtex-target-nbl-gene-expression-rsem-tpm-collapsed.polya_density.pdf](https://github.com/PediatricOpenTargets/ticket-tracker/files/6503786/gtex-target-nbl-gene-expression-rsem-tpm-collapsed.polya_density.pdf)

2. `GTEx + TARGET`:

UMAP:

[gtex-target-gene-expression-rsem-tpm-collapsed_umap.pdf](https://github.com/PediatricOpenTargets/ticket-tracker/files/6503789/gtex-target-gene-expression-rsem-tpm-collapsed_umap.pdf)

Density plots:
[gtex-target-gene-expression-rsem-tpm-collapsed_density.pdf](https://github.com/PediatricOpenTargets/ticket-tracker/files/6503790/gtex-target-gene-expression-rsem-tpm-collapsed_density.pdf)

Some issues to address: having trouble with adding black borders - needs `pch > 20` but if I do that, the legend does not show up correctly. Will work on that but hopefully you can use these for tomorrow without issues.

**Comment by komalsrathi** [comment]
Actually I was able to resolve the issue so I will upload the new plots soon. Thanks for your patience.

**Comment by jharenza** [comment]
Thanks @komalsrathi this looks great. It also looks like TARGET polyA and GTEX polyA largely overlap in the density plots before batch correction, so I am leaning toward not correcting for dataset in this case. Could you also generate one more density plot/UMAP for correction only by library?

**Comment by jharenza** [comment]
>t-SNE is taking a lot of time, so I can add those later

UMAP is fine here, no worries about adding tSNE

**Comment by komalsrathi** [comment]
> Thanks @komalsrathi this looks great. It also looks like TARGET polyA and GTEX polyA largely overlap in the density plots before batch correction, so I am leaning toward not correcting for dataset in this case. Could you also generate one more density plot/UMAP for correction only by library?

Yes sounds good

**Comment by komalsrathi** [comment]
Here is what I have until now:

GTEx + TARGET (correct by default i.e. study + library)
[gtex-target-gene-expression-rsem-tpm-collapsed_density.pdf](https://github.com/PediatricOpenTargets/ticket-tracker/files/6504528/gtex-target-gene-expression-rsem-tpm-collapsed_density.pdf)
[gtex-target-gene-expression-rsem-tpm-collapsed_umap.pdf](https://github.com/PediatricOpenTargets/ticket-tracker/files/6504529/gtex-target-gene-expression-rsem-tpm-collapsed_umap.pdf)

GTEx + TARGET (correct by library only)
[gtex-target-gene-expression-rsem-tpm-collapsed-libraryonly_umap.pdf](https://github.com/PediatricOpenTargets/ticket-tracker/files/6504532/gtex-target-gene-expression-rsem-tpm-collapsed-libraryonly_umap.pdf)
[gtex-target-gene-expression-rsem-tpm-collapsed-libraryonly_density.pdf](https://github.com/PediatricOpenTargets/ticket-tracker/files/6504531/gtex-target-gene-expression-rsem-tpm-collapsed-libraryonly_density.pdf)

GTEx + TARGET NBL (correct by default i.e. study + library)
[gtex-target-nbl-gene-expression-rsem-tpm-collapsed.polya_density.pdf](https://github.com/PediatricOpenTargets/ticket-tracker/files/6504533/gtex-target-nbl-gene-expression-rsem-tpm-collapsed.polya_density.pdf)
[gtex-target-nbl-gene-expression-rsem-tpm-collapsed.polya_umap.pdf](https://github.com/PediatricOpenTargets/ticket-tracker/files/6504534/gtex-target-nbl-gene-expression-rsem-tpm-collapsed.polya_umap.pdf)

GTEx + GMKF NBL (correct by default i.e. study + library)
[gtex-kfnbl-gene-expression-rsem-tpm-collapsed_umap.pdf](https://github.com/PediatricOpenTargets/ticket-tracker/files/6504527/gtex-kfnbl-gene-expression-rsem-tpm-collapsed_umap.pdf)
[gtex-kfnbl-gene-expression-rsem-tpm-collapsed_density.pdf](https://github.com/PediatricOpenTargets/ticket-tracker/files/6504526/gtex-kfnbl-gene-expression-rsem-tpm-collapsed_density.pdf)

**Comment by jharenza** [comment]
great, thank you
