### ISSUE TITLE
Histology file miss tumor_ploidy information

### ISSUE THREAD

**Issue by runjin326** [PediatricOpenTargets/ticket-tracker#121]
#### What data file(s) does this issue pertain to?
histologies.tsv

#### What release are you using?

v6 

#### Put your question or report your issue here.
When using the v7 `cnv-cnvkit.seg.gz` to update CNV annotation for WXS specimens [for this ticket](https://github.com/PediatricOpenTargets/ticket-tracker/issues/102) out of the 1561 samples in the CNV file, only 940 of them have tumor_ploidy information.
Looking more in detail, realized that "Targeted Sequencing" and "WXS" specimens both do not have tumor_ploidy information: 
`> histologies_df %>% filter(experimental_strategy != "RNA-Seq") %>% filter(sample_type == "Tumor") %>% select(tumor_ploidy,cohort,experimental_strategy) %>% table()`
<img width="291" alt="image" src="https://user-images.githubusercontent.com/47674661/126358706-47dc9f1f-e436-4768-b649-6eeb72a0c709.png">

And the # of specimens missing tumor_ploidy are:
`> histologies_df %>% filter(experimental_strategy != "RNA-Seq") %>% filter(sample_type == "Tumor") %>% filter(is.na(tumor_ploidy)) %>% select(cohort, experimental_strategy) %>% table()`
<img width="205" alt="image" src="https://user-images.githubusercontent.com/47674661/126358789-74b44273-d1d5-43ef-8cf3-021cbd55c66d.png">

`missing_tumor_ploidy <- histologies_df %>% filter(experimental_strategy != "RNA-Seq") %>% filter(sample_type == "Tumor") %>% filter(is.na(tumor_ploidy))`
[missing_tumor_ploidy.txt](https://github.com/PediatricOpenTargets/ticket-tracker/files/6849761/missing_tumor_ploidy.txt)

And among them - 285 are in v7 `cnv-cnvkit.seg.gz` (and 284 of them are WXS)
`> sum(missing_tumor_ploidy$Kids_First_Biospecimen_ID %in% CNVsample)
[1] 285`

cc: @jharenza , @kgaonkar6

**Comment by jharenza** [comment]
thanks for opening this @runjin326 ! @zhangb1 can you or someone from your team pull the ploidy information for these samples? thanks!

**Comment by zhangb1** [comment]
[missing_WXS_tumor_ploidy.txt](https://github.com/PediatricOpenTargets/ticket-tracker/files/6850382/missing_WXS_tumor_ploidy.txt)

@jharenza @runjin326  please see the file attached. I listed all the biospecimen id in cnv-cnvkit.seg.gz file and tumor_ploidy above.

**Comment by runjin326** [comment]
Thanks, @zhangb1! I also noticed some of their `germline_sex_estimate ` are missing. If that is not expected, could you please pull those information as well? Thanks!

**Comment by zhangb1** [comment]
So for the WXS we don't have the `germline_sex_estimate` . cc @jharenza

**Comment by runjin326** [comment]
Gotcha! Thanks!

**Comment by runjin326** [comment]
I ran the [analyses yesterday](https://github.com/PediatricOpenTargets/ticket-tracker/issues/102) and the results were all as expected, thanks!
I just checked and the v7 histologies.tsv now have tumor_ploidy for those specimens. Just want to confirm, we are not expecting to have tumor_ploidy for the following samples, right? 
<img width="620" alt="image" src="https://user-images.githubusercontent.com/47674661/126536565-9badcf89-68d9-462f-90b4-717d6eed2645.png">
[NA_ploidy_list.txt](https://github.com/PediatricOpenTargets/ticket-tracker/files/6857900/NA_ploidy_list.txt)

**Comment by jharenza** [comment]
We are not expecting panel ploidy, as we will not use CNVs from panel data. However, we should have ploidy from the TARGET WXS data that was just run, which is what I thought @zhangb1 had gathered - is that not the case?

**Comment by runjin326** [comment]
So there are only 285 WXS that are actually in the `cnv-cnvkit.seg.gz` and that was what he gathered. I was just wondering whether we would expect ploidy for the rest

**Comment by jharenza** [comment]
Oh, gotcha - sorry I misunderstood. Only TARGET NBL and AML will currently have ploidy, as those are the ones just run. The rest are in queue for v8.

**Comment by runjin326** [comment]
Oh gotcha! Thanks for clarifying :)

**Comment by jharenza** [comment]
closing with [PR 61](https://github.com/PediatricOpenTargets/OpenPedCan-analysis/pull/61)
