### ISSUE TITLE
Create CAVATICA delivery project for OT release dataa

### ISSUE THREAD

**Issue by jharenza** [PediatricOpenTargets/ticket-tracker#127]
Create OT release project similar to the OpenPBTA project: https://cavatica.sbgenomics.com/u/cavatica/openpbta

cc @yuankunzhu @bmennis @bmennis

**Comment by zhangb1** [comment]
project has been created:

https://cavatica.sbgenomics.com/u/cavatica/opentarget/

SBG will make it as public project

**Comment by jharenza** [comment]
closing, updated v7 as of [PR 61](https://github.com/PediatricOpenTargets/OpenPedCan-analysis/pull/61)
