### ISSUE TITLE
Proposed Analysis: Create GTEX v. TARGET NBL and GTEX v. GMKF NBL boxplot for GPC2 +/- batch correction

### ISSUE THREAD

**Issue by jharenza** [PediatricOpenTargets/ticket-tracker#13]
#### What are the scientific goals of the analysis?
Similar to #12 , but at the level of the known NBL immunotherapeutic target, GPC2, determine whether batch correction produces a different visual output and differences in TPM expression across tumor vs normals.

#### What methods do you plan to use to accomplish the scientific goals?
Create 4 plots of log2 GPC2 TPM:
1. TARGET NBL + GTEX, uncorrected
2. TARGET NBL + GTEX, corrected by dataset (both polyA)
3. GMKF NBL (collapsed matrix in the v2 data folder) + GTEX, uncorrected
4. GMKF NBL (collapsed matrix in the v2 data folder) + GTEX, corrected by library/dataset (GMKF is stranded, GTEX is polyA)

#### What input data are required for this analysis?
collapsed matrices for the above
GMKF NBL matrix can be found in [this branch](https://github.com/sangeetashukla/OpenPBTA-analysis/blob/update-collapse-rnaseq-1-1/analyses/collapse-rnaseq/results/kfnbl-gene-expression-rsem-fpkm-collapsed.stranded.rds)

#### How long do you expect is needed to complete the analysis? Will it be a multi-step analysis?
0.5 day

#### Who will complete the analysis (please add a GitHub handle here if relevant)?
@komalsrathi 

#### What relevant scientific literature relates to this analysis?
NA

**Comment by komalsrathi** [comment]
And here are the GTEx + GMKF NBL (n = 224) plots:

I know this looks exactly same but look at the y-axis and outliers:

![gmkf_nbl_uncorrected_gpc2](https://user-images.githubusercontent.com/7000615/118725794-6dfff800-b7fe-11eb-93a9-365f59eb1cbc.png)

![gmkf_nbl_corrected_gpc2](https://user-images.githubusercontent.com/7000615/118725803-6fc9bb80-b7fe-11eb-9aab-54bf780bf611.png)

**Comment by sangeetashukla** [comment]
> @komalsrathi I think 1 and 2 can be completed while we wait for the kbnbl matrix from @sangeetashukla

@jharenza @komalsrathi I have now added the the KFNBL TPM matrices to the branch I filed a PR for. 
Please take a look and let me know in case there is anything missing.

**Comment by jharenza** [comment]
thank you
