### ISSUE TITLE
Updated analysis: Subset manta FILTER=="PASS" consensus cnv

### ISSUE THREAD

**Issue by kgaonkar6** [PediatricOpenTargets/ticket-tracker#134]
#### What analysis module should be updated and why?
Add a FILTER==PASS for manta calls used in copy_number_consensus_call. I think this filter is necessary so that we use a subset of high-confidence broad SVs called by manta. https://github.com/Illumina/manta/blob/master/docs/userGuide/README.md#vcf-format-fields

Similar to https://github.com/AlexsLemonade/OpenPBTA-analysis/issues/1113

#### What changes need to be made? Please provide enough detail for another participant to make the update.
Add a filter to only keep manta calls where FILTER=='PASS'
$11 == 'PASS'
https://github.com/PediatricOpenTargets/OpenPedCan-analysis/blob/a6a1d0eb009039e3fd2041e5e0bd8a74ea557cc4/analyses/copy_number_consensus_call/Snakefile#L91-L106

#### What input data should be used? Which data were used in the version being updated?
pbta-sv-manta.tsv.gz

#### When do you expect the revised analysis will be completed?
1day

**Comment by jharenza** [comment]
Since this PR went in and we have this in #151 , I will close this issue. https://github.com/PediatricOpenTargets/OpenPedCan-analysis/pull/77
