### ISSUE TITLE
Updated analysis: select the same independent `Kids_First_Biospecimen_ID`s for all-cohorts and each-cohort procedures if possible in `independent-samples` module

### ISSUE THREAD

**Issue by logstar** [PediatricOpenTargets/ticket-tracker#135]
#### What analysis module should be updated and why?

The `independent-samples` module needs to be updated to select the same independent `Kids_First_Biospecimen_ID`s for the same `Kids_First_Participant_ID`s in both all-cohorts and each-cohort selection procedures if possible. This would allow analysis modules to use all-cohorts independent sample lists (ISLs) for all-cohort analyses and use each-cohort ISLs for each-cohort analyses, without discrepancies caused by the following random independent sample selection procedure, which is used in`independent-samples.R` and `independent_rna_samples.R`, in the analysis module results.

```R
dplyr::summarize(Kids_First_Biospecimen_ID = sample(Kids_First_Biospecimen_ID, 1)) %>%
```

This update is necessary to make all-cohorts and each-cohort analyses results directly comparable without being confounded by the randomness in the independent sample selection procedures, even though there are only several `Kids_First_Participant_ID`s that have different independent `Kids_First_Biospecimen_ID`s in all-cohorts and each-cohort ISLs that are caused by the random selection procedures, with the numbers listed below. The `FALSE n` values in the following table are the different ones.

(EDIT 08/19/2021 YZ: add code results)

```text
> library(tidyverse)
> each_cohort_filenames <- c('independent-specimens.rnaseq.primary.eachcohort.tsv',
+                            'independent-specimens.rnaseq.relapse.eachcohort.tsv',
+                            'independent-specimens.wgs.primary.eachcohort.tsv',
+                            'independent-specimens.wgs.relapse.eachcohort.tsv',
+                            'independent-specimens.wgswxspanel.primary.eachcohort.tsv',
+                            'independent-specimens.wgswxspanel.relapse.eachcohort.tsv')
> map_df(each_cohort_filenames, function(x) {
+     each_cohort_df <- read_tsv(x, col_types = cols())
+     all_cohort_df <- read_tsv(str_remove(x, 'eachcohort\\.'), col_types = cols())
+     # Do not compare Kids_First_Participant_IDs that are duplicated in each_cohort_df
+     each_cohort_duplicated_participant_ids <- each_cohort_df %>%
+         group_by(Kids_First_Participant_ID) %>%
+         summarise(n_Kids_First_Participant_ID = n()) %>%
+         filter(n_Kids_First_Participant_ID > 1) %>%
+         pull(Kids_First_Participant_ID)
+     
+     each_cohort_df %>%
+         filter(!Kids_First_Participant_ID %in% each_cohort_duplicated_participant_ids) %>%
+         rename(Kids_First_Biospecimen_ID_each_cohort = Kids_First_Biospecimen_ID) %>%
+         inner_join(rename(all_cohort_df,
+                           Kids_First_Biospecimen_ID_all_cohorts = Kids_First_Biospecimen_ID),
+                    by = 'Kids_First_Participant_ID') %>%
+         filter(!is.na(Kids_First_Biospecimen_ID_each_cohort), !is.na(Kids_First_Biospecimen_ID_all_cohorts)) %>%
+         mutate(same_Biospecimen_ID_for_the_same_Patient_ID = (
+             Kids_First_Biospecimen_ID_each_cohort == Kids_First_Biospecimen_ID_all_cohorts)) %>%
+         count(same_Biospecimen_ID_for_the_same_Patient_ID) %>%
+         mutate(list = str_remove(
+             str_replace(x, '\\.eachcohort\\.tsv', ' each-cohort vs all-cohorts'),
+             'independent-specimens\\.')) %>%
+         select(list, same_Biospecimen_ID_for_the_same_Patient_ID, n)
+ })
# A tibble: 12 x 3
   list                                           same_Biospecimen_ID_for_the_same_Patient_ID     n
   <chr>                                          <lgl>                                       <int>
 1 rnaseq.primary each-cohort vs all-cohorts      FALSE                                          52
 2 rnaseq.primary each-cohort vs all-cohorts      TRUE                                        11563
 3 rnaseq.relapse each-cohort vs all-cohorts      FALSE                                          13
 4 rnaseq.relapse each-cohort vs all-cohorts      TRUE                                          349
 5 wgs.primary each-cohort vs all-cohorts         FALSE                                           6
 6 wgs.primary each-cohort vs all-cohorts         TRUE                                          996
 7 wgs.relapse each-cohort vs all-cohorts         FALSE                                          10
 8 wgs.relapse each-cohort vs all-cohorts         TRUE                                          153
 9 wgswxspanel.primary each-cohort vs all-cohorts FALSE                                           9
10 wgswxspanel.primary each-cohort vs all-cohorts TRUE                                         2020
11 wgswxspanel.relapse each-cohort vs all-cohorts FALSE                                          10
12 wgswxspanel.relapse each-cohort vs all-cohorts TRUE                                          191
```

The different independent `Kids_First_Biospecimen_ID`s for the same `Kids_First_Participant_ID`s between all-cohorts and each-cohort ISLs can also be caused by overlapping `Kids_First_Participant_ID` between cohorts, and such differences are expected, and the same `Kids_First_Biospecimen_ID`s should **not** be used for both all-cohorts and each-cohort ISLs. The `FALSE n` values in the following table are the different ones.

```text
> map_df(each_cohort_filenames, function(x) {
+   each_cohort_df <- read_tsv(x, col_types = cols())
+   all_cohort_df <- read_tsv(str_remove(x, 'eachcohort\\.'), col_types = cols())
+   # Only compare Kids_First_Participant_IDs that are duplicated in each_cohort_df
+   each_cohort_duplicated_participant_ids <- each_cohort_df %>%
+     group_by(Kids_First_Participant_ID) %>%
+     summarise(n_Kids_First_Participant_ID = n()) %>%
+     filter(n_Kids_First_Participant_ID > 1) %>%
+     pull(Kids_First_Participant_ID)
+   
+   each_cohort_df %>%
+     filter(Kids_First_Participant_ID %in% each_cohort_duplicated_participant_ids) %>%
+     rename(Kids_First_Biospecimen_ID_each_cohort = Kids_First_Biospecimen_ID) %>%
+     left_join(rename(all_cohort_df,
+                      Kids_First_Biospecimen_ID_all_cohorts = Kids_First_Biospecimen_ID),
+                by = 'Kids_First_Participant_ID') %>%
+     filter(!is.na(Kids_First_Biospecimen_ID_each_cohort), !is.na(Kids_First_Biospecimen_ID_all_cohorts)) %>%
+     mutate(same_Biospecimen_ID_for_the_same_Patient_ID = (
+       Kids_First_Biospecimen_ID_each_cohort == Kids_First_Biospecimen_ID_all_cohorts)) %>%
+     count(same_Biospecimen_ID_for_the_same_Patient_ID) %>%
+     mutate(list = str_remove(
+       str_replace(x, '\\.eachcohort\\.tsv', ' each-cohort vs all-cohorts'),
+       'independent-specimens\\.')) %>%
+     select(list, same_Biospecimen_ID_for_the_same_Patient_ID, n)
+ })
# A tibble: 12 x 3
   list                                           same_Biospecimen_ID_for_the_same_Patient_ID     n
   <chr>                                          <lgl>                                       <int>
 1 rnaseq.primary each-cohort vs all-cohorts      FALSE                                          15
 2 rnaseq.primary each-cohort vs all-cohorts      TRUE                                           14
 3 rnaseq.relapse each-cohort vs all-cohorts      FALSE                                           3
 4 rnaseq.relapse each-cohort vs all-cohorts      TRUE                                            3
 5 wgs.primary each-cohort vs all-cohorts         FALSE                                           4
 6 wgs.primary each-cohort vs all-cohorts         TRUE                                            3
 7 wgs.relapse each-cohort vs all-cohorts         FALSE                                           6
 8 wgs.relapse each-cohort vs all-cohorts         TRUE                                            2
 9 wgswxspanel.primary each-cohort vs all-cohorts FALSE                                           4
10 wgswxspanel.primary each-cohort vs all-cohorts TRUE                                            3
11 wgswxspanel.relapse each-cohort vs all-cohorts FALSE                                           6
12 wgswxspanel.relapse each-cohort vs all-cohorts TRUE                                            2
```

#### What changes need to be made? Please provide enough detail for another participant to make the update.

(EDIT 07/28/2021 YZ)

There are several potential approaches to implement this update:

1. Update the each-cohort independent sample selection procedure to run all-cohort procedure first, and then handle `Kids_First_Participant_ID`s that have multiple cohorts by adding missing cohort `Kids_First_Biospecimen_ID`s.
2. Add a harmonizing R script for each-cohort and all-cohorts ISLs. After generating all ISLs using the current procedure, run the harmonizing R script to modify the each-cohort ISLs to have the same independent `Kids_First_Biospecimen_ID`s for the same `Kids_First_Participant_ID`s as the all-cohorts ISLs, for only the `Kids_First_Biospecimen_ID`s in the each-cohort ISLs that are from the same cohort as the all-cohorts ISLs (these differences are caused by the random selection procedure).
3. Update the each-cohort independent sample selection procedure to use all-cohort independent samples as a reference to select independent samples.
4. Manipulate the random seed, so the same Biospecimen IDs are always selected.

The first approach seem to be fairly straightforward and less redundant than the second and third approaches. The fourth approach seems to be infeasible. The second approach can keep the previous each-cohort and all-cohorts procedures.

#### What input data should be used? Which data were used in the version being updated?

v7 `histologies.tsv`.

#### When do you expect the revised analysis will be completed?

1-3 days

#### Who will complete the updated analysis?

cc @jharenza

**Comment by jharenza** [comment]
hi @komalsrathi - can you take this ticket?

**Comment by komalsrathi** [comment]
I am not familiar (at all) with this module so I will have to go through it. When do we need this by?

**Comment by komalsrathi** [comment]
@logstar I will start working on this ticket today, will let you know reg. any questions.

**Comment by logstar** [comment]
> @logstar I will start working on this ticket today, will let you know reg. any questions.

Thank you. We could also cc @runjin326 for the questions. She had updated the `independent-samples` module several times.

> When do we need this by?

I think before v9 release seems to be a practical plan. @jharenza I wonder if you have any suggestion on the timeline.

**Comment by komalsrathi** [comment]
@logstar so just clarifying - the numbers for the second test i.e. `Only compare Kids_First_Participant_IDs that are duplicated in each_cohort_df` **should remain the same as what we have now** but for the first test i.e. `Do not compare Kids_First_Participant_IDs that are duplicated in each_cohort_df`, it should give us all TRUE?

**Comment by jharenza** [comment]
Sorry for the delay, having this for v9 seems reasonable.  V8 should be out this week.

**Comment by logstar** [comment]
Thank you for checking @komalsrathi

> the numbers for the second test i.e. `Only compare Kids_First_Participant_IDs that are duplicated in each_cohort_df` **should remain the same as what we have now** 

The numbers for the second test may also change, if all-cohort ISL `Kids_First_Biospecimen_ID`s for duplicated `Kids_First_Participant_ID` are selected differently by randomness.

> but for the first test i.e. `Do not compare Kids_First_Participant_IDs that are duplicated in each_cohort_df`, it should give us all TRUE?

! Sorry that I forgot to add output of the first test. I have just updated the description. The first test does not give us all TRUE.

**Comment by komalsrathi** [comment]
Ok, so I made a small change in the independent-samples.R and independent_rna_samples.R codes: instead of using the `sample` function which randomly selects 1 out of all duplicates, we can just use `dplyr::distinct` which will use the first occurence of the duplicated KF participant id. So using that here are the numbers:

### Only compare Kids_First_Participant_IDs that are duplicated in each_cohort_df:

Old (using `sample`):
```
> map_df(each_cohort_filenames, .f = function(x) 
+     compare(file.path('results/archive',x)))
# A tibble: 12 x 3
   list                                                           same_Biospecimen_ID_for_the_same_Patient_ID     n
   <chr>                                                          <lgl>                                       <int>
 1 results/archive/rnaseq.primary each-cohort vs all-cohorts      FALSE                                          15
 2 results/archive/rnaseq.primary each-cohort vs all-cohorts      TRUE                                           14
 3 results/archive/rnaseq.relapse each-cohort vs all-cohorts      FALSE                                           3
 4 results/archive/rnaseq.relapse each-cohort vs all-cohorts      TRUE                                            3
 5 results/archive/wgs.primary each-cohort vs all-cohorts         FALSE                                           4
 6 results/archive/wgs.primary each-cohort vs all-cohorts         TRUE                                            3
 7 results/archive/wgs.relapse each-cohort vs all-cohorts         FALSE                                           6
 8 results/archive/wgs.relapse each-cohort vs all-cohorts         TRUE                                            2
 9 results/archive/wgswxspanel.primary each-cohort vs all-cohorts FALSE                                           4
10 results/archive/wgswxspanel.primary each-cohort vs all-cohorts TRUE                                            3
11 results/archive/wgswxspanel.relapse each-cohort vs all-cohorts FALSE                                           6
12 results/archive/wgswxspanel.relapse each-cohort vs all-cohorts TRUE                                            2
```

New (using `distinct`): 
```
> map_df(each_cohort_filenames, .f = function(x) 
+     compare(file.path('results', x)))
# A tibble: 12 x 3
   list                                                   same_Biospecimen_ID_for_the_same_Patient_ID     n
   <chr>                                                  <lgl>                                       <int>
 1 results/rnaseq.primary each-cohort vs all-cohorts      FALSE                                          15
 2 results/rnaseq.primary each-cohort vs all-cohorts      TRUE                                           14
 3 results/rnaseq.relapse each-cohort vs all-cohorts      FALSE                                           3
 4 results/rnaseq.relapse each-cohort vs all-cohorts      TRUE                                            3
 5 results/wgs.primary each-cohort vs all-cohorts         FALSE                                           4
 6 results/wgs.primary each-cohort vs all-cohorts         TRUE                                            3
 7 results/wgs.relapse each-cohort vs all-cohorts         FALSE                                           4
 8 results/wgs.relapse each-cohort vs all-cohorts         TRUE                                            4
 9 results/wgswxspanel.primary each-cohort vs all-cohorts FALSE                                           4
10 results/wgswxspanel.primary each-cohort vs all-cohorts TRUE                                            3
11 results/wgswxspanel.relapse each-cohort vs all-cohorts FALSE                                           4
12 results/wgswxspanel.relapse each-cohort vs all-cohorts TRUE                                            4
```

### Do not compare Kids_First_Participant_IDs that are duplicated in each_cohort_df

Old (using `sample`):
```
> map_df(each_cohort_filenames, .f = function(x) do_not_compare(file.path('results/archive', x)))
# A tibble: 12 x 3
   list                                                           same_Biospecimen_ID_for_the_same_Patient_ID     n
   <chr>                                                          <lgl>                                       <int>
 1 results/archive/rnaseq.primary each-cohort vs all-cohorts      FALSE                                          52
 2 results/archive/rnaseq.primary each-cohort vs all-cohorts      TRUE                                        11563
 3 results/archive/rnaseq.relapse each-cohort vs all-cohorts      FALSE                                          13
 4 results/archive/rnaseq.relapse each-cohort vs all-cohorts      TRUE                                          349
 5 results/archive/wgs.primary each-cohort vs all-cohorts         FALSE                                           6
 6 results/archive/wgs.primary each-cohort vs all-cohorts         TRUE                                          996
 7 results/archive/wgs.relapse each-cohort vs all-cohorts         FALSE                                          10
 8 results/archive/wgs.relapse each-cohort vs all-cohorts         TRUE                                          153
 9 results/archive/wgswxspanel.primary each-cohort vs all-cohorts FALSE                                           9
10 results/archive/wgswxspanel.primary each-cohort vs all-cohorts TRUE                                         2020
11 results/archive/wgswxspanel.relapse each-cohort vs all-cohorts FALSE                                          10
12 results/archive/wgswxspanel.relapse each-cohort vs all-cohorts TRUE                                          191
```

New (using `distinct`): 
```
> map_df(each_cohort_filenames, .f = function(x) do_not_compare(file.path('results', x)))
# A tibble: 6 x 3
  list                                                   same_Biospecimen_ID_for_the_same_Patient_ID     n
  <chr>                                                  <lgl>                                       <int>
1 results/rnaseq.primary each-cohort vs all-cohorts      TRUE                                        11615
2 results/rnaseq.relapse each-cohort vs all-cohorts      TRUE                                          362
3 results/wgs.primary each-cohort vs all-cohorts         TRUE                                         1002
4 results/wgs.relapse each-cohort vs all-cohorts         TRUE                                          163
5 results/wgswxspanel.primary each-cohort vs all-cohorts TRUE                                         2029
6 results/wgswxspanel.relapse each-cohort vs all-cohorts TRUE                                          201
```

**Comment by logstar** [comment]
> Ok, so I made a small change in the independent-samples.R and independent_rna_samples.R codes: instead of using the `sample` function which randomly selects 1 out of all duplicates, we can just use `dplyr::distinct` which will use the first occurence of the duplicated KF participant id. So using that here are the numbers:
> 
> ### Only compare Kids_First_Participant_IDs that are duplicated in each_cohort_df:
> Old (using `sample`):
> 
> ```
> > map_df(each_cohort_filenames, .f = function(x) 
> +     compare(file.path('results/archive',x)))
> # A tibble: 12 x 3
>    list                                                           same_Biospecimen_ID_for_the_same_Patient_ID     n
>    <chr>                                                          <lgl>                                       <int>
>  1 results/archive/rnaseq.primary each-cohort vs all-cohorts      FALSE                                          15
>  2 results/archive/rnaseq.primary each-cohort vs all-cohorts      TRUE                                           14
>  3 results/archive/rnaseq.relapse each-cohort vs all-cohorts      FALSE                                           3
>  4 results/archive/rnaseq.relapse each-cohort vs all-cohorts      TRUE                                            3
>  5 results/archive/wgs.primary each-cohort vs all-cohorts         FALSE                                           4
>  6 results/archive/wgs.primary each-cohort vs all-cohorts         TRUE                                            3
>  7 results/archive/wgs.relapse each-cohort vs all-cohorts         FALSE                                           6
>  8 results/archive/wgs.relapse each-cohort vs all-cohorts         TRUE                                            2
>  9 results/archive/wgswxspanel.primary each-cohort vs all-cohorts FALSE                                           4
> 10 results/archive/wgswxspanel.primary each-cohort vs all-cohorts TRUE                                            3
> 11 results/archive/wgswxspanel.relapse each-cohort vs all-cohorts FALSE                                           6
> 12 results/archive/wgswxspanel.relapse each-cohort vs all-cohorts TRUE                                            2
> ```
> 
> New (using `distinct`):
> 
> ```
> > map_df(each_cohort_filenames, .f = function(x) 
> +     compare(file.path('results', x)))
> # A tibble: 12 x 3
>    list                                                   same_Biospecimen_ID_for_the_same_Patient_ID     n
>    <chr>                                                  <lgl>                                       <int>
>  1 results/rnaseq.primary each-cohort vs all-cohorts      FALSE                                          15
>  2 results/rnaseq.primary each-cohort vs all-cohorts      TRUE                                           14
>  3 results/rnaseq.relapse each-cohort vs all-cohorts      FALSE                                           3
>  4 results/rnaseq.relapse each-cohort vs all-cohorts      TRUE                                            3
>  5 results/wgs.primary each-cohort vs all-cohorts         FALSE                                           4
>  6 results/wgs.primary each-cohort vs all-cohorts         TRUE                                            3
>  7 results/wgs.relapse each-cohort vs all-cohorts         FALSE                                           4
>  8 results/wgs.relapse each-cohort vs all-cohorts         TRUE                                            4
>  9 results/wgswxspanel.primary each-cohort vs all-cohorts FALSE                                           4
> 10 results/wgswxspanel.primary each-cohort vs all-cohorts TRUE                                            3
> 11 results/wgswxspanel.relapse each-cohort vs all-cohorts FALSE                                           4
> 12 results/wgswxspanel.relapse each-cohort vs all-cohorts TRUE                                            4
> ```
> 
> ### Do not compare Kids_First_Participant_IDs that are duplicated in each_cohort_df
> Old (using `sample`):
> 
> ```
> > map_df(each_cohort_filenames, .f = function(x) do_not_compare(file.path('results/archive', x)))
> # A tibble: 12 x 3
>    list                                                           same_Biospecimen_ID_for_the_same_Patient_ID     n
>    <chr>                                                          <lgl>                                       <int>
>  1 results/archive/rnaseq.primary each-cohort vs all-cohorts      FALSE                                          52
>  2 results/archive/rnaseq.primary each-cohort vs all-cohorts      TRUE                                        11563
>  3 results/archive/rnaseq.relapse each-cohort vs all-cohorts      FALSE                                          13
>  4 results/archive/rnaseq.relapse each-cohort vs all-cohorts      TRUE                                          349
>  5 results/archive/wgs.primary each-cohort vs all-cohorts         FALSE                                           6
>  6 results/archive/wgs.primary each-cohort vs all-cohorts         TRUE                                          996
>  7 results/archive/wgs.relapse each-cohort vs all-cohorts         FALSE                                          10
>  8 results/archive/wgs.relapse each-cohort vs all-cohorts         TRUE                                          153
>  9 results/archive/wgswxspanel.primary each-cohort vs all-cohorts FALSE                                           9
> 10 results/archive/wgswxspanel.primary each-cohort vs all-cohorts TRUE                                         2020
> 11 results/archive/wgswxspanel.relapse each-cohort vs all-cohorts FALSE                                          10
> 12 results/archive/wgswxspanel.relapse each-cohort vs all-cohorts TRUE                                          191
> ```
> 
> New (using `distinct`):
> 
> ```
> > map_df(each_cohort_filenames, .f = function(x) do_not_compare(file.path('results', x)))
> # A tibble: 6 x 3
>   list                                                   same_Biospecimen_ID_for_the_same_Patient_ID     n
>   <chr>                                                  <lgl>                                       <int>
> 1 results/rnaseq.primary each-cohort vs all-cohorts      TRUE                                        11615
> 2 results/rnaseq.relapse each-cohort vs all-cohorts      TRUE                                          362
> 3 results/wgs.primary each-cohort vs all-cohorts         TRUE                                         1002
> 4 results/wgs.relapse each-cohort vs all-cohorts         TRUE                                          163
> 5 results/wgswxspanel.primary each-cohort vs all-cohorts TRUE                                         2029
> 6 results/wgswxspanel.relapse each-cohort vs all-cohorts TRUE                                          201
> ```
> 
> NOTE: I moved old files to `results/archive` and added new files to `results/` which you will see in the calls above. Have not pushed the code because wanted to make sure if this approach is acceptable.

Thank you for the quick updates @komalsrathi .

Selecting the first distinct `Kids_First_Biospecimen_ID` fulfills the requirements in this issue. This will guarantee that we have the same `Kids_First_Biospecimen_ID` for every `Kids_First_Participant_ID` that is in only one cohort. This will also guarantee that `Kids_First_Biospecimen_ID`s are selected from multiple cohorts for every `Kids_First_Participant_ID` that is in more than one cohorts.

However, selecting the first distinct `Kids_First_Biospecimen_ID` may introduce selection biases. For example, GMKF `Kids_First_Biospecimen_ID`s are always the first distinct ones for the same `experimental_strategy` in the v7 `histologies.tsv`, so GMKF samples are always selected every `Kids_First_Participant_ID` that is in more than one cohorts. Speculatively, the order of the `histologies.tsv` rows may also have other implications, such that selecting the first distinct sample may introduce selection bias favoring certain samples.

I am not sure whether we need to avoid the potential sample selection biases in PedOT analysis modules. @jharenza I wonder if you have any suggestions or comments.

**Comment by komalsrathi** [comment]
If selection bias is an issue, we can always randomize the histology rows prior to using them as input for the module.:

```
hist_df <- read.delim('../../data/histologies.tsv')
hist_df <- hist_df[sample(nrow(hist_df)), ]
```

**Comment by logstar** [comment]
> If selection bias is an issue, we can always randomize the histology rows prior to using them as input for the module.:
> 
> ```
> hist_df <- read.delim('../../data/histologies.tsv')
> hist_df <- hist_df[sample(nrow(hist_df)), ]
> ```
> 
> Just a few lines showing how randomizing would work well:
> 
> ```
>   Kids_First_Participant_ID Kids_First_Biospecimen_ID_no_randomization cohort_no_randomization
> 1                    PARTRP                                BS_S0B4WASX                    GMKF
> 2                    PARUTJ                                BS_S5KDWVEA                    GMKF
> 3                    PARUZA                                BS_ERHKS2Y7                    GMKF
> 4                    PARVPD                                BS_NPVE58AT                    GMKF
> 5                    PARWEV                                BS_DBXCETW2                    GMKF
> 6                    PARXPD                                BS_3N0ZS3G3                    GMKF
>   Kids_First_Biospecimen_ID_randomization cohort_randomization
> 1                TARGET-30-PARTRP-01A-01D               TARGET
> 2                TARGET-30-PARUTJ-01A-01D               TARGET
> 3                             BS_6PKF4RCZ                 GMKF
> 4                             BS_Z862V8M7                 GMKF
> 5                             BS_HQNBAC1K                 GMKF
> 6                TARGET-30-PARXPD-01A-01D               TARGET
> ```
> 
> Counts of cohort showing no bias if using randomized histology as input:
> 
> ```
> > plyr::count(test$cohort_no_randomization)
>        x freq
> 1   GMKF  206
> 2 TARGET    1
> > plyr::count(test$cohort_randomization)
>        x freq
> 1   GMKF  164
> 2 TARGET   43
> ```

Thank you for the suggestion. Randomizing the histology data frame rows should work and remove the selection biases! This will also avoid all the proposed refactoring work. Awesome solution to this issue!

I think we could still aim for v9 release, even though we may be able to rush this update into v8. @jharenza I wonder if you have any suggestions.

**Comment by komalsrathi** [comment]
One more suggestion, to keep it reproducible across releases, we can randomize using a seed: 

```
set.seed(100)
hist_df <- read.delim('../../data/histologies.tsv')
hist_random_df <- hist_df[sample(nrow(hist_df)), ]
...
```

**Comment by logstar** [comment]
> One more suggestion, to keep it reproducible across releases, we can randomize using a seed:
> 
> ```
> set.seed(100)
> hist_df <- read.delim('../../data/histologies.tsv')
> hist_random_df <- hist_df[sample(nrow(hist_df)), ]
> ...
> ```

Thank you for the suggestion. I agree. This will also reproduce the same results in different runs of the same release.

**Comment by jharenza** [comment]
thanks for the updates and discussion @komalsrathi and @logstar  - this solution sounds good to me. If you are ready with this, we can coordinate with @runjin326 for having these files added to the v8 release, sure!

**Comment by komalsrathi** [comment]
Sure, I will push the code in a few. Thanks!

**Comment by runjin326** [comment]
Thanks, @komalsrathi and @logstar! I will add this change to the v8 release task list and we can incorporate the change with v8.

**Comment by logstar** [comment]
> Sure, I will push the code in a few. Thanks!

Hi @komalsrathi . Thank you for preparing the PR for v8 release. Could you use <https://s3.amazonaws.com/kf-openaccess-us-east-1-prd-pbta/open-targets/v8/histologies.tsv> in `run-independent-samples.sh` like the following code, so the results will be ready for v8 release as well?

```bash
if [[ RUN_FOR_SUBTYPING -eq "0" ]]
then
   HISTOLOGY_FILE="path/to/v8/downloaded/from/s3/histologies.tsv"
else
   HISTOLOGY_FILE="../../data/histologies-base.tsv"
fi
```

**Comment by jharenza** [comment]
just want to note we need to do another update of the v8 histologies file, so this won't be ready yet - #176. Perhaps @runjin326 can take care of the rerun once this code is in so that everything is in order.

**Comment by logstar** [comment]
> just want to note we need to do another update of the v8 histologies file, so this won't be ready yet - #176. Perhaps @runjin326 can take care of the rerun once this code is in so that everything is in order.

Thank you for the note. I agree.

@komalsrathi could open the PR with `../../data/histologies.tsv`. We will review the PR and merge, which I estimate could be done by today or early tomorrow. Then, @runjin326 could rerun with the updated v8 `histologies.tsv`.

@komalsrathi Sorry for the back-and-forth. Could you use v7 `../../data/histologies.tsv` in the PR for this issue?

**Comment by runjin326** [comment]
Thanks @logstar and @jharenza. The plan sounds good!

**Comment by logstar** [comment]
Closed with <https://github.com/PediatricOpenTargets/OpenPedCan-analysis/pull/92> merged.
