### ISSUE TITLE
map broad histologies for TARGET

### ISSUE THREAD

**Issue by jharenza** [PediatricOpenTargets/ticket-tracker#136]
#### What data file(s) does this issue pertain to?
histologies.tsv

#### What release are you using?

v7

#### Put your question or report your issue here.
the `broad_histologies` field is a duplication of the TARGET disease type:
```
                                 . Freq
1     Acute Lymphoblastic Leukemia  957
2           Acute Myeloid Leukemia  248
3 Clear cell sarcoma of the kidney   13
4                    Neuroblastoma 1100
5                     Osteosarcoma  177
6                   Rhabdoid tumor   64
7                      Wilms tumor  180
```

ALL and AML can be combined into `Hematologic malignancies` and CCSK, Rhabdoid, and Wilms can all be combined into `Renal tumors`. OS should be `Mesenchymal, non-meningothelial tumors` and NBL can _possibly_ be converted to `Embryonal tumors`. 

Either @jharenza will create a new mapping file for use in subtyping modules or @ewafula or @kgaonkar6 can update in the v8 release. TBD

**Comment by ewafula** [comment]
@jharenza, I’ll start a v8-OpenPedCan PR with this first update for TARGET
broad_histology column on D3B-codes GitHub repo. The PR can be blocked
until when other future update to histologies.tsv have been performed for
v8 data release.

**Comment by runjin326** [comment]
Close with [PR89 ](https://github.com/PediatricOpenTargets/OpenPedCan-analysis/pull/89)
