### ISSUE TITLE
Updated analysis: change independent sample lists used in `snv-frequencies` module (rerun after v9)

### ISSUE THREAD

**Issue by logstar** [PediatricOpenTargets/ticket-tracker#137]
#### What analysis module should be updated and why?

The `snv-frequencies` module should be updated to use all-cohorts independent sample lists (ISLs) for computing all-cohorts SNV frequencies and use each-cohort ISLs for computing each-cohort SNV frequencies. Currently, each-cohort ISLs are used for computing both all-cohorts and each-cohort SNV frequencies.

**Note**: Only work on this issue after the following issue is closed.

- [x] <https://github.com/PediatricOpenTargets/ticket-tracker/issues/135>

#### What changes need to be made? Please provide enough detail for another participant to make the update.

For computing all-cohorts SNV frequencies, use the following ISLs.

- independent-specimens.wgswxspanel.primary.tsv
- independent-specimens.wgswxspanel.relapse.tsv

For computing each-cohort SNV frequencies, use the following ISLs.

- independent-specimens.wgswxspanel.primary.eachcohort.tsv
- independent-specimens.wgswxspanel.relapse.eachcohort.tsv

#### What input data should be used? Which data were used in the version being updated?

- histologies.tsv
- snv-consensus-plus-hotspots.maf.tsv.gz
- ped_opentargets_2021_pedcbio_case_set_ids.json
- independent-specimens.wgswxspanel.primary.tsv
- independent-specimens.wgswxspanel.relapse.tsv
- independent-specimens.wgswxspanel.primary.eachcohort.tsv
- independent-specimens.wgswxspanel.relapse.eachcohort.tsv

#### When do you expect the revised analysis will be completed?

1 day

#### Who will complete the updated analysis?

@ewafula 

@runjin326 could review the upcoming PR.

cc @jharenza

**Comment by runjin326** [comment]
Closing with[ PR107](https://github.com/PediatricOpenTargets/OpenPedCan-analysis/pull/107) merged.
