### ISSUE TITLE
Updated analysis: change independent sample lists used in `cnv-frequencies` module (rerun after v9)

### ISSUE THREAD

**Issue by logstar** [PediatricOpenTargets/ticket-tracker#139]
#### What analysis module should be updated and why?

The `cnv-frequencies` module should be updated to use all-cohorts independent sample lists (ISLs) for computing all-cohorts CNV frequencies and use each-cohort ISLs for computing each-cohort CNV frequencies. Currently, each-cohort ISLs are used for computing both all-cohorts and each-cohort CNV frequencies.

**Note**: Only work on this issue after the following issue is closed.

- [x] <https://github.com/PediatricOpenTargets/ticket-tracker/issues/135>

#### What changes need to be made? Please provide enough detail for another participant to make the update.

For computing all-cohorts CNV frequencies, use the following ISLs.

- independent-specimens.wgswxspanel.primary.tsv
- independent-specimens.wgswxspanel.relapse.tsv

For computing each-cohort CNV frequencies, use the following ISLs.

- independent-specimens.wgswxspanel.primary.eachcohort.tsv
- independent-specimens.wgswxspanel.relapse.eachcohort.tsv

#### What input data should be used? Which data were used in the version being updated?

- histologies.tsv
- consensus_wgs_plus_cnvkit_wxs_autosomes.tsv.gz
- consensus_wgs_plus_cnvkit_wxs_x_and_y.tsv.gz
- independent-specimens.wgswxspanel.primary.tsv
- independent-specimens.wgswxspanel.relapse.tsv
- independent-specimens.wgswxspanel.primary.eachcohort.tsv
- independent-specimens.wgswxspanel.relapse.eachcohort.tsv

#### When do you expect the revised analysis will be completed?

1-2 days

#### Who will complete the updated analysis?

@ewafula ?

**Comment by ewafula** [comment]
Sure, @logstar, will work to update cnv-frequencies module once issue #135
is closed.

**Comment by runjin326** [comment]
Closing with [PR98 ](https://github.com/PediatricOpenTargets/OpenPedCan-analysis/pull/98) merged
