### ISSUE TITLE
Updated analysis: change independent sample lists used in `fusion-frequencies` module (rerun after v9)

### ISSUE THREAD

**Issue by logstar** [PediatricOpenTargets/ticket-tracker#140]
#### What analysis module should be updated and why?

The `fusion-frequencies` module should be updated to use all-cohorts independent sample lists (ISLs) for computing all-cohorts fusion frequencies and use each-cohort ISLs for computing each-cohort fusion frequencies. Currently, each-cohort ISLs are used for computing both all-cohorts and each-cohort fusion frequencies.

**Note**: Only work on this issue after the following issue is closed.

- [x] <https://github.com/PediatricOpenTargets/ticket-tracker/issues/135>

#### What changes need to be made? Please provide enough detail for another participant to make the update.

For computing all-cohorts fusion frequencies, use the following ISLs.

- independent-specimens.rnaseq.primary.tsv
- independent-specimens.rnaseq.relapse.tsv

For computing each-cohort fusion frequencies, use the following ISLs.

- independent-specimens.rnaseq.primary.eachcohort.tsv
- independent-specimens.rnaseq.relapse.eachcohort.tsv

#### What input data should be used? Which data were used in the version being updated?

- `../../data/histologies.tsv`
- `../fusion_filtering/results/fusion-putative-oncogenic.tsv`
- independent-specimens.rnaseq.primary.tsv
- independent-specimens.rnaseq.relapse.tsv
- independent-specimens.rnaseq.primary.eachcohort.tsv
- independent-specimens.rnaseq.relapse.eachcohort.tsv

#### When do you expect the revised analysis will be completed?

1-3 days

#### Who will complete the updated analysis?

@kgaonkar6 ?

**Comment by runjin326** [comment]
@logstar, I think I need some clarifications about this ticket. Do you meant we want to run [this section](https://github.com/PediatricOpenTargets/OpenPedCan-analysis/blob/61e23154a34e1d8b3fc1c50a67dd8f79c2067776/analyses/fusion-frequencies/01-fusion-frequencies.R#L202-L240) with ISLs for all cohorts and output a separate table with all cohorts? Or do you want additional [columns in this function](https://github.com/PediatricOpenTargets/OpenPedCan-analysis/blob/61e23154a34e1d8b3fc1c50a67dd8f79c2067776/analyses/fusion-frequencies/utils/freq_counts.R#L125-L224)?

**Comment by logstar** [comment]
@runjin326 Thank you for the questions.

> Do you meant we want to run [this section](https://github.com/PediatricOpenTargets/OpenPedCan-analysis/blob/61e23154a34e1d8b3fc1c50a67dd8f79c2067776/analyses/fusion-frequencies/01-fusion-frequencies.R#L202-L240) with ISLs for all cohorts and output a separate table with all cohorts?

Not exactly. You can implement this issue in the way that you prefer. Although it seems an `if (is_all_cohorts) { ... } else {...}` statement around [this code section](https://github.com/PediatricOpenTargets/OpenPedCan-analysis/blob/61e23154a34e1d8b3fc1c50a67dd8f79c2067776/analyses/fusion-frequencies/01-fusion-frequencies.R#L216-L218) is sufficient, I recommend to go over the module comprehensively before implementing the changes. I also cannot provide concrete instructions on all places that need to be changed, as I have not been changing the code of this module for more than a month, and I have to develop the boxplot API before the deadlines.

However, I think it may not be necessary to output a separate table. We keep the same TSV output files.

The goal is to generate `cohort == all-cohorts` results using all-cohorts ISL, and generate single/each-cohort, e.g. `cohort == GMKF`, results using each-cohort ISL.

> Or do you want additional [columns in this function](https://github.com/PediatricOpenTargets/OpenPedCan-analysis/blob/61e23154a34e1d8b3fc1c50a67dd8f79c2067776/analyses/fusion-frequencies/utils/freq_counts.R#L125-L224)?

I think it may not be necessary to have additional columns, but I am not sure.

> Could you please point out where in the code we generate table using each cohort ISLs for all-cohorts as well?

[This section](https://github.com/PediatricOpenTargets/OpenPedCan-analysis/blob/61e23154a34e1d8b3fc1c50a67dd8f79c2067776/analyses/fusion-frequencies/01-fusion-frequencies.R#L216-L218) generates the table. I am not sure if other places are also involved.

**Comment by runjin326** [comment]
Closing with [PR96](https://github.com/PediatricOpenTargets/OpenPedCan-analysis/pull/96) left
