### ISSUE TITLE
Updated analysis: add single variant PedcBioPortal lollipop plot URLs to `snv-frequencies` module

### ISSUE THREAD

**Issue by logstar** [PediatricOpenTargets/ticket-tracker#143]
#### What analysis module should be updated and why?

The `snv-frequenccies` module needs to be updated to add single-variant PedcBioPortal lollipop plot URLs to the variant-level mutation frequency table. In addition, the gene-level PedcBioPortal plot URLs need to be removed from the variant-level mutation frequency table.

This update is suggested in a meeting discussion.

#### What changes need to be made? Please provide enough detail for another participant to make the update.

Update `01-snv-frequencies.R` to remove gene-level PedcBioPortal plot URLs from variant-level mutation frequency tables.

Update `01-snv-frequencies.R` to add single-variant PedcBioPortal lollipop plot URLs.

Update README.md for the changes.

#### What input data should be used? Which data were used in the version being updated?

- `../../data/histologies.tsv`
- `../../data/snv-consensus-plus-hotspots.maf.tsv.gz`
- Appropriate independent sample lists, per the status of <https://github.com/PediatricOpenTargets/ticket-tracker/issues/137>
- `input/ped_opentargets_2021_pedcbio_case_set_ids.json`

#### When do you expect the revised analysis will be completed?

1-3 days.

#### Who will complete the updated analysis?

@logstar 

cc @jharenza

**Comment by logstar** [comment]
@kalletlak I was wondering if it is possible to have a PedcBioPortal lollipop plot URL that highlight only a single variant. For example, in <https://pedcbioportal.kidsfirstdrc.org/results/mutations?cancer_study_list=ped_opentargets_2021&case_set_id=ped_opentargets_2021_pbta_diffuse_midline_glioma&Action=Submit&gene_list=BRAF>, I could click the V600E lollipop to highlight the V600E variant in the plot and subset the table to only list the V600E variant, but the URL did not change after I clicked a variant lollipop. Therefore, I was wondering if I could have an URL to directly link to the page with a single variant being highlighted.

cc @jharenza

**Comment by kalletlak** [comment]
@logstar @jharenza Currently it is not possible to save highlighted variant in URL. I'll have to check with cbio team and see if it feasible to include it.

**Comment by jharenza** [comment]
We can close this for now, since it is not yet possible.
