### ISSUE TITLE
Some `sample_id` and `aliquot_id` in `histologies.tsv` are mis-coded

### ISSUE THREAD

**Issue by jharenza** [PediatricOpenTargets/ticket-tracker#145]
#### What data file(s) does this issue pertain to?
`histologies.tsv`

#### What release are you using?

v7

#### Put your question or report your issue here.
Some TARGET samples have `sample_id` == `03`, while their corresponding TARGET ids (in `Kids_First_Biospecimen_ID`) contain other ids indicative of sample ids. Similarly, these samples have the wrong `aliquot_id`:
```
> v7 %>%
+   filter(cohort == "TARGET" & sample_id == "03") %>%
+   select(Kids_First_Biospecimen_ID, sample_id, aliquot_id)
# A tibble: 812 x 3
   Kids_First_Biospecimen_ID sample_id aliquot_id
   <chr>                     <chr>     <chr>     
 1 TARGET-50-CAAAAQ-01A-01R  03        02        
 2 TARGET-50-PALJIP-02A-01R  03        02        
 3 TARGET-50-PALFME-02A-01R  03        02        
 4 TARGET-50-PAJNLT-01A-01R  03        02        
 5 TARGET-50-PAKKSE-01A-01R  03        02        
 6 TARGET-50-PAJNCJ-01A-01R  03        02        
 7 TARGET-50-PAKRVH-01A-01R  03        02        
 8 TARGET-50-PAJMKJ-01A-01R  03        02        
 9 TARGET-50-PAECJB-01A-01R  03        02        
10 TARGET-50-PAKFME-01A-01R  03        02        
# … with 802 more rows
```

Please double check logic for all TARGET ids.

**Comment by jharenza** [comment]
cc @migbro 

@ewafula when you have a fix for this posted to the D3b-codes repo, can you mention that here and let @migbro know - he can then use the updated file for the pedcbio load mentioned in #118

**Comment by ewafula** [comment]
Sure, will before the end the day.

**Comment by runjin326** [comment]
Close with [PR89](https://github.com/PediatricOpenTargets/OpenPedCan-analysis/pull/89)
