### ISSUE TITLE
`snv-consensus-plus-hotspots.maf.tsv.gz` has gene ENSG IDs and symbols that are not in `ensg-hugo-rmtl-mapping.tsv`

### ISSUE THREAD

**Issue by logstar** [PediatricOpenTargets/ticket-tracker#146]
#### What data file(s) does this issue pertain to?

- `snv-consensus-plus-hotspots.maf.tsv.gz`
- `ensg-hugo-rmtl-mapping.tsv`

#### What release are you using?

v7

#### Put your question or report your issue here.

`snv-consensus-plus-hotspots.maf.tsv.gz` has gene ENSG IDs and symbols that are not in `ensg-hugo-rmtl-mapping.tsv`, which is shown below. Attached is the full TSV list of such ENSG IDs and symbols. I was wondering if these gene ENSG ID and symbol mappings will be added to the `ensg-hugo-rmtl-mapping.tsv` in future releases.

I looked several ENSG IDs that are in `snv-consensus-plus-hotspots.maf.tsv.gz` but are not in `ensg-hugo-rmtl-mapping.tsv`. It seems that `snv-consensus-plus-hotspots.maf.tsv.gz` ENSG IDs are GRCh38, whereas `ensg-hugo-rmtl-mapping.tsv` ENSG IDs are GRCh37.

This is related to the annotator submodule, since annotator downloads gene full name and refseq protein IDs using all ENSG IDs in `ensg-hugo-rmtl-mapping.tsv`. If an unannotated table has ENSG IDs that are not in `ensg-hugo-rmtl-mapping.tsv`, those ENSG IDs will not have gene full name or refseq protein ID annotations.

If these gene ENSG ID and symbol mappings will be added to the `ensg-hugo-rmtl-mapping.tsv` in future releases, annotator will not need to be updated. Otherwise, the annotator `long-format-table-utils/annotator/download-annotation-data.R` may need to be updated to look for ENSG IDs from both `snv-consensus-plus-hotspots.maf.tsv.gz` and `ensg-hugo-rmtl-mapping.tsv`.

```text
> eh_df <- read_tsv('../../data/ensg-hugo-rmtl-mapping.tsv')
> maf_df <- read_tsv(
> maf_df %>%
+   select(Gene, Hugo_Symbol) %>%
+   filter(!is.na(Gene), !Gene %in% eh_df$ensg_id) %>%
+   group_by(Gene, Hugo_Symbol) %>%
+   tally()
# A tibble: 155 x 3
# Groups:   Gene [155]
   Gene            Hugo_Symbol     n
   <chr>           <chr>       <int>
 1 ENSG00000284753 EEF1AKMT4      21
 2 ENSG00000284755 AL049557.1     50
 3 ENSG00000284762 AC022414.1    279
 4 ENSG00000284763 AL449105.1     13
 5 ENSG00000284770 TBCE          246
 6 ENSG00000284772 AC011330.3      7
 7 ENSG00000284773 AC114490.3     40
 8 ENSG00000284776 AL121900.2     44
 9 ENSG00000284779 IGF2           60
10 ENSG00000284788 AC183088.1     46
# … with 145 more rows
```

[maf_gene_ensg_symbol_not_in_rmtl.txt](https://github.com/PediatricOpenTargets/ticket-tracker/files/6910090/maf_gene_ensg_symbol_not_in_rmtl.txt)

I also checked the CNV files, and there is no gene ENSG ID or symbol that is not present in `ensg-hugo-rmtl-mapping.tsv`.

```text
> cnv_auto_df <- read_tsv('../../data/consensus_wgs_plus_cnvkit_wxs_autosomes.tsv.gz', guess_max = 1e6)
> cnv_allo_df <- read_tsv('../../data/consensus_wgs_plus_cnvkit_wxs_x_and_y.tsv.gz', guess_max = 1e6)
> 
> bind_rows(select(cnv_auto_df, ensembl, gene_symbol),
+           select(cnv_allo_df, ensembl, gene_symbol)) %>%
+   filter(!is.na(ensembl), !ensembl %in% eh_df$ensg_id) %>%
+   group_by(ensembl, gene_symbol) %>%
+   tally()
# A tibble: 0 x 3
# Groups:   ensembl [0]
# … with 3 variables: ensembl <chr>, gene_symbol <chr>, n <int>
```

**Comment by jharenza** [comment]
Hi @logstar - thanks for noticing this! 

So it seems the best approach would be to update the mapping file to contain all ENSG IDs in the MAF not currently in the mapping file. My question, though, is since you mentioned MAF ENSG being in hg38 and the mapping file being in hg37, are there any gene symbols which overlap the MAF and mapping file _and_ have different ENSG IDs between hg37 and hg38? If not, I think this would be a straightforward rbind. If so, we need to strategize.

**Comment by logstar** [comment]
> Hi @logstar - thanks for noticing this!
> 
> So it seems the best approach would be to update the mapping file to contain all ENSG IDs in the MAF not currently in the mapping file. My question, though, is since you mentioned MAF ENSG being in hg38 and the mapping file being in hg37, are there any gene symbols which overlap the MAF and mapping file _and_ have different ENSG IDs between hg37 and hg38? If not, I think this would be a straightforward rbind. If so, we need to strategize.

I agree. The updated mapping files will also help RNA modules to add all ENSG IDs.

There are some gene symbols that are in both MAF and mapping files but have different ENSG IDs, which are listed below.

```text
> maf_df %>%
+   select(Gene, Hugo_Symbol) %>%
+   filter(!is.na(Gene), !is.na(Hugo_Symbol)) %>%
+   filter(Hugo_Symbol %in% eh_df$gene_symbol, !Gene %in% eh_df$ensg_id) %>%
+   group_by(Gene, Hugo_Symbol) %>%
+   summarise(n = n()) %>%
+   ungroup() %>%
+   left_join(eh_df, by = c('Hugo_Symbol' = 'gene_symbol')) %>%
+   select(MAF_ENSG = Gene, MAF_symbol = Hugo_Symbol, Mapping_ENSG = ensg_id,
+          n_MAF_rows = n)
# A tibble: 23 x 4
   MAF_ENSG        MAF_symbol Mapping_ENSG    n_MAF_rows
   <chr>           <chr>      <chr>                <int>
 1 ENSG00000284770 TBCE       ENSG00000116957        246
 2 ENSG00000284779 IGF2       ENSG00000167244         60
 3 ENSG00000284788 AC183088.1 ENSG00000280724         46
 4 ENSG00000284834 AC183088.2 ENSG00000283137         72
 5 ENSG00000284848 LINC02359  ENSG00000256342        272
 6 ENSG00000284862 CCDC39     ENSG00000145075        162
 7 ENSG00000284932 AC017083.4 ENSG00000273398         20
 8 ENSG00000284934 DIABLO     ENSG00000184047         57
 9 ENSG00000284988 LINC02203  ENSG00000280709         44
10 ENSG00000285045 AC006548.3 ENSG00000280156         22
# … with 13 more rows
```

**Comment by logstar** [comment]
For example, TBCE only has one GRCh37 ENSG ID in the mapping file:

```text
$ grep -P 'TBCE\t' ../../data/ensg-hugo-rmtl-mapping.tsv 
ENSG00000116957 TBCE    NA      NA
```

However, TBCE has other mappings in the MAF file:

```text
> maf_df %>%
+   select(Gene, Hugo_Symbol) %>%
+   filter(Hugo_Symbol == 'TBCE') %>%
+   group_by(Gene, Hugo_Symbol) %>%
+   summarise(n = n()) %>%
+   ungroup()
# A tibble: 2 x 3
  Gene            Hugo_Symbol     n
  <chr>           <chr>       <int>
1 ENSG00000284770 TBCE          246
2 ENSG00000285053 TBCE           91
```

**Comment by jharenza** [comment]
We ended up merging GENCODE v28 and v38 to create a new mapping file. Closing with https://github.com/d3b-center/D3b-codes/pull/45
