### ISSUE TITLE
add updated MB subtypes to v8 histologies file

### ISSUE THREAD

**Issue by jharenza** [PediatricOpenTargets/ticket-tracker#148]
#### What data file(s) does this issue pertain to?
`histologies.tsv`

#### What release are you using?

v7

#### Put your question or report your issue here.
Since https://github.com/PediatricOpenTargets/OpenPedCan-analysis/pull/57 has been merged, update the MB subtypes in the histologies file for medulloblastoma.

**Comment by runjin326** [comment]
Implemented in v8 histologies file.

**Comment by runjin326** [comment]
Close with [PR89 ](https://github.com/PediatricOpenTargets/OpenPedCan-analysis/pull/89)
