### ISSUE TITLE
Prepare and format TCGA manifest

### ISSUE THREAD

**Issue by jharenza** [PediatricOpenTargets/ticket-tracker#15]
#### What data file(s) does this issue pertain to?
tcga-histologies.tsv

#### What release are you using?

v2

#### Put your question or report your issue here.
Will have to gather clinical data as well as `RNA_library`

**Comment by yuankunzhu** [comment]
we can use this notebook as an example of getting library information from GDC API endpoint: https://github.com/yuankunzhu/yuankunzhu.github.io/blob/master/target-nb-lib/target-nb-rnaseq-lib-info.ipynb

**Comment by komalsrathi** [comment]
Hey guys, I got this response from GDC in case you don't have this info. Not sure this is helpful but you can try!

The following query will result in a JSON file containing all the cases that have used "Poly-T Enrichment" (alias Poly-A) and "rRNA Depletion" (alias ribo-depleted) as library type: [link](https://nam10.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapi.gdc.cancer.gov%2Ffiles%3Ffilters%3D%257B%250D%250A%2522op%2522%253A%2522and%2522%252C%250D%250A%2522content%2522%253A%255B%250D%250A%257B%250D%250A%2522op%2522%253A%2522in%2522%252C%250D%250A%2522content%2522%253A%257B%250D%250A%2522field%2522%253A%2522analysis.metadata.read_groups.library_selection%2522%252C%250D%250A%2522value%2522%253A%255B%2522Poly-T%2520Enrichment%2522%252C%2522rRNA%2520Depletion%2522%255D%250D%250A%257D%250D%250A%257D%250D%250A%250D%250A%255D%250D%250A%257D%26pretty%3Dtrue%26fields%3Dcases.project.project_id%2Ccases.case_id%2Canalysis.metadata.read_groups.library_selection%26size%3D1000&amp;data=04%7C01%7Crathik%40chop.edu%7Cf807f305bd8441b0675608d91bcded00%7Ca611241607b041a59bb1d146b575c975%7C1%7C0%7C637571393527919936%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&amp;sdata=HNXS0%2FoiDoWDD0BIjYuSTBiwI4okkQgshqU1n03QrIs%3D&amp;reserved=0)

The following query will result in a file containing cases from TCGA | RNA-Seq + miRNA-Seq data, with a non-null library type: [link](https://nam10.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapi.gdc.cancer.gov%2Ffiles%3Ffilters%3D%257B%250D%250A%2522op%2522%253A%2522and%2522%252C%250D%250A%2522content%2522%253A%255B%250D%250A%257B%250D%250A%2522op%2522%253A%2522%253D%2522%252C%250D%250A%2522content%2522%253A%257B%250D%250A%2522field%2522%253A%2522cases.project.program.name%2522%252C%250D%250A%2522value%2522%253A%2522TCGA%2522%250D%250A%257D%250D%250A%257D%252C%250D%250A%257B%250D%250A%2522op%2522%253A%2522in%2522%252C%250D%250A%2522content%2522%253A%257B%250D%250A%2522field%2522%253A%2522experimental_strategy%2522%252C%250D%250A%2522value%2522%253A%255B%250D%250A%2522RNA-Seq%2522%252C%250D%250A%2522miRNA-Seq%2522%250D%250A%255D%250D%250A%257D%250D%250A%257D%252C%250D%250A%257B%250D%250A%2522op%2522%253A%2522not%2522%252C%250D%250A%2522content%2522%253A%257B%250D%250A%2522field%2522%253A%2522analysis.metadata.read_groups.library_selection%2522%252C%250D%250A%2522value%2522%253Anull%250D%250A%257D%250D%250A%257D%250D%250A%255D%250D%250A%257D%26pretty%3Dtrue%26fields%3Dcases.project.project_id%2Canalysis.metadata.read_groups.library_selection%2Ccases.case_id%2Ccases.project.program%26size%3D1000&amp;data=04%7C01%7Crathik%40chop.edu%7Cf807f305bd8441b0675608d91bcded00%7Ca611241607b041a59bb1d146b575c975%7C1%7C0%7C637571393527919936%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&amp;sdata=5cPgm6RFXgv9UmUBjmHfC9URyPc49G4IB3WBU%2FHO80M%3D&amp;reserved=0)

You can collect the result of the above queries in a spreadsheet by adding a &format=tsv to the end of the link.

More instructions on customizing the API queries can be found [here](https://nam10.safelinks.protection.outlook.com/?url=https%3A%2F%2Fdocs.gdc.cancer.gov%2FAPI%2FUsers_Guide%2FSearch_and_Retrieval%2F&amp;data=04%7C01%7Crathik%40chop.edu%7Cf807f305bd8441b0675608d91bcded00%7Ca611241607b041a59bb1d146b575c975%7C1%7C0%7C637571393527929888%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&amp;sdata=FS3UaUFhf8RD4bsjcU%2B7whNGJHlQKchKaEr8tEpjTHQ%3D&amp;reserved=0)

**Comment by jharenza** [comment]
Great, thanks @komalsrathi!

**Comment by jharenza** [comment]
Docs about naming of samples: 
https://docs.gdc.cancer.gov/Encyclopedia/pages/TCGA_Barcode/
https://gdc.cancer.gov/resources-tcga-users/tcga-code-tables/center-codes

**Comment by jharenza** [comment]
closed with https://github.com/PediatricOpenTargets/OpenPedCan-analysis/pull/16
