### ISSUE TITLE
Double checking  Acute Lymphoblastic Leukemia (ALL) sample numbers ~800 on isilon vs ~300 in GDC

### ISSUE THREAD

**Issue by afarrel** [PediatricOpenTargets/ticket-tracker#150]
#### What data file(s) does this issue pertain to?

Histologies file

#### What release are you using?

pedOT Release v7

#### Put your question or report your issue here.
As stated in ticket [111](https://github.com/PediatricOpenTargets/ticket-tracker/issues/111#issuecomment-890155727), 
there are 308 WXS ALL pairs. See below:

                         experimental_strategy
                cancer_group             WXS
           Acute Lymphoblastic Leukemia  308
           Acute Myeloid Leukemia        31
           Neuroblastoma                 222
           Osteosarcoma                  90
           Wilms tumor                   50

The original list has T/N ~800 pairs which is mirrored on isilon and TARGET clinical/metadata files. 
What caused this discrepancy?
Why do we have 308 pairs instead of ~800 WXS pairs?

**Comment by afarrel** [comment]
COPYING CONVO FROM SLACK between @afarrel @ewafula @jharenza :

AlvinF  4:21 PM
Hey Eric, We have some questions about the histologies file. In regards to TARGET ALL, How did you get the final list list of patients/samples for the whole exome data (DNA)? We are noticing there are ~800 files on isilon and ~300 files pulled from GDC.

Eric Wafula  5:14 PM
@AlvinF, I  prepared from the data manifest flies you prepared and sent me attached.  Do have the the manifest files from GDC? I can reconcile to determine common samples among the two.
DNA_manifests_-_Whole_Exome_and_DNA_Capture-Panel.zip

Eric Wafula  5:27 PM
Samples that did not have clinical info were left out. Samples sequenced multiple time are represented once the v7/v8 histologies file. Based on the conversation with Patee, multi-sequenced samples were merged when submitted to GDC. I'll send you comprehensive list of samples from all these categories shortly. Need to go back to the primary data manifest files and work way up to current histologies file.


Jo Lynne Rokita  5:33 PM
Ahh, maybe that is what it was - the merging of the samples
5:34
The samples in GDC were listed here by Brian: https://github.com/PediatricOpenTargets/ticket-tracker/issues/111#issuecomment-889344589
5:34
and that TARGET ALL file had ~800

AlvinF  5:39 PM
Those files have ~800 ALL Tumors (790 Diagnostic [with unique participant IDs] and 20 Relapsed  )... For some reason we have 308 from GDC?  Did the "split" samples that were merged have unique sample IDs? The histologies file from v7 seems to have 564 unique participant IDs for ALL

AlvinF  5:54 PM
So from original list, there are 800 matched T-N pairs -  780 diagnostic and 20 relapsed
5:55
In v7 histology, there are 564 unique cohort IDs for ALL, 289 of which have matched normals.


Jo Lynne Rokita  5:56 PM
hmm, i wonder if this is related to the sample IDs here: https://github.com/d3b-center/D3b-codes/pull/43 - can you take a look to be sure these are coded correctly? the basis of sample id was to be able to match DNA/RNA, which is what is used in PBTA … and based on the OCG coding
5:57
still, i think the bs_ids were duplicated and @Eric Wafula merged all of the data in each row to deduplicate those (correct me if i am wrong) ?


AlvinF  6:29 PM
Hmm, the numbers I got (564,289) were by cohort_participant_ID (v7 histologies) - I also looked at the BS_ids and cut off the flags which indicate aliquot, diagnosis,relapse -etc. Not sure which steps we lost the Tumor or normal and why they either are not in GDC or weren't pulled.

**Comment by afarrel** [comment]
FROM SLACK Continued:

Eric Wafula  7:00 PM
Attached  are the sample with left out because there don't corresponding info clinical files. these includes  487 Normal and 486 Tumor  samples for ALL

[TARGET_WXS_WITHOUT_CLINICAL_INFO.txt](https://github.com/PediatricOpenTargets/ticket-tracker/files/6948234/TARGET_WXS_WITHOUT_CLINICAL_INFO.txt)

**Comment by afarrel** [comment]
CONTINUED CONVERSATION FROM SLACK:



AlvinF  1:57 PM
Hi Eric and Asif, I found the clinical data for the list of ALL patients.
1:58
So if we were able to get their files from the GDC they should be included
1:58
That's in regards to the ALL patients.
1:58
I'll check the histologies on the list also

Asif Chinwalla  1:59 PM
Thanks!, whats the number of ALL samples T/N that you have clinical data for? (edited) 

AlvinF  2:00 PM
Let me get the totals

AlvinF  2:06 PM
Back to the original: 720 Diagnostic T/N pairs with clinical data, 20 Relapsed t/N pairs with clinical data;
2:06
Total: 800 T/N pairs with clinical data

Asif Chinwalla  2:08 PM
nice.  Thanks.  We should let Bo/Yuankun know to expect these additional numbers/samples

AlvinF  2:09 PM
Were all these samples available in and copied over?

Asif Chinwalla  2:10 PM
Need to check with Brian/Bo to whats available via CAVATICA, as I think the list he had gone with, did not have the full 800 set - and from the set he had, only 1 sample was in GDC but not available via CATVATICS, so required a manual upload (edited) 

Eric Wafula  2:55 PM
@AlvinF, can you send me the clinical data file? I can start working to integrate them into the v8 master histologies file

Jo Lynne Rokita  2:56 PM
they used the histology file to search, so if they weren’t in the histology file, they didn’t query
2:56
@Eric Wafula can you add these then to v8? in a new staggered PR (edited) 

Eric Wafula  3:02 PM
@AlvinF, they are not  in the current release of the histologies file. Bo might not have pull them from GDC if he was relaying on samples IDs in histologies file. @Jo Lynne Rokita, I’ll work to integrate into v8 histologies file using the staggered PR.

Jo Lynne Rokita  3:03 PM
ok, in the meantime, maybe someone can just supply a list of ids for bo and add to that wxs ticket?

AlvinF  3:21 PM
I'll create a ticket with the other ALL IDs.

Asif Chinwalla  3:24 PM
Do we need to also update TARGET DCC/Pattie - with the additional info that was missing ?

AlvinF  3:26 PM
The data should be in the TARGET portal
3:26
that's where I got it from.

**Comment by jharenza** [comment]
closing this now that we have #158
