### ISSUE TITLE
v8 data release

### ISSUE THREAD

**Issue by jharenza** [PediatricOpenTargets/ticket-tracker#151]
#### What data file(s) does this issue pertain to?
Update the following files to include new TARGET WXS data processed and per the issues that follow.
- [x] histologies.tsv
- [x] cnv-cnvkit.seg.gz
- [x] cnv-controlfreec.tsv.gz
- [x] cnv-consensus.seg.gz
- [x] ensg-hugo-rmtl-mapping.tsv
- [x] release-notes.md and data-files-description.md
- [x] snv-consensus-plus-hotspots.maf.tsv.gz
- [x] fusion-putative-oncogenic.tsv

Add the following
- [x] independent-specimens.wgswxspanel*tsv
- [x] consensus_wgs_plus_cnvkit_wxs.tsv.gz

#### What release are you using?

v7

#### Put your question or report your issue here.

- Update ensg-hugo-rmtl-mapping.tsv [here](https://github.com/d3b-center/D3b-codes/blob/master/gene_match/results/ensg-hugo-rmtl-mapping.tsv) #146 
- Update TARGET WXS samples analyzed #111  
        - #156
- Update histologies.tsv 
       - #148
       - GMKF germline_sex_estimate update https://github.com/PediatricOpenTargets/ticket-tracker/issues/160#issuecomment-898687034
       - new TARGET WXS ploidy  https://github.com/PediatricOpenTargets/ticket-tracker/issues/160#issuecomment-898744372
       - modify TARGET broad_histology column: https://github.com/PediatricOpenTargets/ticket-tracker/issues/136; https://github.com/PediatricOpenTargets/ticket-tracker/issues/176

- Update WGS consensus seg file 
      - #149
      - #134 
      - ***NOTE** cnvkit seg file was not updated in s3 for v7 so will need a rerun #81       
      - Consensus file to contain only WGS samples: https://github.com/PediatricOpenTargets/ticket-tracker/issues/152
 
- Add consensus_wgs_plus_cnvkit_wxs_autosome_and_xy.tsv.gz
      - create WGS annotated files #159 
      - create WXS annotated files #160 
      - merge in #161. 
      - A filter to remove NA status for WXS samples needs to be added to code to fix #168 

- Update independent files:
     - Incorporate changes that select same independent samples for `each cohort` and `allcohort` if possible:  https://github.com/PediatricOpenTargets/ticket-tracker/issues/135
     - Re-run the module with above-mentioned update and new histologies.tsv file: https://github.com/PediatricOpenTargets/ticket-tracker/issues/165
     - Implement an `arrange` before writing out files for easier comparison between releases https://github.com/PediatricOpenTargets/ticket-tracker/issues/179
- Update release notes and data description file: https://github.com/PediatricOpenTargets/ticket-tracker/issues/166
- Update putative oncogenic fusion using v8 histology file: https://github.com/PediatricOpenTargets/ticket-tracker/issues/175

**Comment by jharenza** [comment]
Note: the new `ensg-hugo-rmtl-mapping.tsv` file is located [here](https://github.com/d3b-center/D3b-codes/blob/master/gene_match/results/ensg-hugo-rmtl-mapping.tsv)

**Comment by logstar** [comment]
v8 `ensg-hugo-rmtl-mapping.tsv` will be updated to include all gene symbol and ENSG ID mappings in v7 `ensg-hugo-rmtl-mapping.tsv`.

I will open a PR in <https://github.com/d3b-center/D3b-codes> to implement this. I estimate this PR will be merged tomorrow morning.

**Comment by runjin326** [comment]
@logstar, so on top of the changes mentioned in[ this ticket ](https://github.com/PediatricOpenTargets/ticket-tracker/issues/146 ) (which was taken cared of by this merge https://github.com/d3b-center/D3b-codes/pull/45 I thought), we will do additional modifications on this file?

**Comment by logstar** [comment]
> @logstar, so on top of the changes mentioned in[ this ticket ](https://github.com/PediatricOpenTargets/ticket-tracker/issues/146) (which was taken cared of by this merge [d3b-center/D3b-codes#45](https://github.com/d3b-center/D3b-codes/pull/45) I thought), we will do additional modifications on this file?

Correct. I will cc you on the upcoming PR.

**Comment by runjin326** [comment]
Closing with [PR89] (https://github.com/PediatricOpenTargets/OpenPedCan-analysis/pull/89)
