### ISSUE TITLE
Updated analysis: Experimental_strategy  specific copy_consensus run

### ISSUE THREAD

**Issue by kgaonkar6** [PediatricOpenTargets/ticket-tracker#152]
#### What analysis module should be updated and why?
[copy_number_consensus_call](https://github.com/PediatricOpenTargets/OpenPedCan-analysis/tree/cnv-Manta-oveerlap-fix/analyses/copy_number_consensus_call) currently uses all samples in the following CNV files which 
```
cnv-cnvkit.seg.gz
cnv-controlfreec.tsv.gz
sv-manta.tsv.gz
```

But WGS and WXS samples need to be handled differently so the code will need update.

#### What changes need to be made? Please provide enough detail for another participant to make the update.
The options I see are:

1) Logic inside the code to only use WGS samples in [script](https://github.com/PediatricOpenTargets/OpenPedCan-analysis/blob/dev/analyses/copy_number_consensus_call/scripts/merged_to_individual_files.py) that creates the Snakemake file and run the module to generate 2/3 cnv caller consensus calls. (I believe this is faster because it doesn't have to separate the input merged files to the WXS files in scratch)

2) Logic to handle WGS and WXS separately with different Snakemake files as implemented by [bix-ops](https://github.com/d3b-center/d3b-bixu-data-assembly/tree/consensus_cnv_cwl/scripts/copy_number_consensus_call) that uses cnvkit_freec consensus calls however for OT it was decided to only use cnvkit calls for WXS ( This will help get the bixops and OT development on the same page though) 

@jharenza @logstar @zhangb1 for input.

#### What input data should be used? Which data were used in the version being updated?
v7
```
cnv-cnvkit.seg.gz
cnv-controlfreec.tsv.gz
sv-manta.tsv.gz
histologies.tsv
```

#### When do you expect the revised analysis will be completed?
2 days

#### Who will complete the updated analysis?
@kgaonkar6

**Comment by jharenza** [comment]
Cc @yuankunzhu as well

**Comment by jharenza** [comment]
Note: filenames will also need to be updated

**Comment by jharenza** [comment]
@runjin326 can you work on part 1 as priority? then, I think @zhangb1 can use this code (part 2) in the toolkit.

**Comment by runjin326** [comment]
@jharenza, sure! I will prioritize this and I'll ping you and @zhangb1 when completed!

**Comment by runjin326** [comment]
@jharenza, hmm I am getting a bit confused right now. I think the [code in this script](https://github.com/PediatricOpenTargets/OpenPedCan-analysis/blob/3207f152fc762e53fc8aa487e8aa8b2e2d578fa3/analyses/copy_number_consensus_call/scripts/merged_to_individual_files.py#L68-L98) already subset for WGS and only run for those? And I think the [run script already called the right file](https://github.com/PediatricOpenTargets/OpenPedCan-analysis/blob/3207f152fc762e53fc8aa487e8aa8b2e2d578fa3/analyses/copy_number_consensus_call/run_consensus_call.sh#L22-L29) (although the README.md does need an update)?
I also ran the code that generate the snakeMake and individual file , they all have 1276 samples which is as expected for all WGS + Tumor. Am I missing something here?

**Comment by jharenza** [comment]
Ahh, ok- I thought @kgaonkar6 did this for v7, but then saw the ticket - so maybe part 1 is complete.

**Comment by kgaonkar6** [comment]
The code is run on v7 but since we didn't add any more WGS in v8 the files in the `dev` branch is up-to-date.

**Comment by runjin326** [comment]
Close with [PR89](https://github.com/PediatricOpenTargets/OpenPedCan-analysis/pull/89)
