### ISSUE TITLE
merge TARGET WXS to existing SNV and CNV files for data release

### ISSUE THREAD

**Issue by kgaonkar6** [PediatricOpenTargets/ticket-tracker#156]
What data file(s) does this issue pertain to?

- cnv-cnvkit.seg.gz
- cnv-controlfreec.tsv.gz
- snv-consensus-plus-hotspots.maf.tsv.gz 

What release are you using?
v7

Put your question or report your issue here.
Please support v8 data release 
- [x] New TARGET WXS files were generated  [here](https://github.com/PediatricOpenTargets/ticket-tracker/issues/111)
- Merge v7 SNV consensus MAF (above) with consensus MAFs from TARGET new WXS 
- Merge v7 controlfreeC TSV (above) with controlfreeC output from TARGET new WXS 
- Merge v7 CNVkit seg (above) with CNVkit output from TARGET new WXS 

- [ ] Upload to v8 folder: s3://kf-openaccess-us-east-1-prd-pbta/open-targets/v8/
- [ ] G enerate md5sums and update md5sum.txt file in v8 folder

cc @zhangb1 @yuankunzhu

**Comment by kgaonkar6** [comment]
Hi @zhangb1  just wanted to confirm if you have the toolkit set up to run the annoated cnvkit 

`RUN_ORIGINAL=1 bash analyses/focal-cn-file-preparation/run-prepare-cn.sh`

which we then want to merge with WGS consensus file (2 of 3) like below

```
consensus_seg_annotated_cn_autosomes.tsv.gz + cnvkit_annotated_cn_wxs_autosomes.tsv.gz 
 to create consensus_wgs_plus_cnvkit_wxs_autosomes.tsv.gz

```

```
consensus_seg_annotated_cn_x_and_y.tsv.gz + cnvkit_annotated_cn_wxs_x_and_y.tsv.gz 
 to create consensus_wgs_plus_cnvkit_wxs_x_and_y.tsv.gz
```

**Comment by jharenza** [comment]
@zhangb1 how are you adding WXS cnvkit only files to the consensus seg file in the toolkit if not annotating them? (I thought you mentioned yesterday that you had this in the workflow now?)

**Comment by zhangb1** [comment]
> @zhangb1 how are you adding WXS cnvkit only files to the consensus seg file in the toolkit if not annotating them? (I thought you mentioned yesterday that you had this in the workflow now?)

sorry I may be misunderstand.... for the WXS in my cwl only get the CNVkit merged files no annotation,    also keep the consensus using the both control-freeC and cnvkit  results for the annotation.

**Comment by kgaonkar6** [comment]
Thanks for the clarification @zhangb1 !

Here's what we have done before for v7 : 
@runjin326 updated 04 script https://github.com/PediatricOpenTargets/OpenPedCan-analysis/blob/dev/analyses/focal-cn-file-preparation/04-prepare-cn-file.R to be able to run annotation only for WXS samples to create a WXS-only annotated cnkit file.

The commands are here:
https://github.com/PediatricOpenTargets/OpenPedCan-analysis/blob/241521a8d12c01c5f79e044722f4990a77a9ce5e/analyses/focal-cn-file-preparation/run-prepare-cn-OpenTarget.sh#L47-L65

And merged the annotated cnvkit with consensus consensus_seg_annotated_cn_autosomes.tsv.gz and consensus_seg_annotated_cn_x_and_y.tsv.gz

cc @runjin326 to add anything that I've missed.

**Comment by zhangb1** [comment]
Thank you @kgaonkar6 . seems for the WXS we only keep the CNVkit seg file for the annotation?  . then I need to change my cwl tool to adapt that then.  sorry I am not quite clear about that .

**Comment by jharenza** [comment]
It seems like we might need to have a quick internal meeting about this @zhangb1 @yuankunzhu

**Comment by kgaonkar6** [comment]
Since there needs to be more detailed discussion over the creating annotated CNV seg files @jharenza suggested I make different tickets, create WGS annotated files #159 and create WXS annotated files #160 and merge in #161. We can follow up there for further discussion. Thanks!

**Comment by zhangb1** [comment]
```
cnv-cnvkit.seg.gz
cnv-controlfreec.tsv.gz
snv-consensus-plus-hotspots.maf.tsv.gz
```
These 3 files have been updated in the s3 bucket:   s3://kf-openaccess-us-east-1-prd-pbta/open-targets/v8/ 
I will do the data merge and update the md5 later

**Comment by zhangb1** [comment]
while doing the merge, I found this issue haven't been solved . 

https://github.com/PediatricOpenTargets/ticket-tracker/issues/81

So I update the GMKF , cnvkit result with the tumor ID, and updated in the cnv-cnvkit.seg.gz file.  s3://kf-openaccess-us-east-1-prd-pbta/open-targets/v8/

@kgaonkar6 @jharenza

**Comment by kgaonkar6** [comment]
Thanks for pointing that out, I'm rerunning WGS consensus cnv for v8

**Comment by kgaonkar6** [comment]
Sorry for the confusion, I think since the code in updated in https://github.com/PediatricOpenTargets/OpenPedCan-analysis/tree/dev/analyses/copy_number_consensus_call  @zhangb1 could rerun the code with the new merged v8 files (which fixes the tumor normal ID for GMKF WGS issues that seems I missed to upload to s3 for v7 )

**Comment by zhangb1** [comment]
This has been done in the v8 release.
