### ISSUE TITLE
Start Downloading Missing TARGET ALL WXS Data from GDC and harmonizing it

### ISSUE THREAD

**Issue by afarrel** [PediatricOpenTargets/ticket-tracker#158]
#### What data file(s) does this issue pertain to?
TARGET Acute lymphoblastic leukemia (ALL) WXS data for pedOT

#### What release are you using?

v7, v8

#### Put your question or report your issue here.
In issue [#150](https://github.com/PediatricOpenTargets/ticket-tracker/issues/150), We were assessing the discrepancy between the 800 WXS T/N pairs on isilon and the 308 WXS pairs in the histologies file in v7.
About 970 samples representing 485 patients were listed as samples without clinical data available, but after further investigation we found that the clinical data is available for these samples.

Can we download these additional 970 samples representing 485 T/N pairs and begin harmonizing/processing them? 
[TARGET_AL_WXS_Additional_samples_WITH_CLINICAL_INFO.txt](https://github.com/PediatricOpenTargets/ticket-tracker/files/6971293/TARGET_AL_WXS_Additional_samples_WITH_CLINICAL_INFO.txt)

We will include them in the next (v8) version of the histologies file.

This should solve the discrepancy between the numbers reported in ticket [#111](https://github.com/PediatricOpenTargets/ticket-tracker/issues/111#issuecomment-890155727) and the 800 T/N we see on isilon with matching clinical data.

Comments, questions, and concerns from @yuankunzhu @zhangb1  @jharenza @chinwallaa @ewafula are welcomed.

**Comment by jharenza** [comment]
Thanks @afarrel - cc-ing @bmennis to do the query since he had worked on this.

**Comment by zhangb1** [comment]
I just did a quick check the bam files in the GDC datasets, I can find 921 uuid the same as the in  list `TARGET_AL_WXS_Additional_samples_WITH_CLINICAL_INFO.txt` 

but the 49 samples below I can't find in the query. 

```
Sample_ID	Patient_ID	Experimental_Strategy	Sample_Type	Primary_Site
TARGET-10-PANURR-09A-01D	PANURR	WXS	Tumor	Bone Marrow
TARGET-10-PARJBZ-03A-01D	PARJBZ	WXS	Tumor	Peripheral Whole Blood
TARGET-10-PARCKJ-03A-01D	PARCKJ	WXS	Tumor	Peripheral Whole Blood
TARGET-10-PARDFI-09A-01D	PARDFI	WXS	Tumor	Bone Marrow
TARGET-10-PARDHW-09A-01D	PARDHW	WXS	Tumor	Bone Marrow
TARGET-10-PAREBA-09A-01D	PAREBA	WXS	Tumor	Bone Marrow
TARGET-10-PAREEE-09A-01D	PAREEE	WXS	Tumor	Bone Marrow
TARGET-10-PANWWG-09A-01D	PANWWG	WXS	Tumor	Bone Marrow
TARGET-10-PANXLC-09A-01D	PANXLC	WXS	Tumor	Bone Marrow
TARGET-10-PANZSE-09A-01D	PANZSE	WXS	Tumor	Bone Marrow
TARGET-10-PAPAMA-09A-01D	PAPAMA	WXS	Tumor	Bone Marrow
TARGET-10-PAPIPG-09A-01D	PAPIPG	WXS	Tumor	Bone Marrow
TARGET-10-PAPZWP-09A-01D	PAPZWP	WXS	Tumor	Bone Marrow
TARGET-10-PARBRM-09A-01D	PARBRM	WXS	Tumor	Bone Marrow
TARGET-10-PARBZT-09A-01D	PARBZT	WXS	Tumor	Bone Marrow
TARGET-10-PARCSH-09A-01D	PARCSH	WXS	Tumor	Bone Marrow
TARGET-10-PANUKF-09A-01D	PANUKF	WXS	Tumor	Bone Marrow
TARGET-10-PARHMT-09A-01D	PARHMT	WXS	Tumor	Bone Marrow
TARGET-10-PARGLI-09A-01D	PARGLI	WXS	Tumor	Bone Marrow
TARGET-10-PARGYV-09A-01D	PARGYV	WXS	Tumor	Bone Marrow
TARGET-10-PARKBT-09A-01D	PARKBT	WXS	Tumor	Bone Marrow
TARGET-10-PANXZX-09A-01D	PANXZX	WXS	Tumor	Bone Marrow
TARGET-10-PANYDL-09A-01D	PANYDL	WXS	Tumor	Bone Marrow
TARGET-10-PANYHB-03A-01D	PANYHB	WXS	Tumor	Peripheral Whole Blood
TARGET-10-PANYJL-09A-01D	PANYJL	WXS	Tumor	Bone Marrow
TARGET-10-PANYJV-09A-01D	PANYJV	WXS	Tumor	Bone Marrow
TARGET-10-PANYXD-09A-01D	PANYXD	WXS	Tumor	Bone Marrow
TARGET-10-PANYXR-09A-01D	PANYXR	WXS	Tumor	Bone Marrow
TARGET-10-PANZBR-09A-01D	PANZBR	WXS	Tumor	Bone Marrow
TARGET-10-PANZCF-09A-01D	PANZCF	WXS	Tumor	Bone Marrow
TARGET-10-PANZPU-09A-01D	PANZPU	WXS	Tumor	Bone Marrow
TARGET-10-PARCHY-09A-01D	PARCHY	WXS	Tumor	Bone Marrow
TARGET-10-PARDIN-09A-01D	PARDIN	WXS	Tumor	Bone Marrow
TARGET-10-PARDSN-09A-01D	PARDSN	WXS	Tumor	Bone Marrow
TARGET-10-PANUXU-14A-01D	PANUXU	WXS	Normal	Bone Marrow
TARGET-10-PARJJP-10A-01D	PARJJP	WXS	Normal	Peripheral Whole Blood
TARGET-10-PARCMD-10A-01D	PARCMD	WXS	Normal	Peripheral Whole Blood
TARGET-10-PAREDS-10A-01D	PAREDS	WXS	Normal	Peripheral Whole Blood
TARGET-10-PANWEI-10A-01D	PANWEI	WXS	Normal	Peripheral Whole Blood
TARGET-10-PANWJH-10A-01D	PANWJH	WXS	Normal	Peripheral Whole Blood
TARGET-10-PANWLH-10A-01D	PANWLH	WXS	Normal	Peripheral Whole Blood
TARGET-10-PANXLC-10A-01D	PANXLC	WXS	Normal	Peripheral Whole Blood
TARGET-10-PARCGU-10A-01D	PARCGU	WXS	Normal	Peripheral Whole Blood
TARGET-10-PARDCJ-10A-01D	PARDCJ	WXS	Normal	Peripheral Whole Blood
TARGET-10-PAREKG-10A-01D	PAREKG	WXS	Normal	Peripheral Whole Blood
TARGET-10-PARRKG-10A-01D	PARRKG	WXS	Normal	Peripheral Whole Blood
TARGET-10-PARRPA-14A-01D	PARRPA	WXS	Normal	Bone Marrow
TARGET-10-PANXZX-14A-01D	PANXZX	WXS	Normal	Bone Marrow
TARGET-10-PARDCR-10A-01D	PARDCR	WXS	Normal	Peripheral Whole Blood
```

any ideas where I can get the data?  @jharenza @afarrel ?

**Comment by jharenza** [comment]
I think that is fine if those are missing - @afarrel will take those back to Patee at NIH. 

Just to note, we can move this data processing to after August and for v9.

**Comment by bmennis** [comment]
@jharenza @afarrel, do we have the target and bait interval bed files for these samples?

**Comment by jharenza** [comment]
> @jharenza @afarrel, do we have the target and bait interval bed files for these samples?

cc @ewafula on this

**Comment by bmennis** [comment]
@ewafula @jharenza  I want to update that the additional ALL samples are finished running through alignment with one tumor sample that has permission issues. That sample is not finished, but I have asked the SBG team to look into the permission issue. I will start preparing for the somatic analysis of the tumor and normal paired samples.

The file name that has the permission issue is: 60ac91fc-422d-5297-a65b-2fbea320937b_wxs_gdc_realn.bam
the aliquot ID is: TARGET-10-PARUBU-09A-01D

**Comment by jharenza** [comment]
Thanks @bmennis! Do you have the list of samples completed that you can attach here?

**Comment by bmennis** [comment]
Ok to update the tumor sample that had/has access issues was aligned. I downloaded the sample from the GDC, uploaded it to Cavatica and aligned it in the tumor WXS project. I then ran NGS checkmate on its matching paired normal sample and it is a match.

The somatic analysis for the paired samples has been run as well. In total there are 438 paired tumor and normal samples, this includes the tumor sample with the access issues and its normal paired sample. All pairs have completed and I am patching metadata to the outputs now, unfortunately this will take some time due to the large amount of files from the many pairs. I will run consensus calling as the outputs get tagged with metadata and will update further.

**Comment by ewafula** [comment]
@bmennis,can you post sample IDs for the normal/tumor pairs that you have successfully analyzed. Need to use them for updating the OpenPedCan v10 histologies file.

**Comment by jharenza** [comment]
Thank you @bmennis and @ewafula

**Comment by bmennis** [comment]
@ewafula do you need all additional ALL samples analyzed in this ticket or just the tumor and normal paired samples?

**Comment by ewafula** [comment]
@bmennis, yes the normal and tumor pairs. In v9 we left out sample that were not paired.

**Comment by bmennis** [comment]
@ewafula here is the list of tumor and matching normal aliquot IDs for the additional ALL samples. Let me know if you have any questions. This has the 438 pairs processed

[Additional_ALL_samples_somatic_pairs.txt](https://github.com/PediatricOpenTargets/ticket-tracker/files/7197807/Additional_ALL_samples_somatic_pairs.txt)

**Comment by ewafula** [comment]
@bmennis, thank you!

**Comment by bmennis** [comment]
I have also copied over the somatic outputs to the open target delivery project. The outputs copied over include the public and protected outputs for all 4 variant callers, the manta pass vcf and index, as well as cnvkit gainloss and controlfreec p values and ratios. Also the consensus outputs were all copied over. This pertains to the additional ALL samples both somatic and alignment analysis

**Comment by runjin326** [comment]
Hi, @zhangb1! Could you please post the `tumor_ploidy` information for the 438 tumor samples in here so that @ewafula can update our current histology file? Thanks!

**Comment by zhangb1** [comment]
@runjin326  , @bmennis will get that .

**Comment by bmennis** [comment]
@runjin326 @zhangb1 I have generated a file containing the tumor IDs as well as the ploidy. I have it attached here, let me know if there are any issues
[tumor_id_ploidy.txt](https://github.com/PediatricOpenTargets/ticket-tracker/files/7255282/tumor_id_ploidy.txt)
