### ISSUE TITLE
Updated analysis: Generate cnvkit_annotated_cn_wxs_[autosomes|x_and_y].tsv.gz

### ISSUE THREAD

**Issue by kgaonkar6** [PediatricOpenTargets/ticket-tracker#160]
#### What analysis module should be updated and why?
We need to rerun annotation because WGS consensus seg was updated and available in dev we will annotate the CNV region if it overlaps with a gene region.

#### What changes need to be made? Please provide enough detail for another participant to make the update.
Just a rerun of focal-cn-file-preparation module for original cnv merged files as below:

` RUN_ORIGINAL=1 bash analyses/focal-cn-file-preparation/run-prepare-cn-OpenTarget.sh`

#### What input data should be used? Which data were used in the version being updated?
**v8**
histologies.tsv
cnv-cnvkit.seg.gz
cnv-controlfreec.tsv.gz

#### Who will complete the updated analysis?

**Comment by zhangb1** [comment]
One question here, We don't have the germline_estimate_gender for the pannel and WXS, the code are using the germline_estimate_gender  column in the histology file. 

 how should we handle that ? 

@jharenza @kgaonkar6

**Comment by kgaonkar6** [comment]
Thanks for checking this our @zhangb1!

 I see some Tumor WXS in PBTA did have gender_sex_estimates in v7 but GMKF WGS didn't have gender-estimates as well. Do we know how some PBTA WXS have the gender_sex_estimates? 

```
histology[which(histology$experimental_strategy != "RNA-Seq" & histology$sample_type=="Tumor"),]%>% group_by(germline_sex_estimate,cohort,experimental_strategy) %>% tally()
# A tibble: 9 × 4
# Groups:   germline_sex_estimate, cohort [5]
  germline_sex_estimate cohort experimental_strategy     n
  <chr>                 <chr>  <chr>                 <int>
1 Female                PBTA   WGS                     429
2 Female                PBTA   WXS                       7
3 Male                  PBTA   Targeted Sequencing       1
4 Male                  PBTA   WGS                     511
5 Male                  PBTA   WXS                       8
6 NA                    GMKF   WGS                     336
7 NA                    PBTA   WXS                      16
8 NA                    TARGET Targeted Sequencing     499
9 NA                    TARGET WXS                     701

```

**Comment by zhangb1** [comment]
I am adding GMKF WGS gender-estimates in the v8 histology file now. 

PBTA WXS I just checked, those are from PNOC003, which has both WGS and WXS data. I am not quite who add that. but maybe use the same gender-estimates as it's WGS . @kgaonkar6

**Comment by kgaonkar6** [comment]
Thanks @zhangb1 , do we have a file with the ploidy for the new TARGET WXS?

**Comment by zhangb1** [comment]
Yes ,here : 
[tumor_ploidy_extre_WXS_target.txt](https://github.com/PediatricOpenTargets/ticket-tracker/files/6985352/tumor_ploidy_extre_WXS_target.txt)

**Comment by zhangb1** [comment]
WXS cnvkit annotation also done , this can be close too
