### ISSUE TITLE
Create consensus_wgs_plus_cnvkit_wxs_[autosomes|x_and_y].tsv.gz 

### ISSUE THREAD

**Issue by kgaonkar6** [PediatricOpenTargets/ticket-tracker#161]
#### What data file(s) does this issue pertain to?
- consensus_wgs_plus_cnvkit_wxs_autosomes.tsv.gz
- consensus_wgs_plus_cnvkit_wxs_x_and_y.tsv.gz

#### What release are you using?

v8

#### Put your question or report your issue here.
We will need to merge output files from #159  and #160 such that 
- merging consensus_seg_annotated_cn_autosomes.tsv.gz + cnvkit_annotated_cn_wxs_autosomes.tsv.gz 
  creates consensus_wgs_plus_cnvkit_wxs_autosomes.tsv.gz

- merging consensus_seg_annotated_cn_x_and_y.tsv.gz + cnvkit_annotated_cn_wxs_x_and_y.tsv.gz 
  creates consensus_wgs_plus_cnvkit_wxs_x_and_y.tsv.gz

**Comment by jharenza** [comment]
@kgaonkar6 while we are updating these, maybe we can handle autosomes and xy as one file?

**Comment by zhangb1** [comment]
The data has been merged and copy to V8 :
as long as the cnvkit , controlfreec and maf merged files ., md5 also updated

```
cnv-cnvkit.seg.gz
cnv-controlfreec.tsv.gz
consensus_wgs_plus_cnvkit_wxs_autosomes.tsv.gz
consensus_wgs_plus_cnvkit_wxs_x_and_y.tsv.gz
snv-consensus-plus-hotspots.maf.tsv.gz
```

**Comment by jharenza** [comment]
cc @runjin326 @logstar @afarrel

**Comment by runjin326** [comment]
Merged file uploaded to S3 and file name change already merged.

**Comment by runjin326** [comment]
Close with [PR89 ](https://github.com/PediatricOpenTargets/OpenPedCan-analysis/pull/89).
