### ISSUE TITLE
Updated analysis: Rerun independent samples modules for v8

### ISSUE THREAD

**Issue by kgaonkar6** [PediatricOpenTargets/ticket-tracker#165]
#### What analysis module should be updated and why?

We have added new Target WXS to v8 so we will need to rerun https://github.com/PediatricOpenTargets/OpenPedCan-analysis/tree/dev/analyses/independent-samples to create updated independent-specimens.wgswxspanel.*.tsv files. 

#### What changes need to be made? Please provide enough detail for another participant to make the update.

Rerun

#### What input data should be used? Which data were used in the version being updated?
v8 histologies.tsv 

#### When do you expect the revised analysis will be completed?
1 day

#### Who will complete the updated analysis?
@runjin326

**Comment by runjin326** [comment]
Close with [PR89 ](https://github.com/PediatricOpenTargets/OpenPedCan-analysis/pull/89).
