### ISSUE TITLE
Updated analysis: subset each-cohort independent primary tumor RNA-seq samples in `tumor-gtex-plots` module

### ISSUE THREAD

**Issue by logstar** [PediatricOpenTargets/ticket-tracker#169]
#### What analysis module should be updated and why?

The `tumor-gtex-plots` module should be updated to subset each-cohort independent primary tumor RNA-seq samples before generating plots/results. The motivation is to have only one primary tumor RNA-seq sample for each patient of each cohort in the plots/results.

The list of each-cohort independent primary tumor RNA-seq samples (`analyses/independent-samples/results/independent-specimens.rnaseq.primary.eachcohort.tsv`) is generated in the [`independent-samples` module](https://github.com/PediatricOpenTargets/OpenPedCan-analysis/tree/dev/analyses/independent-samples), essentially by selecting only one primary tumor RNA-seq sample for each patient in each cohort.

#### What changes need to be made? Please provide enough detail for another participant to make the update.

Subset RNA-seq samples in `gene-expression-rsem-tpm-collapsed.rds` before generating plots/results.

- For tumor RNA-seq samples, subset samples in `analyses/independent-samples/results/independent-specimens.rnaseq.primary.eachcohort.tsv`.
- For GTEx samples, use all samples like before without any subsetting.

#### What input data should be used? Which data were used in the version being updated?

Input data for `tumor-gtex-plots`.

`analyses/independent-samples/results/independent-specimens.rnaseq.primary.eachcohort.tsv`.

#### When do you expect the revised analysis will be completed?

1-3 days

#### Who will complete the updated analysis?

@komalsrathi 

cc @jharenza

**Comment by logstar** [comment]
Hi @komalsrathi . Same note as in #171 .

> I added `blocked` label to this issue, because the `tumor-gtex-plots` module development/maintenance will temporarily be suspended. The `tumor-gtex-plots` module will be updated at a later point to switch from R API to javascript boxplots.
>
> The code in `tumor-gtex-plots` will be used to develop an R API at <https://github.com/PediatricOpenTargets/OpenPedCan-api> by @taylordm and @logstar for PedOT website demo or production.

**Comment by komalsrathi** [comment]
@logstar will we be still doing this for the `tumor-gtex-plots` module?
