### ISSUE TITLE
Add tumor gtex plot code to api repo

### ISSUE THREAD

**Issue by jharenza** [PediatricOpenTargets/ticket-tracker#170]
#### What has to be done?
Add https://github.com/PediatricOpenTargets/OpenPedCan-exprs-shinyapp code to https://github.com/PediatricOpenTargets/OpenPedCan-api

#### What release are you using?

v7

#### Who will do this?
@komalsrathi 

cc @blackdenc @taylordm @chinwallaa

**Comment by komalsrathi** [comment]
@jharenza Ok just realized, I had made all the new changes to the OpenPedCan module but not to the shiny app (plot output is fine but need to update the tsv output). I will update the shiny app code by end of this week and add to the repo.

**Comment by komalsrathi** [comment]
@blackdenc I just pushed the app code to the repo under the branch `shiny-app`. Please let me know if you have Qs.
