### ISSUE TITLE
V8 histologies file broad_histology update

### ISSUE THREAD

**Issue by runjin326** [PediatricOpenTargets/ticket-tracker#176]
#### What data file(s) does this issue pertain to?
v8 histologies.tsv

#### What release are you using?

Some of the broad_histology columns for TARGET samples are not consistent with what we have for other samples. Modifications needed.

#### Put your question or report your issue here.
Please modify the following:
`Embryonal tumors` to `Embryonal tumor`
`Mesenchymal, non-meningothelial tumors` to `Mesenchymal non-meningothelial tumor`

cc: @jharenza, do we want to also change `Hematologic malignancies` to `Hematologic malignancy` and `Renal tumors` to `Renal tumor` since most of the broad_histology column seemed to be in singular form?

**Comment by jharenza** [comment]
>cc: @jharenza, do we want to also change Hematologic malignancies to Hematologic malignancy and Renal tumors to Renal tumor since most of the broad_histology column seemed to be in singular form?

We can do that

**Comment by runjin326** [comment]
Close with [PR89 ](https://github.com/PediatricOpenTargets/OpenPedCan-analysis/pull/89)
