### ISSUE TITLE
Updated analysis: Rerun `rna-seq-expression-summary-stats` module for v9 data release

### ISSUE THREAD

**Issue by logstar** [PediatricOpenTargets/ticket-tracker#178]
#### What analysis module should be updated and why?

The `rna-seq-expression-summary-stats` module should be updated for v9 data release, after the following issues are closed.

- <https://github.com/PediatricOpenTargets/OpenPedCan-analysis/pull/103>
- <https://github.com/PediatricOpenTargets/ticket-tracker/issues/151>
- <https://github.com/PediatricOpenTargets/ticket-tracker/issues/172>
- <https://github.com/PediatricOpenTargets/ticket-tracker/issues/165>

#### What changes need to be made? Please provide enough detail for another participant to make the update.

- [x] Download v9 data.
- [x] Rerun `analyses/rna-seq-expression-summary-stats/run-rna-seq-expression-summary-stats.sh` using v9 independent sample lists.
- [x] Implement #138.
- [x] (EDIT SEP-1-2021 YZ) Use `n >= 3` for selecting `cancer_group`s. Could start by changing <https://github.com/PediatricOpenTargets/OpenPedCan-analysis/blob/ee98df11477ae3dabc7e788ada4bdfa43add05b4/analyses/rna-seq-expression-summary-stats/01-tpm-summary-stats.R#L437> and <https://github.com/PediatricOpenTargets/OpenPedCan-analysis/blob/ee98df11477ae3dabc7e788ada4bdfa43add05b4/analyses/rna-seq-expression-summary-stats/01-tpm-summary-stats.R#L503>.
- [x] Update `analyses/rna-seq-expression-summary-stats/README.md`.
- [x] (EDIT SEP-1-2021 YZ) Lint R code with the following bash command and fix all style suggestions and warnings, `Rscript --vanilla -e "lintr::lint(filename = '01-tpm-summary-stats.R', linters = lintr::with_defaults(object_name_linter = NULL, assignment_linter = NULL, line_length_linter = lintr::line_length_linter(80), spaces_left_parentheses_linter = NULL, commented_code_linter = NULL, object_length_linter = NULL, cyclocomp_linter = lintr::cyclocomp_linter(complexity_limit = 35L), single_quotes_linter = NULL, object_usage_linter = NULL, infix_spaces_linter = NULL))"`.

#### What input data should be used? Which data were used in the version being updated?

Input data for `rna-seq-expression-summary-stats` module.

#### When do you expect the revised analysis will be completed?

(EDIT 01-SEP-2021) 1-2 days

#### Who will complete the updated analysis?

@ewafula 

@runjin326 could review the upcoming PR.

cc @jharenza

**Comment by logstar** [comment]
To implement <https://github.com/PediatricOpenTargets/ticket-tracker/issues/138>, you could start with the following points

- Update all code that is affected by having an additional [`rna_idps_df` variable](https://github.com/PediatricOpenTargets/OpenPedCan-analysis/blob/afbd6c6c6d9c61db6a4bec01962f7ddccabea6fa/analyses/rna-seq-expression-summary-stats/01-tpm-summary-stats.R#L380-L383).
- Update the [code here](https://github.com/PediatricOpenTargets/OpenPedCan-analysis/blob/afbd6c6c6d9c61db6a4bec01962f7ddccabea6fa/analyses/rna-seq-expression-summary-stats/01-tpm-summary-stats.R#L430-L543) to use corresponding independent sample lists for generating results all-cohorts and each-cohort results. There are two sections of code for all-cohorts and each-cohort respectively.

**Comment by runjin326** [comment]
Closing with [PR106](https://github.com/PediatricOpenTargets/OpenPedCan-analysis/pull/106) and lintr testing passed.
