### ISSUE TITLE
Updated analysis: tumor-gtex-plots to include a plot of all tumor groups per cancer type

### ISSUE THREAD

**Issue by jharenza** [PediatricOpenTargets/ticket-tracker#180]
#### What analysis module should be updated and why?
`tumor-gtex-plots`

Per FNL's, John Maris's, and Sharon Diskin's suggestions, add another plot view which includes `all_cohorts`, `cohort_cancer_group_1`, `cohort_cancer_group_2`, etc

For example, see box file https://nih.box.com/s/vun4nl8d124p4a28wuf1xbv3ts15h99y - Option 1

#### What changes need to be made? Please provide enough detail for another participant to make the update.
- add another plot view which includes `all_cohorts`, `cohort_cancer_group_1`, `cohort_cancer_group_2`, etc
- assuming we would need another table view of this, but should confirm on Monday internally or Wednesday with FNL about these table exports cc @jonkiky 

#### What input data should be used? Which data were used in the version being updated?
same

#### When do you expect the revised analysis will be completed?
next week?

#### Who will complete the updated analysis?
@komalsrathi

**Comment by komalsrathi** [comment]
@jharenza So I am thinking there could be two types in this combined plot, right?:

For each gene, say MYCN:

1) cohort + cancer group level: `GMKF NBL`, `TARGET NBL`, `TARGET ALL`, `TARGET AML` ..., `GTEx Adipose`, `GTEx Brain` ...
2) cancer group level: `NBL`, `ALL`, `AML` ... , `GTEx Adipose`, `GTEx Brain` ...

**Comment by jharenza** [comment]
It would only be specific to a cancer group - this plot would be "combined (all NBL), TARGET NBL, GMKF NBL, GTEX..."

**Comment by komalsrathi** [comment]
Oh okay, so this combined plot will ONLY get generated for Neuroblastoma (as of `v8`) as this cancer group is overlapping in `> 1 cohort`.

**Comment by jharenza** [comment]
That's a good point - at the moment, yes.

**Comment by jharenza** [comment]
@logstar - do you think we should close this, as we are now implementing within the api and not in the module?

**Comment by logstar** [comment]
@jharenza Thank you for asking. I agree. I think we could close this PR. If PedOT starts a transition to use pre-generated static images and tables, we could reopen this issue.
