### ISSUE TITLE
White spaces in cancer types (EFO-MONDO-MAP)

### ISSUE THREAD

**Issue by komalsrathi** [PediatricOpenTargets/ticket-tracker#181]
#### What data file(s) does this issue pertain to?

efo-mondo-map.tsv

#### What release are you using?

v8

#### Put your question or report your issue here.

EFO MONDO map has white spaces in a few cancer types so mapping to other tsv files on these cancer types returns NULL:

```
efo_mondo_map <- read.delim('data/efo-mondo-map.tsv') %>%
  unique()
grep(" $",efo_mondo_map$cancer_group, value = T)
[1] "Acute Lymphoblastic Leukemia " "Acute Myeloid Leukemia "      
[3] "Chordoma "
```

**Comment by logstar** [comment]
Thank you for catching the white spaces, @komalsrathi !

@runjin326 I wonder if it is still possible to update v8 `efo-mondo-map.tsv` to remove the white spaces described in this issue.

@komalsrathi One quick fix is to use `readr::read_tsv` to read `efo-mondo-map.tsv`, as `readr::read_tsv` trims leading and tailing white spaces by default.

`annotator` uses `readr::read_tsv` to read `efo-mondo-map.tsv`, so these white spaces did not affect previous JSONL results.

cc @jharenza

**Comment by runjin326** [comment]
@logstar, I think what @jharenza mentioned before is that after we merge the release-note and the download script, we normally wouldn't update anything in the S3 bucket and all other fixes would be included in v9. Does that sound right, @jharenza?

**Comment by logstar** [comment]
> @logstar, I think what @jharenza mentioned before is that after we merge the release-note and the download script, we normally wouldn't update anything in the S3 bucket and all other fixes would be included in v9. Does that sound right, @jharenza?

Thank you for the quick reply. I wonder if you could remove the white spaces in v9.

For any `efo-mondo-map.tsv` use case that is affected by these white spaces before v9, the use case code could be updated to trim the white spaces.

**Comment by komalsrathi** [comment]
> Thank you for catching the white spaces, @komalsrathi !
> 
> @runjin326 I wonder if it is still possible to update v8 `efo-mondo-map.tsv` to remove the white spaces described in this issue.
> 
> @komalsrathi One quick fix is to use `readr::read_tsv` to read `efo-mondo-map.tsv`, as `readr::read_tsv` trims leading and tailing white spaces by default.
> 
> `annotator` uses `readr::read_tsv` to read `efo-mondo-map.tsv`, so these white spaces did not affect previous JSONL results.
> 
> cc @jharenza

@logstar Thank you for the workaround, I will use that in my code.

**Comment by runjin326** [comment]
> Thank you for the quick reply. I wonder if you could remove the white spaces in v9.
> 
> For any `efo-mondo-map.tsv` use case that is affected by these white spaces before v9, the use case code could be updated to trim the white spaces.

Sure I will take note of that and fix that in v9.

**Comment by jharenza** [comment]
@komalsrathi this may have been taken care of with the annotator - have you tried running that cc @logstar

**Comment by komalsrathi** [comment]
Oh okay, I don't run the annotator in the shiny app and do a merge with the `efo-mondo-map.tsv` and `ensg-hugo-rmtl-mapping.tsv` within the code (to make it less complicated) - but it is working with the readr::read_tsv function so if you want we can close this.

**Comment by runjin326** [comment]
Closing since using 'readr::read_tsv function' this is no longer an issue.
