### ISSUE TITLE
Update EFO MONDO file with EFO IDs

### ISSUE THREAD

**Issue by afarrel** [PediatricOpenTargets/ticket-tracker#182]
#### What data file(s) does this issue pertain to?

efo-mondo-map.tsv

#### What release are you using?

v8/v9

#### Put your question or report your issue here.

Update  EFO/MONDO designations in efo-mondo-map.tsv
Assign all EFO IDs based on information from Open Targets and OLS. (EFO ID may start with "MONDO_######", etc)

#### Who will work on this:

@sangeetashukla  and @afarrel

**Comment by afarrel** [comment]
[efo-mondo-map_NEW.xlsx](https://github.com/PediatricOpenTargets/ticket-tracker/files/7080883/efo-mondo-map_NEW.xlsx)

Hi @sangeetashukla and @jharenza 
I took at look at the list Sangeeta put together and the original list and looked up the EFO codes from OLS and the OpenTargets platform. The 'NEW' codes are in Column E Some are missing with notes and I have specific questions below so we can decide and confirm which codes we should use:

For "**Germinoma;Teratoma**"  Germinoma is EFO_0000514, Teratoma is MONDO_0002601. There is only one patient with this 'combination/histology' - which means they will be excluded from the analysis modules the require n >= 5.

For "**Choroid plexus cyst**" - Are we including cysts even though it's not a tumor? Also, N = 1 patient with 1 NGS and 1 RNAseq  which means they will be excluded from the analysis modules the require n >= 5.

Confirm **CNS Embryonal tumor**:MONDO_0018843 (Actual Description is: embryonal carcinoma of the central nervous system)

"**CNS neuroblastoma**" - will have the same EFO code as neuroblastoma. - The EFO code covers Neuroblastoma and "Central Neuroblastoma" as well as other subtypes of neuroblastoma? Would we need to get subtype EFO/MONDO codes for NBL too?

"**Diffuse midline glioma**" - (DMG) has no code. Currently using DIPG code. DMG with H3 K27M-Mutant does have NCIT codes: NCIT_C129309; DOID_0080684

"**Dysplasia/Gliosis;Glial-neuronal tumor NOS**" - Should there be separates histologies?  Gliosis is HP_0002171 and mixed neuronal-glial tumor is MONDO_0016729.

"**Epilepsy**" - Should we include this: Epilepsy isn’t a tumor; N = 2 1 WGS and 1 RNAseq - same patient

"**Extraventricular Neurocytoma**" - 1 patient with 1 WGS and 1 RNAseq - The old EFO code (EFO_0007201) needs to be reviewed.

"**High-grade glioma/astrocytoma**" - high-grade glioma: MONDO_0100342;   astrocytoma: EFO_0000272 (synonym - astrocytic tumor);  high grade astrocytic tumor: MONDO_0016680 - Which is most appropriate?

"**Low-grade glioma/astrocytoma**" - Low Grade Glioma:MONDO_0021637     ;   Low grade astrocytoma: MONDO_0016685

"**Melanocytic tumor**" - Confirm we can use the EFO code for 'CNS melanocytic tumor'

"**Myxoid spindle cell tumor**" - myxoid isn't specified - maybe need to request subtype in future?

**Comment by jharenza** [comment]
closed with https://github.com/PediatricOpenTargets/OpenPedCan-analysis/pull/99 merged
