### ISSUE TITLE
Updated analysis: fusion-frequencies with correct format json

### ISSUE THREAD

**Issue by kgaonkar6** [PediatricOpenTargets/ticket-tracker#187]
#### What analysis module should be updated and why?
fusion-frequencies

#### What changes need to be made? Please provide enough detail for another participant to make the update.
Here I had just piped the updated `annotated_m_fus_freq_tbl` to write_tsv here:
https://github.com/PediatricOpenTargets/OpenPedCan-analysis/blob/dfc41e2a4f4566c95f5e6a4ea30f3f2aa510b291/analyses/fusion-frequencies/01-fusion-frequencies.R#L272-L283

write_json then writes a older version of `annotated_m_fus_freq_tbl` .

I think we need to update to the following to update `annotated_m_fus_freq_tbl` correctly before `write_json()`:
```
# write to tsv
annotated_m_fus_freq_tbl <- annotated_m_fus_freq_tbl %>%
  select(keep_cols, Gene_Ensembl_ID, Disease, MONDO, RMTL, EFO,Dataset,
         Total_alterations_Over_Patients_in_dataset,
         Frequency_in_overall_dataset,
         Total_primary_tumors_mutated_Over_Primary_tumors_in_dataset,
         Frequency_in_primary_tumors,
         Total_relapse_tumors_mutated_Over_Relapse_tumors_in_dataset,
         Frequency_in_relapse_tumors) %>%
  unique() %>%
  dplyr::rename(Gene_symbol = Gene_Symbol) 

annotated_m_fus_freq_tbl %>%
  write_tsv(file.path(results_dir, paste0(output_filename,'.tsv')))

# write to json
jsonlite::write_json(
  annotated_m_fus_freq_tbl,
  file.path(results_dir, paste0(output_filename,'.json')))
```

#### What input data should be used? Which data were used in the version being updated?
<s>v8</s> v9 
`fusion_filtering/results/fusion-putative-oncogenic.tsv`

#### When do you expect the revised analysis will be completed?
TBD

**Comment by runjin326** [comment]
Closing with [PR101](https://github.com/PediatricOpenTargets/OpenPedCan-analysis/pull/101) merged.
