### ISSUE TITLE
Updated analysis: Delete EFO and MONDO columns in `pedot-table-column-display-order-name.xlsx`

### ISSUE THREAD

**Issue by logstar** [PediatricOpenTargets/ticket-tracker#189]
#### What analysis module should be updated and why?

The `pedot-table-column-display-order-name` module should be updated to Remove `EFO` and `MONDO` columns in `pedot-table-column-display-order-name.xlsx`. Then, upload the updated xlsx file to box folder, with the same filename.

#### What changes need to be made? Please provide enough detail for another participant to make the update.

Remove EFO and MONDO code columns in all spreadsheets, which could be implemented by adding a `_get_disp_columns` method like the [`_get_col_disp_order`](https://github.com/PediatricOpenTargets/OpenPedCan-analysis/blob/73d7a4d4ca8cbe564b8ae8c4d0401448372cb091/analyses/pedot-table-column-display-order-name/utils/tsv.py#L95-L109) method and subsetting the returned display columns in the [`_get_col_disp_order_name_df`](https://github.com/PediatricOpenTargets/OpenPedCan-analysis/blob/73d7a4d4ca8cbe564b8ae8c4d0401448372cb091/analyses/pedot-table-column-display-order-name/utils/tsv.py#L167-L220) method.

Please use [flake8](https://flake8.pycqa.org/en/latest/) to lint python code before opening a PR.

#### What input data should be used? Which data were used in the version being updated?

Input data listed in `pedot-table-column-display-order-name` module README.md.

#### When do you expect the revised analysis will be completed?

0.5 day.

#### Who will complete the updated analysis?

@ewafula ?

cc @taylordm @afarrel @ewafula @jharenza

**Comment by runjin326** [comment]
Closing with [PR108](https://github.com/PediatricOpenTargets/OpenPedCan-analysis/pull/108) merged.
