### ISSUE TITLE
Updated analysis: Rerun `pedot-table-column-display-order-name` for v9 JSONL files

### ISSUE THREAD

**Issue by logstar** [PediatricOpenTargets/ticket-tracker#190]
#### What analysis module should be updated and why?

The `pedot-table-column-display-order-name` should be rerun for v9 JSONL files, in order to incorporate fusion table changes.

This issue is blocked util all v9 JSONL files are all generated.

#### What changes need to be made? Please provide enough detail for another participant to make the update.

Rerun using v9 JSONL files as input.

#### What input data should be used? Which data were used in the version being updated?

Input data listed in pedot-table-column-display-order-name module README.md.

#### When do you expect the revised analysis will be completed?

1 day.

#### Who will complete the updated analysis?

@ewafula ?

cc @taylordm @afarrel @jharenza @ewafula

**Comment by runjin326** [comment]
Closing with [PR108](https://github.com/PediatricOpenTargets/OpenPedCan-analysis/pull/108) merged.
