### ISSUE TITLE
Edit fields of Somatic Mutation JSONL files for OT compatibility

### ISSUE THREAD

**Issue by zdorman** [PediatricOpenTargets/ticket-tracker#197]
#### What data file(s) does this issue pertain to?
Somatic Mutation JSONL files shared with FNL:
```
gene-level-cnv-consensus-annotated-mut-freq.jsonl
gene-level-snv-consensus-annotated-mut-freq.jsonl
putative-oncogene-fused-gene-freq.jsonl
putative-oncogene-fusion-freq.jsonl
variant-level-snv-consensus-annotated-mut-freq.jsonl
```

#### What release are you using?

v9

#### Put your question or report your issue here.

In order to ingest CHoP somatic mutation data into the Open Targets ETL pipeline, some format and field changes are required. FNL is requesting that CHoP make the following changes to the JSONL files shared with FNL in future releases:

1. Rename the following 2 JSONL fields in all 5 files (values are unchanged):
    From `Gene_Ensembl_Id` to `targetFromSourceId`
    From `EFO` to `diseaseFromSourceMappedId`

2. Add the following 3 new fields to all 5 files:
   `datatypeId`. This defines the category of data as recognized in Open Targets. The value for every row in every file should be `somatic_mutation`.
    `chop_uuid`. A unique id is required for every piece of evidence (every row) ingested into Open Targets. Please generate string values for these with `str(uuid.uuid1())` or similar uuid package. The uuid value for each row should be unique across all files. 
    `datasourceId`. This defines the source of the data and is used to group data within Open Targets. The values for each row within a file should be identical, as the values are determined by the containing file:

    `chop_gene_level_cnv` for rows within file `gene-level-cnv-consensus-annotated-mut-freq.jsonl`
    `chop_gene_level_snv` for rows within file `gene-level-snv-consensus-annotated-mut-freq.jsonl`
    `chop_putative_oncogene_fused_gene` for rows within file `putative-oncogene-fused-gene-freq.jsonl`
    `chop_putative_oncogene_fusion` for rows within file `putative-oncogene-fusion-freq.jsonl`
    `chop_variant_level_snv` for rows within file `variant-level-snv-consensus-annotated-mut-freq.jsonl`

3. In `gene-level-cnv-consensus-annotated-mut-freq.jsonl` only, rename 3 fields to remove special character `/`:
    From `Total_alterations/Patients_in_dataset` to `Total_alterations_over_Patients_in_dataset`
    From `Total_primary_tumors_altered/Primary_tumors_in_dataset` to `Total_primary_tumors_altered_over_Primary_tumors_in_dataset`
    From `Total_relapse_tumors_altered/Relapse_tumors_in_dataset` to `Total_relapse_tumors_altered_over_Relapse_tumors_in_dataset`

**Comment by runjin326** [comment]
@ewafula, do you think you would have time to take on making the changes mentioned above for CNV frequencies module? I should be able to update fusion and SNV frequencies module.

**Comment by jharenza** [comment]
@zdorman - question for this
> A unique id is required for every piece of evidence (every row) ingested into Open Targets. Please generate string values for these with str(uuid.uuid1()) or similar uuid package.

Does this need to be unique for _every_ piece of evidence or just _every_ row within a table? For example, would you expect unique uuids for SNV that may overlap with CNV uuids or should all be unique across the board? If the latter, we may need a module to assign these all at once such that no duplicates are introduced.

To answer @runjin326 - is this something you are taking care of for v9, @zdorman and we can implement in v10?

**Comment by ewafula** [comment]
@runjin326 Yes, I will update the CNV module. But we need to clear up how to do this to ensure there are no duplicate UUIDs across all results files from different modules.  I plan to use the uuid4() function from Python's UUID module, which should produce random 128-bit sequences (str of length 32).  We may want to consider generating  UUIDs that sum up to the total number of records of all JSONL files at once and then distribute them among the results files to guarantee uniqueness across space and time. 
Cc @zdorman, @jharenza, @taylordm

**Comment by runjin326** [comment]
@jharenza, @ewafula, I actually asked the question about UUID in slack to @zdorman. Sorry should have cc'd you both. But basically each file needs to have a UUID but having unique UUID across all 5 files are optimal.

**Comment by ewafula** [comment]
Thank you, @runjin326!  I'll go ahead and implement these changes.

**Comment by runjin326** [comment]
> To answer @runjin326 - is this something you are taking care of for v9, @zdorman and we can implement in v10?
Yes, this is something we can implement in v10 - no need to update for v9 (according to this morning's meeting) - just trying to figure out logistics here. ;)

**Comment by runjin326** [comment]
> Thank you, @runjin326! I'll go ahead and implement these changes.

Maybe we can hold off until we hear back from @jharenza about when to implement these changes :)

**Comment by jharenza** [comment]
Great- I think we can implement this new logic whenever people have free time, and not merge the PRs til v10 is released

**Comment by runjin326** [comment]
Closing with https://github.com/PediatricOpenTargets/OpenPedCan-analysis/pull/110, https://github.com/PediatricOpenTargets/OpenPedCan-analysis/pull/111, https://github.com/PediatricOpenTargets/OpenPedCan-analysis/pull/113 and https://github.com/PediatricOpenTargets/OpenPedCan-analysis/pull/108 merged.
