### ISSUE TITLE
OS_days in histology file update/investigation

### ISSUE THREAD

**Issue by runjin326** [PediatricOpenTargets/ticket-tracker#199]
#### What data file(s) does this issue pertain to?
histologies.tsv

#### What release are you using?

v9 

#### Put your question or report your issue here.
1) Currently, in the histology file, the OS_days for some TCGA samples were negative 
```
> histology %>% filter(cohort == "TCGA") %>% filter(OS_days<0) %>% pull(OS_days)
 [1]  -6 -64  -2  -2  -3  -8  -7  -1  -2  -1
```
Need to figure out why/how those numbers are there.

2) For `Kids_First_Participant_ID` that is in both GMKF and TARGET, the `OS_days` sometimes don't match - 
Need to update the OS_days for TARGET samples to match `OS_days` indicated in GMKF cohort.

**Comment by ewafula** [comment]
I 

> #### What data file(s) does this issue pertain to?
> histologies.tsv
> 
> #### What release are you using?
> v9
> 
> #### Put your question or report your issue here.
> 1. Currently, in the histology file, the OS_days for some TCGA samples were negative
> 
> ```
> > histology %>% filter(cohort == "TCGA") %>% filter(OS_days<0) %>% pull(OS_days)
>  [1]  -6 -64  -2  -2  -3  -8  -7  -1  -2  -1
> ```
> 
>
> 
> 1. For `Kids_First_Participant_ID` that is in both GMKF and TARGET, the `OS_days` sometimes don't match -
>    Need to update the OS_days for TARGET samples to match `OS_days` indicated in GMKF cohort.

I will clean up those negative values in v10.  In the clinical data file from GDC, there were dashes in the field. Some in some cases next to the numbers where the formating wasn't right.  Must have missed cleaning those up when parsing the file.   
```
cut -f 10 clinical.tsv | head -n 5
days_to_death
'--
'--
'--
'--
```

Not sure how to fix the second problem. Those are valid values from the TARGET and GMKF clinical files. Unless one cohort takes precedence over the other? The TARGET and GMFK clinical files are not the same.  @jharenza can decide what we need to do in the case where USI ID is the same for TARGET and GMKF. But might also require changing other columns that don't match beyond the OS_days.

**Comment by jharenza** [comment]
Yes please take GMKF precedence, as our clinical file has a more recent update date. Thank you!

**Comment by ewafula** [comment]
@runjin326, @jharenza,  while working on a (ticket #202](https://github.com/PediatricOpenTargets/ticket-tracker/issues/202), I re-downloaded the TCGA RNA-Seq data manifest, this time around using the API.  The negative `OS_days` values persist for the seven cases. It is not a parsing error on my end. Before changing values in the v10 histologies files, wanting to make sure there wasn't another reason why GDC has these negative values in their database. I have attached the most current GDC-TCGA RNA-Seq data and clinical files. I  had used the `cases.0.diagnoses.0.days_to_last_follow_up` column from the data manifest for the `OS_days`.  I should probably use the `days_to_death` column in the clinical data file which does not have the negative values. 
```
((base) 88665a17de0f:TCGA wafulae$ cut -f 6,14  gdc-tcga-data-manifest.tsv | sort | uniq | grep "^-"
-1	TCGA-QH-A6CX-01A-11R-A32Q-07
-1	TCGA-TQ-A7RS-01A-12R-A33Z-07
-2	TCGA-EB-A430-01A-11R-A24X-07
-2	TCGA-EB-A4P0-01A-41R-A266-07
-2	TCGA-T3-A92N-01A-11R-A39I-07
-3	TCGA-EB-A6QZ-01A-12R-A32P-07
-6	TCGA-AX-A3FV-01A-11R-A22K-07
-64	TCGA-CF-A9FH-01A-11R-A38B-07
-7	TCGA-PL-A8LV-01A-21R-A41B-07
-8	TCGA-NQ-A638-01A-11R-A34F-07
```
This issue of negative values is discussed in this post:
- https://github.com/BioinformaticsFMRP/TCGAbiolinks/issues/324

TCGA data and clinical files:
- [gdc-tcga-clinical.tsv.zip](https://github.com/PediatricOpenTargets/ticket-tracker/files/7148081/gdc-tcga-clinical.tsv.zip)
- [gdc-tcga-data-manifest.tsv.zip](https://github.com/PediatricOpenTargets/ticket-tracker/files/7148082/gdc-tcga-data-manifest.tsv.zip)

**Comment by jharenza** [comment]
@ewafula yes, I would suggest using `days_to_death` here!

**Comment by runjin326** [comment]
Closing with [PR136](https://github.com/PediatricOpenTargets/OpenPedCan-analysis/pull/136) merged.
