### ISSUE TITLE
Proposed Analysis: Update collapse-rnaseq to include TPM files

### ISSUE THREAD

**Issue by jharenza** [PediatricOpenTargets/ticket-tracker#2]
#### What analysis module should be updated and why?
[collapse-rnaseq
](https://github.com/PediatricOpenTargets/OpenPBTA-analysis/tree/dev/analyses/collapse-rnaseq)

Currently, the input is FPKM files only.

#### What changes need to be made? Please provide enough detail for another participant to make the update.
Add functionality to collapse TPM files, as these will be the files we use for OT.

#### What input data should be used? Which data were used in the version being updated?
`kfnbl-gene-expression-rsem-tpm.stranded.rds`

#### When do you expect the revised analysis will be completed?
by next week?

#### Who will complete the updated analysis?
@sangeetashukla

**Comment by sangeetashukla** [comment]
@jharenza @komalsrathi 

Completed the code change, and testing.
Waiting on feedback.
Refer to below PR: 
https://github.com/PediatricOpenTargets/OpenPBTA-analysis/pull/4

**Comment by kgaonkar6** [comment]
linking PR https://github.com/PediatricOpenTargets/OpenPBTA-analysis/pull/4

**Comment by komalsrathi** [comment]
Counts file looks good. Thanks!

**Comment by jharenza** [comment]
updated with this [PR](https://github.com/PediatricOpenTargets/OpenPBTA-analysis/pull/4)
