### ISSUE TITLE
Vardict MAF headers offset

### ISSUE THREAD

**Issue by jharenza** [PediatricOpenTargets/ticket-tracker#20]
#### What data file(s) does this issue pertain to?
`kfnbl-snv-vardict.vep.maf.gz

#### What release are you using?

v2

#### Put your question or report your issue here.
Per this [comment](https://github.com/PediatricOpenTargets/OpenPBTA-analysis/pull/2#issuecomment-846144626), the final column header is missing, so we need to re-merge and upload a new Vardict MAF. @zhangb1 will complete this and upload to a v3 folder

**Comment by zhangb1** [comment]
done, all new four callers results have been updated:

s3://kf-openaccess-us-east-1-prd-pbta/open-targets/v3/

**Comment by jharenza** [comment]
@ewafula tested and these are all good now

**Comment by zhangb1** [comment]
this has been done ,and upload in the s3 bucket

**Comment by jharenza** [comment]
Thanks @zhangb1 - I am going to leave it open just until @kgaonkar6 gets the v3 release PR up and we merge.

**Comment by jharenza** [comment]
closed with https://github.com/PediatricOpenTargets/OpenPBTA-analysis/pull/7
