### ISSUE TITLE
Merge PNOC Dataset 2 RNA-Seq and fusion results to v9 for v10 release

### ISSUE THREAD

**Issue by runjin326** [PediatricOpenTargets/ticket-tracker#203]
#### What data file(s) does this issue pertain to?

gene-counts-rsem-expected_count-collapsed.rds
gene-expression-rsem-tpm-collapsed.rds
fusion-arriba.tsv.gz
fusion-starfusion.tsv.gz

#### What release are you using?

v9

#### Put your question or report your issue here.

Please merge and re-collapse the TPM and count files for RNA-seq after merging RNA-Seq data from PNOC dataset 2. 
Please also merge fusion results (both arriba and starfusion) to the current fusion files.

**Comment by zhangb1** [comment]
```
gene-expression-rsem-count-collapsed.rds
gene-expression-rsem-tpm-collapsed.rds
```

PNOC dataset 2 RNA expression files have been merged to the v10 , md5 has been updated

**Comment by runjin326** [comment]
@zhangb1, thanks so much!

**Comment by runjin326** [comment]
Closing with [PR136](https://github.com/PediatricOpenTargets/OpenPedCan-analysis/pull/136) merged.
