### ISSUE TITLE
Updated analysis: LGAT subtyping to include NF1 splice, frameshift, other?

### ISSUE THREAD

**Issue by jharenza** [PediatricOpenTargets/ticket-tracker#204]
#### What analysis module should be updated and why?
Update LGG subtyping module to include additional somatic NF1 variants and assess how many additional deleterious we find using the categories below

#### What changes need to be made? Please provide enough detail for another participant to make the update.
Per [pedcbio oncoKB annotation](https://pedcbioportal.kidsfirstdrc.org/results/mutations?plots_horz_selection=%7B%7D&plots_vert_selection=%7B%7D&plots_coloring_selection=%7B%7D&tab_index=tab_visualize&Action=Submit&session_id=6140e30d7135a62cfb40d6a3), several splice variants are annotated as deleterious - we should assess using these in LGAT NF1 subtyping.

Add variant classifications:
- Splice_Site
- Translation_Start_Site
- Frame_Shift_Del
- Frame_Shift_Ins
- Splice_Region ?

#### What input data should be used? Which data were used in the version being updated?
snv-consensus-plus-hotspots.maf.tsv.gz

#### When do you expect the revised analysis will be completed?
1-2 days

#### Who will complete the updated analysis?
@runjin326 

cc @yuankunzhu @sickler-alex

**Comment by runjin326** [comment]
Closing with [PR117 ](https://github.com/PediatricOpenTargets/OpenPedCan-analysis/pull/117) merged.
