### ISSUE TITLE
Investigate TARGET, GMKF results for tp53-nf1-scores module

### ISSUE THREAD

**Issue by runjin326** [PediatricOpenTargets/ticket-tracker#205]
#### What data file(s) does this issue pertain to?
`gene-expression-rsem-tpm-collapsed_classifier_scores.tsv`
ROC scores for classifier performance. 

#### What release are you using?

v9 

#### Put your question or report your issue here.

- When running the module with TARGET and GMKF samples added, the TP53 scores for TARGET samples were not as high as expected ( as mentioned in the discussion in [PR94 ](https://github.com/PediatricOpenTargets/OpenPedCan-analysis/pull/94). 
- Additionally, the ROC curves showed no difference between shuffled vs. actual scores (both around 0.5 for all three possible RNA library types). 
- Investigation needed to identify the reason for this. 
- Currently the module is ran with only PBTA samples.

**Comment by jharenza** [comment]
These seemed to resolve for v11/12
