### ISSUE TITLE
Update RMTL v1.0 mappings to PMTL v1.1

### ISSUE THREAD

**Issue by zdorman** [PediatricOpenTargets/ticket-tracker#206]
Update `long-format-table-utils` and `ensg-hugo-rmtl-mapping.tsv` to accommodate the RMTL v1.0 to PMTL v1.1 update.

[PMTL_v1.1.tsv](https://nih.app.box.com/folder/135489780289) (Box link from FNL) contains the updated list of targets and designations. It should be used to update the `ensg-hugo-rmtl-mapping.tsv` and any other downstream analyses or references. 

This update consists of two components based on feedback from the FDA to FNL: 
1. Rename any occurrences of "Relevant Molecular Target List" (RMTL) to "Pediatric Molecular Target Lists" (PMTL)
2. Add/change/remove various targets and designations to update from v1.0 to v1.1

Note that the possible options for designations: `Relevant Molecular Target` or `Non-Relevant Molecular Target` have not changed since v1.0, though the `(RMTL version 1.0)` annotation in the designation should be updated to `(PMTL version 1.1)`.

**Comment by runjin326** [comment]
@sangeetashukla, could you please take on this one? Thanks! cc: @afarrel

**Comment by sangeetashukla** [comment]
@runjin326 Sure, I will work on this.

**Comment by sangeetashukla** [comment]
@runjin326 I am not able to access the below link.
> [PMTL_v1.1.tsv](https://nih.app.box.com/folder/135489780289) (Box link from FNL)

Can you please download the file and attach it to the ticket?

**Comment by runjin326** [comment]
Sure - I will slack you the file.

**Comment by runjin326** [comment]
Closing with [PR136](https://github.com/PediatricOpenTargets/OpenPedCan-analysis/pull/136) merged.
