### ISSUE TITLE
Remove trailing white spaces from cancer_group in efo-mondo-mapping.tsv

### ISSUE THREAD

**Issue by sangeetashukla** [PediatricOpenTargets/ticket-tracker#208]
#### What data file(s) does this issue pertain to?
efo-mondo-mapping.tsv

#### What release are you using?

v9

#### Put your question or report your issue here.
There are a few cancer_groups such as "Acute Lymphoblastic Leukemia", "Acute Myeloid Leukemia", and "Chordoma" that have an unnecessary trailing white space in the file.

Review the file for proper formatting, and to remove any unnecessary characters/white spaces.

**Comment by runjin326** [comment]
Closing with [PR136](https://github.com/PediatricOpenTargets/OpenPedCan-analysis/pull/136) merged.
