### ISSUE TITLE
Updated analysis: HGG Molecular Subtyping Module

### ISSUE THREAD

**Issue by runjin326** [PediatricOpenTargets/ticket-tracker#212]
#### What analysis module should be updated and why?
`molecular-subtyping-HGG`

- Currently, this module takes in GISTIC scores and use this to find whether there are `1p/19q co-deleted oligodendrogliomas`. As per discussion with @jharenza, it might be better to completely remove that part from HGG subtype module, and generate a separate module to subtype `1p/19q co-deleted oligodendrogliomas`.
- Additionally, the LGG part can be commented out and make this module a simple one that searches for lesions and assigns subtypes

#### What changes need to be made? Please provide enough detail for another participant to make the update.
Following parts needed to be updated:
1) Remove the code that read in and process GISTIC scores (both in 02 and 03) 
2) Comment out LGG clustering 
3) Remove 09 code where `1p/19q co-deleted oligodendrogliomas` is looked at

#### What input data should be used? Which data were used in the version being updated?
v10
```
consensus_wgs_plus_cnvkit_wxs.tsv.gz
fusion-putative-oncogenic.tsv
fusion-arriba.tsv.gz
fusion-starfusion.tsv.gz
gene-expression-rsem-tpm-collapsed.rds
histologies.tsv
snv-consensus-plus-hotspots.maf.tsv.gz
```

#### When do you expect the revised analysis will be completed?
1-2 days

#### Who will complete the updated analysis?

@runjin326

**Comment by jharenza** [comment]
will close this one, as we have new oligo coming in and we should keep/re-strategize
