### ISSUE TITLE
Updated analysis: Immune deconvolution

### ISSUE THREAD

**Issue by komalsrathi** [PediatricOpenTargets/ticket-tracker#217]
#### What analysis module should be updated and why?

`immune-deconv`

#### What changes need to be made? Please provide enough detail for another participant to make the update.

- [x] Currently we are using FPKM data instead we should use TPM. 
- [x] Would also like to investigate if [xCell](https://github.com/dviraran/xCell) package and [immunedeconv](https://github.com/icbi-lab/immunedeconv) package give similar results (ideally they should give identical results)

#### What input data should be used? Which data were used in the version being updated?

`gene-expression-rsem-tpm-collapsed.rds`
`histologies.tsv`

#### When do you expect the revised analysis will be completed?

Because this module generates heatmaps of immune cell types stratified by molecular subtypes per histology, so once all the molecular subtype information is available in the `histologies.tsv` file .

#### Who will complete the updated analysis?

@komalsrathi

**Comment by komalsrathi** [comment]
@runjin326 is all molecular subtype info up-to-date in the latest release histology file?

**Comment by runjin326** [comment]
@komalsrathi, the OpenPBTA samples all ran through molecular subtyping modules so they are up-to-date. For samples that are not in PBTA cohort, I think it is filled out based on the metadata information we have - for example, NBL has some molecular subtyping information - but not all samples have molecular subtyping info yet.

**Comment by jharenza** [comment]
@runjin326 and @komalsrathi just to weigh in here - we don't need to plot these for OT for now because the types of plots will likely be different (ie starting with cancer group and adding to api if desired, but this is beyond the scope here). When updating these modules, we can be simply updated the outputs and either archive the plot code or keep it subsetted to PBTA for now.

**Comment by komalsrathi** [comment]
@jharenza thanks, makes sense. Going to work on this today - will generate the deconvolution scores + heatmap with scores per `cancer_group`. I can open a new ticket later and add the molecular subtype plots once all subtyping is available.

**Comment by runjin326** [comment]
Closing with PR#161 merged.
