### ISSUE TITLE
Validate number of patients in SNV tables

### ISSUE THREAD

**Issue by zdorman** [PediatricOpenTargets/ticket-tracker#220]
#### What data file(s) does this issue pertain to?

`results/gene-level-snv-consensus-annotated-mut-freq.jsonl.gz`
`results/gene-level-snv-consensus-annotated-mut-freq.tsv.gz`
`results/variant-level-snv-consensus-annotated-mut-freq.jsonl.gz`
`results/variant-level-snv-consensus-annotated-mut-freq.tsv.gz`

#### What release are you using?

v9 

#### Put your question or report your issue here.

Please verify that the number of patients in each cohort and `all_cohorts` is being calculated as intended. Any additional clarity around samples included in multiple cohorts would be particularly helpful. 

As an example, consider the number of patients in the SNV tables for ALK in Neuroblastoma:
`GMKF    336`
`PBTA    3`
`TARGET    519`
The sum of patients in each cohort = 858, while number of patients in the `all_cohorts` = 793. 

Some difference in the patient numbers is expected due to samples included in multiple cohorts - please verify that this is the only cause of different patient counts.

**Comment by logstar** [comment]
@zdorman I will validate Neuroblastoma sample and patient numbers with the following steps:

- Rerun v9 `snv-frequencies` module.
- Output `Kids_First_Participant_ID`s and `Kids_First_Biospecimen_ID`s for Neuroblastoma GMKF, PBTA, TARGET, and all_cohorts.
- Validate that `Kids_First_Biospecimen_ID`s are from only 793 `Kids_First_Participant_ID`s.

The results can only be used to check whether the number of patients is expected in v9 Neuroblastoma. 

Therefore, could you list other potential causes that you are interested in looking into for different patient counts? They will be helpful for us to validate the SNV module. If you speculate that the different patient counts are caused by potential bug in the code, could you describe some unit testing cases that we could implement to check? We have a unit testing framework set up for the SNV module <https://github.com/PediatricOpenTargets/OpenPedCan-analysis/tree/dev/analyses/snv-frequencies/tests>.

**Comment by logstar** [comment]
@zdorman - The neuroblastoma patient numbers in v9 SNV tables are expected. Attached are neuroblastoma samples/biospecimens and patients that are included in v9 SNV tables. Following are the number of samples/biospecimens and patients in each file:

```text
> nbl_histologies <- list(
+   GMKF = read_tsv('Neuroblastoma_GMKF_tsv.txt',
+                   guess_max = 1e6, col_types = cols()),
+   TARGET = read_tsv('Neuroblastoma_TARGET_tsv.txt',
+                     guess_max = 1e6, col_types = cols()),
+   all_cohorts = read_tsv('Neuroblastoma_all_cohorts_tsv.txt',
+                          guess_max = 1e6, col_types = cols())
+ )
> imap_dfr(nbl_histologies, function(xdf, xname) {
+   stats_df <- tibble(
+     cohort = xname,
+     n_rows = nrow(xdf),
+     n_uniq_patients = length(unique(xdf$Kids_First_Participant_ID)),
+     n_uniq_biospecimens = length(unique(xdf$Kids_First_Biospecimen_ID))
+   )
+   return(stats_df)
+ })
# A tibble: 3 x 4
  cohort      n_rows n_uniq_patients n_uniq_biospecimens
  <chr>        <int>           <int>               <int>
1 GMKF           336             336                 336
2 TARGET         519             519                 519
3 all_cohorts    855             793                 855
```

[Neuroblastoma_TARGET_tsv.txt](https://github.com/PediatricOpenTargets/ticket-tracker/files/7247007/Neuroblastoma_TARGET_tsv.txt)

[Neuroblastoma_GMKF_tsv.txt](https://github.com/PediatricOpenTargets/ticket-tracker/files/7247008/Neuroblastoma_GMKF_tsv.txt)

[Neuroblastoma_all_cohorts_tsv.txt](https://github.com/PediatricOpenTargets/ticket-tracker/files/7247009/Neuroblastoma_all_cohorts_tsv.txt)

cc @runjin326 @ewafula

**Comment by zdorman** [comment]
@logstar Thank you for looking into this and validating the numbers - I appreciate it. 

I don't have any suspicion of bugs in the code. I was asking from the perspective of an Open Targets user confused about why the apparent totals do not match. Reading through OpenPedCan documentation led me to understand that some patients provided multiple biospecimens, and that those can be included across multiple cohorts. Your validation helped me to confirm this. When we build the documentation for the Somatic Mutation table in Open Targets, I suggest we explicitly and simply state this to head off any user confusion. Thanks again.

**Comment by logstar** [comment]
@zdorman

> When we build the documentation for the Somatic Mutation table in Open Targets, I suggest we explicitly and simply state this to head off any user confusion.

I agree.

Thank you for checking the results.

It is difficult, if not impossible, to prove that certain code is and will always be working as expected. We have code review and testing in CHOP analytics group to reduce error rate.

It is really helpful to have other perspectives outside of CHOP analytics to check the results. It would be a greater help if bugs could be identified from these perspectives. Feel free to let us know if you have any other questions or concerns.
