### ISSUE TITLE
Gene-disease-gtex TPM plot widget title and source

### ISSUE THREAD

**Issue by zdorman** [PediatricOpenTargets/ticket-tracker#223]
Please provide the text that should appear in the Molecular Targets Platform widget containing the `gene-disease-gtex` TPM plots in a format that matches the existing Open Targets widgets. FNL will implement the responses into the MTP code. 

1. Widget title

     - Title that indicates data type, relevance, and/or source
     - Proposed 9/29: "OpenPedCan Gene Expression"

2. Widget descriptive subtitle

     - One sentence description of the data, containing a dynamic gene and disease reference
     - e.g. "RNA expression of `%gene` in `%disease` tumor tissue and in normal GTEx tissue" 

3. Source and link

     - Source name with publicly accessible hyperlink for the data and/or analysis
     - e.g. [OpenPedCan](https://github.com/PediatricOpenTargets/OpenPedCan-analysis/tree/dev/analyses/tumor-gtex-plots)

-----------------------

![Widget Diagram](https://user-images.githubusercontent.com/82673924/135479578-0b752324-774a-44bc-a455-620e45bdb70e.png)

**Comment by runjin326** [comment]
@zdorman, since the changes are merged - this should be ready to close right?

**Comment by zdorman** [comment]
@runjin326  Yes, thanks for following up. This one can be closed. 
What's your preferred protocol? Should I be closing this (and the others) since I submitted the issue? I was assuming you would close it after successful merge.

**Comment by runjin326** [comment]
Yes - I just want to double check. I will close the issue.
