### ISSUE TITLE
Somatic Mutation widget title and text

### ISSUE THREAD

**Issue by zdorman** [PediatricOpenTargets/ticket-tracker#224]
Please provide the title and source text that should appear in the Molecular Targets Platform widget containing the somatic mutation tables:

`gene-level-cnv-consensus-annotated-mut-freq.jsonl`
`gene-level-snv-consensus-annotated-mut-freq.jsonl`
`putative-oncogene-fused-gene-freq.jsonl`
`putative-oncogene-fusion-freq.jsonl`
`variant-level-snv-consensus-annotated-mut-freq.jsonl`

FNL will implement the responses into the MTP code. Note that though multiple tabs/analyses are used within this widget, there should be a single set of titles and source to match the existing Open Targets design. Descriptions and sourcing of the individual tabs/analyses can be included in user documentation at a later date. 

1. Widget title

     - Title that indicates data type, relevance, and/or source
     - Proposed 9/29: "OpenPedCan Somatic Mutation"

2. Widget descriptive subtitle

     - One sentence description of the data, containing a dynamic gene and disease reference
     - e.g. "Somatic mutations associated with `%gene` patients affected by `%disease`." 

3. Source and link

     - Source name with publicly accessible hyperlink for the data and/or analysis
     - e.g. [OpenPedCan](https://github.com/PediatricOpenTargets/OpenPedCan-analysis/tree/dev/analyses)

-----------------------

![SomaticMutationWidgetTitle](https://user-images.githubusercontent.com/82673924/135482030-3f0c2cae-c543-4fa6-b365-1a1c9ec730f3.png)

**Comment by zdorman** [comment]
@taylordm 
cc @chinwallaa 
Can you please confirm that you'd like us to make the following changes to the site based on @jharenza's About Page mockup comments? (thanks for the detailed feedback, by the way!)

On both Target and Evidence pages:
1. Change widget title from "OpenPedCan Somatic **Mutations**" to "OpenPedCan Somatic **Alterations**" (because fusions and CNVs are included)
2. Change icon from "SM" to "SA"
2. Change source link from "OpenPBTA for CBTN (v21)" https://www.ccdatalab.org/openpbta to "OpenPBTA for CBTN and PNOC (v21)" https://alexslemonade.github.io/OpenPBTA-manuscript/

**Comment by zdorman** [comment]
Following up on my previous questions:

We confirmed in the weekly meeting 11/3 to change the widget name to Somatic Alterations and the icon to SA.

Can you please confirm that we should change the source link from "OpenPBTA for CBTN (v21)" https://www.ccdatalab.org/openpbta to "OpenPBTA for CBTN and PNOC (v21)" https://alexslemonade.github.io/OpenPBTA-manuscript/ ? 
@taylordm
cc @chinwallaa @jharenza @runjin326

**Comment by runjin326** [comment]
@zdorman, similarly - can this issue be closed now?
