### ISSUE TITLE
Pan-Cancer TPM plot (Target Page) widget title and source

### ISSUE THREAD

**Issue by zdorman** [PediatricOpenTargets/ticket-tracker#225]
Please provide the text that should appear in the Molecular Targets Platform widget containing the `pan-cancer` TPM plots (on the Target Page) in a format that matches the existing Open Targets widgets. FNL will implement the responses into the MTP code.

Note that some of these fields may be similar or identical to that of the `gene-disease-gtex` TPM plots (Evidence Page) in #223

1. Widget title

     - Title that indicates data type, relevance, and/or source
     - Proposed 9/29: "OpenPedCan Gene Expression"

2. Widget descriptive subtitle

     - One sentence description of the data, containing a dynamic gene reference
     - e.g. "RNA expression of `%gene` in tumor tissues from various histologies"

3. Source and link

     - Source name with publicly accessible hyperlink for the data and/or analysis
     - e.g. [OpenPedCan](https://github.com/PediatricOpenTargets/OpenPedCan-analysis/tree/dev/analyses/tumor-gtex-plots)

**Comment by taylordm** [comment]
Ticket #225: Please provide the text that should appear in the Molecular Targets Platform widget containing the `pan-cancer`  TPM plots (on the Target Page) in a format that matches the existing  Open Targets widgets. FNL will implement the responses into the MTP code.
        Note that some of these fields may be similar or identical to that of the `gene-disease-gtex` TPM plots (Evidence Page) in [#223](https://github.com/PediatricOpenTargets/ticket-tracker/issues/223)
        
        1. Widget title:  Title that indicates data type, relevance, and/or source
**OpenPedCan Gene Expression**
            
        2. Widget descriptive subtitle: One sentence description of the data, containing a dynamic gene reference
**mRNA expression of '%gene' in pediatric tumors**
            
        3. Source and link
            
            Source name with publicly accessible hyperlink for the data and/or analysis
            
            - [OpenPedCan](https://github.com/PediatricOpenTargets/OpenPedCan-analysis/tree/dev/analyses/tumor-gtex-plots) v10 [https://github.com/PediatricOpenTargets/OpenPedCan-analysis](https://github.com/PediatricOpenTargets/OpenPedCan-analysis)
            - TARGET v 23: [https://www.ncbi.nlm.nih.gov/projects/gap/cgi-bin/study.cgi?study_id=phs000218.v23.p8](https://www.ncbi.nlm.nih.gov/projects/gap/cgi-bin/study.cgi?study_id=phs000218.v23.p8)
            - Kids First Neuroblastoma:  [https://www.ncbi.nlm.nih.gov/projects/gap/cgi-bin/study.cgi?study_id=phs001436.v1.p1](https://www.ncbi.nlm.nih.gov/projects/gap/cgi-bin/study.cgi?study_id=phs001436.v1.p1)
            - OpenPBTA for the CBTN, v21: [https://www.ccdatalab.org/openpbta](https://www.ccdatalab.org/openpbta)

**Comment by runjin326** [comment]
@zdorman - this should be ready to close as well?

**Comment by runjin326** [comment]
Closing with PR merged
