### ISSUE TITLE
Update PBTA pedcbio cohort case IDs

### ISSUE THREAD

**Issue by runjin326** [PediatricOpenTargets/ticket-tracker#229]
#### What data file(s) does this issue pertain to?
In v10 release, we added more PBTA samples and hence we need to update PBTA cohort case IDs.

Additionally, please also load all GTEx RNA-Seq data available in v10 release to pedcbio.

#### What release are you using?

v10 
Please find the relevant files in this S3 bucket - s3://d3b-openaccess-us-east-1-prd-pbta/open-targets/v10/.

**Comment by jharenza** [comment]
this is completed as of this [QA load](https://kf-strides-cbioportal-qa.kidsfirstdrc.org/study/summary?id=ped_opentargets_2021)

**Comment by runjin326** [comment]
PR for this is [here ](https://github.com/PediatricOpenTargets/OpenPedCan-analysis/pull/163)
