### ISSUE TITLE
How to handle PBTA data files?

### ISSUE THREAD

**Issue by jharenza** [PediatricOpenTargets/ticket-tracker#23]
#### What data file(s) does this issue pertain to?
`pbta-gene-counts-rsem-expected_count*` files as related to [this issue](https://github.com/PediatricOpenTargets/OpenPBTA-analysis/pull/8)

#### What release are you using?

v19 OpenPBTA

#### Put your question or report your issue here.
First, should we merge these upstream? I think this may be simpler, to be dealing with fewer files. Would also require some module changes.
Second, should we release these in OT/OpenPBTA? 

cc @yuankunzhu and @kgaonkar6

**Comment by kgaonkar6** [comment]
It makes sense to me to merge the files to just access 1 file, but then we will need specific documentation to always make sure people refer to the histology file to access the stranded and polya metadata while using the merged file. 
To me, with the 2 files named with the RNA library prep it is just easier to convey that message.

**Comment by jharenza** [comment]
>but then we will need specific documentation to always make sure people refer to the histology file to access the stranded and polya metadata while using the merged file.

This is in the histologies file and if you think about the TARGET and TCGA data, we will have a mixed bag of libraries. We will need to take this into account for batch correction before we do anything else anyway, so I don't think it should be a problem.

**Comment by jharenza** [comment]
After discussion with @yuankunzhu , we decided that we will create one large matrix for each type of file: counts, TPM, etc and we will use the d3b 2/4+consensus maf and will generalize the naming to not have project prefix, so this will allow us to add additional data more easily. I will add tickets to track this.
