### ISSUE TITLE
Updated analysis: rerun `snv-frequencies` with v10 pedcbio open targets dataset cohort case IDs

### ISSUE THREAD

**Issue by logstar** [PediatricOpenTargets/ticket-tracker#230]
#### What analysis module should be updated and why?

`snv-frequencies` module needs to be updated to use v10 pedcbio cohort case IDs, aka case set IDs, to generate pedcbio plot URLs.

#### What changes need to be made? Please provide enough detail for another participant to make the update.

After #229 is resolved, update `analyses/snv-frequencies/input/ped_opentargets_2021_pedcbio_case_set_ids.json` and rerun `snv-frequencies`.

#### What input data should be used? Which data were used in the version being updated?

`snv-frequencies` input data files.

#### When do you expect the revised analysis will be completed?

1-2 days.

#### Who will complete the updated analysis?

@ewafula ? Eric had updated the last pedcbio case set ID list.

**Comment by logstar** [comment]
Thank you!

**Comment by jharenza** [comment]
Closed with https://github.com/PediatricOpenTargets/OpenPedCan-analysis/pull/222
