### ISSUE TITLE
Move gene_match module and modify 

### ISSUE THREAD

**Issue by runjin326** [PediatricOpenTargets/ticket-tracker#231]
#### What analysis module should be updated and why?
https://github.com/d3b-center/D3b-codes/tree/master/gene_match
1) Move this gene match module to PediatricOpenTargets 
2) Change the file paths to directly take files from the `data` in the QC code
3) Filter the output `ensg-hugo-pmtl-mapping.tsv` as described below

#### What changes need to be made? Please provide enough detail for another participant to make the update.

Currently this file has this line:
```
ensg_id gene_symbol            pmtl      version
Symbol_Not_Found     NA Relevant Molecular Target PMTL version 1.1
```
Please modify the code that generated this file to filter any line that has `ensg_id` == "Symbol_Not_Found` &`gene_symbol` == NA

#### What input data should be used? Which data were used in the version being updated?
v10 
snv-consensus-plus-hotspots.maf.tsv.gz
consensus_wgs_plus_cnvkit_wxs.tsv.gz
gene-expression-rsem-tpm-collapsed.rds
fusion-putative-oncogenic.tsv
and input files from the module

#### When do you expect the revised analysis will be completed?
1 day

**Comment by jharenza** [comment]
closing with #145
