### ISSUE TITLE
2 disease names, but 1 disease ontology ID in gene-level-snv-consensus-annotated-mut-freq.jsonl

### ISSUE THREAD

**Issue by dunnpa** [PediatricOpenTargets/ticket-tracker#232]
#### What data file(s) does this issue pertain to?
gene-level-snv-consensus-annotated-mut-freq.jsonl

#### What release are you using?
v10

#### Put your question or report your issue here.
2 disease names are listed for some records "Disease":"Metastatic secondary tumors;Neuroblastoma", but only 1 disease ontology ID ("diseaseFromSourceMappedId":"EFO_0000621")
usually (if not always) where "Dataset":"PBTA"

{"Gene_symbol":"SNAP91","PMTL":"","Dataset":"PBTA","Disease":"Metastatic secondary tumors;Neuroblastoma","diseaseFromSourceMappedId":"EFO_0000621","MONDO":"MONDO_0005072","Gene_full_name":"synaptosome associated protein 91","Gene_type":"","Protein_RefSeq_ID":"NP_001229721.1,NP_001229722.1,NP_001229723.1,NP_001243646.1,NP_001243647.1,NP_001350606.1,NP_001363604.1,NP_001363605.1,NP_001363606.1,NP_001363607.1,NP_001363608.1,NP_001363609.1,NP_001363610.1,NP_001363611.1,NP_001363612.1,NP_001363613.1,NP_001363614.1,NP_001363615.1,NP_001363616.1,NP_001363617.1,NP_001363618.1,NP_001363619.1,NP_001363620.1,NP_001363621.1,NP_001363622.1,NP_001363623.1,NP_001363624.1,NP_001363625.1,NP_001363626.1,NP_001363627.1,NP_001363628.1,NP_001363629.1,NP_001363630.1,NP_001363631.1,NP_001363632.1,NP_001363633.1,NP_001363634.1,NP_001363635.1,NP_001363636.1,NP_001363637.1,NP_001363638.1,NP_001363639.1,NP_001363640.1,NP_001363641.1,NP_001363642.1,NP_001363643.1,NP_001363644.1,NP_001363645.1,NP_001363646.1,NP_001363647.1,NP_001363648.1,NP_001363649.1,NP_001363650.1,NP_001363652.1,NP_001363655.1,NP_001363657.1,NP_001363660.1,NP_001363662.1,NP_001363663.1,NP_001363664.1,NP_001363665.1,NP_001363666.1,NP_001363667.1,NP_001363668.1,NP_001363669.1,NP_001363670.1,NP_001363671.1,NP_055656.1","targetFromSourceId":"ENSG00000065609","Protein_Ensembl_ID":"ENSP00000400459","Total_mutations_Over_Patients_in_dataset":"2/3","Frequency_in_overall_dataset":"66.67%","Total_primary_tumors_mutated_Over_Primary_tumors_in_dataset":"0/0","Frequency_in_primary_tumors":"","Total_relapse_tumors_mutated_Over_Relapse_tumors_in_dataset":"2/3","Frequency_in_relapse_tumors":"66.67%","OncoKB_cancer_gene":"N","OncoKB_oncogene_TSG":"","PedcBio_PedOT_oncoprint_plot_URL":"","PedcBio_PedOT_mutations_plot_URL":"","datatypeId":"somatic_mutation","datasourceId":"chop_gene_level_snv","chop_uuid":"88df04b8-7466-47c4-b1b0-642520c57a3a"}

**Comment by jharenza** [comment]
>Glad to read you are back!

Well... not really - just tying up some other things while on leave =)

These are one tumor and are metastatic neuroblastoma.  These are "progressive" samples, not primary tumors (if you mean primary to be diagnostic).

**Comment by ewafula** [comment]
Will start v11 PR and update.

**Comment by jharenza** [comment]
closing in favor of #234
