### ISSUE TITLE
Proposed Analysis: MYCN AMP/Gain Thresholding using SNP Array data

### ISSUE THREAD

**Issue by afarrel** [PediatricOpenTargets/ticket-tracker#233]
#### What are the scientific goals of the analysis?
MYCN AMP/gain Thresholding using TARGET SNP array data

The purpose of this analysis module is to access the status of the MYCN gene amplification status between the OpenPedCan NeuroblastomaGMKF and TARGET consensus copy number variants (CNV) calls from WSX/WGS, SNP array data, and clinical information in the master histologies file.

#### What methods do you plan to use to accomplish the scientific goals?

- identify discordant samples in MYCN amplification status between the SNP array data Segmental CN (hg19), SNP array MYCN loci Log R Rations (LRR) (hg19), consensus CNV calls, and the clinical information.
- Calculate True Positive Rate (TPR) and True Negative Rate (TNR) for SNParray data (added to previous work for CNV data in [PR 112](https://github.com/PediatricOpenTargets/OpenPedCan-analysis/pull/112))
- Determine SNParray LRR threshold for for MYCN amplification.

#### What input data are required for this analysis?

- Clinically annotated MYCN status from histologies file
- Segmental Copy Number data from patient SNP array (hg19)
- TARGET Log R Ratios data from patient SNP array data (hg19)
- analyses/data/cnv-cnvkit.seg.gz
- analyses/data/cnv-controlfreec.tsv.gz
- GATK Results if available
- hg19 GTF

#### How long do you expect is needed to complete the analysis? 
1-2 weeks

#### Who will complete the analysis (please add a GitHub handle here if relevant)?
@ewafula

**Comment by jharenza** [comment]
completed with #417 https://github.com/PediatricOpenTargets/OpenPedCan-analysis/pull/264
