### ISSUE TITLE
Neuroblastoma/met cancer group update for v11 histologies file

### ISSUE THREAD

**Issue by runjin326** [PediatricOpenTargets/ticket-tracker#234]
#### What data file(s) does this issue pertain to?
histologies.tsv

#### What release are you using?

v10

#### Put your question or report your issue here.
In current `histologies.tsv` file, we have `cancer_group` of `Metastatic secondary tumors;Neuroblastoma`.
Since no EFO code exists for any child terms of `Neuroblastoma`, we will change `Metastatic secondary tumors;Neuroblastoma` to `Neuroblastoma` in histologies file to avoid confusion. 

See discussion in https://github.com/PediatricOpenTargets/ticket-tracker/issues/232.

**Comment by jharenza** [comment]
Closed with https://github.com/PediatricOpenTargets/OpenPedCan-analysis/pull/188
