### ISSUE TITLE
`All Cohorts` only sampling one or few diseases

### ISSUE THREAD

**Issue by zdorman** [PediatricOpenTargets/ticket-tracker#235]
#### What data file(s) does this issue pertain to?

SNV by Gene: `gene-level-snv-consensus-annotated-mut-freq.jsonl`
SNV by Variant: `variant-level-snv-consensus-annotated-mut-freq.jsonl`
CNV by Gene: `gene-level-cnv-consensus-annotated-mut-freq.jsonl`
Fusion by Gene: `putative-oncogene-fused-gene-freq.jsonl`
Fusion: `putative-oncogene-fusion-freq.jsonl`

#### What release are you using?

v10

#### Put your question or report your issue here.

The `All Cohorts` dataset in each file only contains data from a small subset of diseases:
- SNV by Gene, SNV by Variant, and CNV by Gene: only `Neuroblastoma` data
- Fusion by Gene and Fusion: only `Acute Myeloid Leukemia`, `Neuroblastoma`, and `Sarcoma` data

Is the lack of diseases in `All Cohorts` by design?  The `All Cohorts` datasets should contain the cumulative data from all other cohorts (GMKF, PBTA, TARGET) and include all diseases present in each cohort.

I suspect that it is a case of undersampling rather than misattributed disease IDs because the number of **unique** `Gene_symbol`s is lower in each `All Cohorts` dataset than in some of the individual datasets. The number of unique `Gene_symbol`s of an `All Cohorts` dataset should be approximately equal to the sum of unique `Gene_symbol`s across the other datasets.

**Comment by zdorman** [comment]
### Update after discussion in Slack:
`All Cohorts` is working as intended when present in Neuroblastoma data. `All Cohorts` is not working as intended in AML and sarcoma data in the Fusion tables because it is including TCGA RNA data. 

### Copy/Pasted full discussion from Slack on 10/19/2021:
(@ symbols removed)

Run Jin  9:59 AM
Hey Zachary Dorman thanks for submitting the issue. So sorry that the naming of the file information is a bit confusing. So for All Cohorts, it is not saying that it is all cohorts, it is saying that those samples are present in more than 2 cohorts - and it is expected that this is just a subset of the data since not all samples are present in multiple cohorts.
And the reason for having those rows is because we used a different independent sample list to calculate the frequency - when a sample is present in multiple cohorts AND if the row is saying All Cohorts, we use independent sample lists that randomly select one sample from all the cohorts that it is present and we use that number to calculate the frequency.
Since the calculation is based on per cohort per cancer group, there is not a way to get a cumulative data from all other cohorts (GMKF, PBTA, TARGET) and include all diseases present in each cohort in one single row - it would be displayed in separate rows specifying specific cohort and disease.
Does it all make sense?
10:00
Also cc Yuanchao Zhang if I am missing anything.

Eric Wafula  10:15 AM
Zachary Dorman, the computation of frequencies is for for each cohort  and all cohorts is described in the REAME of the SNV modules here: https://github.com/PediatricOpenTargets/OpenPedCan-analysis/blob/dev/analyses/snv-frequencies/README.md
All cohort is not the tallying of individual cohort frequencies.  May need a clear description on the OT portal to avoid confusing users.
Frequency_in_overall_dataset:
For each unique variant/gene, count the number of patients (identified by Kids_First_Participant_ID) that have mutations at the variant/gene, and call this number Total_mutations.
Count the total number of patients in the cancer_group_cohort, and call this number Patients_in_dataset.
Frequency_in_overall_dataset = Total_mutations / Patients_in_dataset.
Frequency_in_primary_tumors:
For each unique variant/gene, count the number of samples (identified by Kids_First_Biospecimen_ID) that have mutations at the variant/gene and are in the independent primary sample list, and call this number Total_primary_tumors_mutated.
Count the total number of samples in the cancer_group_cohort that are also in the independent primary sample list, and call this number Primary_tumors_in_dataset.
Frequency_in_primary_tumors = Total_primary_tumors_mutated / Primary_tumors_in_dataset.
Frequency_in_relapse_tumors:
For each unique variant/gene, count the number of samples (identified by Kids_First_Biospecimen_ID) that have mutations at the variant/gene and are in the independent relapse sample list, and call this number Total_relapse_tumors_mutated.
Count the total number of samples in the cancer_group_cohort that are also in the independent relapse sample list, and call this number Relapse_tumors_in_dataset.
Frequency_in_relapse_tumors = Total_relapse_tumors_mutated / Relapse_tumors_in_dataset.

Zachary Dorman Today at 11:35 AM
Thanks for the explanations. I think I am finally following...
From a user's perspective, it's redundant to see a single specific cohort row and an All Cohorts row when they are identical. So the All Cohorts should only contain disease/gene combos that appear in multiple cohorts (and thus when All Cohorts is not identical to an individual cohort). I saw that All Cohorts only had Neuroblastoma data and assumed a problem, but did not realize that Neuroblastoma is the ONLY disease present in more than one cohort right now. For instance, TP53 in Osteosarcoma: because there is only data from the TARGET dataset, it would be useless to also include rows that are identical but list 'All Cohorts' as the dataset. Is this the idea? ![TP53_osteosarcoma](https://user-images.githubusercontent.com/82673924/137982005-573877a8-2a92-44b4-880f-2f385b79caed.png)

With that understanding, is there still an issue with the Fusion and Fusion by Gene All Cohorts containing data for AML and Sarcoma? These don't seem to appear in cohorts other than TARGET. For instance, this view of FLT3 in AML in dev MTP reflects the data. Is this intended? What conclusion about the frequency and number of patients should a user draw from this view? ![FLT3_AML](https://user-images.githubusercontent.com/82673924/137982036-c0b271ce-7e1d-41b7-af82-cb5a82f8b0fb.png)


Run Jin  4 hours ago
Yes - for samples that are only present in one cohort, we did not include All Cohorts since those will just be the same number.

Run Jin  4 hours ago
I will look into fusion FLT3 issue.

Run Jin  2 hours ago
Zachary Dorman, figured out what the issue is. For the FLT3 you showed (and maybe other fusions), the reason stems from the fact that our histologies file and independent sample lists contain TCGA RNA samples that does not contain fusion information. That is why the total alteration remains the same and only patients in dataset changed for the All Cohorts row. This can be confusing to viewers so I will open a ticket and fix that - again, we can discuss timeline tomorrow and see what we can do before MVP1 demo. Sorry about the inconvenience!

Zachary Dorman  2 hours ago
Thanks for looking into it. I think this is minor enough that we will not need emergency fix before the November demo, but should consider changing after the demo before the product release (MVP1)

**Comment by runjin326** [comment]
@zdorman, since we are clear on what `All Cohorts` mean, can this issue be closed?

**Comment by runjin326** [comment]
Closing with with PR149 merged.
