### ISSUE TITLE
Somatic Mutation data missing disease IDs

### ISSUE THREAD

**Issue by zdorman** [PediatricOpenTargets/ticket-tracker#236]
#### What data file(s) does this issue pertain to?

SNV by Gene: `gene-level-snv-consensus-annotated-mut-freq.jsonl`
SNV by Variant: `variant-level-snv-consensus-annotated-mut-freq.jsonl`
Fusion by Gene: `putative-oncogene-fused-gene-freq.jsonl`
Fusion: `putative-oncogene-fusion-freq.jsonl`

#### What release are you using?

v10

#### Put your question or report your issue here.

The following diseases do not have `diseaseFromSourceMappedId` values, which are required for MTP integration. (They also do not have `MONDO` values, which are informative for user downloads but not functionally necessary).

SNV by Gene and SNV by Variant:
- `Desmoplastic infantile astrocytoma and ganglioglioma`
- `Neurocytoma`

Fusion by Gene and Fusion:
- `Desmoplastic infantile astrocytoma and ganglioglioma`
- `Neurocytoma`
- `Juvenile xanthogranuloma`

**Comment by runjin326** [comment]
Closing since this is fixed by [ticket237](https://github.com/PediatricOpenTargets/ticket-tracker/issues/237) and PR137 merged.
