### ISSUE TITLE
EFO MONDO cancer group mapping file 

### ISSUE THREAD

**Issue by runjin326** [PediatricOpenTargets/ticket-tracker#237]
#### What data file(s) does this issue pertain to?
`efo-mondo-map.tsv`

#### What release are you using?

v10

#### Put your question or report your issue here.

Three new cancer groups need EFO terms and MONDO code added to the `efo-mondo-map.tsv` file
- `Desmoplastic infantile astrocytoma and ganglioglioma`
- `Neurocytoma`
- `Juvenile xanthogranuloma`

Additionally, `Metastatic secondary tumors;Neuroblastoma` is not required since it would be modified to `Neuroblastoma`

**Comment by runjin326** [comment]
@jharenza, yes I think it is N>=3. I will do that.

**Comment by jharenza** [comment]
this has been updated in #147
