### ISSUE TITLE
Proposed Analysis: Create Gene CNV Table using TARGET SNP array data

### ISSUE THREAD

**Issue by afarrel** [PediatricOpenTargets/ticket-tracker#241]
#### What are the scientific goals of the analysis?
SNP arrays are are accurate in determining copy number alterations than our current CNV pipelines. We currently have SNP array data and will receive some more when the P30s come in. Our goal is to create a CNV Table (similar to the one from the current CNV module) and CNV pipeline using SNP array data

#### What methods do you plan to use to accomplish the scientific goals?
Call focal accurate copy using Log R Ratios from TARGET data on a gene level.

#### What input data are required for this analysis?
v10/v11 histologies file
TARGET SNP array data

#### How long do you expect is needed to complete the analysis? Will it be a multi-step analysis?
1-2 weeks

#### Who will complete the analysis (please add a GitHub handle here if relevant)?
@sangeetashukla

**Comment by jharenza** [comment]
@afarrel I am going to close this in favor of us getting SNP array data released and then modifying consensus CNV
