### ISSUE TITLE
Bix Dev PedcbioPortal Support: add PMTL as predefined gene list

### ISSUE THREAD

**Issue by jharenza** [PediatricOpenTargets/ticket-tracker#243]
# 🆘

#### [Required] How would you most generally describe your issue? 
- [c] Update data for project in pedcbio portal
- [ ] Questions related to data on pedcbio portal 

#### If an update to a project, provide links to the input files that should be used and descriptions we might find helpful. If new `case_set_ids` need to be added, please provide instructions below.

Add PMTL list (available in s3 bucket as a released file) to show up in predefined lists as below:
![image](https://user-images.githubusercontent.com/207034/139090860-9e75b7c4-5883-478b-8983-0231c1f78399.jpeg)

### Ticket will be considered resolved either by a successful PR with updated release if applicable, or a simple denial of the request backed by a good reason

**Comment by allisonheath** [comment]
It looks like it's a configuration change, you need to update the JSON file and then redeploy: https://docs.cbioportal.org/2.3-customization/portal.properties-reference#gene-sets-used-for-gene-querying

**Comment by jharenza** [comment]
awesome, thank you @allisonheath! 

@runjin326 can you create the JSON entries for @alubneuski to add to the current file? 
`PMTL: Pediatric Relevant Molecular Targets (476 genes)`

from: `s3://d3b-openaccess-us-east-1-prd-pbta/open-targets/v10/ensg-hugo-rmtl-mapping.tsv`

**Comment by runjin326** [comment]
Here is the JSON file - @jharenza, among the 476 genes with `pmtl == "Relevant Molecular Target"`, one of them is NA so I filtered that one out and rename the ID to `PMTL: Pediatric Relevant Molecular Targets (475 genes)`.  @alubneuski , could you please check and make sure the format is what you expected? I will make modifications if it is not. Thanks!
[pmtl_v1.1_475genes.json.zip](https://github.com/PediatricOpenTargets/ticket-tracker/files/7461439/pmtl_v1.1_475genes.json.zip)

**Comment by jharenza** [comment]
Ok great, thank you! I also thought maybe we can add the version to the description. Can you make that update?

**Comment by runjin326** [comment]
[pmtl_v1.1_475genes.json.zip](https://github.com/PediatricOpenTargets/ticket-tracker/files/7462397/pmtl_v1.1_475genes.json.zip)
Sure - included now.

**Comment by jharenza** [comment]
@migbro created https://d3b.atlassian.net/jira/software/projects/DEVOPS/boards/10?selectedIssue=DEVOPS-372&text=ped for @alubneuski

**Comment by jharenza** [comment]
There is a problem with this, in that we cannot view > 1M genes (samples * gene) at any given time, so we would only be able to select few samples to view this list. An alternative proposed by @adamcresnick is to break down this list into smaller, biologically-defined lists (eg kinases, cell cycle genes, etc) and upload multiple small PMTL lists. I will close this for now and create a new issue for that.
