### ISSUE TITLE
Proposed Analysis: Create SNV table from DGD Panel data

### ISSUE THREAD

**Issue by afarrel** [PediatricOpenTargets/ticket-tracker#246]
#### What are the scientific goals of the analysis?
Create DGD Gene Panel pedOT SNV table to report SNV calls from DGD VCFs/MAFS .
Report DGD  Tier 1,2,3 clinical calls when/if available.

#### What input data are required for this analysis?
DGD variant call VCF/MAF files.
V10 - Histology file

#### How long do you expect is needed to complete the analysis? Will it be a multi-step analysis?
3 weeks

#### Who will complete the analysis (please add a GitHub handle here if relevant)?
@ewafula

**Comment by jharenza** [comment]
> Report DGD Tier 1,2,3 clinical calls when/if available.

For this point - can we create a new discussion ticket to brainstorm how best to include this data in releases? From discussion with @afarrel, sounds like it won't be in the MAF itself.

**Comment by runjin326** [comment]
@afarrel - are we still doing this? I think the current plan is to release fusion and MAF from DGD separate from other cohorts. The question is, do we want to add tier info or release as a separate file?

**Comment by jharenza** [comment]
@afarrel since we have #361 open to add DGD to the snv tables _and_ we do not have tier information, I am going to close this.
