### ISSUE TITLE
Bix Dev PedcbioPortal Support: data clinical sample has normal sample

### ISSUE THREAD

**Issue by runjin326** [PediatricOpenTargets/ticket-tracker#247]
# 🆘

#### Please describe your issue in a couple of sentences and provide a link to the relevant pedcbio project of interest, if it already exists
The `data_clinical_sample.txt` in s3://kf-cbioportal-studies/public/ped_opentargets_2021/ bucket has one sample with BS ID `BS_0TCRV9AC` that is a normal sample - and its matched tumor sample is not in the file. 
Please investigate.

#### [Required] How would you most generally describe your issue? 
- [ ] Update data for project in pedcbio portal
- [x] Questions related to data on pedcbio portal

**Comment by migbro** [comment]
@runjin326  has removed the offending sample. Please review https://kf-strides-cbioportal-qa.kidsfirstdrc.org/study/summary?id=ped_opentargets_2021

**Comment by migbro** [comment]
Closing as @runjin326 reviewed QA and given the ok for prod. This sample no longer shows in prod.
