### ISSUE TITLE
Concatenate DGD MAF files for v11 release

### ISSUE THREAD

**Issue by runjin326** [PediatricOpenTargets/ticket-tracker#248]
#### What data file(s) does this issue pertain to?
`snv-consensus-plus-hotspots.maf.tsv.gz`

#### What release are you using?

v10 

#### Put your question or report your issue here.
Please format the DGD panel MAF files to match the format of `snv-consensus-plus-hotspots.maf.tsv.gz`
And then merge the files to SNV MAF file for v11 data release.

**Comment by jharenza** [comment]
@zhangb1 did we run our variant callers on DGD data or did we just use their workflow and convert to hg38? we might want to strategize whether we add to our consensus maf or release their own maf with matching column headers

**Comment by zhangb1** [comment]
@jharenza  DGD maf files will be merged. 

Xiaoyan, already has the script to merge that. DGD also used the hg38, just need to make the column as the same as our results.

**Comment by jharenza** [comment]
@zhangb1 great - can you call this file `snv-dgd.maf.tsv.gz` once the column names are adjusted?

**Comment by zhangb1** [comment]
@HuangXiaoyan0106  FYI.  we can do that... 

> @zhangb1 great - can you call this file `snv-dgd.maf.tsv.gz` once the column names are adjusted?

**Comment by HuangXiaoyan0106** [comment]
@zhangb1  Done

**Comment by runjin326** [comment]
@HuangXiaoyan0106 - could you please put the file in s3://d3b-openaccess-us-east-1-prd-pbta/open-targets/v11/ and update the md5sum? Thanks!

**Comment by zhangb1** [comment]
I just uploaded the file to the v11 folder :

s3://d3b-openaccess-us-east-1-prd-pbta/open-targets/v11/snv-dgd.maf.tsv.gz

md5 also updated

**Comment by jharenza** [comment]
@zhangb1 I was just checking out the DGD merged MAF and noticed that the `Tumor_Sample_Barcode` is the `sample_id`, but to be consistent with the other files, can you update this to the `Kids_First_Biospecimen_ID` please?

**Comment by zhangb1** [comment]
@HuangXiaoyan0106  can you check this?   seems we only concatenate the original DGD maf files together.

the BS ID matched maf file is in the datawarehouse 

![Uploading image.png…]()

**Comment by HuangXiaoyan0106** [comment]
> @HuangXiaoyan0106 can you check this? seems we only concatenate the original DGD maf files together.
> 
> maf file's BS_ID manifest is in the datawarehouse

@zhangb1 @jharenza 
Yes, we just formatted the dgd maf header the same as our maf files and then concatenate them without changing anything else. These formatted maf files are also used for monthly releases of maf files merging.

Do we just need to change the `snv-dgd.maf.tsv.gz` file or need to change all formatted maf files for monthly release?

**Comment by jharenza** [comment]
> Do we just need to change the snv-dgd.maf.tsv.gz file or need to change all formatted maf files for monthly release?

I think to be consistent, we should use bs_id for all TSBs.

**Comment by zhangb1** [comment]
snv-dgd.maf.tsv.gz with the BS_ID has been updated in the v11 folder..

**Comment by jharenza** [comment]
Closed with https://github.com/PediatricOpenTargets/OpenPedCan-analysis/pull/188
