### ISSUE TITLE
Concatenate DGD fusion results for v11 release 

### ISSUE THREAD

**Issue by runjin326** [PediatricOpenTargets/ticket-tracker#249]
#### What data file(s) does this issue pertain to?
*fusions.tsv from DGD fusion panel outputs 

#### What release are you using?

N/A

#### Put your question or report your issue here.
@Bo will generate a concatenated file with all available fusion panel data merged 
@runjin326 will take the file and reformat them to match the column of `fusion-putative-oncogenic.tsv` and merge with v10 `fusion-putative-oncogenic.tsv` for v11 data release.

**Comment by jharenza** [comment]
create `fusion-dgd.tsv` for this?

**Comment by zhangb1** [comment]
We talked this before, but the DGD fusion results have such minimal column, we can't have them in the same format of our fusion results,  for example DGD fusion results here. 

```
Hugo_Symbol	Entrez_Gene_Id	Center	Tumor_Sample_Barcode	Fusion	DNA_support	RNA_support	Method	Frame
KMT2A		CHOP-DGD	BS_02R0RSH8	KMT2A-ELL	unknown	yes		
ELL		CHOP-DGD	BS_02R0RSH8	KMT2A-ELL	unknown	yes		
KMT2A		CHOP-DGD	BS_02R0RSH8	KMT2A-ELL	unknown	yes		
ELL		CHOP-DGD	BS_02R0RSH8	KMT2A-ELL	unknown	yes		
```

**Comment by jharenza** [comment]
looks like `Entrez_Gene_Id` is missing - can you just remove that and we can just create a tsv called `fusion-dgd.tsv` of what you have above

**Comment by zhangb1** [comment]
@HuangXiaoyan0106 FYI ^

**Comment by runjin326** [comment]
Once complete - could you please put the file in s3://d3b-openaccess-us-east-1-prd-pbta/open-targets/v11/ and update the md5sum? Thanks!

**Comment by runjin326** [comment]
@HuangXiaoyan0106, any update on this?

**Comment by jharenza** [comment]
@zhangb1 can you add me to the project above please

**Comment by zhangb1** [comment]
Sorry for the late

The DGD fusion files are in the bucket now

s3://d3b-openaccess-us-east-1-prd-pbta/open-targets/v11/fusion-dgd.tsv.gz

**Comment by jharenza** [comment]
Hi @HuangXiaoyan0106 - it looks like this file is largely using old BS_IDs for DGD. Can you use the v11 OpenPedCan histology file (s3://d3b-openaccess-us-east-1-prd-pbta/open-targets/v11/histologies-base.tsv) or the genomics mapping file as mentioned [here](https://github.com/PediatricOpenTargets/ticket-tracker/issues/347#issuecomment-1148146090).

610/870 are not current IDs in the histologies file. Can you re-map these please? cc @zhangb1

**Comment by HuangXiaoyan0106** [comment]
@jharenza I didn't use any histology file to do the fusion merge, just concatenated the original fusion files. So I think in the short term, I can update the merged file directly, but in the long run, maybe need to update the original fusion file? cc @zhangb1

**Comment by HuangXiaoyan0106** [comment]
@jharenza 
I have checked the IDs in` fusion-dgd.tsv.gz`, `bix_workflows.dgd_genomics_file_manifest` and `histologies-base.tsv`, all IDs in ` fusion-dgd.tsv.gz` are exist in the other two files.

```
awk -F "\t" '{print $3}' fusion-dgd.tsv  |sort|uniq > merge_ids.txt

grep fusions.tsv dgd_genomics_file_manifest.csv |awk -F ","  '{print $1}' |sort|uniq  > dw_ids.txt

awk -F "\t" '{print $1}' histologies-base.tsv |sort |uniq > s3_ids.txt
```
[ids.xlsx](https://github.com/PediatricOpenTargets/ticket-tracker/files/8875429/ids.xlsx)


### check results
```
% comm -23 merge_ids.txt dw_ids.txt
Tumor_Sample_Barcode

% comm -23 merge_ids.txt s3_ids.txt
Tumor_Sample_Barcode
```

**Comment by jharenza** [comment]
Oh you know what- I was looking in the opposite direction - trying to make sure all samples were in the fusion file, but they're probably missing because they don't have fusions. Sorry about that! Disregard!

**Comment by runjin326** [comment]
@HuangXiaoyan0106 - I was using the files for some analyses and noticed that for sample `BS_WQN6CS9Q`, the fusion listed was `DGD-19-6752_COMPT`. Could you please check to see why that is the case?

Additionally, when you write out the file, could you please call a `distinct` on the rows. There are currently 864 rows but there are actually only 562 unique rows. Thanks!

**Comment by HuangXiaoyan0106** [comment]
> @HuangXiaoyan0106 - I was using the files for some analyses and noticed that for samples `BS_WQN6CS9Q`, `BS_YKEK4YWT`, the fusion listed was `DGD-19-6752_COMPT`. Could you please check to see why that is the case?

@runjin326 I don't know the reason, but the original file provided by DGD is like this. cc @zhangb1 
- BS_WQN6CS9Q.fusions.tsv 
https://cavatica.sbgenomics.com/u/zhangb1/dgd-pipeline-output/files/617963487461755228d4e98f/
- BS_YKEK4YWT.fusions.tsv 
https://cavatica.sbgenomics.com/u/zhangb1/dgd-pipeline-output/files/6179634c7461755228d4ea5d/

**Comment by runjin326** [comment]
Thanks for checking @HuangXiaoyan0106 - @jharenza, should we just remove those two samples from the files then?

**Comment by jharenza** [comment]
@runjin326 are there actual fusions in the files? It seems the rows might be shifted and we should definitely fix these @zhangb1 @yuankunzhu - this may be an issue for pedcbio also cc @migbro for how this was handled

**Comment by migbro** [comment]
So, if it's the ones that Mark Welsh converted a while back, pretty sure I was able to account for any shifting, I processed them separately and basically appended to PBTA results in my ETL

**Comment by jharenza** [comment]
> So, if it's the ones that Mark Welsh converted a while back, pretty sure I was able to account for any shifting, I processed them separately and basically appended to PBTA results in my ETL

Do you have some code for this that you can pointt @HuangXiaoyan0106 to to fix the files? We probably should fix the native file, so this is not a problem with future merges.

**Comment by jharenza** [comment]
@HuangXiaoyan0106 or @zhangb1 can you update the columns in the original file, then re-merge? Thanks!

**Comment by HuangXiaoyan0106** [comment]
> Sure, so it's here: https://github.com/kids-first/kf-cbioportal-etl/blob/master/scripts/add_dgd_fusion.py
> May want to modify as it was designed to work with a manifest


@migbro where can I get the metadata? I only have the original tsv files, as follows. I don't know what the real Hugo_Symbol/Fusion of these two samples should be.
```
% head BS_WQN6CS9Q.fusions.tsv
Hugo_Symbol	Entrez_Gene_Id	Center	Tumor_Sample_Barcode	Fusion	DNA_support	RNA_support	Method	Frame
DGD		CHOP-DGD	BS_WQN6CS9Q	DGD-19-6752_COMPT	unknown	yes
19		CHOP-DGD	BS_WQN6CS9Q	DGD-19-6752_COMPT	unknown	yes
DGD		CHOP-DGD	BS_WQN6CS9Q	DGD-19-6752_COMPT	unknown	yes
19		CHOP-DGD	BS_WQN6CS9Q	DGD-19-6752_COMPT	unknown	yes
DGD		CHOP-DGD	BS_WQN6CS9Q	DGD-19-6752_COMPT	unknown	yes

% head BS_YKEK4YWT.fusions.tsv
Hugo_Symbol	Entrez_Gene_Id	Center	Tumor_Sample_Barcode	Fusion	DNA_support	RNA_support	Method	Frame
DGD		CHOP-DGD	BS_YKEK4YWT	DGD-19-6772_COMPT	unknown	yes
19		CHOP-DGD	BS_YKEK4YWT	DGD-19-6772_COMPT	unknown	yes
DGD		CHOP-DGD	BS_YKEK4YWT	DGD-19-6772_COMPT	unknown	yes
19		CHOP-DGD	BS_YKEK4YWT	DGD-19-6772_COMPT	unknown	yes
DGD		CHOP-DGD	BS_YKEK4YWT	DGD-19-6772_COMPT	unknown	yes
```

**Comment by runjin326** [comment]
@jharenza and @HuangXiaoyan0106 - I removed the 2 samples from the file, kept only distinct entries and uploaded both fusion + md5sum to s3. Also created a ticket for this.

**Comment by migbro** [comment]
Hmmm, yeah, I think those two files are an anomaly no one has ever noticed. All other files either have no calls, or just a couple fusion calls with gene names. I agree with the assessment to remove those two. Good catch!

**Comment by jharenza** [comment]
https://github.com/PediatricOpenTargets/OpenPedCan-analysis/pull/188
