### ISSUE TITLE
Add PBTA samples for v11 release 

### ISSUE THREAD

**Issue by runjin326** [PediatricOpenTargets/ticket-tracker#253]
#### What data file(s) does this issue pertain to?

DNA-related files:
```
cnv-cnvkit.seg.gz
cnv-controlfreec.tsv.gz
snv-consensus-plus-hotspots.maf.tsv.gz
```
Please add back `BS_4SCDT7M9` to `cnv-cnvkit.seg.gz` 

RNA-related files:
```
gene-counts-rsem-expected_count-collapsed.rds
gene-expression-rsem-tpm-collapsed.rds
fusion-arriba.tsv.gz
fusion-starfusion.tsv.gz
```
Please merge and re-collapse the TPM and count files for RNA-seq after merging RNA-Seq data from PNOC.

#### What release are you using?

v10

**Comment by runjin326** [comment]
@zhangb1 - do we have any updates on the status of this ticket?

**Comment by zhangb1** [comment]
humm, I missed this ticket... 

Do we know which PNOC samples need to merged to V11, we have the patient up to 54 now .. but missing one patient 53 which is the last patient of PNOC

**Comment by zhangb1** [comment]
@jharenza  seems you will confirm with Adam, do we know we need to wait for the last patient ?  should be come back in this week or so.

**Comment by jharenza** [comment]
Yes, we will wait

**Comment by runjin326** [comment]
Thanks @zhangb1 !

**Comment by jharenza** [comment]
@zhangb1 it seems like GTEX are missing from the files below:

Can you add those back to the original merge files and re-do this collapse? Or, I am not sure if you collapsed separately last time and merged the common genes?

```
gene-counts-rsem-expected_count-collapsed.rds
gene-expression-rsem-tpm-collapsed.rds
```

cc @komalsrathi @runjin326

**Comment by zhangb1** [comment]
Oh, I merged separate , I am adding Gtex samples now.

**Comment by jharenza** [comment]
Thanks, no worries - forgot to mention it. Are md5 also updated?

**Comment by zhangb1** [comment]
Yes.

**Comment by jharenza** [comment]
thank you!

**Comment by jharenza** [comment]
https://github.com/PediatricOpenTargets/OpenPedCan-analysis/pull/188
