### ISSUE TITLE
Generate CNV annotation file for v11 release

### ISSUE THREAD

**Issue by runjin326** [PediatricOpenTargets/ticket-tracker#254]
#### What data file(s) does this issue pertain to?
```
 consensus_wgs_plus_cnvkit_wxs.tsv.gz
 consensus_wgs_plus_cnvkit_wxs_autosomes.tsv.gz
 consensus_wgs_plus_cnvkit_wxs_x_and_y.tsv.gz
```
Once `cnv-cnvkit.seg.gz` is updated to include new PNOC samples and the annotation scheme is implemented (see [PR#153](https://github.com/PediatricOpenTargets/OpenPedCan-analysis/pull/153)), focal CN annotation module needs to be re-ran to generate the above updated files. 

#### What release are you using?

v10 + additional PNOC

**Comment by zhangb1** [comment]
rerun the consensus call now , using the latest genecode.

**Comment by zhangb1** [comment]
```
2022-05-25 08:59:22  316563970 consensus_wgs_plus_cnvkit_wxs.tsv.gz
2022-05-25 09:02:12  300641036 consensus_wgs_plus_cnvkit_wxs_autosomes.tsv.gz
2022-05-25 09:04:38   16317262 consensus_wgs_plus_cnvkit_wxs_x_and_y.tsv.gz
```

CNV annotation files updated in the v11 bucket....

**Comment by runjin326** [comment]
@zhangb1 - thanks so much!

**Comment by jharenza** [comment]
@zhangb1 can you pull recent code from https://github.com/PediatricOpenTargets/OpenPedCan-analysis/pull/186/files which will generate 2 more files for the release?

**Comment by jharenza** [comment]
`cnvkit_with_status.tsv` and `consensus_seg_with_status.tsv` are the files we would need

**Comment by zhangb1** [comment]
```
2022-06-06 15:39:07  139034795 cnvkit_with_status.tsv
2022-06-06 15:40:28    1081778 consensus_seg_with_status.tsv
```

I ran the merged for this locally ,so I had the data updated in the v11 bucket now. 

s3://d3b-openaccess-us-east-1-prd-pbta/open-targets/v11/

Let me know whether they are good.

**Comment by jharenza** [comment]
😅 thank you! @runjin326 can you double check these please?

**Comment by jharenza** [comment]
https://github.com/PediatricOpenTargets/OpenPedCan-analysis/pull/188
