### ISSUE TITLE
Getting bed files for TMB calculation 

### ISSUE THREAD

**Issue by runjin326** [PediatricOpenTargets/ticket-tracker#258]
#### What data file(s) does this issue pertain to?
Padded bed files used for MAF calling in GMKF, TARGET and PNOC

#### What release are you using?
@ewafula, the bed files for PBTA samples can be found in this S3 bucket: s3://d3b-openaccess-us-east-1-prd-pbta/data/release-v21-20210820/ - I can also download them and sent them to you if you do not have access.
I think for those, we can stick with the original calculation in OpenPBTA - @jharenza, when you mentioned we need to update PBTA, do you mean to update what we currently have in OT repo to be in sync with v21 release? 

For PNOC, from [this file](https://github.com/d3b-center/d3b-pnoc003-HGG-DMG-omics/blob/master/analyses/tmb-plots/input/config_files/target_cfg.targetcombos.txt) - it looks like different trial and different panels use different bed files for calculation. Do we want to use those bed files? Alternatively, in OMPARE, `ashion_confidential_exome_v2_2nt_pad.Gh38.bed` file is used for all samples for TMB calculation. Should we use that file for `PNOC_dataset_2` and use PBTA calculation for `PNOC_dataset_1` then? @jharenza

For GMKF and TARGET, @zhangb1, could you please generate/share the padded bed files used for MAF calling? We could release those in v11 as well.

**Comment by jharenza** [comment]
@runjin326 i made a comment on the analysis ticket regarding your question above:

https://github.com/PediatricOpenTargets/ticket-tracker/issues/250#issuecomment-982163724

**Comment by zhangb1** [comment]
@runjin326 , for openTagret, please see the slack message from : 

https://opentargetspediatrics.slack.com/archives/C021N2D56DB/p1625114498299200?thread_ts=1624885379.266600&cid=C021N2D56DB

it's pinned in the data-harmonization channel. 

there is a manifest for the bed files for each samples.  but there are all hg19 or 37.  we converted to the hg38, I will send you the hg38 by tomorrow.

**Comment by runjin326** [comment]
@zhangb1, thanks so much! A few more follow up questions:
1) Do you also have bed files for GMKF? 
2) For `PNOC_dataset_2`, as you mentioned, 3 sequencing centers were involved - do you have the matching bed file for all these 3 center: 
```
[1] "CHOP DGD"  "Ashion"    "NantOmics"
```
3) I see that for `PNOC_dataset_1`, there are WGS, WXS with various different sequencing center, e.g., `"BGI@CHOP Genome Center" "Novogene"  `. Do you have the matching manifest and the respective bed files? 

Thanks!

**Comment by zhangb1** [comment]
sent the region files to Run by slack

**Comment by runjin326** [comment]
@ewafula, please use the attached file for matching Kids First Biospecimen ID to bed files:
[biospecimen_id_to_bed_map.txt](https://github.com/PediatricOpenTargets/ticket-tracker/files/7685369/biospecimen_id_to_bed_map.txt)
And attached here is the folder containing all the bed except for `intersect_strelka_mutect2_vardict_WGS.bed` which is a bed intersect of `wgs_canonical_calling_regions.hg38.bed` and `hg38_strelka.bed` - let me know if you need help making the intersect. 
Currently, the bed file I specified here are all 100bp padded (for both WXS and panel) - we can start with this and if later on, we get feedback about using a different padding, we can simply switch out the files used. But I think the files should be able to get you started with the project. Let me know if there is anything else you need. Thanks!

**Comment by jharenza** [comment]
> @ewafula, please use the attached file for matching Kids First Biospecimen ID to bed files:
> 
> [biospecimen_id_to_bed_map.txt](https://github.com/PediatricOpenTargets/ticket-tracker/files/7685369/biospecimen_id_to_bed_map.txt)
> 
> And attached here is the folder containing all the bed except for `intersect_strelka_mutect2_vardict_WGS.bed` which is a bed intersect of `wgs_canonical_calling_regions.hg38.bed` and `hg38_strelka.bed` - let me know if you need help making the intersect. 
> 
> Currently, the bed file I specified here are all 100bp padded (for both WXS and panel) - we can start with this and if later on, we get feedback about using a different padding, we can simply switch out the files used. But I think the files should be able to get you started with the project. Let me know if there is anything else you need. Thanks!

@runjin326 can you do a quick release of these files so they're in the download,if ready?

**Comment by runjin326** [comment]
@jharenza , sure - this will be quick v11 release? or v10.1? Currently, the v11 is sort of planned out to include new DGD etc. 
Also - do you think it's ok to use 100bp padded bed for all panels and WXS? And we would make our own intersect of bed files instead of using OpenPBTA version?

**Comment by ewafula** [comment]
> @jharenza , sure - this will be quick v11 release? or v10.1? Currently, the v11 is sort of planned out to include new DGD etc. Also - do you think it's ok to use 100bp padded bed for all panels and WXS? And we would make our own intersect of bed files instead of using OpenPBTA version?

@runjin326, when ready let me where the are located. I will create the intersect file, `intersect_strelka_mutect2_vardict_WGS.bed`

**Comment by runjin326** [comment]
@ewafula, yes - here is the zip file with all bed files that we would use for this project.
[all_bed_files_for_OT.zip](https://github.com/PediatricOpenTargets/ticket-tracker/files/7686139/all_bed_files_for_OT.zip)

**Comment by jharenza** [comment]
> @jharenza , sure - this will be quick v11 release? or v10.1? Currently, the v11 is sort of planned out to include new DGD etc. 
> 
> Also - do you think it's ok to use 100bp padded bed for all panels and WXS? And we would make our own intersect of bed files instead of using OpenPBTA version?

We could make this v11 and DGD v12, since it's going to take some time for histologies and efo/mondo/etc.

The padded beds should be whatever was used in variant calling. I'm still somewhat confused. If @zhangb1 used 100bp padding for MUTECT WXS variant calling for example, we use that for calculating Tmb from the mutect MAF for those WXS. We shouldn't pad extra if the variant calling didn't include those regions - then we could miss variants going into the numerator and simultaneously increase the denominator for Tmb artificially, does that make sense?

Regarding the intersect, this will likely have to be done per wxs panel. For ex, TARGET WXS will have a different intersect BED than PBTA WXS for dataset 1. All of those intersects should be done within the module.

Regarding the 2bp padding @migbro - can you review the workflow with @zhangb1 for those clinical trial samples? Cc @aadamk - it sounds like we might want to rerun those with 100bp padding and update this workflow for future samples?

**Comment by runjin326** [comment]
@jharenza, thanks - I will double check with Bo to see whether padded or unpadded files are used for calling. 
In terms of intersecting - I think this only pertains to WGS samples? For all WXS and panels, there is only one associated bed file and I don't think it is caller-specific? I will double check all these. 
In the meantime @ewafula, please use this updated bed mapping file - the NA that you saw before was fixed (thanks for checking) -
[biospecimen_id_to_bed_map.txt](https://github.com/PediatricOpenTargets/ticket-tracker/files/7695811/biospecimen_id_to_bed_map.txt)
And also maybe implemented what Jo Lynne mentioned - add the intersect code in the TMB module if possible. Thanks!

**Comment by ewafula** [comment]
> @jharenza, thanks - I will double check with Bo to see whether padded or unpadded files are used for calling. In terms of intersecting - I think this only pertains to WGS samples? For all WXS and panels, there is only one associated bed file and I don't think it is caller-specific? I will double check all these. In the meantime @ewafula, please use this updated bed mapping file - the NA that you saw before was fixed (thanks for checking) - [biospecimen_id_to_bed_map.txt](https://github.com/PediatricOpenTargets/ticket-tracker/files/7695811/biospecimen_id_to_bed_map.txt) And also maybe implemented what Jo Lynne mentioned - add the intersect code in the TMB module if possible. Thanks!

**Comment by runjin326** [comment]
@ewafula, I have now modified the bed file mapping - attached here. 
[biospecimen_id_to_bed_map.txt](https://github.com/PediatricOpenTargets/ticket-tracker/files/7704544/biospecimen_id_to_bed_map.txt)

And also confirmed with Bo that for variant calling, he used 100bp padded bed files for all of them.

**Comment by ewafula** [comment]
> @ewafula, I have now modified the bed file mapping - attached here. 
> 
> [biospecimen_id_to_bed_map.txt](https://github.com/PediatricOpenTargets/ticket-tracker/files/7704544/biospecimen_id_to_bed_map.txt)
> 
> 
> 
> And also confirmed with Bo that for variant calling, he used 100bp padded bed files for all of them. 

@runjin326,thanks! What about the 6 samples in snv consensus file and absent in both the sample-bed mapping and histologies files? Any work from @zhangb1

**Comment by runjin326** [comment]
@ewafula, I will keep you posted about that - but that would need to be fixed for a data release - unlikely to get fixed right now. So maybe you can write your code to mitigate that (e.g., use the bed file map file to search SNV, or however you want to do0?

**Comment by jharenza** [comment]
Thanks @runjin326, @zhangb1, and @ewafula for your work on this!

**Comment by ewafula** [comment]
@zhangb1, is there a reason why this bed files (attached)for that provided @runjin326 utilized the [OpenPedCan TMB calculation PR](https://github.com/PediatricOpenTargets/OpenPedCan-analysis/pull/157) has some of the coordinates flipped - `start` supposed to be a lower value than `end `  in the bed files? I re-oriented them in the module development. But  @runjin326 is trying to figure out the reason why were not oriented correctly before and if there technical reason why before makes the next  OpenPedCan data release. [See discussion here](https://github.com/PediatricOpenTargets/OpenPedCan-analysis/pull/157#issuecomment-1012393278)

```
  > read_tsv("Strexome_targets_intersect_sorted_padded100.GRCh38.bed", col_names = c("chr", "start", "end")) %>% filter(start > end)
Rows: 191872 Columns: 3                                                                                            
-- Column specification ---------------------------------------------------------------------------------------------------------------------------------------------------
Delimiter: "\t"
chr (1): chr
dbl (2): start, end

i Use `spec()` to retrieve the full column specification for this data.
i Specify the column types or set `show_col_types = FALSE` to quiet this message.
# A tibble: 48 x 3
   chr       start       end
   <chr>     <dbl>     <dbl>
 1 chr1    1715054   1654410
 2 chr1   13420578  13369740
 3 chr1  143883915 121374293
 4 chr1  144994907 144955700
 5 chr1  149029686 120176807
 6 chr1  148784365 145608302
 7 chr1  147966671 145483681
 8 chr1  148334337 143544474
 9 chr1  206115845 206010446
10 chr1  248916478 146547684
# ... with 38 more rows
>  
```
[Strexome_targets_intersect_sorted_padded100.GRCh38.bed.zip](https://github.com/PediatricOpenTargets/ticket-tracker/files/7867452/Strexome_targets_intersect_sorted_padded100.GRCh38.bed.zip)

**Comment by zhangb1** [comment]
@ewafula  the PNOC003 should be this one. I may send Run the incorrect one? . I just double checked the email. and find this one attached . seems no issues with this one. 
[Strexome_targets_intersect_sorted_padded100.GRCh38.bed.zip](https://github.com/PediatricOpenTargets/ticket-tracker/files/7870864/Strexome_targets_intersect_sorted_padded100.GRCh38.bed.zip)

**Comment by ewafula** [comment]
> @ewafula  the PNOC003 should be this one. I may send Run the incorrect one? . I just double checked the email. and find this one attached . seems no issues with this one. 
> 
> [Strexome_targets_intersect_sorted_padded100.GRCh38.bed.zip](https://github.com/PediatricOpenTargets/ticket-tracker/files/7870864/Strexome_targets_intersect_sorted_padded100.GRCh38.bed.zip)
> 
> 

@zhangb1, thank you!

**Comment by jharenza** [comment]
these are now in the repo within `tmb-calculation`
