### ISSUE TITLE
Fill in harmonized diagnosis in histology file

### ISSUE THREAD

**Issue by runjin326** [PediatricOpenTargets/ticket-tracker#259]
#### What data file(s) does this issue pertain to?
histologies.tsv

#### What release are you using?

v10

#### Put your question or report your issue here.
Starting from v11, for tumor samples without harmonized diagnosis that are not from TCGA cohort - let's update `harmonized_diagnosis` field using the following logic:
- If `pathology_diagnosis` is not "Unknown", fill in `harmonized_diagnosis` with `pathology_diagnosis`;
- If `pathology_diagnosis` is "Unknown", fill in `harmonized_diagnosis` with `cancer_group`

See[ this code](https://github.com/runjin326/CHOP_miscellaneous/blob/main/PedCBio_delivery/histology_v10_pedcbio.R) for guidance.

**Comment by jharenza** [comment]
this will be completed in #299
