### ISSUE TITLE
Update EFO MONDO mapping file

### ISSUE THREAD

**Issue by runjin326** [PediatricOpenTargets/ticket-tracker#261]
#### What data file(s) does this issue pertain to?
`efo-mondo-map.tsv`

#### What release are you using?

v10

#### Put your question or report your issue here.
Currently, this file only has EFO and MONDO terms mapped to it -
1) Please review and make sure all the terms that we have listed there are up-to-date with newest OLS update
2) Please add another column to include NCIT code as well 

This can be done when TARGET AML terms are updated - see [this issue ](https://github.com/PediatricOpenTargets/Histologies/issues/2)

**Comment by jharenza** [comment]
Closed with https://github.com/PediatricOpenTargets/OpenPedCan-analysis/pull/188
