### ISSUE TITLE
Added proposed cBio names to histologies table

### ISSUE THREAD

**Issue by migbro** [PediatricOpenTargets/ticket-tracker#263]
#### What data file(s) does this issue pertain to?

histologies

#### What release are you using?

v10

#### Put your question or report your issue here.

Request to add a column for cBio names for non-PBTA/KF studies. If possible, for samples in PBTA, KF would recommend using existing cBio names, maintained in the D3b data warehouse. Sample naming conventions:

# Sample Naming Guidelines

## Ground Rules

In general, the sample ID used to identify related sample data is a somatic event ID. This means that, from a biospecimen collection event - be it a blood draw, biopsy, etc - many possible "omics" assays can be run, such as DNA sequencing (WGS, panel, exome), RNA, Mass spec. Data derived from each of these assay types must be tied together by a common ID that allows a user to uniquely explore all of the derived facets of that biospecimen.  Per cBio ID, a hard and fast rule is that per analyte_type, only one sample id should appear.

## Overall Format

The overall format of KF cBioPortal Sample names will be:
`{sample_id}_{string}`

The breakdown of the sample ID is as such:

- `sample_id` - typically generated by some kind of LIMS system and is normally shared across data derived from various assays
- `string` - An optional "tie-breaker" string. This is often needed when technical replicates are made from the same biospecimen, or some type of continued in-vitro derivation (cell line, PDX, organoid,  etc) has been derived from the original biospecimen and additionally assayed.
    - If cell line - append `-CL`
    - If multiple cell lines, append additional descriptor to `CL`, like `-CL-adh`
    - If from same surgical event, append an aliquot ID if available
    - Until further notice, technical replicates are not loaded and are added to the `bix_workflows.cbio_hide_reasons` table

**Comment by jharenza** [comment]
@migbro how about instead of adding to the histologies file, we create a module for this, which will then create a tsv file of all columns required for pedcbio?

I am partial to doing it this way to not weigh down the histologies file, especially because we may not be able to do this upfront prior to analyses, which is when the histologies file itself is generated.

**Comment by migbro** [comment]
Yeah, sure! The most useful thing would be to create it in the warehouse - basically BS ID + cBio name for the tumor samples. Could  pre-populate with the existing IDs from the cBio naming tables from the data warehouse and then supplement the rest. @runjin326 , the tables in the warehouse I am referring to that have `specimen_id` (as an array with DNA/RNA pairs) and `formatted_sample_id` are in the `prod_cbio` schema, tables with suffix `_cbio_sample`

**Comment by jharenza** [comment]
Ok- maybe we can go that route, but may need some help from Nick or Meen?

**Comment by runjin326** [comment]
@migbro - to follow up on this ticket, could you please offer some pointers as to how to get those pedcbio schema tables? I am not that familiar with DWH yet. 
And to confirm, the way to approach this would be: 
1) use a module to supplement histology file with pedcbio name 
2) get the tables from DWH and use those names for samples that have cBio name already 
3) for samples that do not have cBio name in DWH, supplement them with names following the sample naming guidelines?

**Comment by migbro** [comment]
Hi @runjin326,
Sure! If you don't have access to the D3b data warehouse yet, you can asked for access creating a Jira ticket here: https://d3b.atlassian.net/jira/software/projects/DEVOPS/boards/10 and assingn Nick Van Kuren. You'll want to be sure to request access to the `prod_cbio` schema as well as `bix_workflows` for good measure. Once you have access to those, you can see what BS IDs I have already created cBio names for in the tables ending with `_cbio_sample`.

With the above information, I think your plan is solid and will be supported!

**Comment by runjin326** [comment]
@migbro, thanks so much! I will work on getting access and tables and proceed with creating a module.

**Comment by runjin326** [comment]
@jharenza and @migbro, as I am looking into this, I got a bit confused as to how to add the additional strings to the sample ID and when it would be necessary to do so. Hence I have the following questions - basically trying to figure out the current procedure for adding strings and discuss methods for adding strings for this ticket. 

Currently, for what is in `prod_cbio` schema, it looks like the formatted ID is done as following:
1) For GMKF, looks like we are just using the `Kids_First_Participant_ID` as formatted specimen ID - should we do the same procedure for all TARGET cohorts?
2) For PBTA, looks like an additional string is given when multiple samples with the same experimental strategy was taken and the parent aliquot ID was used as the tie breaker if the `composition` is not the same. And when the `composition` is NOT the same, additional string specifying the `composition` is added. Is that correct? If so, should we do the same for the rest of PBTA which does not have the formatted ID yet? 
3) For GTEx and TCGA, should we just use the `Kids_First_Participant_ID` as formatted sample ID?

**Comment by migbro** [comment]
@runjin326 , yeah, it's tricky - maybe we can talk about it some time today or tomorrow? I can try and set up a meeting.

**Comment by runjin326** [comment]
@migbro, sure - a meeting will be great!

**Comment by jharenza** [comment]
@runjin326 will add her code/link to PR here, but this is updated in [QA](https://kf-strides-cbioportal-qa.kidsfirstdrc.org/study/summary?id=ped_opentargets_2021)

**Comment by runjin326** [comment]
The PR for this is [here](https://github.com/PediatricOpenTargets/OpenPedCan-analysis/pull/163). The PR should be ready for merge now.

**Comment by jharenza** [comment]
completed in https://github.com/PediatricOpenTargets/OpenPedCan-analysis/pull/163
