### ISSUE TITLE
Proposed Analysis: Add a module to remove ENSGs not in GENCODEv38 from jsonl tables

### ISSUE THREAD

**Issue by runjin326** [PediatricOpenTargets/ticket-tracker#268]
#### What are the scientific goals of the analysis?

- As mentioned in [ticket 265 ](https://github.com/PediatricOpenTargets/ticket-tracker/issues/265) and [ticket 264](https://github.com/PediatricOpenTargets/ticket-tracker/issues/264), there are ENSGs in the tables for FNL that are not in GENCODE v38 and Ensembl package 104.
- Since various versions were used for different datasets, creating a module that filters out ENSGs that are no longer present in GENCODE v38 and Ensembl package 104 would be the desirable solution. 

#### What methods do you plan to use to accomplish the scientific goals?
Create a module that handles the following:
1) Reads in frequency table 
2) Filter out ENSGs that are not in GENCODE v38 and Ensembl package 104 
3) Generate a Rmd notebook that showed the number of dropouts (and what are those) during the filtering process.

Per discussion with Jo Lynne, we would likely be missing some IGH@ genes when filtering out - for those samples, we would have to remap with star and star fusion, and manually use those samples for the frequency tables. This would be contingent on the results of the QC Rmd note specified in step 3.

#### What input data are required for this analysis?
All the frequency tables that are currently uploaded to FNL box (SNV, CNV and fusion, by variant and by gene).

#### How long do you expect is needed to complete the analysis? Will it be a multi-step analysis?
2-3 days.

#### Who will complete the analysis (please add a GitHub handle here if relevant)?
@ewafula 

#### What relevant scientific literature relates to this analysis?
N/A

**Comment by jharenza** [comment]
closed with #162
