### ISSUE TITLE
Proposed Analysis: TARGET arrays methylation analysis/methylation table

### ISSUE THREAD

**Issue by ewafula** [PediatricOpenTargets/ticket-tracker#269]
#### What are the scientific goals of the analysis?
Preprocess probe hybridization intensity values of selected methylated and unmethylated cytosine (CpG) loci into usable methylation measurements for the Pediatric Open Targets, OPenPedCan-analysis raw DNA methylation array datasets.

#### What methods do you plan to use to accomplish the scientific goals?
[minfi Bioconductor package](https://bioconductor.org/packages/release/bioc/html/minfi.html).

#### What input data are required for this analysis?
The TARGET Illumina `Infinium HumanMethylation (450k and 27k) BeadChip` and `Roche Nimblegen HELP` methylation arrays and sample metadata for following TARGET pediatric cancers
 
- [Neuroblastoma (NBL)](https://target-data.nci.nih.gov/Public/NBL/methylation_array/) - `Infinium HumanMethylation450`
- [Osteosarcoma (OS)](https://target-data.nci.nih.gov/Public/OS/methylation_array/) - `Infinium HumanMethylation450`
- [Clear Cell Sarcoma of the Kidney (CCSK)](https://target-data.nci.nih.gov/Public/CCSK/methylation_array/) - `Infinium HumanMethylation450`
- [Wilms Tumor (WT)](https://target-data.nci.nih.gov/Public/WT/methylation_array/) - `Infinium HumanMethylation450`
- [Acute Myeloid Leukemia (AML)](https://target-data.nci.nih.gov/Public/AML/methylation_array/) - `Infinium HumanMethylation450 and Infinium HumanMethylation27`
- [Acute Lymphoblastic Leukemia (ALL)](https://target-data.nci.nih.gov/Public/ALL/methylation_array/Phase2/) - `Nimblegen HELP methylation`

#### How long do you expect is needed to complete the analysis? Will it be a multi-step analysis?
2- 3 weeks

#### Who will complete the analysis (please add a GitHub handle here if relevant)?
@ewafula, @afarrel 

#### What relevant scientific literature relates to this analysis?
- https://www.ncbi.nlm.nih.gov/pmc/articles/PMC5907140/
- https://academic.oup.com/bioinformatics/article/30/10/1363/267584
- https://academic.oup.com/bioinformatics/article/33/4/558/2666344

**Comment by ewafula** [comment]
[Part A- methylation-preprocessing;  PR #169](https://github.com/PediatricOpenTargets/OpenPedCan-analysis/pull/169) ready for review 
[Part B- methylation-summary;  PR #165](https://github.com/PediatricOpenTargets/OpenPedCan-analysis/pull/165) is awaiting v11 histologies update with CBTN methylation samples to be rerun.

**Comment by runjin326** [comment]
Once the file is ready, please upload the file to s3://d3b-openaccess-us-east-1-prd-pbta/open-targets/v11/ and update the md5sum.

**Comment by ewafula** [comment]
@afarrel, can you upload the `TARGET and CBTN methylation preprocessing results` to the S3 bucket. Only a few in our group have access. I don't.  You'll upload the downstream results (`beta/m-value matrices` and `methylation summary table`) produced by the `methylation-summary module` when the v11 histologies file is ready. Here are the md5 checksums of the files located in the OT storage on Isilon (`/mnt/isilon/opentargets/wafulae/methylation-preprocessing/results/`). Very large files and might take a long time to complete the transfer (CBTN ~15G and TARGET ~3.8 when gzipped).
```
91643df198bf74e3677b2dfa6ea0fa9b  CBTN-m-values-methylation.tsv.gz
e1784eaaacf90fb6371919e92d7b69a6  CBTN-beta-values-methylation.tsv.gz
53de6e4480a222316a5be679d7c2a57f  TARGET-m-values-methylation.tsv.gz
da141bbb19c2964fbea41ab4aa8a7c25  TARGET-beta-values-methylation.tsv.gz
```

**Comment by jharenza** [comment]
@ewafula can you merge the cohorts altogether, and also keep with the naming conventions within the repo, so something like:
`methyl-beta.tsv.gz` and `methyl-m.tsv.gz`?

**Comment by ewafula** [comment]
> @ewafula can you merge the cohorts altogether, and also keep with the naming conventions within the repo, so something like: `methyl-beta.tsv.gz` and `methyl-m.tsv.gz`?

@jharenza, as discussed on slack, I assume we are no longer uploading the methylation pre-processing results, but the downstream methylation scores matrices and the methylation summary table. The cohorts are merged together in these.  I'll rename the two files following the convention you have shown above:
```
- Beta-value matrix: methyl-beta.rds
- M-value matrix: methyl-m.rds
- Methylation summary table: methyl-summary.tsv.gz
```
