### ISSUE TITLE
Proposed Analysis: Compare RNAseq expression values from JAX/PIVOT pipelines, KidsFirst pipelines, and Baylor pipelines from original PPTC project

### ISSUE THREAD

**Issue by afarrel** [PediatricOpenTargets/ticket-tracker#271]
#### What are the scientific goals of the analysis?
Compare the Expression values from JAX/PIVOT pipelines, KidsFirst pipelines, and Baylor pipelines from original PPTC paper to understand the difference in quantitative output from the 3 methods.

#### What methods do you plan to use to accomplish the scientific goals?
Calculate correlation, standard error and percent error between the 3 pipelines taking into consideration 3 levels of evaluation:

1. All Genes
2. Cancer Genes (PMTL and Cancer gene panel genes)
3. Genes with high homology between mouse and human

These additional levels of evaluating the methods should be included:
1. Genes >= 5 TPM in at least cohort
2. All Genes

#### What input data are required for this analysis?
Counts and TPM values from various outputs

#### How long do you expect is needed to complete the analysis? Will it be a multi-step analysis?
2 weeks

#### Who will complete the analysis (please add a GitHub handle here if relevant)?
@sangeetashukla 
@afarrel 

cc @chinwallaa @migbro 

#### What relevant scientific literature relates to this analysis?
https://www.cell.com/cell-reports/pdfExtended/S2211-1247(19)31268-9

**Comment by migbro** [comment]
To help add more context to this ticket, results from the JAX and KF modified workflows can be found here: https://cavatica.sbgenomics.com/u/d3b-bixu/open-targets-pdx-workflow-dev

A file manifest of relevant results can be found here: https://cavatica.sbgenomics.com/u/d3b-bixu/open-targets-pdx-workflow-dev/files/61ddde26bb82bd039aad7390/
using `workflow` column to show the method of processing:
Kids First: `d3b-bixu/open-targets-pdx-workflow-dev/kfdrc-pdx-rnaseq-wf`
JAX: `d3b-bixu/open-targets-pdx-workflow-dev/pdx-rna-tumor-only`

**Comment by migbro** [comment]
Also, probably the easiest, fastest way to download results:
Install this https://docs.sevenbridges.com/docs/command-line-interface (follow all directions!)

Then do something like `cut -f 1 gene.results_jax_kf_manifest.tsv | xargs -IFN sb download FN --profile <your profile name>`

Could also add `-P 8` flag to xargs to get 8 at a time.

**Comment by jharenza** [comment]
Also for reference: https://github.com/marislab/pdx-mouse-subtraction/tree/master/rna-hybrid for FPKM (Cufflinks) hg19 but @komalsrathi should be able to point to the STAR/RSEM hg38 workflow which may be on isilon. If I recall, this was either the same workflow as the Treehouse samples or KF samples.

**Comment by komalsrathi** [comment]
The pipeline is on isilon: `/mnt/isilon/maris_lab/target_nbl_ngs/PPTC-PDX-genomics/mouse_subtraction_pipeline` as well as on github: https://github.com/marislab/pdx-mouse-subtraction. It's been a while but let me know if you have questions and I'll try my best to answer.

**Comment by komalsrathi** [comment]
The STAR RSEM workflow is the same that we use for KF samples.

**Comment by jharenza** [comment]
> The STAR RSEM workflow is the same that we use for KF samples. 

Great, thanks! So, possibly one fewer comparison @afarrel - we used TPM for expression for our clustering etc, and this is the same workflow used for KF. The comparison may be new aligned BAM output from PIVOT run through the KF STAR/RSEM workflow compared to our BCM processed hg19 aligned human bam, converted back to hg38 fastq, run through STAR/RSEM.

**Comment by komalsrathi** [comment]
Actually just double checked and it was slightly different. We used Treehouse pipeline from way back which used 1-pass STAR and KF is two pass STAR. But I think the differences should not be that significant between the two pipelines.

**Comment by jharenza** [comment]
@migbro and @sangeetashukla - do we have this data in matrix format (eg - ideally, we should have 3 tpm matrices with identical row and column names?)

**Comment by migbro** [comment]
> To help add more context to this ticket, results from the JAX and KF modified workflows can be found here: https://cavatica.sbgenomics.com/u/d3b-bixu/open-targets-pdx-workflow-dev
> 
> A file manifest of relevant results can be found here: https://cavatica.sbgenomics.com/u/d3b-bixu/open-targets-pdx-workflow-dev/files/61ddde26bb82bd039aad7390/ using `workflow` column to show the method of processing: Kids First: `d3b-bixu/open-targets-pdx-workflow-dev/kfdrc-pdx-rnaseq-wf` JAX: `d3b-bixu/open-targets-pdx-workflow-dev/pdx-rna-tumor-only`

@zhangb1 manifest is referenced above, with what workflow to search for to get get JAX and KF results

**Comment by zhangb1** [comment]
Okay, downloading the files now. @migbro  seems we don't have the results from `Baylor pipeline `  right?

**Comment by jharenza** [comment]
ah - that can be found [here](https://figshare.com/articles/dataset/RNA-Seq_data_files/7751825) - @sangeetashukla do you have these files?

@zhangb1 can you use `Model` for the sample name in the files please?

**Comment by sangeetashukla** [comment]
> ah - that can be found [here](https://figshare.com/articles/dataset/RNA-Seq_data_files/7751825) - @sangeetashukla do you have these files?
> 
> @zhangb1 can you use `Model` for the sample name in the files please?

@jharenza No, I did not have those files, I discussed it with @afarrel and he said we could skip the Baylor pipeline for now. But now that I have those files, I will look into them.

**Comment by zhangb1** [comment]
Okay, uploaded the merged two matrix in the project here :

```
PPTC-JAX-gene-expression-rsem-tpm-matrix.tsv
PPTC-KF-gene-expression-rsem-tpm-matrix.tsv
```

https://cavatica.sbgenomics.com/u/d3b-bixu/open-targets-pdx-workflow-dev/files/62718deb4d85bc2e0271ef09/
https://cavatica.sbgenomics.com/u/d3b-bixu/open-targets-pdx-workflow-dev/files/62718e284d85bc2e0271ef0f/

**Comment by jharenza** [comment]
@zhangb1 sorry for not asking before - can you remap these matrices to gene symbols please

**Comment by zhangb1** [comment]
@jharenza you mean do the collapsed ?

**Comment by zhangb1** [comment]
@jharenza  , @migbro  , I am tying to covert the esemble id to gene_id and found an issue, seems there is one sample as `Not reported` in the Model, any suggest for the name I need to use? or just use `Not reported`? 

```
61c47a7cbb82bd039a977ba8	93bc0cba-c402-4eb7-b0d6-5e574ba3ccd4.rsem.genes.results.gz	2459383	d3b-bixu/open-targets-pdx-workflow-dev		PPTC-NCH-S13-7484-R			tumor	Illumina		ICD_IND-PPCTC.PPTC-NCH-S13-7484-R-1_1pA	GRCh38Not reported				GENCODE27		170103_SN898_0752_BCA0WJACXX_6_ID05	d3b-bixu/open-targets-pdx-workflow-dev/kfdrc-pdx-rnaseq-wf	BCM					RNA-Seq
61c2850cc7ad4b5dc3f30502	PPTC-NCH-S13-7484-R.genes.results	5908336	d3b-bixu/open-targets-pdx-workflow-dev		PPTC-NCH-S13-7484-R	0.020027		tumor	Illumina	0.801583	ICD_IND-PPCTC.PPTC-NCH-S13-7484-R-1_1pA			91.5501	Not reported	47919244					170103_SN898_0752_BCA0WJACXX_6_ID05	d3b-bixu/open-targets-pdx-workflow-dev/pdx-rna-tumor-only	BCM			0.992037		RNA-Seq
```

**Comment by jharenza** [comment]
> PPTC-NCH-S13

@zhangb1 this model is `NCH-ARMS-2-NCH-S13-7484`

**Comment by jharenza** [comment]
below are the TSBs for RNA I have, and the models (should have 261)

```r
TSB-RNA	Model
PPTCALL02-R	ALL-02
PPTCALL03-R	ALL-03
PPTCALL04-R	ALL-04
PPTCALL07-R	ALL-07
PPTCALL08-R	ALL-08
PPTCALL10-R	ALL-10
PPTC-AF02-XTP1-B-1-0-R	ALL-102
PPTC-AF03-XTP1-A-1-0-R	ALL-105
PPTC-AF04-XTP1-A-1-0-R	ALL-106
PPTC-AF05-XTP1-B-1-0-R	ALL-107
PPTC-AF06-XTP1-A-1-0-R	ALL-108
PPTC-AF07-XTP1-A-1-0-R	ALL-11
PPTC-AF08-XTP1-A-1-0-R	ALL-115
PPTC-AF09-XTP1-A-1-0-R	ALL-116
PPTC-AF0A-XTP1-A-1-0-R	ALL-117
PPTC-AF0B-XTP1-A-1-0-R	ALL-118
PPTC-AF0C-XTP1-B-1-0-R	ALL-121
PPTC-AF0D-XTP1-B-1-0-R	ALL-122
PPTC-AF0E-XTP1-A-1-0-R	ALL-123
PPTC-AF0F-XTP1-A-1-0-R	ALL-16
PPTC-AF0G-XTP1-A-1-0-R	ALL-17
PPTC-ALL-19-R	ALL-19
PPTC-ALL-25-R	ALL-25
PPTC-AF0H-XTP1-A-1-0-R	ALL-26
PPTC-ALL-27-D	ALL-27
PPTC-AF0I-XTP1-A-1-0-R	ALL-28
PPTC-AF0J-XTP1-B-1-0-R	ALL-29
TARGET-10-PPT098-60A-01R	ALL-30
TARGET-10-PPT099-60A-01R	ALL-31
TARGET-10-PPT100-60A-01R	ALL-32
PPTC-AF0K-XTP1-B-1-0-R	ALL-33
PPTC-AF0L-XTP1-A-1-0-R	ALL-39
PPTC-ALL-42-R	ALL-42
PPTC-AF0M-XTP1-A-1-0-R	ALL-43
PPTC-AF0N-XTP1-A-1-0-R	ALL-46
PPTC-ALL-47-R	ALL-47
PPTC-ALL-50-R	ALL-50
PPTC-AF0O-XTP1-A-1-0-R	ALL-51
PPTC-AF0P-XTP1-A-1-0-R	ALL-52
PPTC-AF0Q-XTP1-A-1-0-R	ALL-53
PPTC-AF0R-XTP1-A-1-0-R	ALL-54
PPTC-AF0S-XTP1-B-1-0-R	ALL-55
PPTC-ALL-56-R	ALL-56
PPTC-ALL-57-R	ALL-57
PPTC-AF0T-XTP1-A-1-0-R	ALL-58
PPTC-ALL-59-R	ALL-59
PPTC-AF0U-XTP1-A-1-0-R	ALL-60
PPTC-AF0V-XTP1-B-1-0-R	ALL-61
PPTC-AF0W-XTP1-A-1-0-R	ALL-63
PPTC-AF0X-XTP1-A-1-0-R	ALL-75
PPTC-AF0Y-XTP1-A-1-0-R	ALL-80
PPTC-AF0Z-XTP1-A-1-0-R	ALL-81
PPTC-ALL-82-R	ALL-82
PPTC-ALL-83-R	ALL-83
PPTC-ALL-84-R	ALL-84
PPTC-ALL-85-R	ALL-85
PPTC-AF10-XTP1-A-1-0-R	ALL-87
PPTC-ALL-88-R	ALL-88
PPTC-AF11-XTP1-A-1-0-R	ALL-90
PPTC-ALL-91-R	ALL-91
PPTC-ALL-93-R	ALL-93
PPTC-AF12-XTP1-B-1-0-R	ALL-94
PPTC-AF13-XTP1-A-1-0-R	ALL-95
PPTC-AF14-XTP1-A-1-0-R	ALL-97
PPTC-ASPS-KY-R	ASPS-KY
TARGET-65-PPT033-60A-01R	BT-27
TARGET-62-PPT001-60A-01R	BT-29
TARGET-41-PPT039-61A-01R	CHLA-258
TARGET-30-PPT063-61A-01R	CHLA-79
PPTC-COG-N-415x-R	COG-N-415x
PPTC-COG-N-421x-R	COG-N-421x
PPTC-COG-N-424x-R	COG-N-424x
PPTC-COG-N-426x-Felix-PDX-R	COG-N-426x-Felix-PDX
PPTC-COG-N-440x-R	COG-N-440x
PPTC-COG-N-452x-R	COG-N-452x
PPTC-COG-N-453x-R	COG-N-453x
PPTC-COG-N-471x-R	COG-N-471x
PPTC-COG-N-480x-R	COG-N-480x
PPTC-COG-N-496x-R	COG-N-496x
PPTC-COG-N-519x-R	COG-N-519x
PPTC-COG-N-549x-R	COG-N-549x
PPTC-COG-N-557x-R	COG-N-557x
PPTC-COG-N-560x-R	COG-N-560x
PPTC-COG-N-561x-R	COG-N-561x
PPTC-COG-N-564x-R	COG-N-564x
COG-N-589x-R	COG-N-589x
PPTC-COG-N-590x-R	COG-N-590x
PPTC-COG-N-603x-R	COG-N-603x
NA	COG-N-618x
COG-N-619x-R1	COG-N-619x
PPTC-COG-N-620x-R	COG-N-620x
PPTC-COG-N-623x-R	COG-N-623x
PPTC-COG-N-624x-R	COG-N-624x
PPTC-COG-N-625x-R	COG-N-625x
NA	COG-N-628x
PPTC-ES-1-R	ES-1
TARGET-41-PPT040-61A-01R	ES-4
TARGET-41-PPT041-61A-01R	ES-6
PPTC-ES-8-R	ES-8
PPTC-ETP-1-R	ETP-1
PPTC-ETP-2-R	ETP-2
PPTC-ETP-3-R	ETP-3
PPTC-ETP-4-R	ETP-4
PPTC-ETP-5-R	ETP-5
PPTC-ETP-6-R	ETP-6
TARGET-41-PPT035-60A-01R	EW-5
TARGET-41-PPT036-60A-01R	EW-8
PPTC-G401-R	G401
PPTC-IBs-2373PNET-R	IBs-2373PNET
NA	IBs-P1215DIPG
NA	IBs-W0128DIPG
NA	IC-1128GBM
NA	IC-1425EPN
PPTC-IC-1499EPB-R	IC-1499EPB
PPTC-IC-1621GBM-R	IC-1621GBM
PPTC-IC-22909PNET-rIII-R	IC-22909PNET-rIII
NA	IC-2305GBM
PPTC-IC-2264PNET-R	IC-2664PNET
PPTC-IC-3635PXA-R	IC-3635PXA
NA	IC-3704GBM
PPTCIC3752GBM-R	IC-3752GBM
PPTC-IC-6634GBM-TC-R	IC-6634GBM
PPTCIC9320GCT-R	IC-9320GCT
PPTC-IC-9635EPN-R	IC-9635EPN
PPTC-IC-9811EPN-R	IC-9811EPN
PPTC-ICb-10593ATRT-R	ICb-10593ATRT
PPTC-ICb-0614EPN-R	ICb-10614EPN
NA	ICb-1078MB
NA	ICb-1140MB
NA	ICb-1197MB
PPTC-ICb-1218ATRT-R	ICb-1218ATRT
PPTC-ICb-1338MB-R	ICb-1338MB
PPTC-ICb-1343ENB-R	ICb-1343ENB
NA	ICb-1487MB
NA	ICb-1494MB
NA	ICb-1572MB
NA	ICb-1595MB
PPTC-ICB-1744MB-R	ICB-1744MB
PPTC-ICb-2002EPN-R	ICb-2002EPN
PPTC-ICb-2123MB-R	ICb-2123MB
NA	ICb-2164MB
PPTC-ICb-2555MB-R	ICb-2555MB
PPTC-ICb-3130MB-R	ICb-3130MB
NA	ICb-3400MB
PPTC-ICb-5108ATRT-R	ICb-5108ATRT
PPTC-ICb-5323EPN-R	ICb-5323EPN
PPTC-ICb-5610MB-Cb-Cb-R	ICb-5610MB
PPTC-ICb-6753ATRT-R	ICb-6753ATRT
PPTCICb8008MB-R	ICb-8008MB
PPTC-ICb-9508MB-R	ICb-9508MB
PPTCICb984MB-R	ICb-984MB
PPTC-ICb-9850PNET-R	ICb-9850PNET
PPTCICbJ1017MB-R	ICb-J1017MB
PPTC-ICb-L1115ATRT-R	ICb-L1115ATRT
PPTC-ICb-S1129MB-R	ICb-S1129MB
PPTC-IRS56-R	IRS-56
TARGET-80-PPT056-60A-01R	IRS-68
TARGET-50-PPT025-60A-01R	KT-10
TARGET-50-PPT026-60A-01R	KT-11
TARGET-52-PPT002-60A-01R	KT-12
TARGET-50-PPT027-60A-01R	KT-13
TARGET-52-PPT003-60A-01R	KT-14
PPTC-KT-18-R	KT-18
NA	KT-5
PPTC-KT-6-R	KT-6
TARGET-52-PPT028-60A-01R	KT-8
PPTC-KT-9-R	KT-9
PPTC-AF16-XTP1-B-1-0-R	MLL-1
TARGET-10-PPT109-60A-01R	MLL-14
TARGET-10-PPT103-60A-01R	MLL-2
TARGET-10-PPT104-60A-01R	MLL-3
TARGET-10-PPT105-60A-01R	MLL-5
TARGET-10-PPT106-60A-01R	MLL-6
TARGET-10-PPT107-60A-01R	MLL-7
TARGET-10-PPT108-60A-01R	MLL-8
PPTC-ALL-86-R	MLL-86
TARGET-30-PPT065-61A-01R	NB-1382
TARGET-30-PPT064-61A-01R	NB-1643
TARGET-30-PPT061-61A-01R	NB-1691
TARGET-30-PPT060-61A-01R	NB-1771
TARGET-30-PPT062-61A-01R	NB-EBc1
PPTC-Fly-623m-R	NB-Fly-623m
TARGET-30-PPT059-61A-01R	NB-SD
PPTC-NCH-S13-7484-R	NCH-ARMS-2-NCH-S13-7484
PPTC-NCH-CA-1-R	NCH-CA-1
PPTC-NCH-CA-2-R	NCH-CA-2
PPTC-NCH-CA-3-R	NCH-CA-3
PPTC-NCH-CCS-1-R	NCH-CCS-1
PPTC-NCH-RMS-1-R	NCH-ERMS-1-NCH-RMS-1
NA	NCH-EWS-1
PPTC-NCH-HEP-1-R	NCH-HEP1
PPTC-NCH-MB-1-R	NCH-MB-1
PPTC-NCH-MN-1-R	NCH-MN-1
PPTC-NCH-NB-1-R	NCH-NB-1
PPTC-NCH-OS-1-R	NCH-OS-1
PPTC-NCH-PXA-1-R	NCH-PXA-1
NA	NCH-RBD-1
PPTC-NCH-RBD-2-R	NCH-RBD-2
PPTC-NCH-RBD-4-R	NCH-RBD-4
PPTC-NCH-WT-4-R	NCH-WT-4
PPTC-NCH-WT-5-R	NCH-WT-5
PPTC-NCH-WT-6-R	NCH-WT-6-S13-1506
PPTC-NCH-WT-7-R	NCH-WT-7
PPTC-NCH-WT-8-R	NCH-WT-8-S13-3700
PPTC-NCI-ASPS-R	NCI-ASPS
TARGET-40-PPT067-60A-01R	OS-1
NA	OS-17
TARGET-40-PPT068-60A-01R	OS-2
NA	OS-25
TARGET-40-PPT071-60A-01R	OS-29
TARGET-40-PPT072-60A-01R	OS-31
PPTC-OS-32-R	OS-32
TARGET-40-PPT073-60A-01R	OS-33
TARGET-40-PPT076-60A-01R	OS-34
PPTC-OS-34-SJ-R	OS-34-SJ
NA	OS-36
NA	OS-36-SJ
PPTC-OS-41-R	OS-41
PPTC-OS-42-R	OS-42
TARGET-40-PPT078-60A-01R	OS-43-TPMX
PPTC-OS-44-R	OS-44
TARGET-40-PPT079-60A-01R	OS-44-KPDX-x
TARGET-40-PPT080-60A-01R	OS-45-TSX-pr1
PPTC-OS-46-R	OS-46
PPTC-OS-46-AOX-R	OS-46-AOX
PPTC-OS-47-SJ-R	OS-47-SJ
PPTC-OS-48-R	OS-48
PPTC-OS-49-SJ-R	OS-49-SJ
PPTC-OS-49-STTX-sc-R	OS-49-STTX-sc
NA	OS-50-SJ
PPTCOS51CHLX-R	OS-51-CHLX
PPTC-OS-52-SJ-R	OS-52-SJ
PPTC-OS-54-OHS-x-R	OS-54-OHS-x
PPTC-OS-54-SJ-R	OS-54-SJ
PPTC-OS-55-R	OS-55
PPTC-OS-55-SBX-R	OS-55-SBX
NA	OS-56
PPTC-OS-56-TTX-R	OS-56-TTX
PPTC-OS-60-R	OS-60
PPTCOS9-R	OS-9
PPTC-TGT-020-R	PAKHZT
PPTC-TGT-047-R	PAKRSL
PPTC-TGT-052-R	PAKSWW
PPTC-TGT-065-R	PAKVKK
PPTC-AF1D-XTP1-B-1-0-R	PAKYEP
PPTC-TGT-145-R	PALJDL
PPTC-TGT-151-R	PALKTY
PPTC-TGT-161-R	PALLSD
PPTC-TGT-174-R	PALNTB
PPTC-TGT-196-R	PALTWS
PPTC-TGT-258-R	PAMDRM
TARGET-80-PPT042-60A-01R	Rh-10
TARGET-80-PPT050-60A-01R	Rh-12
TARGET-80-PPT045-60A-01R	Rh-30
TARGET-80-PPT046-60A-01R	Rh-30R
TARGET-80-PPT047-60A-01R	Rh-36
TARGET-80-PPT048-60A-01R	Rh-41
TARGET-80-PPT049-60A-01R	Rh-65
PPTC-Rh-70-R	Rh-70
TARGET-41-PPT037-61A-01R	SK-NEP-1
TARGET-41-PPT038-61A-01R	TC-71
```

**Comment by zhangb1** [comment]
Okay, collapsed files are in the project now:

https://cavatica.sbgenomics.com/u/d3b-bixu/open-targets-pdx-workflow-dev/files/6272d372d63f7c6d8d3a8480/

https://cavatica.sbgenomics.com/u/d3b-bixu/open-targets-pdx-workflow-dev/files/6272d342d63f7c6d8d3a81ca/

PPTC-JAX-gene-expression-rsem-tpm-collapsed-matrix.tsv
PPTC-KF-gene-expression-rsem-tpm-collapsed-matrix.tsv

**Comment by jharenza** [comment]
thanks @zhangb1 !

**Comment by jharenza** [comment]
Hi @migbro - it looks like we have a disconnect on models which were run through the pipelines and those which were released via the manuscript, and it is possible I will have to go back to dbGAP to get them to remove some BAMs which were not in use.

Please see attached for 244 models which should be included.
[244-pptc-models.txt](https://github.com/PediatricOpenTargets/ticket-tracker/files/8643122/244-pptc-models.txt)

The two matrices above differ by one model each, and there are models in there which should not be (did not pass QC), and we are missing models. Thus, using the list above is probably easiest to remedy. But, for the record, all of the diffs are below:

```r
> setdiff(colnames(pptc), colnames(jax))
 [1] "gene_short_name" "ALL-83"          "COG-N-453x"      "COG-N-619x"     
 [5] "COG-N-623x"      "ICb-9850PNET"    "NCH-CA-2"        "OS-34-SJ"       
 [9] "OS-54-SJ"        "Rh-30R"         
> setdiff(colnames(jax), colnames(pptc))
[1] "ICb-1487MB" "ICb-1572MB" "OS-17"      "OS-56"     
> setdiff(colnames(pptc), colnames(kf))
 [1] "gene_short_name" "ALL-83"          "ASPS-KY"         "COG-N-453x"     
 [5] "COG-N-619x"      "COG-N-623x"      "ICb-9850PNET"    "NCH-CA-2"       
 [9] "OS-34-SJ"        "OS-54-SJ"        "Rh-30R"         
> setdiff(colnames(kf), colnames(pptc))
[1] "gene_id"    "ICb-1487MB" "ICb-1572MB" "NCH-RBD-1"  "OS-17"      "OS-56"     
> setdiff(colnames(kf), colnames(jax))
[1] "gene_id"   "NCH-RBD-1"
> setdiff(colnames(jax), colnames(kf))
[1] "ASPS-KY"
```

**Comment by migbro** [comment]
In SRA, searching by model, I found all but:
```
PPTC-ALL-83-R
PPTC-COG-N-453x-R
COG-N-619x-R1
PPTC-COG-N-623x-R
PPTC-ICb-9850PNET-R
PPTC-NCH-CA-2-R
PPTC-OS-34-SJ-R
PPTC-OS-54-SJ-R
TARGET-80-PPT046-60A-01R
```

After clicking through a maze of links leading me to here:
https://www.ncbi.nlm.nih.gov/sra?linkname=bioproject_sra_all&from_uid=400658

**Comment by jharenza** [comment]
@migbro have you been able to grab these missing files?
