### ISSUE TITLE
QC check RNA-Seq input files

### ISSUE THREAD

**Issue by jharenza** [PediatricOpenTargets/ticket-tracker#272]
# 🆘

#### [Required] How would you most generally describe your issue? 
- [x] Update data for project in pedcbio portal
- [ ] Questions related to data on pedcbio portal 

#### If an update to a project, provide links to the input files that should be used and descriptions we might find helpful. If new `case_set_ids` need to be added, please provide instructions below.

Brought up by @adamcresnick:

In looking at schwannoma samples as an [example](https://pedcbioportal.kidsfirstdrc.org/study/summary?id=ped_opentargets_2021), there are 19 samples profiled but two are not showing up as profiled by RNA when selecting genes to query (example [here](https://pedcbioportal.kidsfirstdrc.org/results?cancer_study_list=ped_opentargets_2021&tab_index=tab_visualize&case_set_id=-1&case_ids=ped_opentargets_2021%3A7316-1094_353655%2Bped_opentargets_2021%3A7316-1463_357623%2Bped_opentargets_2021%3A7316-1463_373373%2Bped_opentargets_2021%3A7316-147_145943%2Bped_opentargets_2021%3A7316-159_151031%2Bped_opentargets_2021%3A7316-1983_389817%2Bped_opentargets_2021%3A7316-1987_389879%2Bped_opentargets_2021%3A7316-2084_407593%2Bped_opentargets_2021%3A7316-2159_434270%2Bped_opentargets_2021%3A7316-291_232977%2Bped_opentargets_2021%3A7316-29_24639%2Bped_opentargets_2021%3A7316-3029_541257%2Bped_opentargets_2021%3A7316-30_25070%2Bped_opentargets_2021%3A7316-377_242804%2Bped_opentargets_2021%3A7316-3963_609858%2Bped_opentargets_2021%3A7316-4341_682315%2Bped_opentargets_2021%3A7316-448_317744%2Bped_opentargets_2021%3A7316-456_323505%2Bped_opentargets_2021%3A7316-641_338727%2Bped_opentargets_2021%3A7316-948_346062&Action=Submit&gene_list=MYC&show_samples=true) with MYC). In this example, `7316-291_232977` (BS_BXXJ9P8C) and `7316-448_317744` (BS_8J09S6MZ) look to not have RNA-Seq, but those samples have _only_ RNA-Seq, so there should be values for them in expression and they should also be in the predicted fusion file, even if no fusions exist so that the user knows they were profiled. Is it possible the clinical file has these samples listed with an RNA-Seq strategy but the RNA-Seq files are missing those samples?

#### Provide the manifest (or a link to a manifest) that will be used to select samples
v10

### Ticket will be considered resolved either by a successful PR with updated release if applicable, or a simple denial of the request backed by a good reason

cc @runjin326

**Comment by migbro** [comment]
Hmmm, interesting. `7316-291_232977`is in the `pbta_all` study as `7316-291`, same BS ID with RNA data. Maybe with the saple ID ticket that Run is working on will help wit the new load? What is in there now is the original v7 load, so perhaps a carry over of an issue from there? The other sample mentioned is the same situation

**Comment by jharenza** [comment]
This appears to be fixed in the [QA load](https://pedcbioportal.kidsfirstdrc.org/results/oncoprint?cancer_study_list=ped_opentargets_2021&tab_index=tab_visualize&case_set_id=-1&case_ids=ped_opentargets_2021%3A7316-1094_353655%2Bped_opentargets_2021%3A7316-1463_357623%2Bped_opentargets_2021%3A7316-1463_373373%2Bped_opentargets_2021%3A7316-147_145943%2Bped_opentargets_2021%3A7316-159_151031%2Bped_opentargets_2021%3A7316-1983_389817%2Bped_opentargets_2021%3A7316-1987_389879%2Bped_opentargets_2021%3A7316-2084_407593%2Bped_opentargets_2021%3A7316-2159_434270%2Bped_opentargets_2021%3A7316-291_232977%2Bped_opentargets_2021%3A7316-29_24639%2Bped_opentargets_2021%3A7316-3029_541257%2Bped_opentargets_2021%3A7316-30_25070%2Bped_opentargets_2021%3A7316-377_242804%2Bped_opentargets_2021%3A7316-3963_609858%2Bped_opentargets_2021%3A7316-4341_682315%2Bped_opentargets_2021%3A7316-448_317744%2Bped_opentargets_2021%3A7316-456_323505%2Bped_opentargets_2021%3A7316-641_338727%2Bped_opentargets_2021%3A7316-948_346062&Action=Submit&gene_list=MYC&Z_SCORE_THRESHOLD=2.0&RPPA_SCORE_THRESHOLD=2.0&profileFilter=mutations%2Cfusion%2Ccna%2Crna_seq_v2_mrna_median_Zscores&geneset_list=%20)https://pedcbioportal.kidsfirstdrc.org/results/oncoprint?cancer_study_list=ped_opentargets_2021&tab_index=tab_visualize&case_set_id=-1&case_ids=ped_opentargets_2021%3A7316-1094_353655%2Bped_opentargets_2021%3A7316-1463_357623%2Bped_opentargets_2021%3A7316-1463_373373%2Bped_opentargets_2021%3A7316-147_145943%2Bped_opentargets_2021%3A7316-159_151031%2Bped_opentargets_2021%3A7316-1983_389817%2Bped_opentargets_2021%3A7316-1987_389879%2Bped_opentargets_2021%3A7316-2084_407593%2Bped_opentargets_2021%3A7316-2159_434270%2Bped_opentargets_2021%3A7316-291_232977%2Bped_opentargets_2021%3A7316-29_24639%2Bped_opentargets_2021%3A7316-3029_541257%2Bped_opentargets_2021%3A7316-30_25070%2Bped_opentargets_2021%3A7316-377_242804%2Bped_opentargets_2021%3A7316-3963_609858%2Bped_opentargets_2021%3A7316-4341_682315%2Bped_opentargets_2021%3A7316-448_317744%2Bped_opentargets_2021%3A7316-456_323505%2Bped_opentargets_2021%3A7316-641_338727%2Bped_opentargets_2021%3A7316-948_346062&Action=Submit&gene_list=MYC&Z_SCORE_THRESHOLD=2.0&RPPA_SCORE_THRESHOLD=2.0&profileFilter=mutations%2Cfusion%2Ccna%2Crna_seq_v2_mrna_median_Zscores&geneset_list=%20
