### ISSUE TITLE
Updated analysis: rerun `tumor-normal-differential-expression` module with v10 data

### ISSUE THREAD

**Issue by logstar** [PediatricOpenTargets/ticket-tracker#273]
#### What analysis module should be updated and why?

`tumor-normal-differential-expression` module needs to be updated to rerun with v10 data and share v10 result using `s3://d3b-openaccess-us-east-1-prd-pbta/open-targets/` S3 bucket.

Currently, the shared `tumor-normal-differential-expression` module result `DESeq_Results_V9_v2.RDS` is generated using v9 data, which will be incompatible with v10 TPM data in OpenPedCan-api. The differential gene expression (DGE) result needs to be compatible with v10 TPM data to resolve issue <https://github.com/PediatricOpenTargets/OpenPedCan-api/issues/61>, which is to add boxplots to the sides of DGE heatmaps.

The `DESeq_Results_V9_v2.RDS` was shared using local file system, which will not be publicly accessible. Therefore, v10 result RDS needs to be shared in the `s3://d3b-openaccess-us-east-1-prd-pbta/open-targets/` S3 bucket, to make the result publicly accessible.

#### What changes need to be made? Please provide enough detail for another participant to make the update.

- Rerun `tumor-normal-differential-expression` module with v10 data.
- Share v10 result using `s3://d3b-openaccess-us-east-1-prd-pbta/open-targets/` S3 bucket.

#### What input data should be used? Which data were used in the version being updated?

v10 data.

#### When do you expect the revised analysis will be completed?

2 days ?

#### Who will complete the updated analysis?

@sangeetashukla ?

cc @afarrel @runjin326 @chinwallaa @taylordm

**Comment by sangeetashukla** [comment]
@logstar The files are ready, and I have access to the Cavatica volume that is linked to the S3 bucket listed here. Do you want me to create a new directory in the bucket for these result files? Or do I upload these files to `open-targets/` or `data/` directory?

**Comment by logstar** [comment]
> @logstar The files are ready, and I have access to the Cavatica volume that is linked to the S3 bucket listed here. Do you want me to create a new directory in the bucket for these result files? Or do I upload these files to `open-targets/` or `data/` directory?

@sangeetashukla Thank you. Could you create a directory `open-targets/api/test/differential_gene_expression_v10/` and upload v10 DESeq results there?

@runjin326 I was wondering if we could put `tumor-normal-differential-expression` module results to future data releases.

**Comment by logstar** [comment]
@sangeetashukla I was wondering if there is any issue with uploading v10 DESeq results to `s3://d3b-openaccess-us-east-1-prd-pbta/open-targets/api/test/differential_gene_expression_v10/`.

**Comment by sangeetashukla** [comment]
@logstar I have the Seven Bridges API set up locally, along with the my credentials, but then I try to access the Cavatica API end point, (the open targets S3 bucket that @zhangb1  added me to), I still see the message 'Unauthorized'.
@zhangb1  Can you please confirm if I have permission to upload to the S3 bucket?

> @sangeetashukla I was wondering if there is any issue or update with uploading v10 DESeq results to `s3://d3b-openaccess-us-east-1-prd-pbta/open-targets/api/test/differential_gene_expression_v10/`.

**Comment by sangeetashukla** [comment]
@logstar While I work out my permissions to the bucket with Chris, @runjin326 has helped upload the files. Please review them when you get a chance.

**Comment by logstar** [comment]
@sangeetashukla The uploaded v10 result only has one unique EFO ID. I was wondering if you could upload the result that has all EFO IDs like `DESeq_Results_V9_v2.RDS`.

```text
> de_res <- readRDS('DESeq_Results_V10.rds')
> table(de_res$EFO)

EFO_0000621 
      36718 
> nrow(de_res)
[1] 36718
```

cc @runjin326

**Comment by jharenza** [comment]
> @logstar While I work out my permissions to the bucket with Chris, @runjin326 has helped upload the files. Please review them when you get a chance.

Hi @sangeetashukla! We have limited people who can write to this bucket since it has other projects in it as well, so perhaps @runjin326 or @logstar can help with uploads?

**Comment by sangeetashukla** [comment]
> @sangeetashukla The uploaded v10 result only has one unique EFO ID. I was wondering if you could upload the result that has all EFO IDs like `DESeq_Results_V9_v2.RDS`.
> 
> ```
> > de_res <- readRDS('DESeq_Results_V10.rds')
> > table(de_res$EFO)
> 
> EFO_0000621 
>       36718 
> > nrow(de_res)
> [1] 36718
> ```
> 
> cc @runjin326

@logstar , I reviewed the v10 data files available on Cavatica and they look fine. I will run the analysis on HPC and upload those result files while I review the Cavatica app code.

**Comment by sangeetashukla** [comment]
> > @logstar While I work out my permissions to the bucket with Chris, @runjin326 has helped upload the files. Please review them when you get a chance.
> 
> Hi @sangeetashukla! We have limited people who can write to this bucket since it has other projects in it as well, so perhaps @runjin326 or @logstar can help with uploads?

Thank you @jharenza for the heads-up. @runjin326 helped me with the upload and I will work with her again once I have the new set of result files ready to deliver to @logstar.

**Comment by sangeetashukla** [comment]
@logstar All three result files from DESeq analysis on v10 data (rds, tsv, and json) have been uploaded to the specified S3 bucket.
Please verify when you get a chance.

**Comment by logstar** [comment]
@sangeetashukla Thank you for preparing and sharing the v10 DESeq analysis results.

The v10 DESeq RDS file looks good. The EFO and MONDO IDs in v10 DESeq RDS file are the same as the ones listed in efo-mondo-map.tsv.
