### ISSUE TITLE
Proposed Analysis: Review JAX/PIVOT PDX DNA Pipeline

### ISSUE THREAD

**Issue by migbro** [PediatricOpenTargets/ticket-tracker#276]
#### What are the scientific goals of the analysis?

To evaluate the efficacy of the JAX PDX pipeline

#### What methods do you plan to use to accomplish the scientific goals?

Use this pipeline: https://cavatica.sbgenomics.com/u/d3b-bixu/open-targets-pdx-workflow-dev/apps/#d3b-bixu/open-targets-pdx-workflow-dev/pdx-wes-tumor-only-xenome-with-variant-calling-msi-and-tmb-score

Alternatively, this one: https://github.com/kids-first/kf-tumor-workflow by using xenome + continue with wf, is a recent candidate. Major advantage being CNV, SV and WGS capability. However, it is still beta.

#### What input data are required for this analysis?

Results from existing paper, similar to #271

#### How long do you expect is needed to complete the analysis? Will it be a multi-step analysis?

A couple weeks to a month

**Comment by jharenza** [comment]
@migbro once you are back, or @dmiller15, if you know- has this been started? If so, can you link to the CAVATICA project/ update here?

**Comment by migbro** [comment]
So, Alvin created this ticket, #283 which I think outlines how we want to test this out.

**Comment by jharenza** [comment]
@migbro this is the manifest of all DNA samples for which we should have MAFs for this project

[pptc-dna-mafs.txt](https://github.com/PediatricOpenTargets/ticket-tracker/files/8654652/pptc-dna-mafs.txt)

**Comment by chinwallaa** [comment]
Do we need permission to run the CHOP data thru the updated pipelines (PIVOT pipelines).   @afarrel will follow up with John Marris.  Do we have other PDX data - PDXFinder?  - Nothing processed yet.  WIll need to get an analysis plan together with FNL/NCI for this new data type.  Have starfusion/ariba for PPTC PDX data.  Expression table, SNV calls, fusion calls - ability to look at mutations in patients and PDX models.
