### ISSUE TITLE
Bix Dev Feature: SBG Multi-CNV Review

### ISSUE THREAD

**Issue by migbro** [PediatricOpenTargets/ticket-tracker#277]
# ✨
Ported over from https://github.com/d3b-center/bixu-tracker/issues/1324

#### [Required] Is this a new Kids First harmonization/analysis tool/workflow, or a D3b collaborative analysis tool/workflow?

Both

#### Otherwise, just provide a link to the existing git repo.

https://cavatica.sbgenomics.com/u/danmiller/kf-gatk-cnv-dev

#### Provide software links and `dockerPull` location is applicable

https://cavatica.sbgenomics.com/u/danmiller/kf-gatk-cnv-dev/apps/#danmiller/kf-gatk-cnv-dev/sb-multicnv-1-0-0-1/0

#### Add reference files and test input locations if applicable

Build on benchmarking work described here:
https://github.com/d3b-center/bixu-tracker/issues/1221

#### [Optional] How long do you think this work will take?

a month

#### [Optional] Who will complete this work?
Would like to confer with @afarrel , @aadamk and @dmiller15

**Comment by chinwallaa** [comment]
No longer going fwd with this as SevenBridges is not working on this.

**Comment by migbro** [comment]
Makes sense. We could compare the F1 scores when we bench the OpenPBTA method, but for now, not a priority.
