### ISSUE TITLE
Updated analysis:  update v11 histologies with TARGET methylation array samples

### ISSUE THREAD

**Issue by ewafula** [PediatricOpenTargets/ticket-tracker#278]
#### What analysis module should be updated and why?
Update [v11 OpenPedCan histologies](https://github.com/d3b-center/D3b-codes/pull/53) with TARGET methylation array samples to be utilized for developing the  proposed `OPenPedCan methylation-summary module` 

#### What changes need to be made? Please provide enough detail for another participant to make the update.
Update the module with  analyzed TARGET methylation samples 

#### What input data should be used? Which data were used in the version being updated?
[TARGET sample clinical  metadata](https://ocg.cancer.gov/programs/target/data-matrix) 
[TARGET methylation sample metadata](https://ocg.cancer.gov/programs/target/data-matrix) 

#### When do you expect the revised analysis will be completed?
1/2 days

#### Who will complete the updated analysis?
@ewafula

**Comment by jharenza** [comment]
this can be closed once #300 is done

**Comment by jharenza** [comment]
Closed with https://github.com/PediatricOpenTargets/OpenPedCan-analysis/pull/188
