### ISSUE TITLE
Proposed Analysis: RUVSeq evaluation of matched samples

### ISSUE THREAD

**Issue by komalsrathi** [PediatricOpenTargets/ticket-tracker#279]
#### What are the scientific goals of the analysis?

Evaluation of RUVSeq batch correction using:

1. `RUVg`:  Estimating the factors of unwanted variation using control genes. We will use the two sets of control genes:
    a. Housekeeping genes identified in Normal tissues by the HRT protocol
    b. Housekeeping genes identified collectively in Tumors + Normal tissues using the HRT protocol
2. `RUVr`: use the residuals from a DGE analysis (without batch correction) as a source of unwanted variation to correct for in a second pass DGE.

#### What methods do you plan to use to accomplish the scientific goals?

1) Methods:

RUVg is easy to incorporate with `DESeq2` but RUVr method requires an `edgeR` output as input. So I will be testing RUVr with edgeR only and RUVg with both DESeq2 and edgeR.

2) Matched samples: 

For the test data, we want to look at individual `cohort + cancer group` with matched samples in order to avoid identifying differences due to biology. I have identified 4 `cohort + cancer_group` categories that have matched samples with multiple library prep methods. 

1. 24 Acute Lymphoblastic Leukemia samples (TARGET)
2. 10 High-grade glioma/astrocytoma (PBTA)
3. 4 CNS Embryonal tumor (PBTA)
4. 4 Diffuse midline glioma (PBTA) 

Based on the sample size, I will be testing `24 ALL samples from TARGET` and `10 HGG samples from PBTA`.

3) Experiment Design: 

My goal is to perform a `paired analysis` using an experimental design that takes the `Kids_First_Participant_ID` of match samples and `RNA_library` into account. The idea behind this is to find differences ONLY due to `RNA_library`.

#### What input data are required for this analysis?

```
data/gene-counts-rsem-expected_count-collapsed.rds
data/histologies.tsv
```

#### How long do you expect is needed to complete the analysis? Will it be a multi-step analysis?

N/A

#### Who will complete the analysis (please add a GitHub handle here if relevant)?

@komalsrathi 

#### What relevant scientific literature relates to this analysis?

RUVSeq: http://bioconductor.org/packages/release/bioc/vignettes/RUVSeq/inst/doc/RUVSeq.pdf
HRT atlas with protocol for identifying HK genes described: https://pubmed.ncbi.nlm.nih.gov/32663312/

cc: @aadamk

**Comment by komalsrathi** [comment]
@aadamk Based on our 1:1 and your suggestions, I'll be doing these and update the outputs/scripts accordingly:

1. For UQ what are those samples that are separated
2. Make UMAP along with PCA (UQ)
3. Does DESeq2 have any inbuilt normalization that can be used. How clustering looks after using the normalized data as input?

But in the meanwhile, these are the two scripts (DESeq2 and edgeR) for the posted results:

DESeq2:

```
# DESeq2 analysis with RUVg

suppressPackageStartupMessages({
  library(tidyverse)
  library(optparse)
  library(RUVSeq)
})

# parse parameters
option_list <- list(
  make_option(opt_str = "--dataset", type = "character",
              help = "Dataset for running differential gene expression analysis: match_pbta_hgg or match_target_all")
)
opt <- parse_args(OptionParser(option_list = option_list))
dataset <- opt$dataset
output_dir <- file.path('output', 'deseq2_outputs', dataset)
dir.create(output_dir, showWarnings = F, recursive = T)

# plotting function
source('util/deseq2_pvals_histogram.R')
source('util/edaseq_plot_pca.R')

# read histology
htl_df <- readr::read_tsv('../../data/histologies.tsv')

# read expected counts
cnt_df <- readRDS('../../data/gene-counts-rsem-expected_count-collapsed.rds')

# filter histology
if (dataset == "match_target_all") {
  # 24 Acute Lymphoblastic Leukemia samples have been sequenced with > 1 technology
  selected_htl_df <- htl_df %>%
    filter(experimental_strategy == "RNA-Seq",
           sample_type == "Tumor",
           cohort == "TARGET") %>%
    group_by(Kids_First_Participant_ID, sample_id) %>%
    mutate(n = length(sort(unique(RNA_library)))) %>% 
    filter(n > 1)
} else if (dataset == "match_pbta_hgg") {
  # 4 CNS Embryonal tumor, 4 Diffuse midline glioma and 10 High-grade glioma/astrocytoma
  # sample size is okay in HGG so we will use that as a test
  selected_htl_df <- htl_df %>%
    filter(experimental_strategy == "RNA-Seq",
           sample_type == "Tumor",
           cohort == "PBTA",
           cancer_group == "High-grade glioma/astrocytoma") %>%
    group_by(Kids_First_Participant_ID, sample_id) %>%
    mutate(n = length(sort(unique(RNA_library)))) %>% 
    filter(n > 1)
} else {
  stop(paste0('unknown dataset', dataset))
}

# filter expression
cnt_df <- cnt_df %>%
  dplyr::select(selected_htl_df$Kids_First_Biospecimen_ID)
cnt_df <- cnt_df[rowSums(cnt_df) > 0,]

# filter by expression and convert to DGElist
# for paired analysis, we need to consider patient id (e.g. https://www.biostars.org/p/437279/)
patient_id <- factor(as.character(selected_htl_df$Kids_First_Participant_ID))
rna_library <- factor(as.character(selected_htl_df$RNA_library))
design <- model.matrix(~ 0 + patient_id + rna_library)
counts_object <- edgeR::DGEList(counts = cnt_df, group = rna_library)
counts_object_filtered <- edgeR::filterByExpr(counts_object, group = rna_library)
counts_object <- counts_object[counts_object_filtered, , keep.lib.sizes = FALSE]

# create new expression set
seq_expr_set <- newSeqExpressionSet(counts = round(counts_object$counts), phenoData = data.frame(patient_id, rna_library, row.names = colnames(round(counts_object$counts))))
pca_p <- edaseq_plot_pca(object = seq_expr_set, title = "Before normalization")

# from https://support.bioconductor.org/p/95805/#95808
# The "betweenLaneNormalization" is just a poorly named function that perform between-sample normalization, 
# independently of the fact that they are organized in lanes, plates, etc. 
# It is used in RUVSeq just to make sure that the factors of unwanted variation don't capture the difference in library size that should be captured by the size factors. 
# normalize the data using upper-quartile (UQ) normalization
seq_expr_set <- EDASeq::betweenLaneNormalization(seq_expr_set, which = "upper")
pca_p_norm <- edaseq_plot_pca(object = seq_expr_set, title = "After UQ normalization")

# save plot
p <- ggpubr::ggarrange(pca_p, pca_p_norm, common.legend = T, legend = "right")
fname <- file.path(output_dir, 'qc_pca.png')
ggsave(filename = fname, plot = p, width = 12, height = 8)

# DGE before running RUVg
# From DESeq2 documentation:
# 1. DESeq2::DESeq performs a default analysis through the steps:
# - estimation of size factors: estimateSizeFactors
# - estimation of dispersion: estimateDispersions
# - Negative Binomial GLM fitting and Wald statistics: nbinomWaldTest
dds <- DESeq2::DESeqDataSetFromMatrix(countData = round(counts_object$counts), colData =  data.frame(patient_id, rna_library), design = design)
dds <- DESeq2::DESeq(dds)

# Export results and save as CSV
dge_output <- DESeq2::results(dds, cooksCutoff = FALSE, pAdjustMethod = 'BH')
dge_output <- dge_output %>% 
  as.data.frame() %>% 
  rownames_to_column('gene') %>%
  arrange(padj) 

# Export results and save as CSV
filename <- file.path(output_dir, 'stranded_vs_polya_dge_deseq2_result.csv')
write_tsv(dge_output, file = filename)

# empirical control genes
emp_neg_ctrl_genes_dge <- dge_output %>% 
  filter(padj < 0.05) %>%
  pull(gene)

# plot and save p-value histogram
p <- deseq2_pvals_histogram(res_df = dge_output,
                            xlab = 'stranded vs poly-A RNA-seq DGE RLE nbinomWaldTest p-value',
                            ylab = 'Gene count', title = paste0('Histogram of stranded vs poly-A RNA-seq\n', 'DESeq2 nbinomWaldTest p-values'))
filename <- file.path(output_dir, 'stranded_vs_polya_dge_deseq2_histogram.png')
ggsave(filename = filename, plot = p, width = 8, height = 7)

# Step 1: function to evaluate RUVg: Estimating the factors of unwanted variation using control genes
# uses negative control genes, assumed to have constant expression across samples
ruvg_test <- function(seq_expr_set, emp_neg_ctrl_genes, prefix){
  
  print(paste0('Run differential gene expression DESeq2 nbinomWaldTest ',
               'with RUVSeq estimated batch effect on poly-A vs stranded RNA-seq...'))
  
  # to estimate the factors of unwanted variation,
  # subset to negative control genes (genes that can be assumed not to be influenced by the covariates of interest)
  emp_neg_ctrl_genes <- intersect(emp_neg_ctrl_genes, rownames(seq_expr_set@assayData$counts))
  emp_neg_ctrl_genes <- emp_neg_ctrl_genes[emp_neg_ctrl_genes %in% rownames(seq_expr_set@assayData$counts)]
  
  # run RUVg assuming there is only 1 major factor of unwanted variation (i.e. k = 1)
  ruvg_set <- RUVg(x = seq_expr_set, cIdx = emp_neg_ctrl_genes, k = 1)
  
  # pca after ruvg
  ruvg_pca <- edaseq_plot_pca(ruvg_set, title = "RUVg output")
  filename <- file.path(output_dir, paste0(prefix, '_qc_ruvg_k1_pca.png'))
  ggsave(filename = filename, plot = ruvg_pca, width = 10, height = 6)
  
  # W corresponds to the factors of "unwanted variation"
  # factor for unwanted variation comes first for deseq2
  design <- model.matrix( ~ 0 + W_1 + patient_id + rna_library, data = pData(ruvg_set))
  ruv_dds <- DESeq2::DESeqDataSetFromMatrix(countData = counts(ruvg_set), colData = pData(ruvg_set), design = design)
  
  # From DESeq2 documentation:
  # DESeq2::DESeq performs a default analysis through the steps:
  # - estimation of size factors: estimateSizeFactors
  # - estimation of dispersion: estimateDispersions
  # - Negative Binomial GLM fitting and Wald statistics: nbinomWaldTest
  ruv_dds <- DESeq2::DESeq(ruv_dds)
  
  # Export results and save as CSV
  dge_output <- DESeq2::results(ruv_dds, cooksCutoff = FALSE, pAdjustMethod = 'BH')
  dge_output <- dge_output %>% 
    as.data.frame() %>% 
    rownames_to_column('gene') %>%
    arrange(padj) 
  filename <- file.path(output_dir, paste0(prefix, '_stranded_vs_polya_dge_ruvg_k1_deseq2_result.csv'))
  write_tsv(dge_output, file = filename)
  
  # plot and save p-value histogram
  p <- deseq2_pvals_histogram(res_df = dge_output,
                              xlab = 'stranded vs poly-A RNA-seq DGE RLE RUVg nbinomWaldTest p-value',
                              ylab = 'Gene count',
                              title = paste0('Histogram of stranded vs poly-A RNA-seq\n',
                                             'differential gene expression RLE normalized\n',
                                             'RUVg DESeq2 nbinomWaldTest p-values'))
  filename <- file.path(output_dir, paste0(prefix, '_stranded_vs_polya_dge_ruvg_k1_deseq2_histogram.png'))
  ggsave(filename = filename, plot = p, width = 8, height = 7)
}

# 1.1. RUVg using hk genes in tumor + normals
emp_neg_ctrl_genes_hk_tumor_normal <- readRDS('output/hk_genes_tumor_normals.rds')
ruvg_test(seq_expr_set = seq_expr_set, emp_neg_ctrl_genes = emp_neg_ctrl_genes_hk_tumor_normal, prefix = "hk_genes_tumor_normals")

# 1.2. RUVg using hk genes in normals only (full HRT atlas)
emp_neg_ctrl_genes_normals <- readRDS('input/hk_genes_normals.rds')
ruvg_test(seq_expr_set = seq_expr_set, emp_neg_ctrl_genes = emp_neg_ctrl_genes_normals, prefix = "hk_genes_normals")

# 1.3. RUVg using empirical control genes (dge)
ruvg_test(seq_expr_set = seq_expr_set, emp_neg_ctrl_genes = emp_neg_ctrl_genes_dge, prefix = "dge_empirical_genes")

print('Done.')
```


edgeR:

```
# edgeR analysis with RUVg and RUVr
# based on this comment: https://support.bioconductor.org/p/67273/#67274
# RUVg and RUVs (not applicable here) are easy to incorporate with DESeq2 but RUVr method requires an edgeR output as input
# so we will repeat all steps in test_ruvseq_deseq2 and add RUVr with edgeR

suppressPackageStartupMessages({
  library(tidyverse)
  library(optparse)
  library(RUVSeq)
})

# parse parameters
option_list <- list(
  make_option(opt_str = "--dataset", type = "character",
              help = "Dataset for running differential gene expression analysis: match_pbta_hgg or match_target_all")
)
opt <- parse_args(OptionParser(option_list = option_list))
dataset <- opt$dataset
output_dir <- file.path('output', 'edger_outputs', dataset)
dir.create(output_dir, showWarnings = F, recursive = T)

# plotting function
source('util/deseq2_pvals_histogram.R')
source('util/edaseq_plot_pca.R')

# read histology
htl_df <- readr::read_tsv('../../data/histologies.tsv')

# read expected counts
cnt_df <- readRDS('../../data/gene-counts-rsem-expected_count-collapsed.rds')

# filter histology
if (dataset == "match_target_all") {
  # 24 Acute Lymphoblastic Leukemia samples have been sequenced with > 1 technology
  selected_htl_df <- htl_df %>%
    filter(experimental_strategy == "RNA-Seq",
           sample_type == "Tumor",
           cohort == "TARGET") %>%
    group_by(Kids_First_Participant_ID, sample_id) %>%
    mutate(n = length(sort(unique(RNA_library)))) %>% 
    filter(n > 1)
} else if (dataset == "match_pbta_hgg") {
  # 4 CNS Embryonal tumor, 4 Diffuse midline glioma and 10 High-grade glioma/astrocytoma
  # sample size is okay in HGG so we will use that as a test
  selected_htl_df <- htl_df %>%
    filter(experimental_strategy == "RNA-Seq",
           sample_type == "Tumor",
           cohort == "PBTA",
           cancer_group == "High-grade glioma/astrocytoma") %>%
    group_by(Kids_First_Participant_ID, sample_id) %>%
    mutate(n = length(sort(unique(RNA_library)))) %>% 
    filter(n > 1)
} else {
  stop(paste0('unknown dataset', dataset))
}

# filter expression
cnt_df <- cnt_df %>%
  dplyr::select(selected_htl_df$Kids_First_Biospecimen_ID)
cnt_df <- cnt_df[rowSums(cnt_df) > 0,]

# filter by expression and convert to DGElist
# for paired analysis, we need to consider patient id (e.g. https://www.biostars.org/p/437279/)
patient_id <- factor(as.character(selected_htl_df$Kids_First_Participant_ID))
rna_library <- factor(as.character(selected_htl_df$RNA_library))
design <- model.matrix(~ 0 + patient_id + rna_library)
counts_object <- edgeR::DGEList(counts = cnt_df, group = rna_library)
counts_object_filtered <- edgeR::filterByExpr(counts_object, group = rna_library)
counts_object <- counts_object[counts_object_filtered, , keep.lib.sizes = FALSE]

# create new expression set
seq_expr_set <- newSeqExpressionSet(counts = round(counts_object$counts), phenoData = data.frame(patient_id, rna_library, row.names = colnames(round(counts_object$counts))))
pca_p <- edaseq_plot_pca(object = seq_expr_set, title = "Before normalization")

# from https://support.bioconductor.org/p/95805/#95808
# The "betweenLaneNormalization" is just a poorly named function that perform between-sample normalization, 
# independently of the fact that they are organized in lanes, plates, etc. 
# It is used in RUVSeq just to make sure that the factors of unwanted variation don't capture the difference in library size that should be captured by the size factors. 
# normalize the data using upper-quartile (UQ) normalization
seq_expr_set <- EDASeq::betweenLaneNormalization(seq_expr_set, which = "upper")
pca_p_norm <- edaseq_plot_pca(object = seq_expr_set, title = "After UQ normalization")

# save plot
p <- ggpubr::ggarrange(pca_p, pca_p_norm, common.legend = T, legend = "right")
fname <- file.path(output_dir, 'qc_pca.png')
ggsave(filename = fname, plot = p, width = 12, height = 8)

# DGE before running RUVg or RUVr
y <- DGEList(counts = counts(seq_expr_set), group = rna_library)
y <- calcNormFactors(y, method = "upperquartile")
y <- estimateGLMCommonDisp(y, design)
y <- estimateGLMTagwiseDisp(y, design)
fit <- glmFit(y, design)
lrt <- glmLRT(fit, coef = grep('rna_library', colnames(fit$coefficients))) # for RNA library
dge_output <- topTags(lrt, n = Inf)$table %>%
  rownames_to_column('gene') %>%
  dplyr::rename("pvalue" = "PValue", "padj" = "FDR")

# Export results and save as CSV
filename <- file.path(output_dir, 'stranded_vs_polya_dge_edger_result.csv')
write_tsv(dge_output, file = filename)

# empirical control genes
emp_neg_ctrl_genes_dge <- dge_output %>% 
  filter(padj < 0.05) %>%
  pull(gene)

# plot and save p-value histogram
p <- deseq2_pvals_histogram(res_df = dge_output,
                            xlab = 'stranded vs poly-A RNA-seq edgeR p-value',
                            ylab = 'Gene count',
                            title = paste0('Histogram of stranded vs poly-A RNA-seq\n',
                                           'differential gene expression edgeR p-values'))
filename <- file.path(output_dir, 'stranded_vs_polya_dge_edger_histogram.png')
ggsave(filename = filename, plot = p, width = 8, height = 7)

# Step 1: function to evaluate RUVg: Estimating the factors of unwanted variation using control genes
# uses negative control genes, assumed to have constant expression across samples
ruvg_test <- function(seq_expr_set, emp_neg_ctrl_genes, prefix){
  
  print(paste0('Run differential gene expression edgeR ',
               'with RUVSeq estimated batch effect on poly-A vs stranded RNA-seq...'))
  
  # to estimate the factors of unwanted variation,
  # subset to negative control genes (genes that can be assumed not to be influenced by the covariates of interest)
  emp_neg_ctrl_genes <- intersect(emp_neg_ctrl_genes, rownames(seq_expr_set@assayData$counts))
  emp_neg_ctrl_genes <- emp_neg_ctrl_genes[emp_neg_ctrl_genes %in% rownames(seq_expr_set@assayData$counts)]
  
  # run RUVg assuming there is only 1 major factor of unwanted variation (i.e. k = 1)
  ruvg_set <- RUVg(x = seq_expr_set, cIdx = emp_neg_ctrl_genes, k = 1)
  
  # pca after ruvg
  ruvg_pca <- edaseq_plot_pca(ruvg_set, title = "RUVg output")
  filename <- file.path(output_dir, paste0(prefix, '_qc_ruvg_k1_pca.png'))
  ggsave(filename = filename, plot = ruvg_pca, width = 10, height = 6)
  
  # W corresponds to the factors of "unwanted variation"
  # factor for unwanted variation comes last for edgeR
  design <- model.matrix( ~ 0 + patient_id + rna_library + W_1, data = pData(ruvg_set))
  y <- DGEList(counts = counts(ruvg_set), group = rna_library)
  y <- calcNormFactors(y, method = "upperquartile")
  y <- estimateGLMCommonDisp(y, design)
  y <- estimateGLMTagwiseDisp(y, design)
  fit <- glmFit(y, design)
  lrt <- glmLRT(fit, coef = grep('rna_library', colnames(fit$coefficients)))
  dge_output <- topTags(lrt, n = Inf)$table %>%
    rownames_to_column('gene') %>%
    dplyr::rename("pvalue" = "PValue", "padj" = "FDR")
  
  # Export results and save as CSV
  filename <- file.path(output_dir, paste0(prefix, '_stranded_vs_polya_dge_ruvg_k1_edger_result.csv'))
  write_tsv(dge_output, file = filename)
  
  # plot and save p-value histogram
  p <- deseq2_pvals_histogram(res_df = dge_output,
                              xlab = 'stranded vs poly-A RNA-seq edgeR-RUVg p-value',
                              ylab = 'Gene count',
                              title = paste0('Histogram of stranded vs poly-A RNA-seq\n',
                                             'differential gene expression RLE normalized\n',
                                             'RUVg edgeR p-values'))
  filename <- file.path(output_dir, paste0(prefix, '_stranded_vs_polya_dge_ruvg_k1_edger_histogram.png'))
  ggsave(filename = filename, plot = p, width = 8, height = 7)
}

# 1.1. RUVg using hk genes in tumor + normals
emp_neg_ctrl_genes_hk_tumor_normal <- readRDS('output/hk_genes_tumor_normals.rds')
ruvg_test(seq_expr_set = seq_expr_set, emp_neg_ctrl_genes = emp_neg_ctrl_genes_hk_tumor_normal, prefix = "hk_genes_tumor_normals")

# 1.2. RUVg using hk genes in normals only (full HRT atlas)
emp_neg_ctrl_genes_normals <- readRDS('input/hk_genes_normals.rds')
ruvg_test(seq_expr_set = seq_expr_set, emp_neg_ctrl_genes = emp_neg_ctrl_genes_normals, prefix = "hk_genes_normals")

# 1.3. RUVg using empirical control genes (dge)
ruvg_test(seq_expr_set = seq_expr_set, emp_neg_ctrl_genes = emp_neg_ctrl_genes_dge, prefix = "dge_empirical_genes")

# Step 2: function to evaluate RUVr: Estimating the factors of unwanted variation using residuals
# uses residuals, e.g., from a first-pass GLM regression of the counts on the covariates of interest.
y <- DGEList(counts = counts(seq_expr_set), group = rna_library)
y <- calcNormFactors(y, method="upperquartile")
y <- estimateGLMCommonDisp(y, design)
y <- estimateGLMTagwiseDisp(y, design)
fit <- glmFit(y, design)
res <- residuals(fit, type="deviance")

# we can use all the genes to estimate the factors of unwanted variation.
genes <- rownames(seq_expr_set@assayData$counts)
ruvr_set <- RUVr(x = seq_expr_set, cIdx = genes, k = 1, residuals = res)

# pca after ruvr
ruvr_pca <- edaseq_plot_pca(ruvr_set, title = "RUVr output")
filename <- file.path(output_dir, paste0('all_genes_qc_ruvr_k1_pca.png'))
ggsave(filename = filename, plot = ruvr_pca, width = 10, height = 6)

# W corresponds to the factors of "unwanted variation"
# factor for unwanted variation comes last for edgeR
design <- model.matrix( ~ 0 + patient_id + rna_library + W_1, data = pData(ruvr_set))
y <- DGEList(counts = counts(ruvr_set), group = rna_library)
y <- calcNormFactors(y, method = "upperquartile")
y <- estimateGLMCommonDisp(y, design)
y <- estimateGLMTagwiseDisp(y, design)
fit <- glmFit(y, design)
lrt <- glmLRT(fit, coef = grep('rna_library', colnames(fit$coefficients)))
dge_output <- topTags(lrt, n = Inf)$table %>%
  rownames_to_column('gene') %>%
  dplyr::rename("pvalue" = "PValue", "padj" = "FDR")

# Export results and save as CSV
filename <- file.path(output_dir, 'stranded_vs_polya_dge_ruvr_k1_edger_result.csv')
write_tsv(dge_output, file = filename)

# plot and save p-value histogram
p <- deseq2_pvals_histogram(res_df = dge_output,
                            xlab = 'stranded vs poly-A RNA-seq edgeR-RUVr p-value',
                            ylab = 'Gene count',
                            title = paste0('Histogram of stranded vs poly-A RNA-seq\n',
                                           'differential gene expression RLE normalized\n',
                                           'RUVr edgeR p-values'))
filename <- file.path(output_dir, 'stranded_vs_polya_dge_ruvr_k1_edger_histogram.png')
ggsave(filename = filename, plot = p, width = 8, height = 7)

print('Done.')
```

**Comment by komalsrathi** [comment]
@aadamk some QC updates

NOTE: the points are colored by same participant id 

### PBTA HGG

PCA is looking much better than UMAP for HGG dataset, could be because of small n of 10 samples. The patients are clustering together vs in UMAP you can see 2 clusters corresponding to RNA library.  Interestingly, the two samples `BS_59ZJWJTF` and `BS_QYPHA40N` are of a different composition type i.e. `Derived Cell Line` which explains why they are clustering away from the other samples of the same participant. This is what I observed in the larger clustering plots with all OT cohorts as well - that composition type is the primary contributor to the differences between the samples. 

1. PCA before and after UQ normalization

![qc_pca](https://user-images.githubusercontent.com/7000615/161593065-3acf0fb8-1327-4528-b8b2-bda977913a4c.png)

2. UMAP before and after UQ normalization

![qc_umap](https://user-images.githubusercontent.com/7000615/161593144-10bfab58-8fe6-4334-8d5d-cfa876f1cd91.png)

I have performed the following comparisons and the best clustering (with paired samples coming closest to each other) is with RUVg empirical genes from 1st pass DGE i.e. 3rd and 4th analysis:

1. DESeq2 RUVg with HK normals 

![hk_genes_normals_qc_ruvg_k1_clustering](https://user-images.githubusercontent.com/7000615/161592302-e5a3067d-b7e4-4433-94b6-380175b78617.png)

2. DESeq2 RUVg with HK tumors + normals 

![hk_genes_tumor_normals_qc_ruvg_k1_clustering](https://user-images.githubusercontent.com/7000615/161592283-b86bceb3-81ba-42a2-9a45-788965a774bb.png)

3. DESeq2 RUVg with empirical genes from 1st pass DGE 

![deseq2_dge_empirical_genes_qc_ruvg_k1_clustering](https://user-images.githubusercontent.com/7000615/161592316-849aa1c9-f043-432b-a29f-1fbd624c5c92.png)

4. edgeR RUVg with empirical genes from 1st pass DGE 

![edgeR_dge_empirical_genes_qc_ruvg_k1_clustering](https://user-images.githubusercontent.com/7000615/161592361-b392960b-4036-45eb-bb88-ab86914d0b35.png)

5. edgeR RUVr with all expressed genes

![all_genes_qc_ruvr_k1_clustering](https://user-images.githubusercontent.com/7000615/161592338-8e9d25be-4c9f-4ad0-bca7-7201228b0c9c.png)

### TARGET ALL 

For TARGET ALL with 24 samples, the UMAP is looking much better and seems to create two separate groups based off of library types. I don't know why `PARBVI-09A-02R` is clustering so weirdly especially after UQ normalization because both PARBVI samples are Primary Tumor from Bone Marrow.  

1. PCA before and after UQ normalization

![qc_pca](https://user-images.githubusercontent.com/7000615/161592990-ce1d9ef8-69a1-4388-bea6-e67cb251bdcb.png)

2. UMAP before and after UQ normalization (not sure why the one sample moved to the second cluster)

![qc_umap](https://user-images.githubusercontent.com/7000615/161593002-af16b9c1-9b33-4e7c-9a21-962fae01f9ef.png)

I have performed the following comparisons for TARGET ALL as well, but this is harder to interpret:

1. DESeq2 RUVg with HK normals 

![hk_genes_normals_qc_ruvg_k1_clustering](https://user-images.githubusercontent.com/7000615/161592852-2ce727e9-9880-41e7-ba85-581349c6c4de.png)

2. DESeq2 RUVg with HK tumors + normals 

![hk_genes_tumor_normals_qc_ruvg_k1_clustering](https://user-images.githubusercontent.com/7000615/161592871-dd3086e8-827c-416a-9970-50281380e237.png)

3. DESeq2 RUVg with empirical genes from 1st pass DGE  

![deseq2_dge_empirical_genes_qc_ruvg_k1_clustering](https://user-images.githubusercontent.com/7000615/161592829-0aadbf80-f27c-469d-ab36-fc5162b1ac1c.png)

4. edgeR RUVg with empirical genes from 1st pass DGE 

![edgeR_dge_empirical_genes_qc_ruvg_k1_clustering](https://user-images.githubusercontent.com/7000615/161592840-b8d84862-d11f-4890-8cd2-98427f412fd9.png)

5. edgeR RUVr with all expressed genes

![all_genes_qc_ruvr_k1_clustering](https://user-images.githubusercontent.com/7000615/161592804-3701d4ef-ed41-4092-b906-d8c8e2142587.png)

**Comment by aadamk** [comment]
Thanks for the thorough analysis. UMAP shows a clear separation between polyA and stranded (it may be the more appropriate method given that linearity and a symmetric distribution are important factors in PCA, but not UMAP)

For empirically defined negative control genes - the criterion of using those with p<0.05 would be appropriate. For instance, for a first pass analysis using HRT atlas genes only, the expectation is that HRT hk genes would not be differentially expressed. Those that are found to be differentially expressed are likely due to unwanted technical variation. So that list can be used as input for the second pass DGE analysis. 

so for example, here i would change to <0.05 to get that gene list
```
emp_neg_ctrl_genes_dge_edgeR <- dge_output %>% 
  filter(padj > 0.05) %>%
  pull(gene)
```

the second notable thing is that looping through multiple k's for ruvg - the value of k dictates how many singular values you retain and how much variability you capture from the neg control genes. Then, when running the second pass DGE (on the full transcriptome) using multiple k's (specifying multiple models that differ by W_k), you would evaluate the distribution of p-values among negative control genes only, looking for the k that results in a uniform distribution of p-values for negative control genes as the optimal result. You could use a chi-sq test of association or k-s test to find the distribution that is not significantly different from a uniform distribution. 

e.g. looping through a set of k's and running multiple second pass dge's here.
ruvg_set <- RUVg(x = seq_expr_set, cIdx = emp_neg_ctrl_genes, k = 1)

at the optimal k, we could then look at batch corrected values from ruvseq in umap.

**Comment by komalsrathi** [comment]
Thank you @aadamk, I'll work on this next week and update (have some ENT/miRNA analysis to work on today).

**Comment by komalsrathi** [comment]
@aadamk I am working on this today so just went through your comment. Agree with the second comment i.e. evaluate multiple K values. 


However, regarding your first comment:

> For empirically defined negative control genes - the criterion of using those with p<0.05 would be appropriate. For instance, for a first pass analysis using HRT atlas genes only, the expectation is that HRT hk genes would not be differentially expressed. Those that are found to be differentially expressed are likely due to unwanted technical variation. So that list can be used as input for the second pass DGE analysis.

I think there is some misunderstanding I wanted to clarify. What I am doing is using 3 approaches:

1. House keeping genes identified only in normal tissues downloaded from HRT atlas: Use them _as is_ in `RUVg's cIdx`  param. There is no p-values associated with these. The results of the RUVg output are used as input in `DESeq2::DESeqDataSetFromMatrix` (i.e. second pass DGE analysis)
2.  House keeping genes identified in both Normal + Tumor samples following the HRT atlas protocol: similar as above i.e. use them _as is_  in `RUVg's cIdx`  param. There is no p-values associated with these. The results of the RUVg output are used as input in `DESeq2::DESeqDataSetFromMatrix` (i.e. second pass DGE analysis)
3. DGEs identified using the paired analysis for matched samples (either PBTA HGG or TARGET ALL). This is where I am using the `padj > 0.05` criterion to get genes that are not differentially expressed. This is taken from section 2.4 of the [RUVSeq vignette](https://bioconductor.org/packages/release/bioc/vignettes/RUVSeq/inst/doc/RUVSeq.pdf)  `“in-silico empirical” negative controls, e.g., least significantly DE genes
based on a first-pass DE analysis performed prior to RUVg normalization.` I am then using these genes as `empirical control genes` in RUVg cIdx param. 

Please let me know if this makes sense?

**Comment by aadamk** [comment]
Thanks for the clarification. Yes, all makes sense. 

What I referenced above was actually Yuanchao's old work doing a first pass among technical replicates, selecting housekeeping genes that were less than 0.05 as differential expressions due to technical variation to use in the RUVg model. That gene set is actually available - it would be a matter of plugging it into the RUVg model and could be a fourth comparator. 

I believe that gene set can be pulled from the results [here](https://github.com/logstar/OpenPedCan-analysis/blob/rna-seq-protocol-ruvseq/analyses/rna-seq-protocol-ruvseq/results/deseq2-significant-house-keeping-genes-as-negative-control/matched_sample_ids/stranded_vs_polya_dge_deseq2_nbinom_wald_test_res.csv), selecting adj-p-val <0.05 and those that are HRT atlas genes.

**Comment by komalsrathi** [comment]
hmm, I dont think that gene list is applicable here. 

Reason: Yuanchao's input data and model is completely different than what I have here. For instance, I am testing this on 2 different datasets: 1) PBTA HGG that were sequenced with >1 protocol 2) TARGET ALL that were sequenced with >1 protocol. He was using all matched samples from PBTA together i.e. HGG, CNS Embryonal tumor and Diffuse midline glioma samples together and I think if we use all these histologies together, we could be seeing biological differences due to histologies. Therefore, I am only specifically selecting subsets of histologies so the differences we capture are due to RNA library or other technical variation and not biological in nature. 

Secondly, I am using a paired analysis incorporating the participant ID which he wasn't using so his model is different than I what I am using here. 

I am in process of creating a PR for this issue as it will be easier to navigate through my code and outputs to avoid confusion. I am probably not understanding the above comment so if we could schedule a call for clarification, that would be great.

**Comment by komalsrathi** [comment]
> What I referenced above was actually Yuanchao's old work doing a first pass among technical replicates, selecting housekeeping genes that were less than 0.05 as differential expressions due to technical variation to use in the RUVg model. That gene set is actually available - it would be a matter of plugging it into the RUVg model and could be a fourth comparator.

@aadamk I see your point now, I will add this to the PR and let you know.

**Comment by komalsrathi** [comment]
@aadamk I added this under [section 1.4](https://github.com/PediatricOpenTargets/OpenPedCan-analysis/blob/rnaseq-batch-correct/analyses/rnaseq-batch-correct/code/03-test_ruvseq.R#L145-L154) and [section 2.4](https://github.com/PediatricOpenTargets/OpenPedCan-analysis/blob/rnaseq-batch-correct/analyses/rnaseq-batch-correct/code/03-test_ruvseq.R#L209-L219)

**Comment by chinwallaa** [comment]
updates on paid teams account for space issue?

**Comment by aadamk** [comment]
per @devbyaccident - the solution was the following

```
git lfs uninstall
git lfs uninstall --local
```

which bypasses github's LFS storage altogether which is fine as no single file is particularly large (only the total storage from the repo is large).

**Comment by chinwallaa** [comment]
ruv seq package may be missing from docker file, @aadamk can you make a seperate PR to get this added

**Comment by jharenza** [comment]
completed with https://github.com/PediatricOpenTargets/OpenPedCan-analysis/pull/247
