### ISSUE TITLE
Bix Ops harmonization request , MTP Multi-CNV

### ISSUE THREAD

**Issue by migbro** [PediatricOpenTargets/ticket-tracker#280]
### [Required] Basic study information 
- [ ] Is this an OT or Kids First study: OT
- [ ] If KF, PI name and fiscal year:
- [ ] Study short name:

**NOTE**: Study short name is required for D3B study, but optional for Kids First X01; Fiscal year is required for Kids First X01, but optional for D3B study. Those information will be used for project naming in Cavatica.

### [Required] What workflow needs to be done?
For reference: https://www.notion.so/d3b/workflow-type-365a604413534b2b9d93c969557d60a2 

- [ ] alignment
- [ ] gatk-hc-gvcf
- [ ] family-vcf-genotyping
- [ ] cohort-vcf-genotyping
- [ ] single-vcf-genotyping
- [ ] somatic-analysis
- [ ] rnaseq-analysis
- [ ] only delivery of the source data
- [ ] rnaseq toolkit run ( this would be D3b toolkit modules like collapse RSEM files , merge RSEM files , merge fusion calls )
- [ ] dnaseq toolkit run ( this would be D3b toolkit modules like consensus CNV analysis, merge consensus maf files )
- [x] Other - [SB Multi-CNV](https://github.com/kids-first/kf-somatic-workflow/blob/master/workflow/sb_multicnv_wf.cwl)

### [Required] Requested sample manifest.
Please provide a description selection criteria for the samples need to be processed. E.g. "the entire study" or "all visible tumors". Along with a requested sample manifest in the format of tab delimited file with columns of `biospecimen_id`, `experiment_strategy`, `source_text_tissue_type` and `genomics_file_id`. Please attach the manifest directly to this ticket or post a downloadable link if manifest is on DataTracker. 

Everything?

### [Required] Billing group for this study? 
If there's no billing group setup for this study or project yet, please follow the [D3b Billing Workflow guidelines](https://www.notion.so/d3b/D3b-Billing-Workflow-a60afac8f4ce4e6ea0ec416c0adc749b) and submit your request at [D3b Billing Group Creation board](https://www.notion.so/d3b/259a780a53da4f3e9c9e6be966e02220?v=c1a9a2c342264cf59508e5fba90cd663)

Likely `d3b-OpenTargets-processing`

### [Optional] What is the priority for the analysis? (Low, Medium, High)
High

### [Optional] How long do you think this work will take?
A couple days

### [Optional] Who will complete this work?

---

**Comment by zhangb1** [comment]
@migbro  do you have an example run in cavatica?

**Comment by migbro** [comment]
Some added comments:
Inputs for multi-CNV should be:
1. ControlFreeC info file
2. ControlFreeC pvalue file
3. GATK `called_copy_ratio_segments_tumor`
4. CNVKit `theta2_calls` **when available**, `cnvkit_calls` if not

All inputs should have matching `case_id` and `sample_type` metadata filled out for each biospecimen. Example run here: https://cavatica.sbgenomics.com/u/brownm28/mb-controlfreec-troubleshoot/tasks/6f2f55b9-d22b-4186-8e02-fa1b7e34498d/
If needed, workflow has `override` fields for convenience to ensure the same `case_id` and `sample_type` are applied to all files in task.

**Comment by zhangb1** [comment]
@migbro  , just make sure the case_id  and sample_type are from the tumor/somatic results metadata ?

**Comment by migbro** [comment]
Yeah, so each input file for each task, needs to have cavatica `case_id` and `sample_type` filled out. If it already is - which is likely since you guys normally tag metadata, should be fine. It's a seven bridges workflow that we modified. See the **Input Files** section in the workflow doc: https://cavatica.sbgenomics.com/u/brownm28/mb-controlfreec-troubleshoot/apps/#brownm28/mb-controlfreec-troubleshoot/sb_multicnv_wf/6
If it isn't filled out - you can either patch it, or use the "override" app inputs that we added so that it will apply the case_id and sample_type you choose at run time during the task run. Does that make sense?

**Comment by bmennis** [comment]
CBTN cohort update:
I have completed the MultiCNV run on the CBTN somatic samples. The completed tasks are located in the same Cavatica project that the GATK CNV analyses were run. Here is a link to the completed samples:
https://cavatica.sbgenomics.com/u/kfdrc-harmonization/sd-bhjxbdqk-ad-hoc-gatk-cnv/tasks?search=MultiCNV&status=COMPLETED

All metadata has been patched as well.

**Comment by bmennis** [comment]
TARGET cohort update:
I have completed the MultiCNV run on the TARGET somatic samples. The completed tasks are located in the same Cavatica project that the GATK CNV analyses were run. Some of the samples failed to run at first but it appeared to be some were due in part to back end issues and others because the sample type had empty spaces in it. Additionally, some somatic pairs did not have `case_id` metadata patched to them and so one was not provided for the input override setting leaving the outputs missing that case ID. If this is a problem we can re run those samples. Here is a link to the completed samples:
https://cavatica.sbgenomics.com/u/d3b-bixu-ops/open-target-ad-hoc-gatk-cnv/tasks?search=MultiCNV&status=COMPLETED

All metadata has been patched as well from the inputs for the respective somatic pairs.

**Comment by migbro** [comment]
@bmennis can you given an example of a task where a case_id was missing, just to see what it looked like? Thanks!

**Comment by bmennis** [comment]
Here is a completed example @migbro:
https://cavatica.sbgenomics.com/u/d3b-bixu-ops/open-target-ad-hoc-gatk-cnv/tasks/5eb657d3-144a-4209-b92b-0f6bd7df3bc5/

**Comment by migbro** [comment]
Um, hmmm, doesn't seem terrible. Some files are getting output like:
`5eb657d3-144a-4209-b92b-0f6bd7df3bc5.undefined.Tumor.cnvkit_status_undefined.Tumor.controlfreec_status_STATUS_multicnv.heatmap.png`
Where that `undefined` would normally be `case_id`. Perhaps we can rename them to replace that with either biospecimen ID, sample ID, or patient ID? like,m whatever makes sense in the context for that project. Kinda subjective.

**Comment by bmennis** [comment]
After discussion on the missing case IDs for some of the TARGET samples, it was decided to re run all cohorts. It was decided that aliquot IDs for TARGET pairs and Kids First Biospecimen IDs for the other cohorts would be more specific and informative IDs to provide the workflow as some participants may have multiple somatic pairs. I am wrapping up the analysis now and will update when complete.

**Comment by bmennis** [comment]
The re run of the cohorts is complete with metadata patched to the outputs. I named the tasks in each project to include `rerun` in the task name, and for the previous completed tasks I added `DEPRECATED` to the task names.

**Comment by jharenza** [comment]
@zhangb1 can you add me to this project

**Comment by zhangb1** [comment]
> @zhangb1 can you add me to this project

just added . there are multiple projects related.

**Comment by afarrel** [comment]
[Summary_Comparison_Results_WXS.pptx](https://github.com/PediatricOpenTargets/ticket-tracker/files/8605566/Summary_Comparison_Results_WXS.pptx)
Specificity, Sensitivity, and F scores for CNV calls vs SNP array calls

**Comment by afarrel** [comment]
GATK CNV calls vs SNP array calls by panel size.
[GATK_SNP_Comparisons2.pptx](https://github.com/PediatricOpenTargets/ticket-tracker/files/8605575/GATK_SNP_Comparisons2.pptx)

**Comment by zhangb1** [comment]
Can we close this ticket?

**Comment by chinwallaa** [comment]
closing this as SB, is no longer actively working on multi-CNV
