### ISSUE TITLE
Proposed Analysis: Curate a list of samples for testing Tumor Only SNV calling pipeline.

### ISSUE THREAD

**Issue by afarrel** [PediatricOpenTargets/ticket-tracker#281]
#### What are the scientific goals of the analysis?
Curate a list of WGS, WXS, and targeted sequencing samples to be used to assess Tumor Only SNV calling pipelines.
This list should contains samples with a TMB < 1 mut/MB, ~5 mut/MB, ~10 mut/MB, and > 100 mut/MB.

#### What methods do you plan to use to accomplish the scientific goals?

Assess `snv-mutation-tmb-coding.tsv` for WXS and WGS data with all categories.

For WGS samples and WGS samples select samples with 10 highest and 10 lowest TMB, 10 samples around 1,5, and 10 but/MB (50 total for each WXS and WGS).

For Targeted Panel data, select samples with 10 highest and 10 lowest TMB, and 10 with TMB around 1 mut/MB (30 samples total).

#### What input data are required for this analysis?
`snv-mutation-tmb-coding.tsv` output from TMB module

#### How long do you expect is needed to complete the analysis? Will it be a multi-step analysis?
1 week

#### Who will complete the analysis (please add a GitHub handle here if relevant)?
@ewafula

**Comment by afarrel** [comment]
[selected-snv-mutation-tmb-coding.txt](https://github.com/PediatricOpenTargets/ticket-tracker/files/8420820/selected-snv-mutation-tmb-coding.txt)

Thanks for the list @ewafula! We will move forward to the next step.

**Comment by chinwallaa** [comment]
should we add ATRT (as they have germline per @jharenza ) need to filter against a clean panel of normals (as not to over filter).

**Comment by jharenza** [comment]
This is being done over in bixu-tracker https://github.com/d3b-center/bixu-tracker/issues/1928
