### ISSUE TITLE
Proposed Analysis: Compare Tumor Only SNV calling pipeline results with Tumor-Normal SNV calls

### ISSUE THREAD

**Issue by afarrel** [PediatricOpenTargets/ticket-tracker#283]
#### What are the scientific goals of the analysis?
Develop and Test a tumor-only (TO) SNV calling pipeline by comparing SNV calls from tumors analyzed using both the the tumor-only pipeline and the tumor-normal (TN) pipeline.

#### What methods do you plan to use to accomplish the scientific goals?
Call SNVs using both TO and TN methods and assess the true positive rate, true negative rate, false positive rate, and false negative rate, etc. of the TO method using the results from the TN pipeline as the standard.

#### What input data are required for this analysis?
WGS, WXS, and Targeted sequencing data from patient samples in the attached sample list (from #281).

#### How long do you expect is needed to complete the analysis? Will it be a multi-step analysis?
3 weeks

#### Who will complete the analysis (please add a GitHub handle here if relevant)?
@migbro 

[selected-snv-mutation-tmb-coding.txt](https://github.com/PediatricOpenTargets/ticket-tracker/files/8420797/selected-snv-mutation-tmb-coding.txt)

**Comment by migbro** [comment]
I've started work on this. A bit tricky since PBTA files are currently only available in cavatica datasets and need access to open TARGETS cavatica repo which Bo is getting me access to.
Input cram file manifests:
[non-PBTA filtered](https://app.zenhub.com/files/366488963/55875295-e34d-44ec-82af-851bd935e8c5/download)
[PBTA-only](https://app.zenhub.com/files/366488963/acfb970e-73a6-4d48-a4d7-3d2e5c852d97/download)

**Comment by zhangb1** [comment]
Just drafted all the task here: 

https://cavatica.sbgenomics.com/u/d3b-bixu/kf-tumor-only-wf-dev/tasks?status=DRAFT

**Comment by zhangb1** [comment]
can we close this ticket ? @migbro

**Comment by migbro** [comment]
Um, not quite. Not sure the best way to do this, as we are tracking progress on a D3b ticket even though it's OpenPedCan related. So, we are trying re-running a couple jobs adding a panel of normals as we had a really big FP rate. So, for example
```
true_positives_baseline	false_positives true_positives_call false_negatives precision sensitivity  f_measure
          127.00	                 149262.00	127.00	          740.00    0.0009     0.1465	     0.0017
```
That's the public tumor-olnly vs public consensus for 1 sample. We're going to see if adding a PON will improve that before passing the results to @afarrel @jharenza and others to decide next steps.

**Comment by jharenza** [comment]
https://github.com/d3b-center/bixu-tracker/issues/1928
