### ISSUE TITLE
Get TCGA count matrix

### ISSUE THREAD

**Issue by runjin326** [PediatricOpenTargets/ticket-tracker#285]
#### What data file(s) does this issue pertain to?
```
tcga-gene-counts-rsem-expected_count-collapsed.rds
tcga-gene-expression-rsem-tpm-collapsed.rds
```

#### What release are you using?

Currently in v10 release, we have TCGA data from UCSC as part of their toil 20k project.
TCGA recently has a new release mapped to GENCODE v36 and we want to get the data and combine them to releasable gene counts.

#### Put your question or report your issue here.
Please download the star count matrix from [GDC portal]([https://portal.gdc.cancer.gov/repository?filters=%7B%22op%22%3A%22and%22%2C%22content%22%3A%5B%7B%22op%22%3A%22in%22%2C%22content%22%3A%7B%22field%22%3A%22files.data_category%22%2C%22value%22%3A%5B%22transcriptome%20profiling%22%5D%7D%7D%2C%7B%22op%22%3A%22in%22%2C%22content%22%3A%7B%22field%22%3A%22files.data_type%22%2C%22value%22%3A%5B%22Gene%20Expression%20Quantification%22%5D%7D%7D%5D%7D](https://nam10.safelinks.protection.outlook.com/?url=https%3A%2F%2Fportal.gdc.cancer.gov%2Frepository%3Ffilters%3D%257B%2522op%2522%253A%2522and%2522%252C%2522content%2522%253A%255B%257B%2522op%2522%253A%2522in%2522%252C%2522content%2522%253A%257B%2522field%2522%253A%2522files.data_category%2522%252C%2522value%2522%253A%255B%2522transcriptome%2520profiling%2522%255D%257D%257D%252C%257B%2522op%2522%253A%2522in%2522%252C%2522content%2522%253A%257B%2522field%2522%253A%2522files.data_type%2522%252C%2522value%2522%253A%255B%2522Gene%2520Expression%2520Quantification%2522%255D%257D%257D%255D%257D&data=04%7C01%7Cjinr%40chop.edu%7Cc34f7737313a4630cf2b08da1bf06a6b%7Ca611241607b041a59bb1d146b575c975%7C0%7C0%7C637853016780467498%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C0&sdata=67krClkhp45A6Y3VoIPIQclmX1DoEk%2Fcs5Fx7RkyIkU%3D&reserved=0)) and combine them for data release.

**Comment by jharenza** [comment]
Hi @zhangb1. Assigned to you. As mentioned in our meeting today, @taylordm's query can be found [here](https://portal.gdc.cancer.gov/repository?filters=%7B%22op%22%3A%22and%22%2C%22content%22%3A%5B%7B%22op%22%3A%22in%22%2C%22content%22%3A%7B%22field%22%3A%22files.data_category%22%2C%22value%22%3A%5B%22transcriptome%20profiling%22%5D%7D%7D%2C%7B%22op%22%3A%22in%22%2C%22content%22%3A%7B%22field%22%3A%22files.data_type%22%2C%22value%22%3A%5B%22Gene%20Expression%20Quantification%22%5D%7D%7D%5D%7D) and counts can be converted to TPM using [this](https://rdrr.io/github/skimlab/CCSBUtils/man/counts_to_tpm.html)v R function.

**Comment by zhangb1** [comment]
> Hi @zhangb1. Assigned to you. As mentioned in our meeting today, @taylordm's query can be found [here](https://portal.gdc.cancer.gov/repository?filters=%7B%22op%22%3A%22and%22%2C%22content%22%3A%5B%7B%22op%22%3A%22in%22%2C%22content%22%3A%7B%22field%22%3A%22files.data_category%22%2C%22value%22%3A%5B%22transcriptome%20profiling%22%5D%7D%7D%2C%7B%22op%22%3A%22in%22%2C%22content%22%3A%7B%22field%22%3A%22files.data_type%22%2C%22value%22%3A%5B%22Gene%20Expression%20Quantification%22%5D%7D%7D%5D%7D) and counts can be converted to TPM using [this](https://rdrr.io/github/skimlab/CCSBUtils/man/counts_to_tpm.html) R function.

Hi @jharenza  I tried to query in cavatica, but seems the files are old files. not the same one showing in the GDC portal...

I neither downloaded the files from GDC portal, can someone show me how to download the counts files, or others can do that?

**Comment by taylordm** [comment]
Here’s the page on the GDC transfer tool. If you need me to install it run it let me know


https://gdc.cancer.gov/access-data/gdc-data-transfer-tool

**Comment by zhangb1** [comment]
Thanks @taylordm ... I am launching a cavatica project to download the data now....

Do you know how to download the sample_id information associate with the file, when doing the merge I think we need to have the sample ID in the big merge file. I tried to search in the portal , but no luck. if you can have the manifest having the sample ID with the tsv file, that would be good.

**Comment by zhangb1** [comment]
all the GENCODE v36  RNAseq star_gene_counts are in the cavatica project : https://cavatica.sbgenomics.com/u/d3b-bixu-ops/open-target-tcga-rnaseq-counts/files/

Total of 17814 files. I am still trying to see how I can get the sample ID associate with these files. Then I will do the file merge.

**Comment by jharenza** [comment]
@yuankunzhu is helping @zhangb1 on this cc @afarrel

**Comment by yuankunzhu** [comment]
@zhangb1 you can use [this script](https://github.com/AlexsLemonade/OpenPBTA-analysis/blob/master/analyses/tcga-capture-kit-investigation/scripts/get-tcga-capture_kit.py) and modify the [line 41](https://github.com/AlexsLemonade/OpenPBTA-analysis/blob/master/analyses/tcga-capture-kit-investigation/scripts/get-tcga-capture_kit.py#L41) to query `cases.samples.submitter_id` using file name

**Comment by yuankunzhu** [comment]
run below
```python
import requests
import json
import pandas as pd

data = pd.read_csv('gdc_manifest.2022-04-18.txt',sep='\t')
tcga_filenames = data['filename'].tolist()

gdc_url = 'https://api.gdc.cancer.gov/files'
headers = {'Content-Type': 'application/json'}

fields = [
    'file_name',
    'cases.samples.submitter_id'
]
fields = ','.join(fields)

## API request body 
payload = {
        'filters':{
            'op':'=',
            'content':{
                'field':'file_name',
                'value':tcga_filenames}},
        'format':'json',
        'fields':fields,
        'size':5000 # make sure we get all the returns
}
payload = json.dumps(payload)

## hit GDC API file endpoint
gdc_response = requests.post(gdc_url, headers=headers, data=payload)
gdc_response = gdc_response.json()

## iterate .data.hits entity manifest
for i in gdc_response['data']['hits']:
    for j in i['cases']:
        for k in j['samples']:
            print(k['submitter_id']+"\t"+i['file_name'])
```
and got returns as [gdc-sample-id-return.txt](https://github.com/PediatricOpenTargets/ticket-tracker/files/8508106/gdc-sample-id-return.txt)

@zhangb1 you might wanna double check as i see some sample ID looks like they are for WES, you can modify the script to query other fields, more details at [GDC API endpoint](https://docs.gdc.cancer.gov/API/Users_Guide/Appendix_A_Available_Fields/#file-fields)

**Comment by zhangb1** [comment]
Okay I modified the script to get the aliquot ID from DGC, since the sample id won't be unique to the files. 

[all_samples_name_aliquot_id.txt](https://github.com/PediatricOpenTargets/ticket-tracker/files/8508598/all_samples_name_aliquot_id.txt)

But still they are 4 files are not unique to the aliquot ID, each has two aliquots attached to it. 


```
0b66c95c-a103-4c7e-99c5-431e89ee1cb3.rna_seq.augmented_star_gene_counts.tsv	 TARGET-30-PANKFE-01A-01R
0b66c95c-a103-4c7e-99c5-431e89ee1cb3.rna_seq.augmented_star_gene_counts.tsv	 TARGET-30-PAPUAR-01A-01R
6718fb2d-efbe-4fd1-b86a-6c37c515041d.rna_seq.augmented_star_gene_counts.tsv	 TARGET-30-PAPEAV-01A-01R
6718fb2d-efbe-4fd1-b86a-6c37c515041d.rna_seq.augmented_star_gene_counts.tsv	 TARGET-30-PAPTFZ-01A-01R
752f448c-c9c8-4de8-9fbc-f488ef8a1580.rna_seq.augmented_star_gene_counts.tsv	 TARGET-30-PANUKV-01A-01R
752f448c-c9c8-4de8-9fbc-f488ef8a1580.rna_seq.augmented_star_gene_counts.tsv	 TARGET-30-PASUML-01A-01R
a53de3f2-9fa3-4099-a5bc-6103e98ba587.rna_seq.augmented_star_gene_counts.tsv	 TARGET-30-PAIXIF-01A-01R
a53de3f2-9fa3-4099-a5bc-6103e98ba587.rna_seq.augmented_star_gene_counts.tsv	 TARGET-30-PASYPX-01A-01R

```

@jharenza

**Comment by jharenza** [comment]
@zhangb1 those are TARGET. Are all TCGA matching? If so, 👍🏻

**Comment by zhangb1** [comment]
> @zhangb1 those are TARGET. Are all TCGA matching? If so, 👍🏻

But which ID I should use?

**Comment by jharenza** [comment]
I don't think we want TARGET in this batch, as we harmonized them on our own.

**Comment by jharenza** [comment]
Yes

**Comment by zhangb1** [comment]
The merged files are in cavatica project here :

tcga-gene-expression-rsem-tpm-collapsed.rds

https://cavatica.sbgenomics.com/u/d3b-bixu-ops/open-target-tcga-rnaseq-counts/files/62614f524d85bc2e024aafea/

tcga-gene-counts-rsem-expected_count-collapsed.rds

https://cavatica.sbgenomics.com/u/d3b-bixu-ops/open-target-tcga-rnaseq-counts/files/626157224d85bc2e024abc5f/

**Comment by runjin326** [comment]
@zhangb1 - could you please put the files in s3://d3b-openaccess-us-east-1-prd-pbta/open-targets/v11/ and update the md5sum file? For some reason, Cavatica kept giving me error messages - maybe I do not have access or something.

**Comment by jharenza** [comment]
https://github.com/PediatricOpenTargets/OpenPedCan-analysis/pull/188
