### ISSUE TITLE
CNV data for pedcbio load has `unknown` 

### ISSUE THREAD

**Issue by runjin326** [PediatricOpenTargets/ticket-tracker#289]
#### What data file(s) does this issue pertain to?
`consensus_wgs_plus_cnvkit_wxs.tsv.gz`
`consensus_wgs_plus_cnvkit_wxs_autosomes.tsv.gz`
`consensus_wgs_plus_cnvkit_wxs_x_and_y.tsv.gz`

#### What release are you using?

v10

#### Put your question or report your issue here.
There are some entries that have `unknown` as `status` - one looked like it is a Y chromosome for a female.
Currently being handled by PedCBio by changing the `unknown` to `NA` - but need to take a look here.

**Comment by jharenza** [comment]
@zhangb1 is this something we should discuss at the toolkit meeting? cc @aadamk

**Comment by zhangb1** [comment]
@runjin326  can you post an example here?

**Comment by runjin326** [comment]
@zhangb1 - yes, Miguel found one when loading to pedcbio:
```
['BS_5Z0GA574', 'unknown', '1', '2', 'ENSG00000251705', 'RNA5-8SP6', 'Yp11.2', 'Female']
```

**Comment by jharenza** [comment]
@zhangb1 any updates on this?

**Comment by zhangb1** [comment]
found this :  https://github.com/PediatricOpenTargets/OpenPedCan-analysis/blob/dev/analyses/focal-cn-file-preparation/01-add-ploidy-cnvkit.Rmd#L125

[    chrom == "chrY" & germline_sex_estimate == "Female" & copy.num > 0 ~ "unknown",](https://github.com/PediatricOpenTargets/OpenPedCan-analysis/blob/b430cbb2d7f50cc4d9f7675395e487b03c16834b/analyses/focal-cn-file-preparation/01-add-ploidy-cnvkit.Rmd#L125)

seems in the code , if is female , and has the Y copy numbers the status will be set to unknown...

**Comment by jharenza** [comment]
Hmm, I think we ought to recode the above to `NA` in our code and likewise yours @zhangb1 - I will create a ticket.

**Comment by jharenza** [comment]
Created #318 to update this
