### ISSUE TITLE
Run consensus calls on Maris X01

### ISSUE THREAD

**Issue by jharenza** [PediatricOpenTargets/ticket-tracker#29]
#### What data file(s) does this issue pertain to?
future `snv-consensus-plus-hotspots.maf.tsv.gz` as referred to in #24 

#### What release are you using?

v4

#### Put your question or report your issue here.
Currently, we have the MAFs released by caller, but we would like the consensus + hotspot calls for KF NBL

#### Who will complete this?
someone from @zhangb1 's team

**Comment by jharenza** [comment]
I think this is done but being merged for v5, correct @zhangb1 ?

**Comment by zhangb1** [comment]
Yes, this task has been finished, just need to merge the files.. 

I will close this one
