### ISSUE TITLE
V10 Histologies file subtyping not up to date

### ISSUE THREAD

**Issue by jharenza** [PediatricOpenTargets/ticket-tracker#290]
#### What data file(s) does this issue pertain to?
`histologies.tsv`

#### What release are you using?

v10

#### Put your question or report your issue here.
Per the comment below within a d3b repo, it looks like old MB subtypes made it into v10. As of V8 (see [comment](https://github.com/d3b-center/bixu-tracker/issues/1344#issuecomment-1099542959)), these had been updated to use only the medulloblastoma classifier, but the v10 version has the older, consensus subtypes from OpenPBTA.

Correct, @runjin326 - the classifier is used to generate MB results as per [here](https://github.com/PediatricOpenTargets/OpenPedCan-analysis/blob/dev/analyses/molecular-subtyping-MB/results/MB_molecular_subtype.tsv). My question is whether this ever made it into the histologies file per [this issue](https://github.com/PediatricOpenTargets/ticket-tracker/issues/148), and [line 17](https://github.com/PediatricOpenTargets/OpenPedCan-analysis/pull/89/files#diff-e04cb1e9f29f76897c6b84334238f621ff45ba13cf180ad1d0d442d50ebe51f7) of the release notes for v8, which sounds like no:

```
> v10 %>%
+   filter(cancer_group == "Medulloblastoma") %>%
+   select(experimental_strategy, molecular_subtype) %>%
+   table()
                     molecular_subtype
experimental_strategy MB, Group3 MB, Group4 MB, SHH MB, To be classified MB, WNT
              RNA-Seq         14         50      31                   17      10
              WGS             10         41      24                   12      10
```

@runjin326 can you submit an issue for this, and do any MB subtype comparisons to [this file]([here](https://github.com/PediatricOpenTargets/OpenPedCan-analysis/blob/dev/analyses/molecular-subtyping-MB/results/MB_molecular_subtype.tsv)), as this is what we expect?

_Originally posted by @jharenza in https://github.com/d3b-center/bixu-tracker/issues/1344#issuecomment-1099541623_

@ewafula can you help identify when this change happened, and also update the QC markdown file to catch this sort of thing in the future? Additionally, these subtypes will have to get re-integrated into v11.

**Comment by ewafula** [comment]
@jharenza, @runjin326. This happened [here in #1](https://github.com/d3b-center/D3b-codes/pull/51#issuecomment-922092382),  which was a wholesale update of the v9 histologies file to match [v21 OpenPBTA](https://github.com/d3b-center/D3b-codes/blob/48b2ab967f61c837c6dfd265bcb160e8a3a98313/weekly_qc/pbta_v21/pbta-histologies.tsv) in addition to other subsequent updates in the thread. 

The code section in v10 for the change is here [in lines 45 -53](https://github.com/d3b-center/D3b-codes/blob/master/v10-OpenPedCan/add_v10_updates.py).

**Comment by ewafula** [comment]
The molecular subtypes that had been updated in v8 and overridden in v10 because of integration of the latest v21-PBTA in v10 as I described above have been brought back in the v11. I'll push the updated results, including RMD QC code to track all the fields in the OpenPedCan histologies.

**Comment by jharenza** [comment]
@ewafula we won't have an update yet until #98 is completed and @runjin326 reruns subtyping on the new histologies file Nick updates this week

**Comment by jharenza** [comment]
https://github.com/PediatricOpenTargets/OpenPedCan-analysis/pull/188
