### ISSUE TITLE
Updated analysis: assert that histology file is compatible with independent sample lists in `snv-frequencies` module

### ISSUE THREAD

**Issue by logstar** [PediatricOpenTargets/ticket-tracker#293]
#### What analysis module should be updated and why?

The `snv-frequencies` module needs to be updated to assert that histology file is compatible with independent sample lists in `01-snv-frequencies.R`.

In <https://github.com/PediatricOpenTargets/OpenPedCan-analysis/pull/167>, histology file is incompatible with independent sample lists.

> 
> The following cohort-cancer_groups will have patients/subjects not counted in primary/relapse tumor samples, in the result files. The [latest `snv-frequencies` module update](https://github.com/PediatricOpenTargets/OpenPedCan-analysis/pull/156) and this PR use v11 histology file, v10 MAF file, and v10 independent sample lists. v11 histology file has patients in v10 MAF file but not in v10 independent sample lists, so v11 added patients and their biospecimens are not counted in the primary/relapse tumor samples. For example, TARGET Acute Lymphoblastic Leukemia has 712 total patients, 659 primary tumors, and 17 relapse tumors.
> 
> ```text
>   cohort cancer_group         n_v11_patients_not_in_v10_independent_sample_lists
>   <chr>  <chr>                                                             <int>
> 1 GMKF   Neuroblastoma                                                         1
> 2 PBTA   Ewing sarcoma                                                         1
> 3 PBTA   High-grade glioma/astrocytoma                                         3
> 4 PBTA   Meningioma                                                            2
> 5 PBTA   Neurofibroma/Plexiform                                                2
> 6 TARGET Acute Lymphoblastic Leukemia                                         36
> 7 TARGET Neuroblastoma                                                         2
> ```

#### What changes need to be made? Please provide enough detail for another participant to make the update.

This issue should be addressed after the following items are completed:

- <https://github.com/PediatricOpenTargets/OpenPedCan-analysis/pull/167> is merged.
- New `histologies.tsv` is ready for release.
- New independent sample lists are generated using the new `histologies.tsv`.

Add the following assertions in `01-snv-frequencies.R`

```R
# assert histology file is compatible with independent sample lists
#
# All patients are in all-cohort/each-cohort primary and relapse independent
# sample lists.
#
# maf_sample_htl_df has the intersection of biospecimens between histology and
# MAF file, so maf_sample_htl_df may have fewer patients than independent sample
# lists.
#
# All maf_sample_htl_df patients should be in independent sample lists.
stopifnot(all(
  unique(maf_sample_htl_df$Kids_First_Participant_ID) %in%
    unique(c(primary_ac_indp_sdf$Kids_First_Participant_ID,
             relapse_ac_indp_sdf$Kids_First_Participant_ID))
))

stopifnot(all(
  unique(maf_sample_htl_df$Kids_First_Participant_ID) %in%
    unique(c(primary_ec_indp_sdf$Kids_First_Participant_ID,
             relapse_ec_indp_sdf$Kids_First_Participant_ID))
))
```

after

```R
# assert samples are the same
stopifnot(identical(sort(unique(maf_df$Kids_First_Biospecimen_ID)),
                    sort(maf_sample_htl_df$Kids_First_Biospecimen_ID)))
```

#### What input data should be used? Which data were used in the version being updated?

Input data for `01-snv-frequencies.R`.

Latest version.

#### When do you expect the revised analysis will be completed?

1-2 days.

#### Who will complete the updated analysis?

@logstar

cc @jharenza @runjin326 @ewafula

**Comment by jharenza** [comment]
@logstar we don't yet have a completed v11 histologies file, and once we do, it should match the genomic files. These checks are good, but just wanted to be sure that the module updates for adding samples are not going through without that v11 release.

**Comment by jharenza** [comment]
completed in https://github.com/PediatricOpenTargets/OpenPedCan-analysis/pull/243
