### ISSUE TITLE
Bix Dev PedcbioPortal Support: `tumor_type` inconsistent

### ISSUE THREAD

**Issue by jharenza** [PediatricOpenTargets/ticket-tracker#296]
# 🆘

#### Please describe your issue in a couple of sentences and provide a link to the relevant pedcbio project of interest, if it already exists
v10 OpenPedCan has the following `tumor_descriptor` which map to pedcbio `tumor_type` per [this table](https://github.com/kids-first/kf-cbioportal-etl/blob/feature/update-OT/COLLABORATIONS/openTARGETS/header_desc.tsv):

```r
> as.data.frame(table(id$tumor_descriptor))
                             Var1 Freq
1               Initial CNS Tumor 1622
2                Metastatic Tumor    3
3                   Primary Tumor 3286
4                     Progressive  299
5 Progressive Disease Post Mortem   13
6                      Recurrence  309
7               Second Malignancy   37
```

But, the current study has the following tumor types:
<img width="405" alt="Screen Shot 2022-04-26 at 1 33 37 PM" src="https://user-images.githubusercontent.com/207034/165359098-248cb7ad-a8e4-42d2-8968-954157fab2c5.png">

1. We need to recode these
2. I propose we add the OpenPedCan ETL code into this repo, which will be a separate ticket. 

#### [Required] How would you most generally describe your issue? 
- [x] Update data for project in pedcbio portal
- [ ] Questions related to data on pedcbio portal 

#### Provide the manifest (or a link to a manifest) that will be used to select samples
v10 OpenPedCaan

**Comment by migbro** [comment]
@jharenza or @runjin326 perhaps if you can review this:
```
1               Initial CNS Tumor 1622
2                Metastatic Tumor    3
3                   Primary Tumor 3286
4                     Progressive  299
5 Progressive Disease Post Mortem   13
6                      Recurrence  309
7               Second Malignancy   37
```
And tell me exactly how it should map to: https://docs.cbioportal.org/file-formats/#clinical-sample-columns (see `SAMPLE_TYPE, TUMOR_TISSUE_SITE or TUMOR_TYPE` bullet), I can feel more confident about mapping the values to leverage the functionality of the column. In the next iteration in which the histologies file is in the warehouse, I can additionally create a new column during ETL import  that keeps original values.

**Comment by migbro** [comment]
Awesome! Thanks, I will update the code to reflect this, then start the long slog of a load into QA for review

**Comment by jharenza** [comment]
Thank you - if you can add the code to the PedCan repo as well, that would be fantastic :)
