### ISSUE TITLE
Updated analysis: add histology information for non-PBTA samples to `molecular-subtyping-integrate`

### ISSUE THREAD

**Issue by jharenza** [PediatricOpenTargets/ticket-tracker#299]
#### What analysis module should be updated and why?
https://github.com/PediatricOpenTargets/OpenPedCan-analysis/tree/dev/analyses/molecular-subtyping-integrate
Need to add `broad_histology`, `short_histology`, `harmonized_diagnosis` and `cancer_group` for non-PBTA samples.

#### What changes need to be made? Please provide enough detail for another participant to make the update.
1. PR1 - Pull in recent code from https://github.com/AlexsLemonade/OpenPBTA-analysis/blob/master/analyses/molecular-subtyping-integrate/01-integrate-subtyping.Rmd
2. PR2 - Add code for `cancer_group` - we can use v10 mappings for now.

Add `cancer_group logic` to:
to this code snippet:
https://github.com/PediatricOpenTargets/OpenPedCan-analysis/blob/6e0495d518b605ce3bfa9b286490253c80ee9b87/analyses/molecular-subtyping-integrate/01-integrate-subtyping.Rmd#L178-L195

OR - should we create something like a JSON file for longer term sustainability and additions?

3. PR3 - Add `broad_histology` and `short_histology` for non-subtyped samples. These normally get added during specific subtyping modules or from the base file?:
[https://github.com/PediatricOpenTargets/OpenPedCan-analysis/blob/6e0495d518b605ce3[…]alyses/molecular-subtyping-integrate/01-integrate-subtyping.Rmd](https://github.com/PediatricOpenTargets/OpenPedCan-analysis/blob/6e0495d518b605ce3bfa9b286490253c80ee9b87/analyses/molecular-subtyping-integrate/01-integrate-subtyping.Rmd#L110-L136)

These fields are blank in base, so asked @kgaonkar6 to weigh in on this. I seem to recall we had a mapping file for this, but can't pinpoint it at the moment. It is possible that we had merged base with a mapping file, and thus the logic below.

Right now, we have many cancers not being subtyped, so we can possibly have a tmp dataframe mapping file such as [this one](https://github.com/PediatricOpenTargets/OpenPedCan-analysis/blob/dev/analyses/molecular-subtyping-integrate/input/pathology_dx%20and%20pathology_free_text_diagnosis%20to%20broad_histology%20for%20subtyping%20module%20-%20other_diagnosis_rules.tsv), which can be used to add the 2 fields. Thoughts or ideas on other solutions? cc @aadamk 

`harmonized_diagnosis` logic already exists, so once we run this module, it will be automatically added for the non-PBTA cohort.

#### What input data should be used? Which data were used in the version being updated?
base adapt file - once we add non-PBTA cohorts to the data warehouse

#### When do you expect the revised analysis will be completed?
We should probably break this up into two PRs - one for cancer group (that can be done immediately, based on what we have in the v10 file) and one for broad/short histology, so this is currently blocked. 

#### Who will complete the updated analysis?
@ewafula

**Comment by ewafula** [comment]
@jharenza, 
For PR1 in this ticket, it seems @runjin326 and already pulled the code from the OPenPBTA repo and to the OpenPedCan The code is identical, and files update commit dates massages are identical too.  Therefore, PR1 for is already done

I can start with PR2 to add `cancer_group` logic to the code, and partly PR3 to add code logic for `broad_histology` and `short_histology` from a tmp file extracted from the v10 histologies. 

You mention that the `harmonized_diagnosis` will automatically be populated when the code is run because the logic already exists.

Can I continue doing this?

**Comment by jharenza** [comment]
@ewafula ok great - sure, you can start it!

**Comment by jharenza** [comment]
Note: make sure #234 is completed within this work

**Comment by aadamk** [comment]
For mapping files referenced above - I found this [file](https://github.com/d3b-center/D3b-codes/blob/7fbb66c8eb1dc9d8086d0c903333810a2bd9d422/OpenPBTA_v20_release_QC/input/pathology_diagnosis_for_subtyping.tsv) in `d3b-codes` for generating short and broad histologies from `pathology_diagnosis`, and [this](https://github.com/d3b-center/D3b-codes/blob/7fbb66c8eb1dc9d8086d0c903333810a2bd9d422/OpenPBTA_v20_release_QC/input/pathology_free_text_diagnosis_for_subtyping.tsv) for `pathology_free_text_diagnosis` that correspond to v20 OpenPBTA.

**Comment by ewafula** [comment]
> Note: make sure #234 is completed within this work

This has already been updated in the ongoing v11 histologies file  among the completed list of associated tickets:
https://github.com/ewafula/D3b-codes/tree/v11-OpenPedCan/v11-OpenPedCan

**Comment by ewafula** [comment]
I'll finish this ticket,  [#299](https://github.com/PediatricOpenTargets/ticket-tracker/issues/299) by tomorrow. Finishing up optimizing the `metylation-summary` module (discussed with @afarrel  on slack)

**Comment by ewafula** [comment]
@jharenza, I have a few questions pertaining to this ticket.
You asked that I update the code snippets in the links included in the ticket for non-PBTA cohorts.  It is pretty straightforward to make inferences for GMFK and TARGET for  `broad_histology`, `short_histology`, and `cancer_group` from the `pathology_diagnosis` column in the base histologies file. I am making an assumption that the non-PBTA cohort histologies files (don't include `broad_histology`, `short_histology`, and `cancer_group` columns) in the [OpenPedCan_cohort_histologies](https://github.com/d3b-center/D3b-codes/tree/master/OpenPedCan_cohort_histologies) module will be integrated into the base histologies. For TCGA, `pathology_diagnosis`, `broad_histology`, `short_histology`, and `cancer_group` were pulled directly from the GDC data manifest. Making inferences from  `pathology_diagnosis`  to  `broad_histology`, `short_histology`, and `cancer_group` is tricky. 

There are a couple of GMFK samples that were left in the histologies with `pathology_diagnosis` as `Unknown` based on the GMFK clinical file following your conversation with Drs Maris and Diskin. 

See attached table of a unique combination of `pathology_diagnosis`, `broad_histology`, `short_histology`, and `cancer_group` from the v10 histologies file.

[non-pbta_unique_diagnosis_columns.tsv.zip](https://github.com/PediatricOpenTargets/ticket-tracker/files/8627981/non-pbta_unique_diagnosis_columns.tsv.zip)

**Comment by jharenza** [comment]
>I am making an assumption that the non-PBTA cohort histologies files (don't include broad_histology, short_histology, and cancer_group columns) in the [OpenPedCan_cohort_histologies](https://github.com/d3b-center/D3b-codes/tree/master/OpenPedCan_cohort_histologies) module will be integrated into the base histologies.

Yes, that is the idea, so we would start this module with the base file in `/data`. Actually, it may make sense to drop the v11 file you created thus far into the `/results` folder of this module (arranged by BS_id) via PR so that when you make these code updates we can see what exactly changed (hopefully not much!).

>For TCGA, pathology_diagnosis, broad_histology, short_histology, and cancer_group were pulled directly from the GDC data manifest. Making inferences from pathology_diagnosis to broad_histology, short_histology, and cancer_group is tricky.

I think we may need to create a quick google doc to work on that.

>There are a couple of GMFK samples that were left in the histologies with pathology_diagnosis as Unknown based on the GMFK clinical file following your conversation with Drs Maris and Diskin.

For those, we still have broad/short/cancer group, correct? I would do a mutate and case_when to recode those specific samples.

I will take a look at the zip file probably tomorrow!

**Comment by jharenza** [comment]
https://github.com/PediatricOpenTargets/OpenPedCan-analysis/pull/188
