### ISSUE TITLE
Alvin to prepare manifests and data locations on isilon for TARGET RNA/WXS/WGS - deliver to Yuankun

### ISSUE THREAD

**Issue by afarrel** [PediatricOpenTargets/ticket-tracker#3]
#### What data file(s) does this issue pertain to?

TARGET RNAseq, WES, and WGS fastq Files on the Diskin drive on isilon

RNA:
/mnt/isilon/diskin_lab/TARGET_RNA/fastq/

 WXS
 /mnt/isilon/dbgap/prj_1812/TARGET-Exome/fastq/
/mnt/isilon/diskin_lab/TARGET_WXS/dbGap/fastq/

- [Request access]  @afarrel to request access to drives  for @yuankunzhu 

#### Who will complete this.
@afarrel

**Comment by jharenza** [comment]
closing this since we will use CGC, @yuankunzhu I will send you the manifest for TARGET RNA
