### ISSUE TITLE
Rerun all molecular subtyping for v11 data release

### ISSUE THREAD

**Issue by runjin326** [PediatricOpenTargets/ticket-tracker#303]
#### What data file(s) does this issue pertain to?
histologies.tsv

#### What release are you using?

v11

#### Put your question or report your issue here.
Re-run all molecular subtyping related modules with v11 data files 

First re-run all the preprocessing modules 
- [x] fusion-summary
- [x] gene-set-enrichment-analysis
- [x] run-gistic
- [x] tp53_nf1_score

Then rerun all subtyping modules
- [x] molecular-subtyping-MB
- [x] molecular-subtyping-CRANIO
- [x] molecular-subtyping-EPN
- [x] molecular-subtyping-embryonal
- [x] molecular-subtyping-chordoma
- [x] molecular-subtyping-EWS
- [x] molecular-subtyping-neurocytoma
- [x] molecular-subtyping-HGG
- [x] molecular-subtyping-LGAT
- [x] molecular-subtyping-pathology
- [x] molecular-subtyping-integrate

Then use the QC code from D3b code [here ](https://github.com/d3b-center/D3b-codes/blob/3e318f9cadc654a8b91013a846e99381d9597f48/weekly_qc/QC_histology_full.Rmd) to check changes/inconsistency.

**Comment by jharenza** [comment]
Note this issue re tp53 https://github.com/AlexsLemonade/OpenPBTA-analysis/pull/1362

**Comment by runjin326** [comment]
When re-running the GSEA module, notice that for some of the samples in histology-base.tsv are not in the RNA gene expression matrix:
```
histology_rna_df$Kids_First_Biospecimen_ID[!histology_rna_df$Kids_First_Biospecimen_ID %in% colnames(expression_data)]
 [1] "BS_05TTCK08" "BS_277SBSCP" "BS_3GZN3RTH" "BS_3KW5B3GY" "BS_4PAKWW7J" "BS_56Z15924" "BS_72DY6M9J" "BS_7EW8HBG9" "BS_862NMAR7" "BS_8TW4H1T3"
[11] "BS_ASM7ANKQ" "BS_AZMPSWJR" "BS_BMMA05FW" "BS_C4TT4XS0" "BS_C97AE5XA" "BS_CMM1Q934" "BS_EE17YHEH" "BS_F63KKBGX" "BS_G7PA9EGA" "BS_H2RX54Z5"
[21] "BS_H6CNYG42" "BS_HYMWP6WF" "BS_JV9G8CNX" "BS_JXF8A2A6" "BS_KSS4AAPP" "BS_NK7K4GFE" "BS_VVNWB3FZ" "BS_WN90GPFR" "BS_X7J2RKVK" "BS_XZ58ASB6"
[31] "BS_Y1ZP55ZK" "BS_Z8JJGT26"
```
[non_rna.txt](https://github.com/PediatricOpenTargets/ticket-tracker/files/8833873/non_rna.txt)

Maybe we need to double check the merged expression matrix.

**Comment by jharenza** [comment]
Hmm, ok, let me go back to the base code - it looks like these are a mix of visible and not visible but none were in V10, so probably need to be removed.

**Comment by jharenza** [comment]
resolved, since wrong base file was being used

**Comment by jharenza** [comment]
Closed with https://github.com/PediatricOpenTargets/OpenPedCan-analysis/pull/188
