### ISSUE TITLE
Rerun independent sample list once v11 histologies file is ready

### ISSUE THREAD

**Issue by runjin326** [PediatricOpenTargets/ticket-tracker#304]
#### What data file(s) does this issue pertain to?
independent-specimens.*

#### What release are you using?

v11 

#### Put your question or report your issue here.
Please re-run the independent-samples module once v11 histologies file is ready.

**Comment by jharenza** [comment]
https://github.com/PediatricOpenTargets/OpenPedCan-analysis/pull/188
