### ISSUE TITLE
base-histologies file has duplicated rows

### ISSUE THREAD

**Issue by jharenza** [PediatricOpenTargets/ticket-tracker#306]
#### What data file(s) does this issue pertain to?
`histologies-base-adapt.tsv` 

#### What release are you using?
pulled today by @komalsrathi - https://github.com/d3b-center/d3b-bixu-data-assembly/issues/14#issuecomment-1117617996

#### Put your question or report your issue here.
This was an issue in the past and was previously fixed, but I think it might have something to do with data being pulled from _both_ the data tracker and BRP. We had reverted to DT for these specific samples were updated in the BRP, which I had thought was completed, but perhaps not. So, this needs an update.

#### Who will complete this??
@nicholasvk 
cc @baileyckelly and @aadamk

**Comment by nicholasvk** [comment]
I have fixed this issue. It was introduced when bringing in the DGD because we had to adjust our joins to account for DGD records not having genomic files registered in Kids First.
