### ISSUE TITLE
TCGA & histologies specimen id cross check 

### ISSUE THREAD

**Issue by runjin326** [PediatricOpenTargets/ticket-tracker#308]
#### What data file(s) does this issue pertain to?
histologies.tsv
tcga-gene-expression-rsem-tpm-collapsed.rds
tcga-gene-counts-rsem-expected_count-collapsed.rds

#### What release are you using?

v11

#### Put your question or report your issue here.
Please check to make sure all the samples in the count and expression matrix are present in histologies file.

**Comment by jharenza** [comment]
@zhangb1 or @HuangXiaoyan0106 can you do this check please?

**Comment by jharenza** [comment]
@zhangb1 or @HuangXiaoyan0106 can you do this check please?

**Comment by HuangXiaoyan0106** [comment]
all samples in rsem files are present in the histology file.
[histology_sample_bs.txt](https://github.com/PediatricOpenTargets/ticket-tracker/files/8759335/histology_sample_bs.txt)
[rsem_sample_bs.txt](https://github.com/PediatricOpenTargets/ticket-tracker/files/8759332/rsem_sample_bs.txt)

**Comment by jharenza** [comment]
these ids are now also in the new base file [here](https://github.com/d3b-center/D3b-codes/pull/68).  @runjin326 can you make sure these RDS files are on S3 and md5sums updated?

**Comment by runjin326** [comment]
@HuangXiaoyan0106 - Look like the two files in the bucket were not updated. Could you please upload the two files to here and update the md5sum.txt? Thanks!
s3://d3b-openaccess-us-east-1-prd-pbta/open-targets/v11/

**Comment by zhangb1** [comment]
Sorry ,I am uploading now....

**Comment by runjin326** [comment]
Thanks so much!

**Comment by jharenza** [comment]
ID crosscheck matches
