### ISSUE TITLE
GTEX rsem file sample IDs mismatching histologies file sample IDs

### ISSUE THREAD

**Issue by jharenza** [PediatricOpenTargets/ticket-tracker#31]
#### What data file(s) does this issue pertain to?
`histologies.tsv`

#### What release are you using?

v4

#### Put your question or report your issue here.
Per [this comment](https://github.com/PediatricOpenTargets/ticket-tracker/issues/22#issuecomment-854825044), the histologies file and rsem files have mismatched sample IDs for gtex. We should update the RSEM files in this case, once we get the mapping.

**Comment by kgaonkar6** [comment]
mapping file in https://github.com/PediatricOpenTargets/ticket-tracker/issues/22#issuecomment-854900493

**Comment by jharenza** [comment]
@kgaonkar6 for v5 release, would you be able to swap out sample ids for the barcodes and only include in the files the samples which can be found in the histologies file mentioned [here](https://github.com/PediatricOpenTargets/ticket-tracker/issues/33#issuecomment-857148476)?

**Comment by kgaonkar6** [comment]
GTEX v8 was used in v5 RSEM files `gene-expression-rsem-tpm-collapsed.rds` and `gene-counts-rsem-expected_count-collapsed.rds` in which GTEx sample ids completely overlap histology file GTEx sample ids in
