### ISSUE TITLE
Re-run fusion filtering module after fusion results from PNOC merged

### ISSUE THREAD

**Issue by runjin326** [PediatricOpenTargets/ticket-tracker#316]
#### What data file(s) does this issue pertain to?
fusion-putative-oncogenic.tsv

#### What release are you using?

v11

#### Put your question or report your issue here.
Re-run fusion filtering module after PNOC fusion results merged.

**Comment by jharenza** [comment]
Closed with https://github.com/PediatricOpenTargets/OpenPedCan-analysis/pull/188
