### ISSUE TITLE
Create weekly QC for `histologies.tsv`

### ISSUE THREAD

**Issue by jharenza** [PediatricOpenTargets/ticket-tracker#317]
#### What data file(s) does this issue pertain to?
`histologies.tsv`

#### Put your question or report your issue here.
Implement https://github.com/d3b-center/D3b-codes/tree/master/weekly_qc (https://github.com/d3b-center/D3b-codes/blob/master/weekly_qc/01-QC_histology.Rmd) for `histologies-base.tsv`

### Who will do this?
@HuangXiaoyan0106
@yuankunzhu 

cc @aadamk

**Comment by jharenza** [comment]
@HuangXiaoyan0106 for your next weekly QC, can you grab the v11 `histologies-base.tsv` for the file against which you will compare? Thanks!

**Comment by HuangXiaoyan0106** [comment]
> @HuangXiaoyan0106 for your next weekly QC, can you grab the v11 `histologies-base.tsv` for the file against which you will compare? Thanks!

@jharenza Weekly QC has been done, but I ran the script manually with  v11 `histologies-base.tsv`, and the results have been uploaded.
- s3://d3b-bix-data-merge-release/histology-weekly-qc-report/2022-0711_tmp_combined_inconsistent_files.xlsx
- s3://d3b-bix-data-merge-release/histology-weekly-qc-report/2022-0711_tmp_combined_changes_file.xlsx

**Comment by chinwallaa** [comment]
@ewafula check to see if you also have access to this s3 bucket -  v12 base histology file

**Comment by chinwallaa** [comment]
Create meeting for Nick/Eric/JoLynne/Asif/AdamK to review histologies and d3b warehouse.

**Comment by chinwallaa** [comment]
looking to streamline the histology workflows.  Decision to put in PRs directly in the histology repository.  Will modify the GTEx file to modify subgroups, and remove that code from downstream modules.  Creating tables for mapping broad, short histologies to path dx, within the d3b wareshouse.  (TBD- who maintains this - to discuss in the next toolkit meeting).
