### ISSUE TITLE
Update ploidy for female Y chr >0 calls

### ISSUE THREAD

**Issue by jharenza** [PediatricOpenTargets/ticket-tracker#318]
Per the below discussion, we should recode
```r
chrom == "chrY" & germline_sex_estimate == "Female" & copy.num > 0 ~ "unknown"
```

to
```r
chrom == "chrY" & germline_sex_estimate == "Female" & copy.num > 0 ~ NA
```

to enable gistic-like formatting for pedcbio

found this :  https://github.com/PediatricOpenTargets/OpenPedCan-analysis/blob/dev/analyses/focal-cn-file-preparation/01-add-ploidy-cnvkit.Rmd#L125

[    chrom == "chrY" & germline_sex_estimate == "Female" & copy.num > 0 ~ "unknown",](https://github.com/PediatricOpenTargets/OpenPedCan-analysis/blob/b430cbb2d7f50cc4d9f7675395e487b03c16834b/analyses/focal-cn-file-preparation/01-add-ploidy-cnvkit.Rmd#L125)

seems in the code , if is female , and has the Y copy numbers the status will be set to unknown...

_Originally posted by @zhangb1 in https://github.com/PediatricOpenTargets/ticket-tracker/issues/289#issuecomment-1116070741_

**Comment by jharenza** [comment]
@sangeetashukla can you make this quick update please

**Comment by sangeetashukla** [comment]
> @sangeetashukla can you make this quick update please

@jharenza Sure, I will work on this now.
