### ISSUE TITLE
Check `kf_visibility` for methylation

### ISSUE THREAD

**Issue by jharenza** [PediatricOpenTargets/ticket-tracker#319]
#### What data file(s) does this issue pertain to?
histologies-base.tsv

#### What release are you using?

`openpedcan_histologies_20220513.tsv`

#### Put your question or report your issue here.
Methylation has NA or FALSE in `kf_visibility`. I think they should either be NA or TRUE (but not sure if registered yet). Can you check on this @nicholasvk ?

**Comment by jharenza** [comment]
@youngnm - not sure if you or @chris-s-friedman can look into this? Are we keeping them hidden for a reason? We will be releasing these (with permission from Brian Rood and @adamcresnick, so should these be visible?)

**Comment by youngnm** [comment]
Yes all the methylation files are currently hidden. This was a requirement at the time of registration, but sounds like they can be unhidden. Let me confirm.

**Comment by jharenza** [comment]
Thanks!

**Comment by jharenza** [comment]
@youngnm following back up on this to close out the issue - have these been unhidden?

**Comment by youngnm** [comment]
Hi @jharenza , yes all the methylation data is now unhidden. Thanks for following up!
