### ISSUE TITLE
Some TCGA sample_barcodes are mapped to multiple sample_ids

### ISSUE THREAD

**Issue by logstar** [PediatricOpenTargets/ticket-tracker#32]
#### What data file(s) does this issue pertain to?

[tcga_mapping.txt](https://github.com/PediatricOpenTargets/ticket-tracker/files/6600354/tcga_mapping.txt) shared by @komalsrathi at <https://github.com/PediatricOpenTargets/ticket-tracker/issues/22#issuecomment-854901528>.

`gtex_target_tcga-gene-counts-rsem-expected_count-collapsed.rds` downloaded from v4 release.

#### What release are you using?

v4

#### Put your question or report your issue here.

In the tcga_mapping.txt, some TCGA `sample_barcode`s are mapped to multiple `sample_id`s, and some of their expected count sums are different in `gtex_target_tcga-gene-counts-rsem-expected_count-collapsed.rds`, as shown in the following table.

Are these duplicates will be resolved in the future releases? 

For now, I will only keep one of the samples that have the same `rsem_expected_cnt_colSum`s.

Regarding the context of this issue:

- The column names of `gtex_target_tcga-gene-counts-rsem-expected_count-collapsed.rds` are not listed in `histologies.tsv` for matching, as described at <https://github.com/PediatricOpenTargets/ticket-tracker/issues/22#issuecomment-854825044> and <https://github.com/PediatricOpenTargets/ticket-tracker/issues/31>.
- @komalsrathi shared mappings between the column names of `gtex_target_tcga-gene-counts-rsem-expected_count-collapsed.rds` and the `Kids_First_Biospecimen_ID` of `histologies.tsv`, as described at <https://github.com/PediatricOpenTargets/ticket-tracker/issues/22#issuecomment-854900493> and <https://github.com/PediatricOpenTargets/ticket-tracker/issues/22#issuecomment-854901528>.

| sample_barcode               | sample_id                            | rsem_expected_cnt_colSum |
|------------------------------|--------------------------------------|--------------------------|
| TCGA-37-4132-01A-01R-1100-07 | 44d729b9-be8f-4ae3-ae4d-b71c9d8463f4 | 59037096.86              |
| TCGA-37-4132-01A-01R-1100-07 | f3f5bd65-72fc-4cee-befb-2b6446be005e | 59037096.86              |
| TCGA-37-4133-01A-01R-1100-07 | 4f8ed570-458a-45c5-ad5c-c254812a4b40 | 63576672.73              |
| TCGA-37-4133-01A-01R-1100-07 | ecb95d43-cada-4159-aeca-197dccd8fcfd | 63576672.73              |
| TCGA-38-4625-01A-01R-1206-07 | 619f167f-d0c0-468f-b6d1-801bf6c0b017 | 82024039.49              |
| TCGA-38-4625-01A-01R-1206-07 | d73deb65-5df1-4fee-bcc6-56b301d77595 | 39274.99                 |
| TCGA-A2-A0EM-01A-11R-A034-07 | 2aaed860-0ed5-4c5e-9842-60aa13785b58 | 62357901.34              |
| TCGA-A2-A0EM-01A-11R-A034-07 | c90db6f3-03b4-4092-8efb-4925a423130d | 62357901.34              |
| TCGA-A6-2672-01B-03R-2302-07 | d32d94d4-0b92-4dc1-b3e9-750071f2d7e0 | 21980139.14              |
| TCGA-A6-2672-01B-03R-2302-07 | f489a86d-ab77-442c-a89d-ee734faf9caf | 23162032.49              |
| TCGA-A6-5661-01B-05R-2302-07 | 298bf211-99f7-44dd-802e-3f1aa3682681 | 7300714.54               |
| TCGA-A6-5661-01B-05R-2302-07 | bfb2cdbd-42f2-4784-9450-81236eb39c85 | 37621239.56              |
| TCGA-A6-5665-01B-03R-2302-07 | 373b0a02-88d2-49fb-8580-e9933a35c7b8 | 17227691.85              |
| TCGA-A6-5665-01B-03R-2302-07 | bdf3b4b3-1619-4ced-8e73-ebde54838291 | 29470181.82              |
| TCGA-A7-A0DC-01A-11R-A00Z-07 | 1b000b10-0b4c-4b56-bfb6-950889775865 | 108936872.87             |
| TCGA-A7-A0DC-01A-11R-A00Z-07 | 5748a77b-0ea0-487b-982f-ccc2f8bab563 | 72140078.13              |
| TCGA-A7-A0DC-01A-11R-A00Z-07 | 98a04bbb-0a89-4809-ad5b-9289a0cdf517 | 72140078.13              |
| TCGA-A7-A0DC-01B-04R-A22O-07 | 4b66df1d-9408-4e25-aaf7-2825809baa0c | 48575580.67              |
| TCGA-A7-A0DC-01B-04R-A22O-07 | b043709e-acfb-4034-838e-768c894f54dc | 31444946.25              |
| TCGA-A7-A0DC-01B-04R-A22O-07 | e59455b1-4bfa-45c2-be8a-1cd8f3a26c0e | 25507397.89              |
| TCGA-A7-A0DC-11A-41R-A089-07 | 9ba3e93f-6b7f-464b-9012-7e26592216d3 | 50908011.83              |
| TCGA-A7-A0DC-11A-41R-A089-07 | e90e4988-b2fb-4aa0-864e-84320abba5c0 | 50908011.83              |
| TCGA-A7-A13G-01A-11R-A13Q-07 | 8e41a6eb-590f-4c75-ba43-33883f6402bb | 80857822.17              |
| TCGA-A7-A13G-01A-11R-A13Q-07 | 9e8d6775-5f94-4a53-aed6-08a18b33a701 | 111945370.88             |
| TCGA-A7-A13G-01B-04R-A22O-07 | 5195e2af-0a23-40e3-a13c-69ea0b306287 | 27946848.41              |
| TCGA-A7-A13G-01B-04R-A22O-07 | 9612e42a-5464-4b48-b7df-819a791bf598 | 50825075.61              |
| TCGA-A7-A13G-01B-04R-A22O-07 | b80cbb60-df1a-4b4a-bf1b-0b1a04e64078 | 21767339.23              |
| TCGA-A7-A26F-01A-21R-A169-07 | 0aa1751e-1661-4b8b-9e5a-cc7edf6f8a8c | 98378280.28              |
| TCGA-A7-A26F-01A-21R-A169-07 | 3d2a9024-b722-4092-989e-bbc1d1332be9 | 125851647.25             |
| TCGA-A7-A26F-01B-04R-A22O-07 | 0c30f5b1-5ed5-48d1-b8df-df4611761dd3 | 52560800.24              |
| TCGA-A7-A26F-01B-04R-A22O-07 | 822d3bb2-b845-4073-a5fb-7ecf9e5c10a1 | 23021884.5               |
| TCGA-A7-A26F-01B-04R-A22O-07 | d7f11b34-6b38-4a7a-80b1-fae9b7243caf | 27747876.78              |
| TCGA-A7-A26I-01A-11R-A169-07 | 0752afb5-f92b-4a55-921c-2f36674e8689 | 82498866.41              |
| TCGA-A7-A26I-01A-11R-A169-07 | 2c8cb5e5-dd58-47f1-9d4e-bdf7559efc6e | 140091800.87             |
| TCGA-A7-A26I-01B-06R-A22O-07 | 373504b8-416a-4bae-9e62-ebf13d22a337 | 58832935.61              |
| TCGA-A7-A26I-01B-06R-A22O-07 | a965f4a8-076e-460e-91bb-f821711a63e5 | 11715966.18              |
| TCGA-A7-A26I-01B-06R-A22O-07 | f7e4051b-a5f1-4be0-b139-43e5ef75644e | 29322709.95              |
| TCGA-AC-A2QH-01A-11R-A18M-07 | 8fe05303-7df7-48a3-862c-e17b39a670c2 | 30632024.4               |
| TCGA-AC-A2QH-01A-11R-A18M-07 | b334f93f-48ff-434a-b6bc-8bc0920a5ce8 | 132806590.93             |
| TCGA-AC-A2QH-01B-04R-A22O-07 | 6c008c2f-bcc4-4497-962e-8e76879b3ecb | 55621677.64              |
| TCGA-AC-A2QH-01B-04R-A22O-07 | 75c3e5e4-ef05-467f-9e7e-d3003db187b1 | 35090851.18              |
| TCGA-AC-A2QH-01B-04R-A22O-07 | 7de0e920-e411-4994-a6d8-460cfcef9bdd | 22928152.09              |
| TCGA-AC-A3OD-01A-11R-A21T-07 | e9de5496-4486-4ceb-b3b3-30a53b2c52f6 | 105998355.69             |
| TCGA-AC-A3OD-01A-11R-A21T-07 | e9f7caba-a833-4c3c-82f2-11d7a233974d | 112332806.62             |
| TCGA-AC-A3OD-01B-06R-A22O-07 | 84a6ed5e-ad73-4399-ac37-381721f3b4e8 | 32717482.06              |
| TCGA-AC-A3OD-01B-06R-A22O-07 | 99ce385c-e0e2-41c2-a868-40a31eac1e50 | 49766248.16              |
| TCGA-AC-A3OD-01B-06R-A22O-07 | a03f6b87-d762-479a-9132-aa42563bacc4 | 90946986.92999999        |
| TCGA-AC-A3QQ-01A-11R-A22K-07 | 32911f1f-0202-4bb2-be86-4b68e5afcc00 | 125602035.27             |
| TCGA-AC-A3QQ-01A-11R-A22K-07 | 81d1e125-7e15-4563-87c0-b0bfa9dfcad7 | 52836757.19              |
| TCGA-AC-A3QQ-01B-06R-A22O-07 | 7af8074e-e82b-4e9e-a66c-3bb0097e1a5b | 30938541.95              |
| TCGA-AC-A3QQ-01B-06R-A22O-07 | 7d9d1e8c-710d-4b17-a3cd-8cd6208d3c08 | 13001988.01              |
| TCGA-AK-3425-01A-02R-1277-07 | 211b37ea-f8ba-4023-b622-15d3e2543505 | 38348466.47              |
| TCGA-AK-3425-01A-02R-1277-07 | 5f4cf18f-5c97-4ee9-adb4-6bc4658ed671 | 52358704                 |
| TCGA-AK-3426-01A-02R-1325-07 | 45b541d8-86f8-42b2-81a3-b41cefd02b87 | 62668358.35              |
| TCGA-AK-3426-01A-02R-1325-07 | a9ad735c-7c05-4efd-9922-3d25c4ec67c0 | 39301779.87              |
| TCGA-AK-3453-01A-02R-1277-07 | 440fa965-8e33-4c48-89e6-0b6518e01c44 | 92771830.38              |
| TCGA-AK-3453-01A-02R-1277-07 | d032ba59-d306-4a51-aa77-a9356bfefd09 | 34056834.22              |
| TCGA-AK-3454-01A-02R-1277-07 | 1b34fe44-0666-49a9-8074-27814eaa1bb6 | 84594722.51              |
| TCGA-AK-3454-01A-02R-1277-07 | 4c2fbb0c-1d39-4a36-919c-0f1574b17761 | 23568316.23              |
| TCGA-BH-A0B2-01A-11R-A10J-07 | 2daa45eb-0e9d-4b80-9baf-b3b145cc6a98 | 57136914.31              |
| TCGA-BH-A0B2-01A-11R-A10J-07 | 750199c0-a667-421a-a329-4521ccf45e01 | 57136914.31              |
| TCGA-BR-4255-01A-01R-1131-13 | 41f331b7-7730-4b05-adae-73271dbbd343 | 112032624.76             |
| TCGA-BR-4255-01A-01R-1131-13 | e114a9c9-10c6-48d2-ba51-f54be6b7b082 | 65833358.38              |
| TCGA-HC-7740-01B-04R-2302-07 | 1ebeb668-2997-4955-9577-1d968df6b51c | 33871400.01              |
| TCGA-HC-7740-01B-04R-2302-07 | 758a6e7b-6799-4958-b68c-7bf886ed4876 | 29568416.89              |
| TCGA-HC-8258-01B-05R-2302-07 | 05bba2ee-831f-4b65-9f52-5e5e7749b732 | 24161119.78              |
| TCGA-HC-8258-01B-05R-2302-07 | d65b7aef-64bd-45f1-8537-03251ad412c1 | 15709507.87              |
| TCGA-HC-8261-01B-05R-2302-07 | 547de96d-9fdd-4cd6-a1e0-3dd2fc244cdf | 101590414.04             |
| TCGA-HC-8261-01B-05R-2302-07 | 9715ca16-390b-4164-a9f3-6212371b2aea | 28499930.63              |
| TCGA-HC-8265-01B-04R-2302-07 | 2b0e3e79-3fdd-4e31-b872-fbd0c2023e74 | 22130941.26              |
| TCGA-HC-8265-01B-04R-2302-07 | c7b4ecf6-1c8c-4719-bee3-c7221f9544e5 | 39724297.01              |

**Comment by ewafula** [comment]
@logstar, attached is the data manifest for TCGA RNA-Seq data that @chinwallaa and pulled from GDC. The `sample_ids` don't match yours in `gtex_target_tcga-gene-counts-rsem-expected_count-collapsed.rds`.  A `sample_barcode` should have one corresponding `sample_id`.  You have multiple. 
[gdc_tcga_rnaseq_metadata.tsv.gz](https://github.com/PediatricOpenTargets/ticket-tracker/files/6624376/gdc_tcga_rnaseq_metadata.tsv.gz)

**Comment by logstar** [comment]
> @logstar, attached is the data manifest for TCGA RNA-Seq data that @chinwallaa and pulled from GDC. The `sample_ids` don't match yours in `gtex_target_tcga-gene-counts-rsem-expected_count-collapsed.rds`. A `sample_barcode` should have one corresponding `sample_id`. You have multiple.
> [gdc_tcga_rnaseq_metadata.tsv.gz](https://github.com/PediatricOpenTargets/ticket-tracker/files/6624376/gdc_tcga_rnaseq_metadata.tsv.gz)

@ewafula Thank you for the note and data manifest. It is good to know that a `sample_barcode` should have one corresponding `sample_id`.

I do not know why the `sample_id`s do not match, because I do not know how `gtex_target_tcga-gene-counts-rsem-expected_count-collapsed.rds` and `sample_barcode`-`sample_id` mapping files are generated. However, it would be helpful figure out why the `sample_id`s do not match the data manifest, and why some `sample_barcode`s have multiple corresponding `sample_id`s in the mapping file.

It would also be helpful to resolve these issues in the future data releases.

**Comment by kgaonkar6** [comment]
Should this be closed since TCGA samples are not part of v5 RSEM files `gene-counts-rsem-expected_count-collapsed.rds` and `gene-expression-rsem-tpm-collapsed.rds`

**Comment by jharenza** [comment]
we can close, but open a new one to add TCGA samples processed via GDC? can confirm with @taylordm today at 3 which processed data we should use
