### ISSUE TITLE
Updated analysis: focal cn prep

### ISSUE THREAD

**Issue by jharenza** [PediatricOpenTargets/ticket-tracker#320]
#### What analysis module should be updated and why?
https://github.com/PediatricOpenTargets/OpenPedCan-analysis/tree/dev/analyses/focal-cn-file-preparation

This module has two run scripts, but we should only maintain one. I _think_ what we want to use is [run-prepare-cn-OpenTarget.sh](https://github.com/PediatricOpenTargets/OpenPedCan-analysis/blob/dev/analyses/focal-cn-file-preparation/run-prepare-cn-OpenTarget.sh), but it is not listed in the README as what we want to use.

Additionally, upon running this script, it crashes at after 02 when searching for the gencode 38 file, which was why the run script was updated.

```bash
Output created: 02-add-ploidy-consensus.nb.html
Parsed with column specification:
cols(
  Kids_First_Biospecimen_ID = col_character(),
  chrom = col_character(),
  loc.start = col_double(),
  loc.end = col_double(),
  num.mark = col_logical(),
  seg.mean = col_double(),
  copy.num = col_double(),
  tumor_ploidy = col_double(),
  status = col_character()
)
Parsed with column specification:
cols(
  .default = col_character(),
  OS_days = col_double(),
  age_last_update_days = col_double(),
  normal_fraction = col_double(),
  tumor_fraction = col_double(),
  tumor_ploidy = col_double()
)
See spec(...) for full column specifications.
Error in open.connection(con, open) : cannot open the connection
Calls: <Anonymous> ... connection -> connectionForResource -> open -> open.connection
In addition: Warning message:
In open.connection(con, open) :
  cannot open compressed file '../../data/gencode.v38.primary_assembly.annotation.gtf.gz', probable reason 'No such file or directory'
```

This file should be added to the data release folder.

#### What changes need to be made? Please provide enough detail for another participant to make the update.
1. Update the module to only use one run script (rename run-prepare-cn-OpenTarget.sh to `run-prepare-cn.sh` and delete `run-prepare-cn-OpenTarget.sh`)
2. gencode.v38.primary_assembly.annotation.gtf.gz needs to be added to the data release script (is listed for the v11 release [here](https://github.com/PediatricOpenTargets/ticket-tracker/issues/239)), but without it, this module will not run. NOTE: this should be coded to be downloaded and not placed within the release folder due to size. See gencode 27 within the download data script.
So, immediately fix this module, we can add a download gencode 38 step into `run-prepare-cn.sh` similar to

https://github.com/PediatricOpenTargets/OpenPedCan-analysis/blob/aa6e28fc1806655c37071b9fad12cb5c2a95bdea/download-data.sh#L49-L56

That will unblock this for now, allow @zhangb1 to pull changes to the toolkit, and create the new files. Once they are created, and once #239 is done, we can update this to use the gencode file from the `/data` folder.

3. Update README

#### What input data should be used? Which data were used in the version being updated?
See above

#### When do you expect the revised analysis will be completed?
1-2 days

#### Who will complete the updated analysis?
@sangeetashukla

**Comment by jharenza** [comment]
@zhangb1 wanted to alert you to this, which will affect your downstream CNV toolkit analyses

**Comment by sangeetashukla** [comment]
This issue can be closed, since the relevant PR is closed.
Note: the PR branch was merged in a parent branch which was approved.

**Comment by jharenza** [comment]
closed with https://github.com/PediatricOpenTargets/OpenPedCan-analysis/pull/188
