### ISSUE TITLE
Updated analysis: immune-deconv to include quanTIseq

### ISSUE THREAD

**Issue by jharenza** [PediatricOpenTargets/ticket-tracker#321]
#### What analysis module should be updated and why?
https://github.com/PediatricOpenTargets/OpenPedCan-analysis/tree/dev/analyses/immune-deconv

Add quanTIseq to this module

#### What changes need to be made? Please provide enough detail for another participant to make the update.
- Sync changes from https://github.com/AlexsLemonade/OpenPBTA-analysis/tree/master/analyses/immune-deconv to this module, to include quanTIseq
- Remove separated stranded/polyA rna-seq inputs to use the one rnaseq input below.
- At this time, plots do not need to come over to this repo.
- For this PR, we can remove GTEX from the expression file and perform only on ped tumors.

#### What input data should be used? Which data were used in the version being updated?
`gene-expression-rsem-tpm-collapsed.rds`

#### When do you expect the revised analysis will be completed?
1-1.5 week

#### Who will complete the updated analysis?
@kelseykeith can you take this?

**Comment by kelseykeith** [comment]
Should CIBERSORT stay as an option or be removed? @jharenza

**Comment by jharenza** [comment]
We can remove, thanks. Just xcell and quanTIseq

**Comment by jharenza** [comment]
completed with https://github.com/PediatricOpenTargets/OpenPedCan-analysis/pull/224
