### ISSUE TITLE
OPC Processing Mulligan 2016 Hematopoetic Malignancy Data

### ISSUE THREAD

**Issue by taylordm** [PediatricOpenTargets/ticket-tracker#327]
#### What data file(s) does this issue pertain to?
 Kids First: Familial Predisposition to Hematopoietic Malignancies (SJFAMILY-HM) 
KF: Mulligan 2016 
phs001738/GRU

Somatic variants (no RNA-seq)

#### What release are you using?

v11

#### Put your question or report your issue here.
Need to process this X01 dataset through OpenPedCan

**Comment by jharenza** [comment]
@zhangb1 @bmennis or @HuangXiaoyan0106 can you get me a count of samples and participants per experimental strategy for these?

**Comment by bmennis** [comment]
Ok so from the Mulligan delivery project https://cavatica.sbgenomics.com/u/kids-first-drc/sd-w0v965xz/files/ there are:
2 RNAseq aligned read samples
368 WGS aligned read samples
2 WXS aligned read samples

**Comment by jharenza** [comment]
> Ok so from the Mulligan delivery project https://cavatica.sbgenomics.com/u/kids-first-drc/sd-w0v965xz/files/ there are:
> 
> 2 RNAseq aligned read samples
> 
> 368 WGS aligned read samples
> 
> 2 WXS aligned read samples

@chinwallaa @taylordm ^
