### ISSUE TITLE
OPC Processing Schiffman 2016 Ewing Sarcoma Data

### ISSUE THREAD

**Issue by taylordm** [PediatricOpenTargets/ticket-tracker#328]
#### What data file(s) does this issue pertain to?
KF: Kids First Pediatric Research Program in Susceptibility to Ewing Sarcoma Based on Germline Risk and Familial History of Cancer
Schiffman 2015
dbgap phs001228/GRU

#### What release are you using?

v11

#### Put your question or report your issue here.

Analysis on RNA-seq, somatic calls.

**Comment by jharenza** [comment]
@zhangb1 @bmennis or @HuangXiaoyan0106 can you get me a count of samples and participants per experimental strategy for these?

**Comment by bmennis** [comment]
From the delivery project https://cavatica.sbgenomics.com/u/kids-first-drc/sd-ygva0e1c/files/#q it looks like there are:
1082 WGS aligned reads samples

**Comment by jharenza** [comment]
> From the delivery project https://cavatica.sbgenomics.com/u/kids-first-drc/sd-ygva0e1c/files/#q it looks like there are:
> 
> 1082 WGS aligned reads samples

@chinwallaa @taylordm ^
