### ISSUE TITLE
OPC Processing Onel 2015 Osteosarcoma 

### ISSUE THREAD

**Issue by taylordm** [PediatricOpenTargets/ticket-tracker#329]
#### What data file(s) does this issue pertain to?

Kids First: Genomic Analysis of Treatment Failure in Pediatric Osteosarcoma
KF: Onel 2015
dbGAP phs001714/GRU

#### Put your question or report your issue here.
RNA-seq, and somatic calls.

**Comment by jharenza** [comment]
@zhangb1 @bmennis or @HuangXiaoyan0106 can you get me a count of samples and participants per experimental strategy for these?

**Comment by bmennis** [comment]
From the delivery project https://cavatica.sbgenomics.com/u/kids-first-drc/sd-zxjffmef/files/#q there are:
126 WGS aligned reads samples
185 WXS aligned reads samples

**Comment by jharenza** [comment]
> From the delivery project https://cavatica.sbgenomics.com/u/kids-first-drc/sd-zxjffmef/files/#q there are:
> 
> 126 WGS aligned reads samples
> 
> 185 WXS aligned reads samples

@taylordm @chinwallaa ^

Thank you @bmennis
