### ISSUE TITLE
GTEX IDs in histologies file don’t match mapping manifest

### ISSUE THREAD

**Issue by jharenza** [PediatricOpenTargets/ticket-tracker#33]
#### What data file(s) does this issue pertain to?
histologies.tsv

#### What release are you using?

V4

#### Put your question or report your issue here.
The sample barcodes in the mapping file for gtex from @komalsrathi do not match any Kids_First_Biospecimen_IDs in the histologies file. 

After slack discussion with @ewafula, it seems like there is an additional tissue-specific mapping file which has IDs which map to the v8 counts data from gtex, but TBD whether these IDs will match our initial 7k.

The histologies file will have to be updated.

**Comment by ewafula** [comment]
I have updated `histologies.tsv` with the correct 17,382 RNA_Seq GTEx v8 sample barcodes. Of 7,863 sample barcodes in @komalsrathi  mapping file (`gtex_mapping.txt`), 7,123 match the GTEx v8. All the 499 sample barcodes in `GTEx_v8_Cerebellum_AdrenalGland.manifest` from @jharenza also match the updated `histologies.tsv` attached. 
[histologies.tsv.zip](https://github.com/PediatricOpenTargets/ticket-tracker/files/6619595/histologies.tsv.zip)

**Comment by jharenza** [comment]
thank you @ewafula! cc @yuankunzhu @allisonheath @taylordm

**Comment by kgaonkar6** [comment]
Hi @ewafula I am subsetting the gtex rsem file to only keep samples that are in histologies.tsv above. Just wanted to confirm if I should only be using the gtex_mapping.txt file to find the matches between the sample_barcode and Kids_First_Biospecimen_ID in the histologies.tsv or will I also need to use `GTEx_v8_Cerebellum_AdrenalGland.manifest`? Could you share  the file `GTEx_v8_Cerebellum_AdrenalGland.manifest` here?

**Comment by jharenza** [comment]
That manifest is 499 samples we have already processed, which should be included in the v8 17,382 GTEX samples above. Here is that manifest: https://drive.google.com/file/d/1LpPFeELjO46j_XrNWZhovVZGbhJnjnvk/view

**Comment by kgaonkar6** [comment]
cool, thank you!

**Comment by ewafula** [comment]
@kgaonkar6 , the 499 samples in `GTEx_v8_Cerebellum_AdrenalGland.manifest` that @jharenza has shared are in the `histologies.txt`. Of 7863 in `gtex_mapping.txt`, 7123 are also in the `histologies.txt`. But there are ~10K in `histologies.txt` from GTEx v8 that are not in the `gtex_mapping.txt`.

**Comment by kgaonkar6** [comment]
Closing since the Toil file was not used, it was all GTEx v8 and 17,382 samples overlap the histology and the RSEM files now.
