### ISSUE TITLE
Update DGD cohort in `histologies-base-adapt.tsv`

### ISSUE THREAD

**Issue by jharenza** [PediatricOpenTargets/ticket-tracker#331]
#### What data file(s) does this issue pertain to?
`histologies-base-adapt.tsv`

#### What release are you using?

20220523

#### Put your question or report your issue here.
For all DGD samples, please make cohort == DGD, even if there are other samples for these patients sequenced through CBTN. This will allow us to keep the cohorts separate based on the sequencing.

**Comment by nicholasvk** [comment]
CBTN DGD samples have been flagged as part of DGD cohort in production.
