### ISSUE TITLE
Some Kids_First_Biospecimen_ID in histologies.tsv are duplicated

### ISSUE THREAD

**Issue by logstar** [PediatricOpenTargets/ticket-tracker#34]
#### What data file(s) does this issue pertain to?

`histologies.tsv`

#### What release are you using?

v4

#### Put your question or report your issue here.

The following `Kids_First_Biospecimen_ID` in `histologies.tsv` are duplicated. It seems that some duplicates are identical, and some have `RNA_library` column values.

Are the duplicates going to be removed in the future data releases?

For now, I only keep the first one of the duplicated `Kids_First_Biospecimen_ID`s when creating analysis modules.

|Kids_First_Biospecimen_ID|sample_id|aliquot_id|Kids_First_Participant_ID|experimental_strategy|sample_type|composition|tumor_descriptor|primary_site|age_bracket|reported_gender|race|ethnicity|diagnosis_type|diagnosis_category|age_at_diagnosis_days|pathology_diagnosis|RNA_library|EFS_days|OS_days|OS_status|PFS_days|cohort|age_last_update_days|seq_center|parent_aliquot_id|previous_parent_aliquot_id|cancer_predispositions|previous_cancer_predispositions|pathology_free_text_diagnosis|cohort_participant_id|germline_sex_estimate|extent_of_tumor_resection|normal_fraction|tumor_fraction|tumor_ploidy|CNS_region|molecular_subtype|integrated_diagnosis|Notes|harmonized_diagnosis|broad_histology|short_histology|cancer_group|gtex_group|gtex_subgroup|
|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|
|TARGET-20-PACDZR-09A-02R|03|02|PACDZR|RNA-Seq|Tumor|Bone Marrow|Primary tumor|NA|NA|Female|White|Not Hispanic or Latino|Clinical|Cancer|1661|Acute Myeloid Leukemia (AML)|poly-A stranded|NA|455|DECEASED|NA|TARGET|NA|British Columbia Cancer Agency (BCCA)|NA|NA|NA|NA|NA|TARGET-20-PACDZR|NA|NA|NA|NA|NA|NA|NA|NA|NA|Acute Myeloid Leukemia|Acute Myeloid Leukemia|AML|NA|NA|NA|
|TARGET-20-PACDZR-09A-02R|03|02|PACDZR|RNA-Seq|Tumor|Bone Marrow|Primary tumor|NA|NA|Female|White|Not Hispanic or Latino|Clinical|Cancer|1661|Acute Myeloid Leukemia (AML)|NA|NA|455|DECEASED|NA|TARGET|NA|HudsonAlpha Institute for Biotechnology (HAIB)|NA|NA|NA|NA|NA|TARGET-20-PACDZR|NA|NA|NA|NA|NA|NA|NA|NA|NA|Acute Myeloid Leukemia|Acute Myeloid Leukemia|AML|NA|NA|NA|
|TARGET-20-PADDXZ-03A-02R|03|02|PADDXZ|RNA-Seq|Tumor|Peripheral Whole Blood|Primary tumor|NA|NA|Male|Black or African American|Not Hispanic or Latino|Clinical|Cancer|4861|Acute Myeloid Leukemia (AML)|poly-A stranded|NA|752|LIVING|NA|TARGET|NA|British Columbia Cancer Agency (BCCA)|NA|NA|NA|NA|RUNX1-RUNX1T1|TARGET-20-PADDXZ|NA|NA|NA|NA|NA|NA|NA|NA|NA|Acute Myeloid Leukemia|Acute Myeloid Leukemia|AML|NA|NA|NA|
|TARGET-20-PADDXZ-03A-02R|03|02|PADDXZ|RNA-Seq|Tumor|Peripheral Whole Blood|Primary tumor|NA|NA|Male|Black or African American|Not Hispanic or Latino|Clinical|Cancer|4861|Acute Myeloid Leukemia (AML)|NA|NA|752|LIVING|NA|TARGET|NA|HudsonAlpha Institute for Biotechnology (HAIB)|NA|NA|NA|NA|RUNX1-RUNX1T1|TARGET-20-PADDXZ|NA|NA|NA|NA|NA|NA|NA|NA|NA|Acute Myeloid Leukemia|Acute Myeloid Leukemia|AML|NA|NA|NA|
|TARGET-20-PAPXUF-09A-01R|03|02|PAPXUF|RNA-Seq|Tumor|Bone Marrow|Primary tumor|NA|NA|Male|White|Not Hispanic or Latino|Clinical|Cancer|6436|Acute Myeloid Leukemia (AML)|poly-A stranded|NA|1070|LIVING|NA|TARGET|NA|British Columbia Cancer Agency (BCCA)|NA|NA|NA|NA|NUP98-NSD1|TARGET-20-PAPXUF|NA|NA|NA|NA|NA|NA|NA|NA|NA|Acute Myeloid Leukemia|Acute Myeloid Leukemia|AML|NA|NA|NA|
|TARGET-20-PAPXUF-09A-01R|03|02|PAPXUF|RNA-Seq|Tumor|Bone Marrow|Primary tumor|NA|NA|Male|White|Not Hispanic or Latino|Clinical|Cancer|6436|Acute Myeloid Leukemia (AML)|NA|NA|1070|LIVING|NA|TARGET|NA|HudsonAlpha Institute for Biotechnology (HAIB)|NA|NA|NA|NA|NUP98-NSD1|TARGET-20-PAPXUF|NA|NA|NA|NA|NA|NA|NA|NA|NA|Acute Myeloid Leukemia|Acute Myeloid Leukemia|AML|NA|NA|NA|
|TARGET-20-PARJYP-03A-01R|03|02|PARJYP|RNA-Seq|Tumor|Peripheral Whole Blood|Primary tumor|NA|NA|Female|Other|Not Hispanic or Latino|Clinical|Cancer|5433|Acute Myeloid Leukemia (AML)|poly-A stranded|NA|1798|LIVING|NA|TARGET|NA|British Columbia Cancer Agency (BCCA)|NA|NA|NA|NA|CBFB-MYH11|TARGET-20-PARJYP|NA|NA|NA|NA|NA|NA|NA|NA|NA|Acute Myeloid Leukemia|Acute Myeloid Leukemia|AML|NA|NA|NA|
|TARGET-20-PARJYP-03A-01R|03|02|PARJYP|RNA-Seq|Tumor|Peripheral Whole Blood|Primary tumor|NA|NA|Female|Other|Not Hispanic or Latino|Clinical|Cancer|5433|Acute Myeloid Leukemia (AML)|NA|NA|1798|LIVING|NA|TARGET|NA|HudsonAlpha Institute for Biotechnology (HAIB)|NA|NA|NA|NA|CBFB-MYH11|TARGET-20-PARJYP|NA|NA|NA|NA|NA|NA|NA|NA|NA|Acute Myeloid Leukemia|Acute Myeloid Leukemia|AML|NA|NA|NA|
|TARGET-20-PARXNG-09A-01R|03|02|PARXNG|RNA-Seq|Tumor|Bone Marrow|Primary tumor|NA|NA|Male|Black or African American|Not Hispanic or Latino|Clinical|Cancer|3687|Acute Myeloid Leukemia (AML)|poly-A stranded|NA|2246|LIVING|NA|TARGET|NA|British Columbia Cancer Agency (BCCA)|NA|NA|NA|NA|NA|TARGET-20-PARXNG|NA|NA|NA|NA|NA|NA|NA|NA|NA|Acute Myeloid Leukemia|Acute Myeloid Leukemia|AML|NA|NA|NA|
|TARGET-20-PARXNG-09A-01R|03|02|PARXNG|RNA-Seq|Tumor|Bone Marrow|Primary tumor|NA|NA|Male|Black or African American|Not Hispanic or Latino|Clinical|Cancer|3687|Acute Myeloid Leukemia (AML)|NA|NA|2246|LIVING|NA|TARGET|NA|HudsonAlpha Institute for Biotechnology (HAIB)|NA|NA|NA|NA|NA|TARGET-20-PARXNG|NA|NA|NA|NA|NA|NA|NA|NA|NA|Acute Myeloid Leukemia|Acute Myeloid Leukemia|AML|NA|NA|NA|
|TARGET-20-PASHBI-09A-01R|03|02|PASHBI|RNA-Seq|Tumor|Bone Marrow|Primary tumor|NA|NA|Male|White|Not Hispanic or Latino|Clinical|Cancer|5727|Acute Myeloid Leukemia (AML)|poly-A stranded|NA|1335|LIVING|NA|TARGET|NA|British Columbia Cancer Agency (BCCA)|NA|NA|NA|NA|RUNX1-RUNX1T1|TARGET-20-PASHBI|NA|NA|NA|NA|NA|NA|NA|NA|NA|Acute Myeloid Leukemia|Acute Myeloid Leukemia|AML|NA|NA|NA|
|TARGET-20-PASHBI-09A-01R|03|02|PASHBI|RNA-Seq|Tumor|Bone Marrow|Primary tumor|NA|NA|Male|White|Not Hispanic or Latino|Clinical|Cancer|5727|Acute Myeloid Leukemia (AML)|NA|NA|1335|LIVING|NA|TARGET|NA|HudsonAlpha Institute for Biotechnology (HAIB)|NA|NA|NA|NA|RUNX1-RUNX1T1|TARGET-20-PASHBI|NA|NA|NA|NA|NA|NA|NA|NA|NA|Acute Myeloid Leukemia|Acute Myeloid Leukemia|AML|NA|NA|NA|
|TARGET-20-PASRTP-09A-01R|03|02|PASRTP|RNA-Seq|Tumor|Bone Marrow|Primary tumor|NA|NA|Female|Other|Unknown|Clinical|Cancer|5389|Acute Myeloid Leukemia (AML)|poly-A stranded|NA|2047|LIVING|NA|TARGET|NA|British Columbia Cancer Agency (BCCA)|NA|NA|NA|NA|NA|TARGET-20-PASRTP|NA|NA|NA|NA|NA|NA|NA|NA|NA|Acute Myeloid Leukemia|Acute Myeloid Leukemia|AML|NA|NA|NA|
|TARGET-20-PASRTP-09A-01R|03|02|PASRTP|RNA-Seq|Tumor|Bone Marrow|Primary tumor|NA|NA|Female|Other|Unknown|Clinical|Cancer|5389|Acute Myeloid Leukemia (AML)|NA|NA|2047|LIVING|NA|TARGET|NA|HudsonAlpha Institute for Biotechnology (HAIB)|NA|NA|NA|NA|NA|TARGET-20-PASRTP|NA|NA|NA|NA|NA|NA|NA|NA|NA|Acute Myeloid Leukemia|Acute Myeloid Leukemia|AML|NA|NA|NA|
|TARGET-30-PANNMS-01A-01R|03|02|PANNMS|RNA-Seq|Tumor|Solid Tissue|Primary tumor|Retroperitoneum  Periadrenal tissue  Perinephric tissue  Peripancreatic tissue  Perirenal tissue  Retrocecal tissue  Retroperitoneal tissue|NA|Female|White|Not Hispanic or Latino|Clinical|Cancer|1080|Neuroblastoma (NBL)|poly-A|NA|4345|LIVING|NA|TARGET|NA|British Columbia Cancer Agency (BCCA)|NA|NA|NA|NA|MYCN non-amp|TARGET-30-PANNMS|NA|NA|NA|NA|NA|NA|MYCN non-amp|NA|NA|Neuroblastoma|Neuroblastoma|NBL|NA|NA|NA|
|TARGET-30-PANNMS-01A-01R|03|02|PANNMS|RNA-Seq|Tumor|Solid Tissue|Primary tumor|Retroperitoneum  Periadrenal tissue  Perinephric tissue  Peripancreatic tissue  Perirenal tissue  Retrocecal tissue  Retroperitoneal tissue|NA|Female|White|Not Hispanic or Latino|Clinical|Cancer|1080|Neuroblastoma (NBL)|poly-A|NA|4345|LIVING|NA|TARGET|NA|NCI Center for Cancer Research (KHAN)|NA|NA|NA|NA|MYCN non-amp|TARGET-30-PANNMS|NA|NA|NA|NA|NA|NA|MYCN non-amp|NA|NA|Neuroblastoma|Neuroblastoma|NBL|NA|NA|NA|
|TARGET-30-PANRRW-01A-01R|03|02|PANRRW|RNA-Seq|Tumor|Solid Tissue|Primary tumor|"Abdomen| NOS  Abdominal wall| NOS  Intra-abdominal site| NOS"|NA|Male|White|Not Hispanic or Latino|Clinical|Cancer|1730|Neuroblastoma (NBL)|poly-A|NA|2178|LIVING|NA|TARGET|NA|British Columbia Cancer Agency (BCCA)|NA|NA|NA|NA|MYCN non-amp|TARGET-30-PANRRW|NA|NA|NA|NA|NA|NA|MYCN non-amp|NA|NA|Neuroblastoma|Neuroblastoma|NBL|NA|NA|NA|
|TARGET-30-PANRRW-01A-01R|03|02|PANRRW|RNA-Seq|Tumor|Solid Tissue|Primary tumor|"Abdomen| NOS  Abdominal wall| NOS  Intra-abdominal site| NOS"|NA|Male|White|Not Hispanic or Latino|Clinical|Cancer|1730|Neuroblastoma (NBL)|poly-A|NA|2178|LIVING|NA|TARGET|NA|NCI Center for Cancer Research (KHAN)|NA|NA|NA|NA|MYCN non-amp|TARGET-30-PANRRW|NA|NA|NA|NA|NA|NA|MYCN non-amp|NA|NA|Neuroblastoma|Neuroblastoma|NBL|NA|NA|NA|
|TARGET-30-PANYGR-01A-01R|03|02|PANYGR|RNA-Seq|Tumor|Solid Tissue|Primary tumor|Overlapping lesion of retroperitoneum and peritoneum  (See note page 1)|NA|Male|Unknown|Not Hispanic or Latino|Clinical|Cancer|993|Neuroblastoma (NBL)|poly-A|NA|283|DECEASED|NA|TARGET|NA|British Columbia Cancer Agency (BCCA)|NA|NA|NA|NA|MYCN non-amp|TARGET-30-PANYGR|NA|NA|NA|NA|NA|NA|MYCN non-amp|NA|NA|Neuroblastoma|Neuroblastoma|NBL|NA|NA|NA|
|TARGET-30-PANYGR-01A-01R|03|02|PANYGR|RNA-Seq|Tumor|Solid Tissue|Primary tumor|Overlapping lesion of retroperitoneum and peritoneum  (See note page 1)|NA|Male|Unknown|Not Hispanic or Latino|Clinical|Cancer|993|Neuroblastoma (NBL)|poly-A|NA|283|DECEASED|NA|TARGET|NA|NCI Center for Cancer Research (KHAN)|NA|NA|NA|NA|MYCN non-amp|TARGET-30-PANYGR|NA|NA|NA|NA|NA|NA|MYCN non-amp|NA|NA|Neuroblastoma|Neuroblastoma|NBL|NA|NA|NA|
|TARGET-52-PAWFWK-01A-01R|03|02|PAWFWK|RNA-Seq|Tumor|Solid Tissue|Primary tumor|Kidney|NA|Male|White|Unknown|Clinical|Cancer|231|Kidney Rhabdoid Tumor (RT)|poly-A stranded|NA|992|LIVING|NA|TARGET|NA|British Columbia Cancer Agency (BCCA)|NA|NA|NA|NA|RT|TARGET-52-PAWFWK|NA|NA|NA|NA|NA|NA|NA|NA|NA|Kidney Rhabdoid Tumor|Kidney Rhabdoid Tumor|RT|NA|NA|NA|
|TARGET-52-PAWFWK-01A-01R|03|02|PAWFWK|RNA-Seq|Tumor|Solid Tissue|Primary tumor|Kidney|NA|Male|White|Unknown|Clinical|Cancer|231|Kidney Rhabdoid Tumor (RT)|poly-A stranded|NA|992|LIVING|NA|TARGET|NA|British Columbia Cancer Agency (BCCA)|NA|NA|NA|NA|RT|TARGET-52-PAWFWK|NA|NA|NA|NA|NA|NA|NA|NA|NA|Kidney Rhabdoid Tumor|Kidney Rhabdoid Tumor|RT|NA|NA|NA|
|TCGA-ZX-AA5X-01A-11R-A42T-07|01|11|AA5X|RNA-Seq|Tumor|Solid Tissue|Primary tumor|Cervix uteri|NA|Female|White|Not Hispanic or Latino|Clinical|Cancer|23440|"Squamous cell carcinoma| NOS"|poly-A|NA|119|LIVING|NA|TCGA|NA|University of North Carolina|NA|NA|NA|NA|NA|TCGA-ZX-AA5X|NA|NA|NA|NA|NA|NA|NA|NA|NA|Squamous cell carcinoma|Squamous cell carcinoma|CESC|NA|NA|NA|
|TCGA-ZX-AA5X-01A-11R-A42T-07|01|11|AA5X|RNA-Seq|Tumor|Solid Tissue|Primary tumor|Cervix uteri|NA|Female|White|Not Hispanic or Latino|Clinical|Cancer|23440|"Squamous cell carcinoma| NOS"|poly-A|NA|119|LIVING|NA|TCGA|NA|University of North Carolina|NA|NA|NA|NA|NA|TCGA-ZX-AA5X|NA|NA|NA|NA|NA|NA|NA|NA|NA|Squamous cell carcinoma|Squamous cell carcinoma|CESC|NA|NA|NA|

**Comment by jharenza** [comment]
Thanks for this issue! @ewafula @afarrel @chinwallaa - can you look into this?

**Comment by jharenza** [comment]
Also related #32

**Comment by ewafula** [comment]
@kgaonkar6 and @jharenza,  please wait a bit before you release v5. Need to address the issue with duplicated sample_ids raised by @logstar in the histologies.txt file. The five duplicates samples below are mostly because of additional samples  with "NA" in `library_type` column or different `seq_center`. Let  me work @afarrel first to determine the correct sample to keep from the TARGET manifest. 
```
TARGET-20-PACDZR-09A-02R
TARGET-30-PANNMS-01A-01R
TARGET-20-PARXNG-09A-01R
TARGET-30-PANRRW-01A-01R
TARGET-20-PADDXZ-03A-02R
TARGET-20-PARJYP-03A-01R
TARGET-20-PASHBI-09A-01R
TARGET-20-PASRTP-09A-01R
TARGET-52-PAWFWK-01A-01R
TARGET-20-PAPXUF-09A-01R
TARGET-30-PANYGR-01A-01R
```

**Comment by jharenza** [comment]
Thanks @ewafula - definitely! In the meantime, we can work on the gtex portion of the files since that seems remedied now.

**Comment by kgaonkar6** [comment]
Duplicate issue seems to be resolved to since the duplicates don't exist now or are deduplicated with "_1" and "_2" from Diskin  Lab naming convention.

We also didn't add any TARGET samples to v5 gene-expression-rsem-tpm-collapsed.rds and gene-counts-rsem-expected_count-collapsed.rds
