### ISSUE TITLE
check DGD remap path_dx and propagation to path_free_text code

### ISSUE THREAD

**Issue by jharenza** [PediatricOpenTargets/ticket-tracker#348]
#### What data file(s) does this issue pertain to?
histologies-base-adapt.tsv

#### What release are you using?

current, 2022-06-07

#### Put your question or report your issue here.
In the current base view, there are a lot of "Other" `pathology_diagnosis` for DGD, but no `pathology_free_text_diagnosis` values.

Can you re-pull the file from https://data-tracker.kidsfirstdrc.org/study/SD_MRK9CPZ9/documents/SF_77B8ZNHJ (fixes one typo) and when re-mapping these `pathology_diagnosis`, propagate/check the code for moving the old `pathology_diagnosis` to `pathology_free_text_diagnosis`.

**Comment by nicholasvk** [comment]
This should be resolved now.
