### ISSUE TITLE
some GTEX aliquot ids turned into scientific notation

### ISSUE THREAD

**Issue by jharenza** [PediatricOpenTargets/ticket-tracker#351]
#### What data file(s) does this issue pertain to?
histologies-base-adapt.tsv

#### What release are you using?

current, 2022-06-07

#### Put your question or report your issue here.
The following seem to have turned into scientific notation and the values are off by two :( 

Kids_First_Biospecimen_ID | sample_id | aliquot_id_latest | aliquot_id_previous
-- | -- | -- | --
GTEX-11ZVC-0226-SM-731E8 | 226 | 7.31E+10 | 7.31E+10
GTEX-13W3W-2826-SM-731E5 | 2826 | 7.31E+07 | 7.31E+07
GTEX-1A3MW-3226-SM-731E1 | 3226 | 7.31E+03 | 7.31E+03
GTEX-1AMFI-0926-SM-731E4 | 926 | 7.31E+06 | 7.31E+06
GTEX-1AX8Z-2526-SM-731E3 | 2526 | 7.31E+05 | 7.31E+05

**Comment by nicholasvk** [comment]
This should now be resolved with importing the latest versions of the histology files.
