### ISSUE TITLE
Updated analysis: independent sample list 

### ISSUE THREAD

**Issue by runjin326** [PediatricOpenTargets/ticket-tracker#352]
#### What analysis module should be updated and why?
`independent-samples`

#### What changes need to be made? Please provide enough detail for another participant to make the update.
For DGD data, both DNA and RNA have `experimental_strategy` of `Targeted sequencing`. We can use field `rna_library` to make the distinction. 
This module needs to be modified to take that into consideration.

#### What input data should be used? Which data were used in the version being updated?
`histologies.tsv` or `histologies-base.tsv`

#### When do you expect the revised analysis will be completed?
1-2 days

**Comment by runjin326** [comment]
@jharenza - as I was reviewing this, I had one question.

Currently, we define primary and secondary as following:
```
primary_descs <- c("Initial CNS Tumor", "Primary Tumor")
relapse_descs <- c("Recurrence", "Progressive", "Progressive Disease Post Mortem")
```
With the v11 update we have the following terms:
```
[1] "Initial CNS Tumor"               "Recurrence"                      "Progressive"                     "Second Malignancy"              
 [5] "Progressive Disease Post-Mortem" "Unavailable"                     "Recurrence;Second Malignancy"    "Primary Tumor"                  
 [9] NA                                "Metastatic Tumor"                "Metastatic"                      "Not Reported"             
```
So should I modify the code to the following?
```
primary_descs <- c("Initial CNS Tumor", "Primary Tumor")
relapse_descs <- c("Recurrence", "Progressive", "Progressive Disease Post-Mortem",
                    "Recurrence;Second Malignancy", "Second Malignancy",
                    "Metastatic Tumor", "Metastatic" )
```

**Comment by runjin326** [comment]
@jharenza - actually one more question. 
For this module, we have one step to only take primary tumor or bone marrow (exclude cell line or unknown composition). 
```
tumor_samples <- histology_df %>%
  dplyr::filter(sample_type == "Tumor", 
                composition == "Solid Tissue" | composition == "Bone Marrow", 
                experimental_strategy %in% c("WGS", "WXS", "Targeted Sequencing"))
```
However, for DGD samples, `composition` is either "Not Available" or "Not Reported". 
Now the question is: do we want to fix DGD in base histology or should we include DGD regardless of composition? For example, as the following:
```
# Get non DGD tumor samples: Note that there are some samples with unknown composition, but these will be ignored for now.
tumor_samples_non_dgd <- histology_df %>%
  dplyr::filter(sample_type == "Tumor", 
                composition == "Solid Tissue" | composition == "Bone Marrow", 
                experimental_strategy %in% c("WGS", "WXS", "Targeted Sequencing")) %>%
  dplyr::filter(cohort != "DGD")
# Get DGD tumor samples: allow unknown composition
tumor_samples_dgd <- histology_df %>%
  dplyr::filter(sample_type == "Tumor", 
                cohort == "DGD", 
                experimental_strategy %in% c("WGS", "WXS", "Targeted Sequencing")) %>%
  dplyr::filter(is.na(RNA_library))
# combine everything together
tumor_samples <- bind_rows(tumor_samples_non_dgd,
                           tumor_samples_dgd)
```

**Comment by jharenza** [comment]
>However, for DGD samples, composition is either "Not Available" or "Not Reported".
Now the question is: do we want to fix DGD in base histology or should we include DGD regardless of composition? For example, as the following:

We need Marilyn's team to fill this in - I had an email out, and based on her response, some can be marrow/blood for leukemias.. but I just don't know which. Can we just do an exclude of cell lines and not worry about other compositions? It may get complicated with all of the leukemias.

**Comment by jharenza** [comment]
> @jharenza - as I was reviewing this, I had one question.
> 
> Currently, we define primary and secondary as following:
> 
> ```
> primary_descs <- c("Initial CNS Tumor", "Primary Tumor")
> relapse_descs <- c("Recurrence", "Progressive", "Progressive Disease Post Mortem")
> ```
> 
> With the v11 update we have the following terms:
> 
> ```
> [1] "Initial CNS Tumor"               "Recurrence"                      "Progressive"                     "Second Malignancy"              
>  [5] "Progressive Disease Post-Mortem" "Unavailable"                     "Recurrence;Second Malignancy"    "Primary Tumor"                  
>  [9] NA                                "Metastatic Tumor"                "Metastatic"                      "Not Reported"             
> ```
> 
> So should I modify the code to the following?
> 
> ```
> primary_descs <- c("Initial CNS Tumor", "Primary Tumor")
> relapse_descs <- c("Recurrence", "Progressive", "Progressive Disease Post-Mortem",
>                     "Recurrence;Second Malignancy", "Second Malignancy",
>                     "Metastatic Tumor", "Metastatic" )
> ```

No modifications needed here. We want to keep relapse/progression separate of other malignancies.

**Comment by jharenza** [comment]
> @jharenza - actually one more question. For this module, we have one step to only take primary tumor or bone marrow (exclude cell line or unknown composition).
> 
> ```
> tumor_samples <- histology_df %>%
>   dplyr::filter(sample_type == "Tumor", 
>                 composition != "Derived Cell Line", 
>                 experimental_strategy %in% c("WGS", "WXS", "Targeted Sequencing"))
> ```
> 
> However, for DGD samples, `composition` is either "Not Available" or "Not Reported". Now the question is: do we want to fix DGD in base histology or should we include DGD regardless of composition? For example, as the following:
> 
> ```
> # Get non DGD tumor samples: Note that there are some samples with unknown composition, but these will be ignored for now.
> tumor_samples_non_dgd <- histology_df %>%
>   dplyr::filter(sample_type == "Tumor", 
>                 composition == "Solid Tissue" | composition == "Bone Marrow", 
>                 experimental_strategy %in% c("WGS", "WXS", "Targeted Sequencing")) %>%
>   dplyr::filter(cohort != "DGD")
> # Get DGD tumor samples: allow unknown composition
> tumor_samples_dgd <- histology_df %>%
>   dplyr::filter(sample_type == "Tumor", 
>                 cohort == "DGD", 
>                 experimental_strategy %in% c("WGS", "WXS", "Targeted Sequencing")) %>%
>   dplyr::filter(is.na(RNA_library))
> # combine everything together
> tumor_samples <- bind_rows(tumor_samples_non_dgd,
>                            tumor_samples_dgd)
> ```

Updated the code above for composition - cc @kelseykeith
