### ISSUE TITLE
Differences in samples in consensus cnv and seg status files

### ISSUE THREAD

**Issue by jharenza** [PediatricOpenTargets/ticket-tracker#354]
#### What data file(s) does this issue pertain to?

We have 2489 WGS/WXS bs_ids in `histologies-base.tsv`.

1. `consensus_wgs_plus_cnvkit_wxs_autosomes.tsv.gz` has 1951 samples while `cnv-cnvkit.seg.gz` and `cnv-controlfreec.tsv.gz` each have 2484 samples. 5 samples are missing from `cnv-cnvkit.seg.gz` and `cnv-controlfreec.tsv.gz`: 
```r
[1] "BS_18RH1034" "BS_AH3RVK53" "BS_JEZBA2EW" "BS_KQPCYZ2K" "BS_TN8CGS84" "BS_AMKQKHJ6"
```

2. For the 2484 samples we have run through consensus, was it expected that we lost 533 samples? This would have been due to having uncallable regions/too many breakpoints.  I see 313/533 in this previous run file:  https://github.com/PediatricOpenTargets/OpenPedCan-analysis/blob/dev/analyses/copy_number_consensus_call/results/uncalled_samples.tsv
It is surprising that these are only PBTA WGS. @zhangb1 do you have this output file for this run, and can you compare it to the 533 attached samples. If any of the 533 are not in the file, can you check why they are not in the consensus file?
[missing.csv](https://github.com/PediatricOpenTargets/ticket-tracker/files/8874058/missing.csv)

3. The combination of `consensus_seg_with_status.tsv` and `cnvkit_with_status.tsv` has 735 samples, but I think this should match what is in `consensus_wgs_plus_cnvkit_wxs_autosomes.tsv.gz`, which is 1951 samples. Can you check on this? 

4. There is one WXS sample `BS_AMKQKHJ6` missing from `cnv-cnvkit.seg.gz`.

#### What release are you using?

v11

#### Put your question or report your issue here.
I think it may be easier to just rerun the copy number consensus and focal cn prep modules now that we have the base-histologies.tsv file (there should be a way to set the param to use base histology and not the main histologies file. Can you rerun these two modules please?

**Comment by jharenza** [comment]
@zhangb1 can you checkout #239, rerun each module separately, then PR back the changes in two separate PRs?

**Comment by zhangb1** [comment]
Hi @jharenza , can you tell me which histologies-base.tsv did you use to check ? 

when I do the merge , I use the v10 histology file  s3://d3b-openaccess-us-east-1-prd-pbta/open-targets/v10/histologies.tsv

and merge only 008  additional samples... I don't find any of those 5 BS ids in the v10.  does it means we have other samples need to be merged to v11?

**Comment by zhangb1** [comment]
```
2022-06-10 09:51:01   36177150 cnv-cnvkit.seg.gz
2022-06-10 09:52:51   48469721 cnv-controlfreec.tsv.gz
2022-06-10 09:55:28  290451591 sv-manta.tsv.gz
```

Those 6 samples all added to the. CNVkit , control-freeC and mantaSV  . md5 also updated.

I am running the consensus calling now, may take a little bit time.

**Comment by jharenza** [comment]
Thanks @zhangb1 !

**Comment by zhangb1** [comment]
```
2021-10-19 13:45:51    1284428 cnv-consensus.seg.gz
2022-06-10 14:02:07    1080125 consensus_seg_with_status.tsv
2022-06-10 14:12:50  315809404 consensus_wgs_plus_cnvkit_wxs.tsv.gz
2022-06-10 14:16:29  299927882 consensus_wgs_plus_cnvkit_wxs_autosomes.tsv.gz
2022-06-10 14:16:57   16286550 consensus_wgs_plus_cnvkit_wxs_x_and_y.tsv.gz
```

consensus call results have been updated, also md5.

checking the consensus CNV results, all WXS total of 1184 samples are in the results... but for the WGS only 787 of 1305 are in the consensus results . 518 samples don't have the consensus CNV results. 

also check the `uncalled_samples.tsv` from copy_number_consensus_call,   they are 407 in the uncalled samples. .

I am not exactly sure why missing more samples ., from `consensus_seg_with_status.tsv` seems we still have 865 samples. but after `04-prepare-cn-file.R` , some samples got filtered . Maybe related to the gencode.v38 annotation.

**Comment by zhangb1** [comment]
Yes, please see the uncalled_samples.tsv file here 
[uncalled_samples.tsv.zip](https://github.com/PediatricOpenTargets/ticket-tracker/files/8881614/uncalled_samples.tsv.zip)

**Comment by chinwallaa** [comment]
@jharenza @zhangb1 just a clarifying question - when we filter for CNV with the consensus filter rules, is this filtering at the sample level, or does this filter for each CNV call/region ?

**Comment by jharenza** [comment]
Hi @chinwallaa - the module README can be found [here](https://github.com/PediatricOpenTargets/OpenPedCan-analysis/tree/dev/analyses/copy_number_consensus_call) - this is a consensus of algorithms per call per sample.
