### ISSUE TITLE
Create GATK CNV seg file for testing

### ISSUE THREAD

**Issue by jharenza** [PediatricOpenTargets/ticket-tracker#357]
### [Optional] What is the priority for the analysis? (Low, Medium, High)
Low-Medium

### [Optional] How long do you think this work will take?
1 week

### [Optional] Who will complete this work?
@zhangb1 @HuangXiaoyan0106 or @yuankunzhu 

### [Required] Provide details for analysis workflow(s).
Create a merged GATK seg file `cnv-gatk-seg.gz` or `cnv-gatk.tsv.gz` of PBTA and TARGET NBL samples to use as input for testing in #356

**Comment by jharenza** [comment]
cc @yuankunzhu @dmiller15

**Comment by dmiller15** [comment]
I'm not sure what this ticket is seeking, but below is a breakdown of the seg files generated by our GATK pipeline.

GATK produces four seg files:
- `modeled_segments_tumor`: modelFinal.seg files. These are tab-separated values (TSV) files with a SAM-style header containing a read group sample name, a sequence dictionary, a row specifying the column headers contained in         `[CONTIG, START, END,NUM_POINTS_COPY_RATIO, NUM_POINTS_ALLELE_FRACTION, LOG2_COPY_RATIO_POSTERIOR_10, LOG2_COPY_RATIO_POSTERIOR_50, LOG2_COPY_RATIO_POSTERIOR_90, MINOR_ALLELE_FRACTION_POSTERIOR_10, MINOR_ALLELE_FRACTION_POSTERIOR_50, MINOR_ALLELE_FRACTION_POSTERIOR_90]`, and the corresponding entry rows.
- `called_copy_ratio_segments_tumor`: Called copy-ratio-segments file. This is a tab-separated values (TSV) file with a SAM-style header containing a read group sample name, a sequence dictionary, a row specifying the column headers contained in `[CONTIG, START, END, NUM_POINTS_COPY_RATIO, MEAN_LOG2_COPY_RATIO, CALL]`, and the corresponding entry rows.
- `funcotated_called_file_tumor`: TSV where each row is a segment and the annotations are the covered genes and which genes+exon is overlapped by the segment breakpoints.
- `funcotated_called_gene_list_file_tumor`: TSV where each row is a gene and the annotations are the covered genes and which genes+exon is overlapped by the segment breakpoints.

At the moment our somatic pipeline returns `called_copy_ratio_segments_tumor` and both funcotated files. The funcotated file naming conventions differ slightly from the called seg file. Here's a breakdown of the changes:

| funcotated_called_file_tumor | called_copy_ratio_segments_tumor|
|-|-|
| Num_Probes | NUM_POINTS_COPY_RATIO |
| Segment_Mean | MEAN_LOG2_COPY_RATIO |
| Segment_Call | CALL |

**Comment by jharenza** [comment]
Closing this as completed.
