### ISSUE TITLE
Missing TIGIT fusion annotation entry

### ISSUE THREAD

**Issue by taylordm** [PediatricOpenTargets/ticket-tracker#359]
#### What data file(s) does this issue pertain to?
I'm going through the use cases to see what we can do for the advisory meeting, and on the TIGIT page under "Fusion" we get an odd '[] ' symbol annotation under  "Annotations" which JLR suggests we check out for  a leftover fusion annotator issue. 

#### What release are you using?

v10 (at the MTP portal)

#### Put your question or report your issue here.

![Screen Shot 2022-06-13 at 10 37 01 AM](https://user-images.githubusercontent.com/11062794/173381938-96729a82-9c13-4e8d-8aa6-bc19a633efa4.png)

**Comment by jharenza** [comment]
This is stemming from when a fusion has no annotation - it gets a  blank set of brackets`[]`.  Why it is not blank, who knows!

I will fix in [#195](https://github.com/PediatricOpenTargets/OpenPedCan-analysis/pull/195)

**Comment by jharenza** [comment]
Closed with https://github.com/PediatricOpenTargets/OpenPedCan-analysis/pull/188
