### ISSUE TITLE
gtex_target_tcga-gene-counts-rsem-tpm-collapsed.rds missing from release

### ISSUE THREAD

**Issue by jharenza** [PediatricOpenTargets/ticket-tracker#36]
#### What data file(s) does this issue pertain to?
gtex_target_tcga-gene-counts-rsem-tpm-collapsed.rds

#### What release are you using?

v4

#### Put your question or report your issue here.
We should add this for the z-scoring module in issue #6

**Comment by kgaonkar6** [comment]
Should we close this since the file is now in v5 with PBTA+KFNBL+GTEX named `gene-expression-rsem-tpm-collapsed.rds` ?

**Comment by jharenza** [comment]
yes
