### ISSUE TITLE
Updated analysis: TMB calculation (Friends of Cancer Research Criteria)

### ISSUE THREAD

**Issue by aadamk** [PediatricOpenTargets/ticket-tracker#360]
#### What analysis module should be updated and why?

TMB calculation to harmonize methodology across OpenPedCan and D3b patient clinical report analyses. 

#### What changes need to be made? Please provide enough detail for another participant to make the update.

Inclusion of Friends of Cancer Research criteria (code below). The example below operates on PASS variants from a Mutect2 MAF file as input (code below from @komalsrathi).
Note: Mutect2 was used for clinical trial reporting (in lieu of consensus) to ensure analytical consistency with TCGA at the time (for which Mutect2 was the only output available). 

```
  # Friends of Cancer Research Project cutoffs
  var_class = c('Missense_Mutation', 'Nonsense_Mutation',
                'Frame_Shift_Del', 'Frame_Shift_Ins', 
                'In_Frame_Del', 'In_Frame_Ins')
  vaf_cutoff = 0.05
  var_count = 3
  tumor_depth = 25
  
  # calculate the length of the bed file
  bed_length <- 0
  for (i in 1:nrow(tmb_bed_file)) {
    distance <- as.numeric(tmb_bed_file[i,3]) - as.numeric(tmb_bed_file[i,2])
    bed_length <- bed_length + distance
  }
  
  # read mutect2 for TMB profile
  mutect2_maf <- list.files(path = patient_dir, pattern = "mutect2", recursive = TRUE, full.names = T)
  mutect2_maf <- data.table::fread(mutect2_maf)
  
  # apply filters using Friends of Cancer Research Project Standards 
  mutect2_maf <- mutect2_maf %>%
    mutate(vaf = t_alt_count/(t_alt_count+t_ref_count)) %>%
    filter(Variant_Classification %in% var_class,
           t_depth >= tumor_depth,
           vaf >= vaf_cutoff,
           t_alt_count >= var_count) %>%
    dplyr::select(Hugo_Symbol, Variant_Classification, Chromosome, Start_Position, End_Position)
  
  # intersect with bed file
  subject <- with(tmb_bed_file, GRanges(chr, IRanges(start = start, end = end)))
  query <- with(mutect2_maf, GRanges(Chromosome, IRanges(start = Start_Position, end = End_Position, names = Hugo_Symbol)))
  res <- findOverlaps(query = query, subject = subject, type = "within")
  res <- data.frame(mutect2_maf[queryHits(res),], tmb_bed_file[subjectHits(res),])
  
  # number of missense+nonsense overlapping with the bed file
  TMB <- (nrow(res))*1000000/bed_length
```

#### What input data should be used? Which data were used in the version being updated?

snv-consensus-plus-hotspots.maf.tsv

**Comment by aadamk** [comment]
I included the above variant classes as FoCR used those variant types when they were able to successfully translate panel tmb values to wes tmb values via their calibration methods (so no active exclusion of the three variant types you mentioned). I wouldn’t oppose including the additional variant types particularly since they may contribute to the repertoire of immunogenic epitopes (with immunogenicity being a major intended correlate/readout of tmb). 

For Mutect2, we use an output file directly from that caller (as opposed to using mutect calls from consensus, which may underestimate tmb relative to using mutect directly).

I agree with running including the 3 variants + filters until there is a decision around harmonizing tcga variant data

**Comment by jharenza** [comment]
Ok, thanks so much @aadamk . @ewafula can you update the TMB module you are workring on today to include the filters above, if not already implemented?
```
  vaf_cutoff = 0.05
  var_count = 3
  tumor_depth = 25
```

**Comment by jharenza** [comment]
Closed with https://github.com/PediatricOpenTargets/OpenPedCan-analysis/pull/188
