### ISSUE TITLE
Updated analysis: update snv-frequencies for v11 data release

### ISSUE THREAD

**Issue by logstar** [PediatricOpenTargets/ticket-tracker#361]
#### What analysis module should be updated and why?

After [v11 data](https://github.com/PediatricOpenTargets/ticket-tracker/issues/239) are released, `snv-frequencies` module needs to be updated to generate the following files using v11 data:

- `analyses/snv-frequencies/results/gene-level-snv-consensus-annotated-mut-freq.jsonl.gz`
- `analyses/snv-frequencies/results/gene-level-snv-consensus-annotated-mut-freq.tsv.gz`
- `analyses/snv-frequencies/results/variant-level-snv-consensus-annotated-mut-freq.jsonl.gz`
- `analyses/snv-frequencies/results/variant-level-snv-consensus-annotated-mut-freq.tsv.gz`

These files will be used to update MTP for OpenPedCan-analysis v11 data release.

#### What changes need to be made? Please provide enough detail for another participant to make the update.

- Update `ped_opentargets_2021_pedcbio_case_set_ids.json` following [README.md](https://github.com/PediatricOpenTargets/OpenPedCan-analysis/blob/65ce650801a3428d38e6b21ddf78f426790dd3a6/analyses/snv-frequencies/README.md).
- Rerun `snv-frequencies` module.
- If any assertion fails, handle the failed assertion. The following assertion might fail:
  - <https://github.com/PediatricOpenTargets/OpenPedCan-analysis/blob/65ce650801a3428d38e6b21ddf78f426790dd3a6/analyses/snv-frequencies/01-snv-frequencies.R#L720-L724>. `Kids_First_Biospecimen_ID` column may have duplicated IDs in `histologies.tsv`, which can be handled by filtering `experimental_strategy` column.
- Resolve <https://github.com/PediatricOpenTargets/ticket-tracker/issues/293>.

@jharenza - I wonder if there is any [v11 data update](https://github.com/PediatricOpenTargets/OpenPedCan-analysis/blob/f31086cdfcc77ad75f079afb92ec55f7fb42e416/doc/release-notes.md) that may directly affect `snv-frequencies` computation procedures or results. For example, should v11 subtyping data be integrated in `snv-frequencies` results?

@chinwallaa - The assertions in module R scripts are used as QC steps for the corresponding input data. Therefore, the QC issue for `snv-frequencies` that you suggested will be tracked by this ticket as well.

#### What input data should be used? Which data were used in the version being updated?

Input data for `snv-frequencies` module.

v11 data release needs to be used.

#### When do you expect the revised analysis will be completed?

2 weeks

#### Who will complete the updated analysis?

cc @taylordm @ewafula

**Comment by jharenza** [comment]
>For example, should v11 subtyping data be integrated in snv-frequencies results?

Not at this time

>@jharenza - I wonder if there is any v11 data update that may directly affect snv-frequencies computation procedures or results.

V11 has Targeted Panel DGD cohort data, which will have to be accounted for in this table. We will not add Panel data to "All cohorts", and will only calculate frequencies per its own cohort.

**Comment by jharenza** [comment]
Note: updating the pedcbio links will require #374 to be completed, but integration of panel data can be started now.

**Comment by jharenza** [comment]
Hi @kelseykeith - today, we discussed that we forgot about TARGET cohort having Targeted Sequencing samples, so we should add those as a second panel cohort to only this table. 

Can you also please update these panel cohorts to "TARGET panel" and "CHOP P30 panel"? cc @afarrel

**Comment by kelseykeith** [comment]
Sure! Just want to double-check two things to make sure I'm on the same page:

1. Everything that is a panel should have as `experimental_strategy`, "Targeted Sequencing", right? 
2. And all the samples that have `cohort` as "DGD" are the CHOP P30 data correct?

**Comment by jharenza** [comment]
Correct!

**Comment by jharenza** [comment]
completed in https://github.com/PediatricOpenTargets/OpenPedCan-analysis/pull/243
