### ISSUE TITLE
Updated analysis: update cnv-frequencies for v11 data release

### ISSUE THREAD

**Issue by logstar** [PediatricOpenTargets/ticket-tracker#363]
#### What analysis module should be updated and why?

After [v11 data](https://github.com/PediatricOpenTargets/ticket-tracker/issues/239) is released, `cnv-frequencies` module needs to be updated to generate the following files using v11 data:

- `analyses/cnv-frequencies/results/gene-level-cnv-consensus-annotated-mut-freq.jsonl.gz`
- `analyses/cnv-frequencies/results/gene-level-cnv-consensus-annotated-mut-freq.tsv.gz`

The JSONL file will be used to update MTP for OpenPedCan-analysis v11 data release.

#### What changes need to be made? Please provide enough detail for another participant to make the update.

- Download v11 data.
- Rerun `cnv-frequencies` module.
- If any assertion fails, handle the failed assertion.
- Investigate whether v11 data may break certain assumptions in the frequency computation, as `cnv-frequencies` module does not have extensive assertions when computing frequencies. For example, if histology file has duplicated `Kids_First_Biospecimen_ID`s, would certain frequencies be incorrect?

@jharenza - I wonder if there is any v11 data specific changes that need to be made to the `cnv-frequencies` module.

#### What input data should be used? Which data were used in the version being updated?

Input data for `cnv-frequencies` module.

v11 data release needs to be used.

#### When do you expect the revised analysis will be completed?

2 weeks.

#### Who will complete the updated analysis?

cc @chinwallaa @taylordm @ewafula

**Comment by jharenza** [comment]
Note: You will have to replace the filenames for the `independent-specimen*` files to match those in V11 release.

**Comment by chinwallaa** [comment]
from JoLynn docker exec -ti container_name bash

**Comment by jharenza** [comment]
completed in https://github.com/PediatricOpenTargets/OpenPedCan-analysis/pull/231
