### ISSUE TITLE
Updated analysis: update `tumor-normal-differential-expression` for v12 data release

### ISSUE THREAD

**Issue by logstar** [PediatricOpenTargets/ticket-tracker#368]
#### What analysis module should be updated and why?

`tumor-normal-differential-expression` needs to be updated to generate results using v11 release data.

This issue is related to <https://github.com/PediatricOpenTargets/ticket-tracker/issues/367>. The PR for this issue should be based on changes in <https://github.com/PediatricOpenTargets/ticket-tracker/issues/367>.

#### What changes need to be made? Please provide enough detail for another participant to make the update.

Rerun `tumor-normal-differential-expression` module using v11 data. Share all result files via OpenPedCan-analysis s3 bucket.

#### What input data should be used? Which data were used in the version being updated?

Input data for tumor-normal-differential-expression.

v11 data release should be used.

#### When do you expect the revised analysis will be completed?

@sangeetashukla - I was wondering if you could estimate the time required for resolving this issue.

#### Who will complete the updated analysis?

cc @jharenza @afarrel @chinwallaa

**Comment by jharenza** [comment]
We can discuss this next week @zhangb1!

**Comment by jharenza** [comment]
This was completed by @sangeetashukla on the HPC
