### ISSUE TITLE
Check whether 2 BS IDs in DGD fusion have data 

### ISSUE THREAD

**Issue by runjin326** [PediatricOpenTargets/ticket-tracker#369]
#### What data file(s) does this issue pertain to?
`fusion-dgd.tsv.gz `

#### What release are you using?

v11

#### Put your question or report your issue here.
Please double check whether  samples `BS_WQN6CS9Q` and `BS_YKEK4YWT` actually have fusion information.

**Comment by jharenza** [comment]
@yuankunzhu who would have this information? These samples were in the fusion file blank.

**Comment by yuankunzhu** [comment]
assign this to the @zhangb1 to double check.

**Comment by zhangb1** [comment]
@jharenza @yuankunzhu 

I can find the fusion files in the s3 bucket:
```
s3://d3b-study-us-east-1-prd-sd-hkrzzhfw/pipeline_outputs/HISTORICAL_CANCER_PANELS_HG38/DGD190006752_FUSIP/fusions/BS_WQN6CS9Q.fusions.tsv
s3://d3b-study-us-east-1-prd-sd-hkrzzhfw/pipeline_outputs/HISTORICAL_CANCER_PANELS_HG38/DGD190006772_FUSIP/fusions/BS_YKEK4YWT.fusions.tsv
```

I downloaded the files , but seems there is error format in the files ... 
[fusion_check_2BS.zip](https://github.com/PediatricOpenTargets/ticket-tracker/files/9244531/fusion_check_2BS.zip)

the  first column is not the GeneID, I think there is the issue when DGD generate the fusion results for these two samples.

```
Hugo_Symbol     Entrez_Gene_Id  Center  Tumor_Sample_Barcode    Fusion  DNA_support     RNA_support     Method  Frame
DGD             CHOP-DGD        BS_YKEK4YWT     DGD-19-6772_COMPT       unknown yes
19              CHOP-DGD        BS_YKEK4YWT     DGD-19-6772_COMPT       unknown yes
DGD             CHOP-DGD        BS_YKEK4YWT     DGD-19-6772_COMPT       unknown yes
19              CHOP-DGD        BS_YKEK4YWT     DGD-19-6772_COMPT       unknown yes
```

**Comment by jharenza** [comment]
Yeah, we had @HuangXiaoyan0106 remove these samples from the DGD fusion file, so the question is really who at DGD can tell us if these samples really had fusions or if they do not/ can we get new files if they do and append them to the DGD fusion file?

**Comment by zhangb1** [comment]
I know is Mark before generated the files, but since he left, I don't know who should contact. @yuankunzhu  do you know who can we ask for?

**Comment by yuankunzhu** [comment]
emailed Kajia and Matt for this.

**Comment by luederm** [comment]
Feng looked into this and there was one reported fusion for DGD-19-6772: C11orf95-RELA

**Comment by jharenza** [comment]
Thanks, must be an ependymoma :)

**Comment by luederm** [comment]
For BS_WQN6CS9Q, there were no reported fusions

**Comment by jharenza** [comment]
Thank you!

**Comment by luederm** [comment]
No problem
