### ISSUE TITLE
Updated analysis: Independent sample list

### ISSUE THREAD

**Issue by jharenza** [PediatricOpenTargets/ticket-tracker#370]
#### What analysis module should be updated and why?
[independent-samples](https://github.com/PediatricOpenTargets/OpenPedCan-analysis/tree/dev/analyses/independent-samples)

#### What changes need to be made? Please provide enough detail for another participant to make the update.
1) DGD panel DNA samples need to be added to the DNA list, but as last preference when either WGS or WXS are available. Rename files to `independent-specimens.wgswxspanel.*.tsv`
2) DNA panel RNA samples need to be added to the RNA list, but as last preference when RNA-Seq is available. Rename files to `independent-specimens.rnaseqpanel.*.tsv`
3) A new `match_id` needs to be created to account for the non-unique `sample_id` in TARGET/GMKF/TCGA cohorts.
4) TCGA should be added to the RNA-Seq sample lists.
5) Methylation samples need to be added - probably make its own lists for primary, primary-plus, relapse? These should be matched on `sample_id` or `match_id` created.
6) Use samples with `composition != "Derived Cell Line"` instead of choosing N compositions.
7) Update tumor descriptors to match those in the independent samples module in this repo.

For reference, see discussions on this old PR: https://github.com/PediatricOpenTargets/OpenPedCan-analysis/pull/199

#### What input data should be used? Which data were used in the version being updated?
`histologies.tsv`

#### When do you expect the revised analysis will be completed?
this week

#### Who will complete the updated analysis?
@ewafula

**Comment by jharenza** [comment]
@logstar and @runjin326 - did I miss anything above?

**Comment by ewafula** [comment]
@jharenza, what differentiates the DGD panel `DNA` and `RNA` samples in the `histologies-base.tsv` and `histologies.tsv`?  Is it the `NAs` and `exome_capture` values in the `RNA_library` column? 
```
> read_tsv("histologies.tsv") %>% 
     select(experimental_strategy, RNA_library, cohort) %>% 
     distinct() %>% 
     arrange(cohort, experimental_strategy) %>% 
     print(n=25)
# A tibble: 21 x 3
   experimental_strategy RNA_library     cohort
   <chr>                 <chr>           <chr> 
 1 Targeted Sequencing   NA              DGD   
 2 Targeted Sequencing   exome_capture   DGD   
 3 RNA-Seq               stranded        GMKF  
 4 RNA-Seq               NA              GMKF  
 5 WGS                   NA              GMKF  
 6 RNA-Seq               poly-A          GTEx  
 7 Methylation           NA              PBTA  
 8 RNA-Seq               exome_capture   PBTA  
 9 RNA-Seq               stranded        PBTA  
10 RNA-Seq               poly-A          PBTA  
11 Targeted Sequencing   NA              PBTA  
12 WGS                   NA              PBTA  
13 WXS                   NA              PBTA  
14 Methylation           NA              TARGET
15 RNA-Seq               poly-A          TARGET
16 RNA-Seq               poly-A stranded TARGET
17 RNA-Seq               stranded        TARGET
18 Targeted Sequencing   NA              TARGET
19 WXS                   NA              TARGET
20 RNA-Seq               poly-A          TCGA  
21 RNA-Seq               stranded        TCGA  
>
```

**Comment by jharenza** [comment]
>Is it the NAs and exome_capture values in the RNA_library column? 

yes exactly

**Comment by jharenza** [comment]
Closed with https://github.com/PediatricOpenTargets/OpenPedCan-analysis/pull/188
