### ISSUE TITLE
Updated analysis: methylation summary module

### ISSUE THREAD

**Issue by ewafula** [PediatricOpenTargets/ticket-tracker#371]
#### What analysis module should be updated and why?
Update [methylation-summary](https://github.com/PediatricOpenTargets/OpenPedCan-analysis/tree/dev/analyses/methylation-summary) modules

#### What changes need to be made? Please provide enough detail for another participant to make the update.
- update the  module to utilize RNA-Seq and methyl  independent sample lists 
- update module to compute gene locus-isoforms in addition to gene locus for beta-tpm correlations 
- create separate gene-level and isoform-level methylation summary tables to reduce the file size 

#### What input data should be used? 
- `infinium-methylationepic-v-1-0-b5-manifest-file-csv.zip`
- `gencode.v39.primary_assembly.annotation.gtf.gz`
- `independent-specimens.rnaseqpanel.primary-plus.eachcohort.tsv`
- `independent-specimens.methyl.primary-plus.eachcohort.tsv`
- `gene-expression-rsem-tpm-collapsed.rds`
- `rna-isoform-expression-rsem-tpm.rds`
- `ensg-hugo-pmtl-mapping.tsv.tsv`
- `methyl-beta-values.rds` 
- `efo-mondo-map.tsv`
- `histologies.tsv`

#### When do you expect the revised analysis will be completed?
Before the v12 data release

#### Who will complete the updated analysis?
@ewafula

**Comment by chinwallaa** [comment]
is there a concern on the size of the raw and summary tables - only being used by the API and possibly by FNL for backend for MTP use.  May be too large to run on a local laptop, currently on Isilon and EC2? isoform table can be seperate table. (to enable gene w/ isoform plots).   This needs to be ported/migrated to a CAVATICA app when ready.
