### ISSUE TITLE
Check v10 JSONL PedCBioPortal URL responses

### ISSUE THREAD

**Issue by logstar** [PediatricOpenTargets/ticket-tracker#379]
#### What file(s) does this issue pertain to?

`analyses/snv-frequencies/results/gene-level-snv-consensus-annotated-mut-freq.jsonl.gz`

#### What release are you using?

v10 <https://github.com/PediatricOpenTargets/OpenPedCan-analysis/blob/1eedaf5825fc999415ff5fd712f98a6f17718b92/analyses/snv-frequencies/results/gene-level-snv-consensus-annotated-mut-freq.jsonl.gz>

#### Put your question or report your issue here.

v10 `analyses/snv-frequencies/results/gene-level-snv-consensus-annotated-mut-freq.jsonl.gz` is generated using v7 PedCBioPortal `ped_opentargets_2021` dataset `case_set_id`s.

PedCBioPortal `ped_opentargets_2021` dataset has been updated using v10 release data, <https://github.com/PediatricOpenTargets/ticket-tracker/issues/286>. However, v10 `analyses/snv-frequencies/results/gene-level-snv-consensus-annotated-mut-freq.jsonl.gz` has not been updated using v10 PedCBioPortal `ped_opentargets_2021` dataset `case_set_id`s, <https://github.com/PediatricOpenTargets/ticket-tracker/issues/230>, so there may be PedCBioPortal URLs not available.

This ticket intends to check if there is any PedCBioPortal URL in v10 `analyses/snv-frequencies/results/gene-level-snv-consensus-annotated-mut-freq.jsonl.gz` that is not working. If there is any, what is the fraction in all PedCBioPortal URLs.

cc @chinwallaa @taylordm @jharenza

**Comment by logstar** [comment]
Hi @chinwallaa @jharenza - All v10 JSONL PedCBioPortal URLs only have `case_set_id`s that are in v10 PedCBioPortal `ped_opentargets_2021` dataset, even though v7 PedCBioPortal `ped_opentargets_2021` dataset `case_set_id` list is used to generate v10 JSONL. This behavior is programmed with <https://github.com/PediatricOpenTargets/OpenPedCan-analysis/blob/1eedaf5825fc999415ff5fd712f98a6f17718b92/analyses/snv-frequencies/01-snv-frequencies.R#L396-L407>, where only `case_set_id`s constructed using histology `cancer_group` and `cohort` that are in the input `case_set_id` list will be used for adding pedcbio URLs.

However, it is not guaranteed that all v10 JSONL PedCBioPortal URLs are working exactly as expected, because they have not been checked directly via HTTP. Checking all v10 JSONL PedCBioPortal URLs via HTTP will require additional efforts to resolve technical difficulties related to web development. Furthermore, the content/plot of each PedCBioPortal URL also needs to be checked, to make sure the content/plot is consistent with MTP, which also requires additional efforts.

Attached are the code and comments for checking this issue, which have more details. As `.Rmd` and `.html` files canot be attached to GitHub comments, I added `.txt` after the original filenames.

- [check_v10_jsonl_pedcbio_url_response.html.txt](https://github.com/PediatricOpenTargets/ticket-tracker/files/9114349/check_v10_jsonl_pedcbio_url_response.html.txt)
- [check_v10_jsonl_pedcbio_url_response.Rmd.txt](https://github.com/PediatricOpenTargets/ticket-tracker/files/9114350/check_v10_jsonl_pedcbio_url_response.Rmd.txt)

Let me know if you have questions or suggestions.

cc @taylordm

**Comment by jharenza** [comment]
Note: regarding Invalid gene symbol URL: [https://pedcbioportal.kidsfirstdrc.org/results/oncoprint?cancer_study_list=ped_opentargets_2[…]lastoma&Action=Submit&gene_list=NOTEXISTINGGENESYMBOL](https://pedcbioportal.kidsfirstdrc.org/results/oncoprint?cancer_study_list=ped_opentargets_2021&case_set_id=ped_opentargets_2021_gmkf_neuroblastoma&Action=Submit&gene_list=NOTEXISTINGGENESYMBOL)

We will add this to a help file.
