### ISSUE TITLE
Proposed Analysis: Tumor vs Normal expression boxplots and tables

### ISSUE THREAD

**Issue by komalsrathi** [PediatricOpenTargets/ticket-tracker#38]
#### What are the scientific goals of the analysis?

For each of the 30k-40k genes, generate boxplots with y-axis representing log2(TPM + 1):

1. `cohort` + `cancer_group` level:
    A. Each tumor histology (`cohort` + `cancer_group`) + GTEx normal sub-groups (e.g. Brain Cerebellum) 
    B. All tumor histologies (`cohort` + `cancer_group`)

2. `cancer_group` level:
    A. Each tumor histology (`cancer_group`) + GTEx normal sub-groups (e.g. Brain Cerebellum) 
    B. All tumor histologies (`cancer_group`)

3. Add `n` to x-axis group labels
4. Table exports (.tsv) of the data per plot (Gene, Mean, SD)
5. File name should be: `studyID_gene_UUID`
5. Metadata file of plot file name and gene/analysis name for @taylordm to use in JSON files

#### What methods do you plan to use to accomplish the scientific goals?

R package ggplot2 and ggpubr for significance (if needed).

@jharenza can inform on any additional details, output format (.png/.pdf/.rds) and s3 location
`png` for plots and `tsv` for tables

#### What input data are required for this analysis?

Either combined or cohort specific TPM expression matrices in `.rds` format
Metadata file with at least sample (columns in expression matrices) and histology mapping 

s3 location of collapsed expression matrix `.rds`files: s3://kf-openaccess-us-east-1-prd-pbta/open-targets/v5/gene-expression-rsem-tpm-collapsed.rds
s3 location of metadata `.tsv` files: s3://kf-openaccess-us-east-1-prd-pbta/open-targets/v5/histologies.tsv

#### How long do you expect is needed to complete the analysis? Will it be a multi-step analysis?

Once files are received, about 3-4 days 

#### Who will complete the analysis (please add a GitHub handle here if relevant)?

@komalsrathi

**Comment by jharenza** [comment]
Thanks @komalsrathi for opening this! Instead of by cohort, we will do by cancer_group, which is a new column in the histologies file- this way, we combine all NBL, and have each brain tumor group more standardized.

**Comment by komalsrathi** [comment]
@jharenza thanks, I will edit the details in the ticket once I receive and go over the expression + metadata.

**Comment by jharenza** [comment]
@komalsrathi please combine `CBTN` and `PNOC` into one cohort, `PBTA` for this analysis

**Comment by jharenza** [comment]
@komalsrathi per our 8 am meeting, will also want a cancer_group level analysis here, but it will also require subsetting the samples per the independent-samples module which is being updated in #26

**Comment by komalsrathi** [comment]
@jharenza is this not same as 2)

**Comment by jharenza** [comment]
Actually for 2, I should clarify - we would just do boxplots for each gene across all (cohort+cancer_group) - no need for comparisons.

For `cancer_group` level, this would look like:
1A: boxplots for each gene in `cancer_group` vs GTEX subgroups
2A: boxplots for each gene across all `cancer_group` - no need for comparisons

For 1A and 2A, we would need to utilize independent-specimens because of overlaps with GMKF+TARGET NBL for ex

**Comment by komalsrathi** [comment]
@jharenza before I generate all the plots, I needed some info on the following:

1. Single-sample groups: Should we remove `n == 1`?
2. Plot colors: Do you want colors in the plot? If so, we can fill/color by `cohort` for `cohort_cancer_group_level` plots. However, for `cancer_group_level` plots, if we do color by `cohort`, it will show as dodged boxplot so we would need something else. 
3. Format of x-axis: Currently, I have set the angle at 90 and if you look at the mock up for `cohort_cancer_group_level` plot for `MT-CO3` between `PBTA` and `GTEx` below, it shows `{cohort}_{cancer_group}_{n}` as x-axis labels.
4. Filename: Do we really need additional UUIDs for the filenames? I am thinking a combination of the `{gene_name}_{cohorts of interest}_{analysis_type}` (analysis_type is either `cohort_cancer_group_level` or `cancer_group_level`) should suffice as a unique identifier. 

For e.g. with the current cohorts that we have, the filenames would be named something like this: gene name followed by tumor cohorts arranged alphabetically (for tumor-only plots) followed by GTEx (for tumor-normal plots) followed by analysis type:

- cohort + cancer_group 

`GMKF + PBTA`: {gene_name}_GMKF_PBTA_cohort_cancer_group_level)

- cohort + cancer_group + gtex_subgroup

`GMKF + GTEx`: {gene_name}_GMKF_GTEx_cohort_cancer_group_level
`PBTA + GTEx`: {gene_name}_PBTA_GTEx_cohort_cancer_group_level

- cancer_group: (only tumors)

`GMKF + PBTA`: {gene_name}_GMKF_PBTA_cancer_group_level

- cancer_group + gtex_subgroup 

`GMKF + PBTA + GTEx`: {gene_name}_GMKF_PBTA_GTEx_cancer_group_level

I have a mock-up below for `MT-CO3_PBTA_GTEx_cohort_cancer_group_level.png`:

![MT-CO3_PBTA_GTEx_cohort_cancer_group_level](https://user-images.githubusercontent.com/7000615/123125650-b1a9db00-d416-11eb-993a-1bd2847316d9.png)

**Comment by jharenza** [comment]
> @jharenza before I generate all the plots, I needed some info on the following:
> 
> 1. Single-sample groups: Should we remove `n == 1`?
yes, let's do n >=5

> 2. Plot colors: Do you want colors in the plot? If so, we can fill/color by `cohort` for `cohort_cancer_group_level` plots. However, for `cancer_group_level` plots, if we do color by `cohort`, it will show as dodged boxplot so we would need something else.
Perhaps we could just color the cancer group

> 3. Format of x-axis: Currently, I have set the angle at 90 and if you look at the mock up for `cohort_cancer_group_level` plot for `MT-CO3` between `PBTA` and `GTEx` below, it shows `{cohort}_{cancer_group}_{n}` as x-axis labels.
> 4. Filename: Do we really need additional UUIDs for the filenames? I am thinking a combination of the `{gene_name}_{cohorts of interest}_{analysis_type}` (analysis_type is either `cohort_cancer_group_level` or `cancer_group_level`) should suffice as a unique identifier.

@taylordm wants them to be UUIDs instead of human readable, but I can confirm again

> 
> For e.g. with the current cohorts that we have, the filenames would be named something like this: gene name followed by tumor cohorts arranged alphabetically (for tumor-only plots) followed by GTEx (for tumor-normal plots) followed by analysis type:
> 
> * cohort + cancer_group
> 
> `GMKF + PBTA`: {gene_name}_GMKF_PBTA_cohort_cancer_group_level)
> 
> * cohort + cancer_group + gtex_subgroup
> 
> `GMKF + GTEx`: {gene_name}_GMKF_GTEx_cohort_cancer_group_level
> `PBTA + GTEx`: {gene_name}_PBTA_GTEx_cohort_cancer_group_level
> 
> * cancer_group: (only tumors)
> 
> `GMKF + PBTA`: {gene_name}_GMKF_PBTA_cancer_group_level
> 
> * cancer_group + gtex_subgroup
> 
> `GMKF + PBTA + GTEx`: {gene_name}_GMKF_PBTA_GTEx_cancer_group_level
> 
> I have a mock-up below for `MT-CO3_PBTA_GTEx_cohort_cancer_group_level.png`:
> 
> ![MT-CO3_PBTA_GTEx_cohort_cancer_group_level](https://user-images.githubusercontent.com/7000615/123125650-b1a9db00-d416-11eb-993a-1bd2847316d9.png)

For this plot, it should only be one cohort_cancer group + GTEX at a time, rather than all of a cohort

**Comment by komalsrathi** [comment]
@jharenza thanks. I think you are right, UUID may be better for naming the files and then I would generate an additional mapping file with UUID, cohorts and/or cancer group, gene, analysis type etc.

**Comment by komalsrathi** [comment]
@jharenza can we close this?
