### ISSUE TITLE
gmail/AWS access

### ISSUE THREAD

**Issue by jharenza** [PediatricOpenTargets/ticket-tracker#385]
Created ticket [here](https://d3b.atlassian.net/browse/DEVOPS-741) for gmail and EC2 access for @adilahiri and @kelseykeith

**Comment by jharenza** [comment]
I believe this is complete. @adilahiri and @kelseykeith can you confirm?

**Comment by adilahiri** [comment]
Yes @jharenza , both me and @kelseykeith got our d3b accounts and AWS access.

**Comment by jharenza** [comment]
great!
