### ISSUE TITLE
Updated analysis: rerun snv-frequencies with  updated v11 pedcbio case IDs

### ISSUE THREAD

**Issue by ewafula** [PediatricOpenTargets/ticket-tracker#386]
#### What analysis module should be updated and why?

`snv-frequencies` module needs to be updated to use v11 pedcbio cohort case IDs, aka case set IDs, to generate pedcbio plot URLs.

#### What changes need to be made? Please provide enough detail for another participant to make the update.

After [#375](https://github.com/PediatricOpenTargets/ticket-tracker/issues/375) is resolved, update `analyses/snv-frequencies/input/ped_opentargets_2021_pedcbio_case_set_ids.json` and rerun `snv-frequencies`.

#### What input data should be used? Which data were used in the version being updated?

`snv-frequencies` input data files.

#### When do you expect the revised analysis will be completed?

1-2 days.

#### Who will complete the updated analysis?

@ewafula

**Comment by jharenza** [comment]
New pedcbio study link: https://pedcbioportal.kidsfirstdrc.org/study/summary?id=openpedcan_v11

**Comment by jharenza** [comment]
@ewafula since @kelseykeith has this in PR, she will update it there, so I re-assigned to her.

**Comment by chinwallaa** [comment]
FYI - we may have a production URL of the released MTP site coming soon, which we can link to in the blurb header -

 This data has been integrated into the pediatric open targets platform to assist in development and query of the FDA's Relevant Pediatric Molecular Targets List (PMTL) to identify new therapeutics for children with cancer.

**Comment by jharenza** [comment]
Hi @kelseykeith - will you be able to get to this and run the SNV module on EC2 this week?

**Comment by kelseykeith** [comment]
Hopefully this Friday, if not, next Monday most likely. I've been working on this in parallel with [#361](https://github.com/PediatricOpenTargets/ticket-tracker/issues/361#issuecomment-1209350783) so I had to make further changes this week for that ticket to fix the panel cohorts.

**Comment by jharenza** [comment]
Thanks. Also have a look at https://github.com/PediatricOpenTargets/OpenPedCan-analysis/pull/233 which I updated for the fusion table if you need some ideas for how to integrate DGD. Could be similar for TARGET.

**Comment by kelseykeith** [comment]
Thanks, I will!

**Comment by jharenza** [comment]
completed in https://github.com/PediatricOpenTargets/OpenPedCan-analysis/pull/243
