### ISSUE TITLE
Bix Dev PedcbioPortal Support: some cancer types are missing, but are in the histology file

### ISSUE THREAD

**Issue by jharenza** [PediatricOpenTargets/ticket-tracker#387]
# 🆘

#### [Required] How would you most generally describe your issue? 
- [x] Update data for project in pedcbio portal
- [ ] Questions related to data on pedcbio portal 

#### If an update to a project, provide links to the input files that should be used and descriptions we might find helpful. If new `case_set_ids` need to be added, please provide instructions below.

Please check the samples here: https://pedcbioportal.kidsfirstdrc.org/study/summary?id=openpedcan_v11#filterJson={"clinicalDataFilters":[{"attributeId":"CANCER_TYPE_DETAILED","values":[{"value":"NA"}]}],"studyIds":["openpedcan_v11"],"alterationFilter":{"copyNumberAlterationEventTypes":{"AMP":true,"HOMDEL":true},"mutationEventTypes":{"any":true},"structuralVariants":null,"includeDriver":true,"includeVUS":true,"includeUnknownOncogenicity":true,"includeUnknownTier":true,"includeGermline":true,"includeSomatic":true,"includeUnknownStatus":true,"tiersBooleanMap":{}}}

Spot-checking, these are all TCGA + TARGET and have `NA` for histology (`cancer_group` and cancer type detailed (`harmonized_diagnosis`). Those values are indeed populated in the histology file, so maybe a code bug somewhere?

Can we also add `(TCGA)` after the cancer type detailed, such as we did with GTEX?

**Comment by migbro** [comment]
So, spot checking the spot checking, and it seems the NA's are just matched normal samples, so they should not have any cancer associated with them. Looks like the suffix thing was done in Run's code...I can add it there but not enthralled with adding code exceptions.

**Comment by jharenza** [comment]
Ohhh, I did not realize we had TCGA normals but did know we had a handful of TARGET- good to know, and no worries then!
