### ISSUE TITLE
Proposed Analysis: Evaluation of the use of empirical negative control genes for batch correction

### ISSUE THREAD

**Issue by aadamk** [PediatricOpenTargets/ticket-tracker#39]
#### What are the scientific goals of the analysis?

From PR 11 (https://github.com/PediatricOpenTargets/OpenPedCan-analysis/pull/11), leverage [empirically defined negative control housekeeping genes](https://github.com/logstar/OpenPedCan-analysis/blob/rna-seq-protocol-dge-fourth/analyses/rna-seq-protocol-dge/results/uqpgq2_normalized/stranded_vs_polya_stably_exp_genes.csv) to evaluate the ability to correct for batch. 

#### What methods do you plan to use to accomplish the scientific goals?

1. Identify a dataset where samples were processed by either polyA or ribodeplete methods and for which we would not expect differences in expression profiles (e.g. a known null DGE comparison). 
2. Run a standard DESeq2 differential expression analysis (`dds <- DESeq(dds)`, all size estimation and dispersion estimates wrapped in the DESeq function) on an RSEM expected counts matrix without batch effect as a regression factor.
3. Run a DESeq2 differential expression analysis on an RSEM expected counts matrix, including batch effect in the design as shown in the RUVseq [vignette](https://bioconductor.riken.jp/packages/3.0/bioc/vignettes/RUVSeq/inst/doc/RUVSeq.pdf). Using the gene list linked above, factors of unwanted variation can be estimated by the following: `set1 <- RUVg(set, neg_cont_gene_list, k=k)`, where `k` can be decided based on the sample size once we know the dataset from `1`. Batch effects can be included in the design formula as such: `dds <- DESeqDataSetFromMatrix(countData = cts,
                              colData = coldata,
                              design= ~ W_k + condition)`, where `W_k` is the RUVg-determined batch effect
4. Plot the p-value distributions from 2 and 3. For a 'null' comparison, the expected distribution from `3` would be uniform. 

Note: If a 'null' dataset cannot be identified, an alternative could be to run a standard two group comparison and look for a nearly uniform distribution after batch correction, with a spike at 0 for genes associated with the biological factor. 

#### What input data are required for this analysis?

@taylordm and @jharenza can inform on the appropriate dataset for step 1? 

#### How long do you expect is needed to complete the analysis? Will it be a multi-step analysis?
~ 1 week

#### Who will complete the analysis (please add a GitHub handle here if relevant)?

@logstar 

#### What relevant scientific literature relates to this analysis?

https://bioconductor.riken.jp/packages/3.0/bioc/vignettes/RUVSeq/inst/doc/RUVSeq.pdf
https://www.nature.com/articles/nbt.2931

**Comment by logstar** [comment]
@aadamk Thank you very much for the detailed analysis description.

I will use the 12 PBTA RNA-seq libraries, which is used in [the poly-A vs ribo-deplete DGE analysis](https://github.com/PediatricOpenTargets/ticket-tracker/issues/17), for this analysis first. If more datasets are required, I will update the analysis code to include them.

**Comment by jharenza** [comment]
@logstar other datasets that can be used would be the following (dipg without the samples you used for the DESeq2 analysis and NBL GMKF vs TARGET):

```
hist <- read_tsv("data/histologies.tsv") 

dipg_cohort <- hist %>%
  filter(pathology_diagnosis == "Brainstem glioma- Diffuse intrinsic pontine glioma" & experimental_strategy == "RNA-Seq" &
           !sample_id %in% c("7316-1455", "7316-161", "7316-255", "7316-536", "A16915", "A18777"))
table(dipg_cohort$RNA_library)
  poly-A stranded 
      30       16 

nbl_cohort <- hist %>%
  filter(broad_histology == "Neuroblastoma" & experimental_strategy == "RNA-Seq")
table(nbl_cohort$RNA_library)

  poly-A stranded 
     171      208 
```

**Comment by logstar** [comment]
> @logstar other datasets that can be used would be the following (dipg without the samples you used for the DESeq2 analysis and NBL GMKF vs TARGET):
> 
> ```
> hist <- read_tsv("data/histologies.tsv") 
> 
> dipg_cohort <- hist %>%
>   filter(pathology_diagnosis == "Brainstem glioma- Diffuse intrinsic pontine glioma" & experimental_strategy == "RNA-Seq" &
>            !sample_id %in% c("7316-1455", "7316-161", "7316-255", "7316-536", "A16915", "A18777"))
> table(dipg_cohort$RNA_library)
>   poly-A stranded 
>       30       16 
> 
> nbl_cohort <- hist %>%
>   filter(broad_histology == "Neuroblastoma" & experimental_strategy == "RNA-Seq")
> table(nbl_cohort$RNA_library)
> 
>   poly-A stranded 
>      171      208 
> ```

@jharenza Thank you for the note and code. I will include these datasets in the analysis as well.

**Comment by jharenza** [comment]
(using `library(tidyverse)` above)

**Comment by kgaonkar6** [comment]
Closing with PediatricOpenTargets/OpenPedCan-analysis#20, please reopen if required
