### ISSUE TITLE
Subset `tcga-gene-expression-rsem-tpm-collapsed.rds` to match `gene-expression-rsem-tpm-collapsed.rds`

### ISSUE THREAD

**Issue by jharenza** [PediatricOpenTargets/ticket-tracker#390]
#### What data file(s) does this issue pertain to?
```
tcga-gene-expression-rsem-tpm-collapsed.rds
gene-expression-rsem-tpm-collapsed.rds
```

#### What release are you using?
v11

#### Put your question or report your issue here.
During the pedcbio load, @migbro noticed that these files had different number of rows (genes), and since these files may be used in combination in the future (and in future pedcbio loads), we should take the overlaps during the matrix generation step to avoid this needing to be done downstream. Both files should have identical rows for future releases.

**Comment by zhangb1** [comment]
Just note here  the v11  rds files  need to be used are in cavatica public project or  aws s3 bucket :
https://cavatica.sbgenomics.com/u/cavatica/opentarget/files/#q?path=v11
 
s3://d3b-openaccess-us-east-1-prd-pbta/open-targets/v11/

**Comment by HuangXiaoyan0106** [comment]
Have completed it, and generated new files. [gene-expression-rsem-tpm-collapsed-subset.rds](https://cavatica.sbgenomics.com/u/d3b-bixu-ops/monthly-release-data/files/6302e9020d345971485dc146/), [tcga-gene-expression-rsem-tpm-collapsed-subset.rds](https://cavatica.sbgenomics.com/u/d3b-bixu-ops/monthly-release-data/files/6302eac75129df274bf6beb8/)
Also, I have uploaded it to the monthly release data project, @zhangb1 please move it to the correct location with the correct file name(if required).

```
library(dplyr)

gene <- readRDS("gene-expression-rsem-tpm-collapsed.rds")
tcga <- readRDS("tcga-gene-expression-rsem-tpm-collapsed.rds")

common <- intersect(rownames(gene), rownames(tcga))
new_gene <- gene[common,]
new_tcga <- tcga[common,]

saveRDS(new_gene, file = "gene-expression-rsem-tpm-collapsed-subset.rds")
saveRDS(new_tcga, file = "tcga-gene-expression-rsem-tpm-collapsed-subset.rds")

```

**Comment by zhangb1** [comment]
Thanks @HuangXiaoyan0106 !

**Comment by zhangb1** [comment]
@jharenza  can you confirm which bucket I should export the files?

**Comment by jharenza** [comment]
`s3://d3b-openaccess-us-east-1-prd-pbta/open-targets/v12/` please - will you update md5sum as well?

**Comment by zhangb1** [comment]
Okay ,files are uploaded in the v12 folder, and md5 also updated.

gene-expression-rsem-tpm-collapsed-subset.rds
tcga-gene-expression-rsem-tpm-collapsed-subset.rds

**Comment by chinwallaa** [comment]
Thanks.  Question @zhangb1 @jharenza is it useful to capture the number, and set off genes that are different and not included in the final set of files, as one of the QC metric ? Assuming that these differences are due to different versions of gencode  or something else?
