### ISSUE TITLE
Add v12b6 CBTN methylation classifier results to data warehouse

### ISSUE THREAD

**Issue by jharenza** [PediatricOpenTargets/ticket-tracker#391]
#### What data file(s) does this issue pertain to?
https://data-tracker.kidsfirstdrc.org/study/SD_BHJXBDQK/documents/SF_FCG4Q8E3

#### What release are you using?

v11

#### Put your question or report your issue here.
We recently got additional, and an updated version of, methylation classifier results. We need to first decide which columns to keep (cc @aadamk) and then pull these into the data WH view. Note, the column names are not identical to last time, so we might need to set some rules. 

From Rust at NCI:
>Here is attached file with added v12b6 results. There are two columns which are kind of duplicated. First instance is just abbreviation the second time it has some extra descriptions added. Scores should  match.

>CNSv12b6   # ==> CNSv12b6.subclass1
CNSv12b6.score  # ==> CNSv12b6.subclass1.score
CNSv12b6.superfamily
CNSv12b6.superfamily.score
CNSv12b6.family
CNSv12b6.family.score
CNSv12b6.class
CNSv12b6.class.score
CNSv12b6.subclass1 # ==> CNSv12b6 
CNSv12b6.subclass1.score  # ==> CNSv12b6.score
CNSv12b6.subclass2  # This is second top hit
CNSv12b6.subclass2.score  # The second top hit score
MGMT.Status
MGMT.Estimated

**Comment by jharenza** [comment]
@aadamk Do you want to have a look at this file and suggest some fields to retain/informative column name mappings we can use?

**Comment by aadamk** [comment]
To me, all fields seem valuable with the exception of the first two redundant fields as they give a hierarchy of predictions, graphically represented [here](https://www.molecularneuropathology.org/mnp/classifiers/11). The more verbose `*subclass1*` descriptions are more informative up-front. 

The score fields will allow us to filter during any downstream analytics. >= 0.9 is the high confidence threshold for the annotation (which differs from the old scoring criteria), and anything with a score <0.5 is something that should be discarded. 

MGMT status is of high interest to clinicians for high grades.

For histology field names, maybe a DKFZ_ prefix for all fields would be informative to specify the source (to go along with the version that they provided).

**Comment by jharenza** [comment]
@nicholasvk is this something you can work on getting into the data warehouse in the next two weeks, using `DKFZ_ prefix for all fields` prior to our large X01 release?

One point of clarification @aadamk - do you want us to remove v11 results or keep both? I only worry the histology file will be getting unwieldy. Or perhaps you or someone else can do a comparison of v11/v12 before we add this?

**Comment by aadamk** [comment]
Yes, I'm thinking this should replace v11. Will likely be able to do a comparison by the end of next week given the upcoming holiday from 9/2-9/6.

**Comment by aadamk** [comment]
A few updates: 

1. v11 vs v12 class-level scores (family scores for v12) were generally linearly correlated, with skewness occurring at scores 0.4 and below (though likely does not matter as 0.5 and below is considered unusable data. 

![image](https://user-images.githubusercontent.com/20973091/192326050-755dfd89-87b7-48f0-b852-a50f5a2c05d5.png)

2. The same is true for subclass scores across v11 and v12 

![image](https://user-images.githubusercontent.com/20973091/192326368-a0b88c49-80f9-45a6-ad00-7945957f0cc9.png)

3. I have compiled the class-level calls into simplified tables, separating by confidence scores. High confidence are those of 0.8 or higher and intermediate confidence corresponds to scores of 0.5<=x<0.8. This summary illustrates the mappings between the different class terms and is arranged by v11 names to highlight instances of where there are deviations from 1:1 mappings between terms. For high confidence class, these deviations from 1:1 occurred with the following v11 classes:


CNS NB, FOXR2 - 2 concordant calls with v12 and 2 called as low-grade glioneuronal tumour in v12
CONTR, INFLAM - 2 called as inflammatory microenvironment in v12 and 2 called as Histiocytic tumours in v12
EFT, CIC - 3 called as Tumours of uncertain differentiation and 1 as malignant peripheral nerve-sheath tumour in v12
EPN, PF A - 2 called as spinal ependymoma and 102 with a concordant v12 call
IHG - 12 with a concordant v12 call and 2 with low-grade ganglioglial/neuroepithelial tumour v12 call
LGG, RGNT- 6 with concordant v12 call and 1 with pilocytic astrocytoma call in v12
MNG - 1 called as Cranial and paraspinal nerve tumours and 27 with concordant call in v12
MTGF_ATRT - 27 with concordant call and 1 with Germ cell tumours of the CNS in v12
MTGF_GBM -18 called as Diffuse pediatric-type high-grade glioma and 2 as Glioblastoma, IDH-wildtype in v12
MTGF_PA - 150 as pilocytic astrocytoma and 22 as low-grade ganglioglial/neuroepithelial tumour in v12
MTGF_MB_G3G4 - 78 as medulloblastoma non-WNT/non-SHH activated, 1 as medullomyoblastoma and 1 as pineoblastoma, MYC/FOXR2 activated in v12
MTGF_PLEX_T - 16 with concordant v12 call and 1 with Germ cell tumours of the CNS v12 call
SCHW, MEL - 6 called as Cranial and paraspinal nerve tumours and 2 as schwann-cell tumours in v12


and with medium confidence class calls, these occurred with the following v11 classes:

CONTR, CEBM -1 case matched to a medullo v12 call, the other to medulloblastoma, SHH-activated in v12
CONTR, REACT (1 case matched a GBM v12 call, a germ cell tumor v12 call, and an inflammatory microenvironment v12 call. 
DMG, K27 - 1 case was called as a medulloblastoma, SHH-activated in v12
EPN, PF A - a more granular ependymoma call was made in v12 for 3 cases
EPN, RELA -  1 case called as a DIPG in v12
MNG - 1 case called as malignant peripheral nerve-sheath tumour in v12
MTGF_GBM - 4 cases called as IDH WT GBMs in v12, 1 case as diffuse high-grade neuroepithelial tumour [adult-type] in v12
MTGF_PA - 2 cases called as low-grade ganglioglial/neuroepithelial tumour and 11 as pilocytic astrocytoma in v12
PXA - 1 case called as low-grade ganglioglial/neuroepithelial tumour in v12
SCHW, MEL - 2 called as Cranial and paraspinal nerve tumours in v12 and 1 as schwann-cell tumours v12


Will attach markdown output shortly.

**Comment by aadamk** [comment]
Attaching the mappings between high and medium confidence (in separate files) methylation calls across v11 vs v12 for reference.


[Methylation_HighConfidence_v11v12Comp.txt](https://github.com/PediatricOpenTargets/ticket-tracker/files/9665605/Methylation_HighConfidence_v11v12Comp.txt)
[Methylation_MedConfidence_v11v12Comp.txt](https://github.com/PediatricOpenTargets/ticket-tracker/files/9665606/Methylation_MedConfidence_v11v12Comp.txt)

**Comment by chinwallaa** [comment]
will set up a working team meeting with @nicholasvk @jharenza @aadamk @chinwallaa @ewafula
