### ISSUE TITLE
D3b Bix Dev Feature: Annotate DGD fusion files

### ISSUE THREAD

**Issue by jharenza** [PediatricOpenTargets/ticket-tracker#397]
# ✨

#### [Required] Is this a new tool/workflow?
Sort of

#### Provide software links and `dockerPull` location if applicable
1. Reformat DGD fusion file:

```r
dgd_fus <- read_tsv("~/Documents/GitHub/ped-ot/OpenPedCan-analysis/data/fusion-dgd.tsv.gz", guess_max = 5000) %>%
  select(-Hugo_Symbol) %>%
  unique() %>%
  dplyr::rename(FusionName = Fusion,
                Sample = Tumor_Sample_Barcode) %>%
  add_row(Sample = "BS_YKEK4YWT", FusionName = "C11orf95--RELA") %>% 
  # add another hyphen in fusion name for consistency with putative oncogenic
  mutate(FusionName = sub("\\-", "\\--", FusionName),
         Fusion_Type = "Not available") %>%
  separate(FusionName, c("Gene1A", "Gene1B"), remove = F) %>%
  select(Sample, FusionName, Fusion_Type, Gene1A, Gene1B) %>%
  write_tsv("~/Documents/v12/fusion-dgd.tsv")

Note: I have already updated this file, and added the missing fusion (#392) and placed it here: s3://d3b-openaccess-us-east-1-prd-pbta/open-targets/v12/, but would be good to implement these changes in the future so we can annotate the files.
```
2. Annotate with FusionAnnotator
3. Run through annoFuse QC step
4. Upload file to v12 bucket as `fusion-dgd-annotated.tsv.gz`

#### Add reference files and test input locations if applicable
NA

#### [Optional] How long do you think this work will take?
1-2 days?

#### [Optional] Who will complete this work?
someone from @migbro or @zhangb1 's team?

**Comment by migbro** [comment]
Hmm, yeah, this looks more like an ops thing. Maybe @zhangb1 can update with on when he or someone on his team can fit this in

**Comment by zhangb1** [comment]
@jharenza 

I ran the tools  FusionAnnotator , in the task here : https://cavatica.sbgenomics.com/u/d3b-bixu-ops/open-target-target-rnaseq/tasks/17a34173-1d95-41d2-850a-fa75005c95d6/

can you check the result in the output?

3. Run through annoFuse QC step,,, which tool is the QC step? I may miss that

**Comment by jharenza** [comment]
Thanks @zhangb1 - can you give me access?

For 3 - the annoFuse filtering step which you run for the KF workflow

**Comment by zhangb1** [comment]
@jharenza 

seems we can't use the annofuse filter step here, in the annofuse tool. the inputs need both arriba and starfusion results also the RSEM gene expression file.  see the cwl below..   the merged DGD fusion files here,  we don't have those inputs

https://github.com/kids-first/kf-rnaseq-workflow/blob/master/tools/annoFuse.cwl
