### ISSUE TITLE
Updated analysis: Documentation Dataset Table

### ISSUE THREAD

**Issue by kelseykeith** [PediatricOpenTargets/ticket-tracker#398]
#### What analysis module should be updated and why?

The table in the dataset section in the documentation repository needs to be updated on the main branch.

#### What changes need to be made? Please provide enough detail for another participant to make the update.

1. Currently the table lists the total number of samples available through OpenPedCan-analysis. As this is not exactly the same as what is shown on the MTP website we would like to update it to better reflect the data. As discussed in [Documentation PR#5](https://github.com/PediatricOpenTargets/documentation/pull/5), a few decisions need to be made, including, but not necessarily limited to:
  - Whether we want to include duplicate biospecimens or only samples in the `independent-specimen` lists
  - Do we only want to include tumor samples or both tumor and normal?
2. The code for table calculation needs to be included in the repository as well.

#### What input data should be used? Which data were used in the version being updated?

Originally only `histologies.tsv` was used, but likely we will want to include the `independent-specimens` tables as well.

#### When do you expect the revised analysis will be completed?

No estimate at the moment, this is not a priority. Once decisions are made on what should be included this should take less than a day to complete.

#### Who will complete the updated analysis?

@kelseykeith

**Comment by chinwallaa** [comment]
We can discuss these at the larger team meeting  as well - 

my 2cents- 
> Whether we want to include duplicate biospecimens or only samples in the independent-specimen lists
Only samples in the independent-specimen list.  (a participant is listed as having a sample, if there is >=1 DNA (WGS, WES, Panel) Tumor and/or Normal available,  and/or >=1 RNA-seq, RNA-fusion-panel, and/or >=1 Methyl Array for that participant) 

Do we only want to include tumor samples or both tumor and normal?
Samples that have tumor and/or normal.   

Also, do we have a systematic method to  add sample counts by cancer_groups, as this would also be a useful summary metric.

**Comment by kelseykeith** [comment]
I actually put stuff together for this on Friday and submitted a PR to the documentation repo, [PR#7](https://github.com/PediatricOpenTargets/documentation/pull/7) that addresses all that. It counts samples per cohort/Dataset, sequencing type, and tumor type (primary/relapse). Also, there is now code in the repo that pulls from `OpenPedCan-analysis` data to generate the count table

**Comment by kelseykeith** [comment]
Completed with documentation [PR #7](https://github.com/PediatricOpenTargets/documentation/pull/7)
