### ISSUE TITLE
Prepare and Format TARGET Manifests

### ISSUE THREAD

**Issue by afarrel** [PediatricOpenTargets/ticket-tracker#4]
#### What data file(s) does this issue pertain to?
Retrieve TARGET manifests for the TARGET fastq files and clinical manifests and deliver to @ewafula for reformatting

#### Who is this assigned to
@afarrel

**Comment by jharenza** [comment]
@ewafula this manifest should also exclude WGS for at least TARGET NBL (since it was CGI data) - if we have other WGS that is GCI, we should also exclude from this manifest

**Comment by ewafula** [comment]
@jharenza, I am redoing the TARGET histologies for all cancers now that all clinical data for all of them. @afarrel asked to focus RNA-Seq and exclude WGS/WSX for now too.

**Comment by jharenza** [comment]
ok great!

**Comment by jharenza** [comment]
Doc about sample naming: 
https://ocg.cancer.gov/sites/default/files/OCG-Project-Codes_Tissues-and-Samples_03-02-2021.pdf
Methods:
https://ocg.cancer.gov/programs/target/target-methods

**Comment by jharenza** [comment]
Keeping open as we verify with Sharon which samples should be included in this maniifest

**Comment by jharenza** [comment]
released in #35
