### ISSUE TITLE
Proposed Analysis: NBL vs GTEX batch correction and plots

### ISSUE THREAD

**Issue by jharenza** [PediatricOpenTargets/ticket-tracker#40]
#### What are the scientific goals of the analysis?
If [this PR20](https://github.com/PediatricOpenTargets/OpenPedCan-analysis/pull/20) is successful at batch correction (Ticket #39), re-assess NBL TARGET and GMKF vs GTEX cell surface protein TPM comparisons/plots. 

#### What methods do you plan to use to accomplish the scientific goals?
1. Use the RUVseq method from [PR20](https://github.com/PediatricOpenTargets/OpenPedCan-analysis/pull/20) and the gene list [here](https://github.com/logstar/OpenPedCan-analysis/blob/rna-seq-protocol-dge-fourth/analyses/rna-seq-protocol-dge/results/uqpgq2_normalized/stranded_vs_polya_stably_exp_genes.csv) to perform batch correction. (This piece can go into the batch correction module.

2. Add a second, staggered PR to plot TPMs of the NBL-specific immunotherapeutic targets for both NBL TARGET and NBL GMKF vs GTEX: 
```ALK, MYCN, GPC2, CAMKV, L1CAM, NCAM1, B4GALNT1, DLL3, PHOX2B, DLK1```

#### What input data are required for this analysis?
gtex_target_tcga-gene-counts-rsem-tpm-collapsed.rds (will come in v5)
gene-counts-rsem-tpm-collapsed.rds (will have GMKF)
histologies.tsv

#### How long do you expect is needed to complete the analysis? Will it be a multi-step analysis?
1-2 days

#### Who will complete the analysis (please add a GitHub handle here if relevant)?
@komalsrathi 

#### What relevant scientific literature relates to this analysis?
NA

**Comment by jharenza** [comment]
@komalsrathi @aadamk @sangeetashukla this is an old issue and I haven't been following https://github.com/PediatricOpenTargets/OpenPedCan-analysis/pull/168 100%, but is this being investigated as a part of that PR as well?

**Comment by sangeetashukla** [comment]
> PediatricOpenTargets/OpenPedCan-analysis#168

@jharenza I was on vacation last week, and I am back now and working on the PR you linked above, but I was not aware of this ticket. I will post an update here along with my updates on the [PR#168](https://github.com/PediatricOpenTargets/OpenPedCan-analysis/pull/168).
