### ISSUE TITLE
Updated analysis: rework release scripts

### ISSUE THREAD

**Issue by jharenza** [PediatricOpenTargets/ticket-tracker#402]
#### What analysis module should be updated and why?
We are going to transition to _all_ analysis files being generated by the BIXU toolkit cc @zhangb1 @yuankunzhu @aadamk @chinwallaa @adamcresnick 

#### What changes need to be made? Please provide enough detail for another participant to make the update.
1. Combine these files:
[generate-analysis-files-toolkit.sh](https://github.com/PediatricOpenTargets/OpenPedCan-analysis/blob/dev/scripts/generate-analysis-files-toolkit.sh)
[generate-analysis-files-repo.sh](https://github.com/PediatricOpenTargets/OpenPedCan-analysis/blob/dev/scripts/generate-analysis-files-repo.sh)
Add the modules from the molecular subtyping script to this script as well:

https://github.com/PediatricOpenTargets/OpenPedCan-analysis/blob/d2c0b7c7719e7305cb60cdde16a946e219b090d2/scripts/run-for-subtyping.sh#L14-L20

2. Add code for upload to AWS, but let's create a folder such as `analysis-files-pre-release` so there is no unintentional overwriting of old or new release files. This can be a staging folder where the analysis files can live before someone copies them into the new release folder.
3. Let's work together to decide on the minimal files which we will want committed back to the repository to track differences.

#### What input data should be used? Which data were used in the version being updated?
NA

#### When do you expect the revised analysis will be completed?
1-2 days, during this next sprint

#### Who will complete the updated analysis?
@ewafula

**Comment by jharenza** [comment]
Perhaps we can also think about adding a "commit_directory" such as the compiled directory which will be reserved for files to commit to examine changes.

**Comment by chinwallaa** [comment]
closed #250
