### ISSUE TITLE
Filter v11 mtp mutation frequencies tables for only genecode v38 genes

### ISSUE THREAD

**Issue by ewafula** [PediatricOpenTargets/ticket-tracker#405]
#### What analysis module should be updated and why?
Filter mutation frequencies tables using [filter-mutation-frequencies-tables module](https://github.com/PediatricOpenTargets/OpenPedCan-analysis/tree/dev/analyses/filter-mutation-frequencies-tables) and update files on `mtp-tables` on the s3 bucket.

#### What changes need to be made? Please provide enough detail for another participant to make the update.
- Remove `Ensembl (ESNG)` gene identifier in the OPenPedCan mutation frequency tables, including [SNV](https://github.com/PediatricOpenTargets/OpenPedCan-analysis/tree/dev/analyses/snv-frequencies), [CNV](https://github.com/PediatricOpenTargets/OpenPedCan-analysis/tree/dev/analyses/cnv-frequencies) and [fusion](https://github.com/PediatricOpenTargets/OpenPedCan-analysis/tree/dev/analyses/fusion-frequencies) that are not in [GENCODE v38 and Ensembl package 104](http://ftp.ebi.ac.uk/pub/databases/gencode/Gencode_human/rellease_38/).
- Will not be required for future OpenPedCan data releases after [ticket #400](https://github.com/PediatricOpenTargets/ticket-tracker/issues/400) is completed 

#### What input data should be used? Which data were used in the version being updated?
v11 mutation frequencies table

#### When do you expect the revised analysis will be completed?
1 day

#### Who will complete the updated analysis?
@ewafula

**Comment by chinwallaa** [comment]
> Will not be required for future OpenPedCan data releases after https://github.com/PediatricOpenTargets/ticket-tracker/issues/400 is completed

Will we not always need this, as it will depend on which version of Ensembl OpenTargets platform updates to (backend) ?

**Comment by chinwallaa** [comment]
closed w/ filter v11 freq tables for gencode v39 #252
