### ISSUE TITLE
update DGD MAF with updated BS_ids for v12 OPC release

### ISSUE THREAD

**Issue by jharenza** [PediatricOpenTargets/ticket-tracker#406]
#### What data file(s) does this issue pertain to?
`snv-dgd.maf.tsv.gz`

#### What release are you using?

v11

#### Put your question or report your issue here.
We need to change `BS_66P79BWX -> BS_TECFMMGC` and remove `BS_20218759` and `ET_CDK68MSH` from MAF + histologies file for v12. See [ticket](https://github.com/d3b-center/bixu-tracker/issues/1563) for more information.

**Comment by HuangXiaoyan0106** [comment]
I have changed `BS_66P79BWX -> BS_TECFMMGC` in `input/samples_to_add.txt` and added `BS_20218759` and `ET_CDK68MSH` in` input/samples_to_remove.txt`.
