### ISSUE TITLE
delete v11 mtp gencode v38 filtered tables on s3 bucket 

### ISSUE THREAD

**Issue by ewafula** [PediatricOpenTargets/ticket-tracker#409]
#### What analysis module should be updated and why?
Subfolder, `filtered-for-gencode-v38/` in the s3 bucket  MTP data release folder, `mtp-tables/` needs to be detected. The v11 MTP filtered tables excluding `Ensembl IDs, not in GENCODE v38` are not needed. We have generated new MPT tables filtered for the required `GENCODE v39 Ensembl IDs` and against `OT deprecated Ensembl IDs` available here: https://s3//d3b-openaccess-us-east-1-prd-pbta/open-targets/mtp-tables/filtered-for-gencode-v39-and-OT/

#### What changes need to be made? Please provide enough detail for another participant to make the update.
delete `s3://d3b-openaccess-us-east-1-prd-pbta/open-targets/mtp-tables/filtered-for-gencode-v38/` and all its content

#### What input data should be used? Which data were used in the version being updated?
NA

#### When do you expect the revised analysis will be completed?
1 day

#### Who will complete the updated analysis?
@devbyaccident

**Comment by devbyaccident** [comment]
This is done.
