### ISSUE TITLE
Updated Analysis: modify methyl independent specimens to match with indep RNA samples

### ISSUE THREAD

**Issue by ewafula** [PediatricOpenTargets/ticket-tracker#412]
#### What are the scientific goals of the analysis?
Update [independent-samples module](https://github.com/PediatricOpenTargets/OpenPedCan-analysis/tree/dev/analyses/independent-samples) `05-generate-independent-specimens-methyl.R` script to create methylation `all_cohorts` and `each_cohorts` `primary` and `relapse` independent sample lists. 

#### What methods do you plan to use to accomplish the scientific goals?
1. Currently, the module creates only methylation `all_cohorts` independent sample lists `independent-specimens.methyl.primary.tsv` and `independent-specimens.methyl.relapse.tsv`.  
2. Need to create additional methylation `each_cohorts` independent sample lists `independent-specimens.methyl.primary.eachcohort.tsv` and `independent-specimens.methyl.relapse.eachcohort.tsv`.  
3. A new `match_id` needs to be created to account for the non-unique `sample_id` in the TARGET cohort and future cohorts with similar `sample_id`. The new `match_id` is for determining methylation samples with matching RNA-Seq samples that need to be prioritized for selection into the independent sample lists. Please refer to a similar approach implemented for matching RNA-Seq to DNA samples in the `util/independent-rna-samples.R ` 

#### What input data are required for this analysis?
`data/histologies.tsv`

#### How long do you expect is needed to complete the analysis? Will it be a multi-step analysis?
?

#### Who will complete the analysis (please add a GitHub handle here if relevant)?
?

#### What relevant scientific literature relates to this analysis?
NA

**Comment by jharenza** [comment]
@sangeetashukla can you take this?
