### ISSUE TITLE
Updated analysis: update `rna-seq-expression-summary-stats` module for v11 data release

### ISSUE THREAD

**Issue by logstar** [PediatricOpenTargets/ticket-tracker#413]
#### What analysis module should be updated and why?

`rna-seq-expression-summary-stats` module needs to be updated to generate the following files using v11 data:

- `long_n_tpm_mean_sd_quantile_gene_wise_zscore.jsonl.gz`
- `long_n_tpm_mean_sd_quantile_gene_wise_zscore.tsv.gz`
- `long_n_tpm_mean_sd_quantile_group_wise_zscore.jsonl.gz`
- `long_n_tpm_mean_sd_quantile_group_wise_zscore.tsv.gz`

The JSONL files will be used to update MTP for OpenPedCan-analysis v11 data release.

#### What changes need to be made? Please provide enough detail for another participant to make the update.

- Download v11 data.
- Rerun `rna-seq-expression-summary-stats` module.
- If any assertion fails, handle the failed assertion.

@jharenza - I wonder if there is any v11 data specific changes that need to be made to the `rna-seq-expression-summary-stats` module.

#### What input data should be used? Which data were used in the version being updated?

Input data for `rna-seq-expression-summary-stats` module.

v11 data release needs to be used.

#### When do you expect the revised analysis will be completed?

1 week

#### Who will complete the updated analysis?

cc @chinwallaa

**Comment by jharenza** [comment]
The only update I can think of which may or may not be needed is that if we are not selecting samples by RNA-Seq strategy, we may need to pre-filter out DGD cohort.
