### ISSUE TITLE
Updated analysis: histologies MYCN status

### ISSUE THREAD

**Issue by ewafula** [PediatricOpenTargets/ticket-tracker#415]
#### What analysis module should be updated and why?
Update OpenPedCan histologies with correct MYCN status from TARGET and GMKF clinical files

#### What changes need to be made? Please provide enough detail for another participant to make the update.

1. Add code at the end `add_v11_updates.py` script in the [v11-OpenPedCan histologies update module](https://github.com/d3b-center/D3b-codes/tree/9daf30f1915f035d0411a186fc4fd682b175437f/v11-OpenPedCan) to update the TARGET and GMKF tumor samples (`sampe_type == Tumor`) with MYCN status in the `molecular_subtype` and `pathology_free_text_diagnosis` columns of the `v11/histologies.tsv file using the cohort level mapping file attached below in this ticket 
2. Recreate the cohort level histologies files for TARGET and GMKF by re-running the [OpenPedCan_cohort_histologies module](https://github.com/d3b-center/D3b-codes/tree/9daf30f1915f035d0411a186fc4fd682b175437f/OpenPedCan_cohort_histologies) using the updated `v11/histolgies.tsv` file in step 1 above. The TARGET and GMKF updated cohort histologies file will have the updated `pathology_free_text_diagnosis` column while the `molecular_subtype` column will be set to all `NAs.`
3. Upload updated  TARGET and GMKF cohort histologies files to Data Tracker  

#### What input data should be used? Which data were used in the version being updated?
[target_patient_clinical_mycn_status.tsv.zip](https://github.com/PediatricOpenTargets/ticket-tracker/files/9635038/target_patient_clinical_mycn_status.tsv.zip)
[gmkf_patient_clinical_mycn_status.tsv.zip](https://github.com/PediatricOpenTargets/ticket-tracker/files/9635040/gmkf_patient_clinical_mycn_status.tsv.zip)

#### When do you expect the revised analysis will be completed?
1/2

#### Who will complete the updated analysis?
@ewafula

**Comment by chinwallaa** [comment]
@jharenza to review
