### ISSUE TITLE
KMT2C 100% Mutation Frequency in DGD Samples

### ISSUE THREAD

**Issue by kelseykeith** [PediatricOpenTargets/ticket-tracker#416]
#### What data file(s) does this issue pertain to?

- `gene-level-snv-consensus-annotated-mut-freq.tsv.gz` in `analyses/snv-frequencies/results/`
- data file `snv-dgd.maf.tsv.gz`

#### What release are you using?

v11

#### Put your question or report your issue here.

FNL noticed when looking through `gene-level-snv-consensus-annotated-mut-freq.tsv.gz` that for KMT2C in the DGD/CHOP P30 Panel samples, all samples in all cancers had some mutation in KMT2C giving a frequency of 100%. See sheet "chop_gene_level_snv_SORT" in the Excel file. [KMT2C_v11_SomaticAlterationsDisplay_CWedits.xlsx](https://github.com/PediatricOpenTargets/ticket-tracker/files/9636666/KMT2C_v11_SomaticAlterationsDisplay_CWedits.xlsx)

@jharenza confirmed that synonymous mutations were filtered out from the DGD MAF so these should all be nonsynonymous variants and that the 100% frequencies are correct based on the MAF. The only samples with no KMT2C mutations, which are also in our indep samples files, are BS_4YNG1QB1 and BS_ZS93AZWP, which are both in the B-ALL cancer group, which is also properly calculated as 45/47 samples with a mutation at 95.74%. It may also be helpful to read through the [Slack discussion on the issue.](https://opentargetspediatrics.slack.com/archives/C040EEHSD1T/p1663808695446159)

We want to confirm that the 100% frequencies are correct, as this high frequency of KMT2C mutations is not found in any other cohorts and seems unlikely. Preliminarily this would involve a more in-depth look at the DGD MAF and/or checking with DGD that this high proportion of KMT2C variants is expected.

**Comment by luederm** [comment]
@jharenza Just to confirm, the DGD MAF you are referring to is the same as the one I annotated with FileMaker classifications, right?

**Comment by jharenza** [comment]
Thank you for this great explanation @luederm. Out of curiosity, do you have a list of genes which have some variants which get filtered out after this process (eg I noticed a variant specific to DGD cohort in H3F3A which may or may not be artifactual). Said another way, will this process be broadly applicable to all genes' artifactual calls and not solely KMT2C?

**Comment by jharenza** [comment]
updated in v12
