### ISSUE TITLE
Missing PedcBio Links in `snv-frequencies` Tables

### ISSUE THREAD

**Issue by kelseykeith** [PediatricOpenTargets/ticket-tracker#419]
#### What data file(s) does this issue pertain to?

`gene-level-snv-consensus-annotated-mut-freq.tsv.gz` in `analyses/snv-frequencies/results/`

#### What release are you using?

v11

#### Put your question or report your issue here.

FNL noticed when looking through `gene-level-snv-consensus-annotated-mut-freq.tsv.gz` that some links to PedcBio are missing and I looked through the table and confirmed the links were missing as well. This may be an issue with the recent v11 updates to the `snv-frequencies` module and we want to find out why the links are missing.

**Comment by chinwallaa** [comment]
@kelseykeith are there any updates with this?

**Comment by kelseykeith** [comment]
Not since the ticket was put in! Will look into it more next wel

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
From: chinwallaa ***@***.***>
Sent: Thursday, October 6, 2022 5:16:02 PM
To: PediatricOpenTargets/ticket-tracker ***@***.***>
Cc: Keith, Kelsey ***@***.***>; Mention ***@***.***>
Subject: [External]Re: [PediatricOpenTargets/ticket-tracker] Missing PedcBio Links in `snv-frequencies` Tables (Issue #419)


@kelseykeith<https://nam10.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fkelseykeith&data=05%7C01%7Ckeithk%40chop.edu%7Cee13bc6b7cfe4286684f08daa7dff9f8%7Ca611241607b041a59bb1d146b575c975%7C0%7C0%7C638006877658360667%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=MirqUSeqWm1bLv7kw29CuWNg10C%2FlA6wRuoou2Cgonc%3D&reserved=0> are there any updates with this?

—
Reply to this email directly, view it on GitHub<https://nam10.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FPediatricOpenTargets%2Fticket-tracker%2Fissues%2F419%23issuecomment-1270707250&data=05%7C01%7Ckeithk%40chop.edu%7Cee13bc6b7cfe4286684f08daa7dff9f8%7Ca611241607b041a59bb1d146b575c975%7C0%7C0%7C638006877658516894%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=GcoiBjRf%2F5YFsGDBkl%2FFfLbK6fR0h6oV5vCO8NC8Vio%3D&reserved=0>, or unsubscribe<https://nam10.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAGGPOOQWEUXRRVSSXKZDKQ3WB46RFANCNFSM6AAAAAAQ33T3JE&data=05%7C01%7Ckeithk%40chop.edu%7Cee13bc6b7cfe4286684f08daa7dff9f8%7Ca611241607b041a59bb1d146b575c975%7C0%7C0%7C638006877658516894%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=iytqqMPWXhwOch7hspzRRFNW264OezNVYCpMETLqcJY%3D&reserved=0>.
You are receiving this because you were mentioned.Message ID: ***@***.***>

** This email originated from an EXTERNAL sender to CHOP. Proceed with caution when replying, opening attachments, or clicking links. Do not disclose your CHOP credentials, employee information, or protected health information to a potential hacker**.

**Comment by kelseykeith** [comment]
After checking into this further, this is actually the expected behavior of the code for groups that are not in PedcBio. The rows that are missing links are missing them because the entire respective `cohort` + `cancer_group` is not in PedcBio. 

The first step in updating this module is using the PedcBio API to fetch sample lists from PedcBio. Where data is missing, it is definitely not in this list. I tried to filter for the data on PedcBio itself and I couldn't find it through the GUI, but it's possible that I didn't have the correct project or filter in the correct way since I'm not super familiar with using the platform.

Table attached with the `cohorts` and `cancer_groups` that do not have PedcBio information:
[2022-10-11_groups_missing_pedcbio.txt](https://github.com/PediatricOpenTargets/ticket-tracker/files/9758382/2022-10-11_groups_missing_pedcbio.txt)

@jharenza @migbro are these groups not currently included in PedcBio? Or is this a data issue we need to address?

**Comment by migbro** [comment]
Hi @kelseykeith , I think I need some more context for this. How are these links generated? Is it that the samples are completely missing from the study, or you are trying to use a case list and not finding it? IF the latter, it could be because I received guidance to skip creating case lists for sets with < 5 samples. Reasoning was it's just a lot of cohort-disease combos overall, and also each case list adds a good chunk of run time to load into the portal

**Comment by jharenza** [comment]
Ahhh, @migbro I think your N should be if <3 (is that what we are using for SNV tables @kelseykeith ?)

**Comment by kelseykeith** [comment]
Yep, must be at least 3 samples

**Comment by migbro** [comment]
Ok, that's a change I can make, maybe load later today or tomorrow

**Comment by migbro** [comment]
Sorry, this kind of got pushed back behind some pbta treatment updates Adam wants for the conference and the openPBTA updates. Also going to look into that single sample difference Adam brought to Jo Lynne's attention, sample `7316-716` in the meantime.

**Comment by migbro** [comment]
Hi @kelseykeith , so after adjusting the min sample count needed for generating a case list, I have the following that would be added:
```
cases_cns_neuroblastoma.txt
cases_desmoplastic_infantile_astrocytoma_and_ganglioglioma.txt
cases_dgd_chordoma.txt
cases_dgd_choroid_plexus_carcinoma.txt
cases_dgd_craniopharyngioma.txt
cases_dgd_hepatoblastoma.txt
cases_dgd_malignant_peripheral_nerve_sheath_tumor.txt
cases_dgd_metastatic_secondary_tumors.txt
cases_gmkf_ganglioneuroma.txt
cases_hepatoblastoma.txt
cases_juvenile_xanthogranuloma.txt
cases_mixed_germ_cell_tumor.txt
cases_oligodendroglioma.txt
cases_pbta_choroid_plexus_carcinoma.txt
cases_pbta_cns_neuroblastoma.txt
cases_pbta_desmoplastic_infantile_astrocytoma_and_ganglioglioma.txt
cases_pbta_ganglioneuroblastoma.txt
cases_pbta_germinoma.txt
cases_pbta_hemangioblastoma.txt
cases_pbta_langerhans_cell_histiocytosis.txt
cases_pbta_malignant_peripheral_nerve_sheath_tumor.txt
cases_pbta_oligodendroglioma.txt
```
would that cover it all?

**Comment by kelseykeith** [comment]
Looks good to me! This has everything that was on my missing list

**Comment by migbro** [comment]
Great to hear! Ok, working on loading that into prod now. It'll take at least 3 hours.

**Comment by kelseykeith** [comment]
Great, thanks!

**Comment by migbro** [comment]
Should be addressed now: https://pedcbioportal.kidsfirstdrc.org/study/summary?id=openpedcan_v11
A spot check of looking for `desmoplastic` popped up two case lists with 3 samples each

**Comment by kelseykeith** [comment]
Awesome, thanks for taking care of it! I'll check it too before I rerun anything just in case
