### ISSUE TITLE
Remove samples with no consent

### ISSUE THREAD

**Issue by jharenza** [PediatricOpenTargets/ticket-tracker#42]
#### What data file(s) does this issue pertain to?
histologies.tsv

#### What release are you using?

v4

#### Put your question or report your issue here.
Some TARGET RNA and DNA samples are listed as having no consent and should be removed.

@ewafula can you add more details please? cc @chinwallaa @yuankunzhu @zhangb1

**Comment by ewafula** [comment]
@jharenza,  there are only 8 no-consent samples, all in ALL cancer type clinical data. The number is no where near the 116 samples that Apexa suggested. Unless this list of no-consents is in some other documents. Can't find in both the clinical data files and data matrices from TARGET portal (https://ocg.cancer.gov/programs/target/data-matrix). I can remove these from the histology file. cc @afarrel @kgaonkar6 @chinwallaa 
```
TARGET-10-PAPDJM
TARGET-10-PAPIGX
TARGET-10-PARBRK
TARGET-10-PASGFH
TARGET-10-PASKGG
TARGET-10-PASSRP
TARGET-10-PATDRC
TARGET-10-PATMXN
```

**Comment by kgaonkar6** [comment]
Closing since the above samples with no consent were removed in v5. Please reopen if required
