### ISSUE TITLE
Updated analysis: Ependymoma subyping - add spinal EPN type

### ISSUE THREAD

**Issue by jharenza** [PediatricOpenTargets/ticket-tracker#425]
#### What analysis module should be updated and why?
https://github.com/PediatricOpenTargets/OpenPedCan-analysis/tree/dev/analyses/molecular-subtyping-EPN

Add subtypes:
- EPN, SP (EPN, spinal)
- EPN, SP-MYCN (EPN, spinal-MYCN amplified)

#### What changes need to be made? Please provide enough detail for another participant to make the update.
We should update the `https://github.com/PediatricOpenTargets/OpenPedCan-analysis/blob/dev/analyses/molecular-subtyping-EPN/results/EPN_all_data.tsv` to add `spinal` into the `diease_group` and add additional alteration columns for MYCN amplification, chr22, NF2. K28M will be added in #424 

Criteria:
**EPN, SP**
- `CNS_region == spine` and 
- No MYCN amplification and 
- Frequent loss of Chr22 and mutations in NF2 can occur in this subtype

**EPN, SP-MYCN**
- `CNS_region == spine` and 
- MYCN amplification
Note: H3 K28M can also rarely occur with MYCN amplification in this subtype

Relevant literature: https://academic.oup.com/neuro-oncology/article/23/8/1231/6311214

#### What input data should be used? Which data were used in the version being updated?
```
CNVs: consensus_wgs_plus_cnvkit_wxs.tsv.gz
Chr arms: broad_values_by_arm.txt
cns region: histologies.tsv
mutations: snv-consensus-plus-hotspots.maf.tsv.gz
```

Note: use `data.table::fread()` to load the maf

#### When do you expect the revised analysis will be completed?
1 week

#### Who will complete the updated analysis?
@rjcorb

**Comment by sickler-alex** [comment]
For SP, chr22 and NF2 aren't required? The other EPN subtypes have different levels of priority with ST RELA having a higher priority than ST YAP1 then PF A and finally PF B. What priority should be given to these new variants? Basically, if a sample has two different subtypes only the higher priority one is given. This can be done for any subtype, but is only being done for EPN. If a sample has multiple subtypes with the same priority all of those are kept.

**Comment by jharenza** [comment]
> For SP, chr22 and NF2 aren't required? 

Correct, but are often associated so it helps with the confidence

> The other EPN subtypes have different levels of priority with ST RELA having a higher priority than ST YAP1 then PF A and finally PF B. What priority should be given to these new variants? 

I'm not sure we need a priority - if it has one of the fusions, it should only land in that subtype, but maybe that's what you're asking

These should not fit into the other categories at all if they are spinal location, so we can make an option for location of spine removing them from those types- would that work?

**Comment by sickler-alex** [comment]
> > For SP, chr22 and NF2 aren't required?
> 
> Correct, but are often associated so it helps with the confidence
> 
> > The other EPN subtypes have different levels of priority with ST RELA having a higher priority than ST YAP1 then PF A and finally PF B. What priority should be given to these new variants?
> 
> I'm not sure we need a priority - if it has one of the fusions, it should only land in that subtype, but maybe that's what you're asking

That's what I'm asking. So I can add this as priority 1 that way we'll remove the other subtypes if they were assigned.

> 
> These should not fit into the other categories at all if they are spinal location, so we can make an option for location of spine removing them from those types- would that work?
