### ISSUE TITLE
Histologies QC to check  germline sex estimate

### ISSUE THREAD

**Issue by ewafula** [PediatricOpenTargets/ticket-tracker#426]
#### What are the scientific goals of the analysis?
Add to histologies QC code for checking if WXS patients have WGS and if the `germline_sex_estimate` is carried over, and if not, it should be carried over. 

#### What methods do you plan to use to accomplish the scientific goals?
1. all WGS should have germline_sex_estimate
2.  all WXS or Targeted Sequencing BS_ids from patients who also have WGS should have the `germline_sex_estimate` carried over from the WGS sample

Code can be adapted from OpenPedCan `data-pre-release-qc` module  here:
https://github.com/PediatricOpenTargets/OpenPedCan-analysis/blob/cd4e379a7f835160284a65b5d7a6c62a5bc125c4/analyses/data-pre-release-qc/data-pre-release-qc.Rmd#L498-L547

#### What input data are required for this analysis?
 `QC_histology.Rmd` notebook in be updated in the [histologies QC repository](https://github.com/d3b-center/histologies-qc)

#### How long do you expect is needed to complete the analysis? Will it be a multi-step analysis?
1/2 days

#### Who will complete the analysis (please add a GitHub handle here if relevant)?
?

#### What relevant scientific literature relates to this analysis?
NA

**Comment by chinwallaa** [comment]
can we PR to Xiaoyan's branch.

**Comment by chinwallaa** [comment]
remove GTEX PR
