### ISSUE TITLE
OT data harmonization - PBTA X01

### ISSUE THREAD

**Issue by ewafula** [PediatricOpenTargets/ticket-tracker#427]
#### What needs to be done?
Harmonize  `PBTA X01`  `WGS` and `RNA-Seq`  CNS/spinal cord tumors datasets for OT utilizing GENCODE v39 for OPenPedCan v12 data release

#### How long do you expect is needed to complete the analysis? Will it be a multi-step analysis?
?

#### Who will complete the analysis (please add a GitHub handle here if relevant)?
bixops team

**Comment by zhangb1** [comment]
related to https://github.com/d3b-center/bixu-tracker/issues/1596

I think we can close one.
