### ISSUE TITLE
OT data reharmonization - TARGET and GMKF NBL

### ISSUE THREAD

**Issue by ewafula** [PediatricOpenTargets/ticket-tracker#428]
#### What needs to be done?
- Reprocessing  `TARGET and GMKF (NBL Maris FY16)` `RNA-Seq`  datasets to Gencode v39 for OPenPedCan v12 data release
- Gencode annotation being swapped out to Gencode v39 for `TARGET Panel-DNA/WXS` datasets and for `GMKF  WGS` dataset

#### How long do you expect is needed to complete the analysis? Will it be a multi-step analysis?
?

#### Who will complete the analysis (please add a GitHub handle here if relevant)?
Being reprocessed by Kids First

**Comment by jharenza** [comment]
@zhangb1 we can use OT funding for this

**Comment by zhangb1** [comment]
OpenTarget billing is out of funds now.....

**Comment by chinwallaa** [comment]
Is there a log of the what we spent the OT billing on to date.   

We got approval for the TARGET re-harmonization.  @chinwallaa will follow up with Bailey,   Mark Cand LBR set up a billing account for this.

**Comment by chinwallaa** [comment]
For TARGET re-harmonization we have approval to use the OT/MTP budget/billing group .

**Comment by zhangb1** [comment]
https://app.zenhub.com/workspaces/d3b-bfx-5cdd720eed0dce4209e0b8a5/issues/d3b-center/bixu-tracker/1667

https://app.zenhub.com/workspaces/d3b-bfx-5cdd720eed0dce4209e0b8a5/issues/d3b-center/bixu-tracker/1693

related tickets  in bixu-tracker

**Comment by jharenza** [comment]
These refer to https://github.com/d3b-center/bixu-tracker/issues/1667 and https://github.com/d3b-center/bixu-tracker/issues/1693

**Comment by zhangb1** [comment]
This has been done ,close the ticket

**Comment by zhangb1** [comment]
This has been done ,close the ticket
