### ISSUE TITLE
Reprocess DGD panel data

### ISSUE THREAD

**Issue by ewafula** [PediatricOpenTargets/ticket-tracker#429]
#### What needs to be done?
Reprocess  `DGD Panel-RNA fusion and Panel-DNA` datasets (MAF files) with liftover due to an earlier DGD data processing pipeline that filtered synonymous variants and was also subject to pseudogene effects (artifact filter). 

#### How long do you expect is needed to complete the analysis? Will it be a multi-step analysis?
?

#### Who will complete the analysis (please add a GitHub handle here if relevant)?
bixops team

**Comment by jharenza** [comment]
Connecting to this issue https://github.com/d3b-center/bixu-tracker/issues/1694

**Comment by jharenza** [comment]
Note: we had to remove one additional spurious mutation:  `chr7:152358681-152358682` associated with the `KMT2C`, but this is completed
