### ISSUE TITLE
GMKF clinical info file

### ISSUE THREAD

**Issue by kgaonkar6** [PediatricOpenTargets/ticket-tracker#43]
#### What data file(s) does this issue pertain to?
histologies.tsv

#### What release are you using?

v5

#### Put your question or report your issue here.

The following samples don't have clinical info but should probably be NBL 

Kids_First_Biospecimen_ID | sample_type | composition | cohort | harmonized_diagnosis | broad_histology | short_histology | cancer_group | gtex_group | gtex_subgroup | pathology_diagnosis | pathology_free_text_diagnosis
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
BS_CH0ZV29W | Tumor | Bone&nbsp;Marrow | GMKF | NA | NA | NA | NA | NA | NA | NA | NA
BS_2F5KDZ93 | Tumor | Bone&nbsp;Marrow | GMKF | NA | NA | NA | NA | NA | NA | NA | NA
BS_ETC8R0TD | Tumor | Solid&nbsp;Tissue | GMKF | NA | NA | NA | NA | NA | NA | NA | NA
BS_JZFMHGNX | Tumor | Solid&nbsp;Tissue | GMKF | NA | NA | NA | NA | NA | NA | NA | NA

After discussing with @jharenza it seems the samples above have clinical info in clinical file she has. I believe @afarrel has the latest clinical info can you share the clinical file here and @ewafula can use it to create the histology file? Thanks!

**Comment by afarrel** [comment]
The above samples have clinical info but are diagnosed as 'unknown'. All the patients did go through neuroblastoma protocols and have been assigned and INSS stage (which is specific to NBL) as well as a risk stratifications. I checked multiple versions of our GMKF manifests and they  are diagnosed as 'unknown' in all.
[2019-09-30-gmkf_clinical_elements.csv](https://github.com/PediatricOpenTargets/ticket-tracker/files/6664595/2019-09-30-gmkf_clinical_elements.csv)

**Comment by kgaonkar6** [comment]
interesting, so should we add these samples as "NBL" in short_histology (and propogate the value to broad_histology and cancer_group)  or remove them since they don't have clinical info in the source files @jharenza @afarrel ?

**Comment by afarrel** [comment]
I would suggest remove them. while they are likely NBL, I don't think we should guess and there might be a reason why they were not conclusively diagnosed as neuroblastoma which we do not know. What are your thoughts @jharenza ?

**Comment by jharenza** [comment]
> I would suggest remove them. while they are likely NBL, I don't think we should guess and there might be a reason why they were not conclusively diagnosed as neuroblastoma which we do not know. What are your thoughts @jharenza ?

maybe quickly ask Sharon and John if they are using them?

**Comment by jharenza** [comment]
Sent an email to John and Sharon about this

**Comment by jharenza** [comment]
[JLR_GMKF_ques.xlsx](https://github.com/PediatricOpenTargets/ticket-tracker/files/6673317/JLR_GMKF_ques.xlsx)
Consensus is to include - let's add "Unknown" to `pathology_diagnosis` but `Neuroblastoma` to the other fields as with the rest of the cohort @kgaonkar6

**Comment by kgaonkar6** [comment]
@jharenza This fix was missed in v5, will need to implement this for v6

**Comment by jharenza** [comment]
added with [PR 34](https://github.com/PediatricOpenTargets/OpenPedCan-analysis/pull/34)
