### ISSUE TITLE
v12 release

### ISSUE THREAD

**Issue by ewafula** [PediatricOpenTargets/ticket-tracker#431]
#### What data file(s) are added/updated/removed in this release?

[**Pre-release files**]
- [x] histologies-base.tsv
- [x] cnv-cnvkit.seg.gz
- [x] cnvkit_with_status.tsv
- [x] cnv-controlfreec.tsv.gz
- [x] cnv-consensus-gistic.zip
- [x] cnv-consensus.seg.gz
- [x] consensus_seg_with_status.tsv 
- [x] consensus_wgs_plus_cnvkit_wxs.tsv.gz
- [x] consensus_wgs_plus_cnvkit_wxs_x_and_y.tsv.gz
- [x] consensus_wgs_plus_cnvkit_wxs_autosomes.tsv.gz
- [x] fusion-annoFuse.tsv.gz
- [x] fusion-arriba.tsv.gz
- [x] fusion-dgd.tsv.gz
- [x] fusion-putative-oncogenic.tsv
- [x] fusion-starfusion.tsv.gz
- [x] fusion_summary_embryonal_foi.tsv
- [x] fusion_summary_ependymoma_foi.tsv
- [x] fusion_summary_ewings_foi.tsv
- [x] fusion_summary_lgg_hgg_foi.tsv
- [x] snv-consensus-plus-hotspots.maf.tsv.gz
- [x] snv-dgd.maf.tsv.gz
- [ ] splice-events-rmats.tsv.gz #480 
- [x] sv-manta.tsv.gz
- [x] snv-mutation-tmb-all.tsv
- [x] snv-mutation-tmb-coding.tsv
- [x] gene-expression-rsem-tpm-collapsed.rds
- [x] gene-counts-rsem-expected_count-collapsed.rds
- [x] tcga-gene-expression-rsem-tpm-collapsed.rds
- [ ] tcga-gene-counts-rsem-expected_count-collapsed.rds
- [x] rna-isoform-expression-rsem-tpm.rds
- [x] methyl-m-values.rds
- [x] methyl-cn-values.rds
- [x] methyl-beta-values.rds
- [x] methyl-md5sum.txt
- [x] independent-specimens.rnaseq.primary-plus.pre-release.tsv
- [x] independent-specimens.rnaseq.primary.pre-release.tsv
- [x] independent-specimens.rnaseq.relapse.pre-release.tsv

[**Commit files**]
- [x] histologies.tsv
- [x] efo-mondo-map.tsv
- [x] ensg-hugo-mapping.tsv
- [x] uberon-map-gtex-group.tsv
- [x] uberon-map-gtex-subgroup.tsv
- [x] independent-specimens.methyl.primary-plus.eachcohort.tsv
- [x] independent-specimens.methyl.primary-plus.tsv
- [x] independent-specimens.methyl.primary.eachcohort.tsv
- [x] independent-specimens.methyl.primary.tsv
- [x] independent-specimens.methyl.relapse.eachcohort.tsv
- [x] independent-specimens.methyl.relapse.tsv
- [x] independent-specimens.rnaseqpanel.primary-plus.eachcohort.tsv
- [x] independent-specimens.rnaseqpanel.primary-plus.tsv
- [x] independent-specimens.rnaseqpanel.primary.eachcohort.tsv
- [x] independent-specimens.rnaseqpanel.primary.tsv
- [x] independent-specimens.rnaseqpanel.relapse.eachcohort.tsv
- [x] independent-specimens.rnaseqpanel.relapse.tsv
- [x] independent-specimens.wgs.primary-plus.eachcohort.tsv
- [x] independent-specimens.wgs.primary-plus.tsv
- [x] independent-specimens.wgs.primary.eachcohort.tsv
- [x] independent-specimens.wgs.primary.tsv
- [x] independent-specimens.wgs.relapse.eachcohort.tsv
- [x] independent-specimens.wgs.relapse.tsv
- [x] independent-specimens.wgswxspanel.primary-plus.eachcohort.prefer.wgs.tsv
- [x] independent-specimens.wgswxspanel.primary-plus.eachcohort.prefer.wxs.tsv
- [x] independent-specimens.wgswxspanel.primary-plus.prefer.wgs.tsv
- [x] independent-specimens.wgswxspanel.primary-plus.prefer.wxs.tsv
- [x] independent-specimens.wgswxspanel.primary.eachcohort.prefer.wgs.tsv
- [x] independent-specimens.wgswxspanel.primary.eachcohort.prefer.wxs.tsv
- [x] independent-specimens.wgswxspanel.primary.prefer.wgs.tsv
- [x] independent-specimens.wgswxspanel.primary.prefer.wxs.tsv
- [x] independent-specimens.wgswxspanel.relapse.eachcohort.prefer.wgs.tsv
- [x] independent-specimens.wgswxspanel.relapse.eachcohort.prefer.wxs.tsv
- [x] independent-specimens.wgswxspanel.relapse.prefer.wgs.tsv
- [x] independent-specimens.wgswxspanel.relapse.prefer.wxs.tsv

[**Bed files and sample mapping**]
- [x] biospecimen_id_to_bed_map.txt
- [x] ashion_exome_v2_targets_hg38_padded100.bed
- [x] hg38_strelka.bed
- [x] intersect_cds_lancet_strelka_mutect_WGS.bed
- [x] intersect_strelka_mutect_WGS.bed
- [x] nexterarapidcapture_exome_targetedregions_v1.2_hg38_100.bed
- [x] S0274956_Padded_HG38.merged.bed
- [x] S02972011_Covered_hg38_100.bed
- [x] S04380110_Regions_hg38_100.bed
- [x] S07604715_100bp_Padded.bed
- [x] SeqCap_EZ_Exome_v2_Padded_HG38.merged.bed
- [x] StrexomeLite_hg38_liftover_100bp_padded.bed
- [x] Strexome_targets_intersect_sorted_padded100.GRCh38.bed
- [x] TARGET_AML_NBL_WT_SeqVal79_attempt06_AllTracks_HG38_bed_expanded100.bed
- [x] truseq-exome-targeted-regions-manifest-v1-2_hg38_100.bed
- [x] wgs_canonical_calling_regions.hg38.bed
- [x] WGS.hg38.lancet.300bp_padded.bed
- [x] WGS.hg38.lancet.unpadded.bed
- [x] WGS.hg38.mutect2.vardict.unpadded.bed
- [x] WGS.hg38.strelka2.unpadded.bed
- [x] WGS.hg38.vardict.100bp_padded.bed
- [x] xgen-exome-research-panel-targets_hg38_ucsc_liftover.100bp_padded.sort.merged.bed
- [x] 20038D-17Q6-01.regions.bed
- [x] agilent-v4-targets-ucsc.bed
- [x] onco1500-v2-targets-ucsc.bed
- [x] onco1500-v4-targets-ucsc.bed
- [x] onco1500-v6-targets-ucsc.bed
- [x] onco1500-v6a-targets-ucsc.bed 

[**Methylation arrays metadata**]
- [x] infinium-methylationepic-v-1-0-b5-manifest-file-csv.zip
- [x] infinium.gencode.v39.probe.annotations.tsv.gz

[**File descriptions and notes**]
- [ ] data-files-description.md
- [ ] release-notes.md

#### Any additional notes to add for discussion?

- Updates for OPC histologies:
   - https://github.com/PediatricOpenTargets/ticket-tracker/issues/445
   - https://github.com/PediatricOpenTargets/ticket-tracker/issues/435
   - https://github.com/PediatricOpenTargets/ticket-tracker/issues/366
   - https://github.com/PediatricOpenTargets/ticket-tracker/issues/415
   - https://github.com/PediatricOpenTargets/ticket-tracker/issues/426
   - https://github.com/PediatricOpenTargets/ticket-tracker/issues/484
   - https://github.com/PediatricOpenTargets/ticket-tracker/issues/479
   - https://github.com/PediatricOpenTargets/ticket-tracker/issues/477
   - https://github.com/PediatricOpenTargets/ticket-tracker/issues/399
   - https://github.com/PediatricOpenTargets/ticket-tracker/issues/454
   - https://github.com/PediatricOpenTargets/ticket-tracker/issues/481
   - https://github.com/PediatricOpenTargets/ticket-tracker/issues/492

- Updates for molecular subtyping 
   - https://github.com/PediatricOpenTargets/OpenPedCan-analysis/pull/287
   - https://github.com/PediatricOpenTargets/ticket-tracker/issues/392
   - https://github.com/PediatricOpenTargets/ticket-tracker/issues/425
   - https://github.com/PediatricOpenTargets/ticket-tracker/issues/424
   - https://github.com/PediatricOpenTargets/ticket-tracker/issues/439
   - https://github.com/PediatricOpenTargets/ticket-tracker/issues/449
   - https://github.com/PediatricOpenTargets/ticket-tracker/issues/451
   - https://github.com/PediatricOpenTargets/ticket-tracker/issues/417
   - https://github.com/PediatricOpenTargets/ticket-tracker/issues/489
   - https://github.com/PediatricOpenTargets/ticket-tracker/issues/474
   - https://github.com/PediatricOpenTargets/ticket-tracker/issues/358
   - https://github.com/PediatricOpenTargets/ticket-tracker/issues/496
   - https://github.com/PediatricOpenTargets/ticket-tracker/issues/504

-  Updates related to  PedcbioPortal 
    - https://github.com/PediatricOpenTargets/ticket-tracker/issues/375

- Updates related to methylation analyses
   - https://github.com/PediatricOpenTargets/ticket-tracker/issues/404
   - https://github.com/PediatricOpenTargets/ticket-tracker/issues/434
   - https://github.com/PediatricOpenTargets/ticket-tracker/issues/391
   - https://github.com/PediatricOpenTargets/ticket-tracker/issues/421
   - https://github.com/PediatricOpenTargets/ticket-tracker/issues/371
   - https://github.com/PediatricOpenTargets/ticket-tracker/issues/478
   - https://github.com/PediatricOpenTargets/ticket-tracker/issues/430

- General module or analyses updates need for v12 data release
   - https://github.com/PediatricOpenTargets/ticket-tracker/issues/447
   - https://github.com/PediatricOpenTargets/ticket-tracker/issues/491
   - https://github.com/PediatricOpenTargets/ticket-tracker/issues/493
   - https://github.com/PediatricOpenTargets/ticket-tracker/issues/494
   - https://github.com/PediatricOpenTargets/ticket-tracker/issues/494
   - https://github.com/PediatricOpenTargets/ticket-tracker/issues/507
   - https://github.com/PediatricOpenTargets/ticket-tracker/issues/480
   - https://github.com/PediatricOpenTargets/ticket-tracker/issues/503

- Updates related to EFO, MONDO, and GENCODE annotations
   - https://github.com/PediatricOpenTargets/ticket-tracker/issues/420
   - https://github.com/PediatricOpenTargets/ticket-tracker/issues/422
   - https://github.com/PediatricOpenTargets/ticket-tracker/issues/423
   - https://github.com/PediatricOpenTargets/ticket-tracker/issues/488
   - https://github.com/PediatricOpenTargets/ticket-tracker/issues/487
   - https://github.com/PediatricOpenTargets/ticket-tracker/issues/486
   - https://github.com/PediatricOpenTargets/ticket-tracker/issues/485
   
-  data release 
   - https://github.com/PediatricOpenTargets/ticket-tracker/issues/437
   - https://github.com/PediatricOpenTargets/ticket-tracker/issues/436

-  bix-dev app and toolkit development
   -  https://github.com/PediatricOpenTargets/ticket-tracker/issues/456
   - https://github.com/PediatricOpenTargets/ticket-tracker/issues/490
  
- Upstream data harmonization and processing 
   - https://github.com/PediatricOpenTargets/ticket-tracker/issues/406
   - https://github.com/PediatricOpenTargets/ticket-tracker/issues/429
   - https://github.com/d3b-center/bixu-tracker/issues/1694
   - https://github.com/PediatricOpenTargets/ticket-tracker/issues/416
   - https://github.com/PediatricOpenTargets/ticket-tracker/issues/427
   - https://github.com/PediatricOpenTargets/ticket-tracker/issues/428
   - https://github.com/PediatricOpenTargets/ticket-tracker/issues/430
   - https://github.com/PediatricOpenTargets/ticket-tracker/issues/480

**Comment by jharenza** [comment]
Closed with https://github.com/PediatricOpenTargets/OpenPedCan-analysis/pull/321
