### ISSUE TITLE
Bix Dev PedcbioPortal Support: update OPC v11 to include cohorts N>=3

### ISSUE THREAD

**Issue by jharenza** [PediatricOpenTargets/ticket-tracker#438]
# 🆘

#### [Required] How would you most generally describe your issue? 
- [x] Update data for project in pedcbio portal
- [ ] Questions related to data on pedcbio portal 

### Ticket will be considered resolved either by a successful PR with updated release if applicable, or a simple denial of the request backed by a good reason

Please update the case lists using N >=3
Please also remove DGD DNA data.

**Comment by migbro** [comment]
Related to https://github.com/PediatricOpenTargets/ticket-tracker/issues/419
This part of the request: `Please also remove DGD DNA data.`
Can be done, but will take a but of time to remove from maf, data sample, data patient, and case lists

**Comment by migbro** [comment]
Latest load should address the missing case list issue. DGD on hold, maybe as another or part of another ticket: https://pedcbioportal.kidsfirstdrc.org/study/summary?id=openpedcan_v11
