### ISSUE TITLE
merge CNV files for v6

### ISSUE THREAD

**Issue by jharenza** [PediatricOpenTargets/ticket-tracker#44]
#### What data file(s) does this issue pertain to?
ControlFREEC GMKF NBL, PBTA files
CNVkit GMKF NBL, PBTA files

#### What release are you using?

v5

#### Put your question or report your issue here.
Currently, we do not have CNVs in the release.

Step 1. (@zhangb1's team) Merge CNV files using v5 `histologies.tsv` for GMKF NBL + PBTA to create `cnv-controlfreec.tsv.gz` and `cnv-cnvkit.tsv.gz`

Step 2. (@kgaonkar6) Create 
```
pbta-cnv-consensus.seg.gz
consensus_seg_annotated_cn.tsv.gz
```

Add to `s3://kf-openaccess-us-east-1-prd-pbta/open-targets/v6/`

**Comment by jharenza** [comment]
@zhangb1 what will be your eta on this so we can plan? Possible to get done by end of this week? Thanks!

**Comment by zhangb1** [comment]
@jharenza  for this  PBTA  merge, should I use the v19 files?  Thank you.

**Comment by jharenza** [comment]
> @jharenza for this large file merge , the PBTA file, should I use the v19 files? Thank you.

yes, that'll do

**Comment by zhangb1** [comment]
@jharenza @kgaonkar6 

I upload the merged files 
```
cnv-cnvkit.tsv.gz
cnv-controlfreec.tsv.gz
```
to the  v6 folder : s3://kf-openaccess-us-east-1-prd-pbta/open-targets/v6/

also I attached the kf-nbl only merge file here if needed:

[kf-nbl-cnv-cnvkit.tsv.gz](https://github.com/PediatricOpenTargets/ticket-tracker/files/6704730/kf-nbl-cnv-cnvkit.tsv.gz)
[kf-nbl-cnv-controlfreec.tsv.gz](https://github.com/PediatricOpenTargets/ticket-tracker/files/6704736/kf-nbl-cnv-controlfreec.tsv.gz)

**Comment by kgaonkar6** [comment]
Thanks! 

@jharenza just confirming, have we decided to do 2 of 2 cnv consensus calls for all of OpenPedCan? Just wondering since PBTA and GMKF have WGS so we could add manta for the consensus CNV calls as well.

**Comment by jharenza** [comment]
> Thanks! 
> 
> 
> 
> @jharenza just confirming, have we decided to do 2 of 2 cnv consensus calls for all of OpenPedCan? Just wondering since PBTA and GMKF have WGS so we could add manta for the consensus CNV calls as well. 
> 
> 

Oh shoot - no, we will do 2/3  for WGS using Manta as well. Sorry @zhangb1 - can you also add the manta merged file?

For WXS samples, we will use CNVkit only for now and revisit consensus after august.

**Comment by zhangb1** [comment]
Sure. running the annotSV now. should finish the merge by today or tomorrow.

**Comment by kgaonkar6** [comment]
Thanks Bo!

**Comment by zhangb1** [comment]
@kgaonkar6 

```
sv-manta.tsv.gz
```
mantaSV file also uploaded in the  s3://kf-openaccess-us-east-1-prd-pbta/open-targets/v6/ 

kf-nbl only SV file is large, I can't upload here , if you need I can transfer to you.

**Comment by kgaonkar6** [comment]
Thanks! 
Just clarifying `sv-manta.tsv.gz` is PBTA+ GMKF NBL right? Then we don't need the KF-NBL only files in s3.

**Comment by zhangb1** [comment]
> Thanks!
> Just clarifying `sv-manta.tsv.gz` is PBTA+ GMKF NBL right? Then we don't need the KF-NBL only files in s3.

Yes , correct.

**Comment by jharenza** [comment]
added with [PR 34](https://github.com/PediatricOpenTargets/OpenPedCan-analysis/pull/34)
