### ISSUE TITLE
Update snv frequencies table with missing pedcbio case set IDs

### ISSUE THREAD

**Issue by ewafula** [PediatricOpenTargets/ticket-tracker#442]
#### What analysis module should be updated and why?
 [snv-frequencies module ](https://github.com/PediatricOpenTargets/OpenPedCan-analysis/tree/dev/analyses/snv-frequencies)

#### What changes need to be made? Please provide enough detail for another participant to make the update.
Update the module with missing  pedcbio portal links and now following @migbro updates 

#### What input data should be used? Which data were used in the version being updated?
get new  [ped_opentargets_v11_pedcbio_case_set_ids.json](https://github.com/PediatricOpenTargets/OpenPedCan-analysis/blob/dev/analyses/snv-frequencies/input/ped_opentargets_v11_pedcbio_case_set_ids.json) from pedcbio portal

#### When do you expect the revised analysis will be completed?
Needed to allow [ticket #433](https://github.com/PediatricOpenTargets/ticket-tracker/issues/433) to be completed. 

#### Who will complete the updated analysis?
@kelseykeith

**Comment by kelseykeith** [comment]
All Cohorts links also need to be modified to exclude panel samples

**Comment by chinwallaa** [comment]
@kelseykeith does this impact @migbro data load into cbio-portal [ticket # ](https://github.com/PediatricOpenTargets/ticket-tracker/issues/441#issuecomment-1289795025)

**Comment by kelseykeith** [comment]
No, the load ticket from this morning was for some missing samples while the issue here is how case lists are defined. We have a discussion on slack going for it

**Comment by kelseykeith** [comment]
Closed with [PR #280](https://github.com/PediatricOpenTargets/OpenPedCan-analysis/pull/280)
