### ISSUE TITLE
[Discussion]: Generating PedcBio Case Lists and Links

### ISSUE THREAD

**Issue by kelseykeith** [PediatricOpenTargets/ticket-tracker#444]
#### What data file(s) does this issue pertain to?

The gene-level `snv-frequencies` data and the corresponding case lists and data in PedcBio Portal.

- `gene-level-snv-consensus-annotated-mut-freq.tsv.gz`
- `gene-level-snv-consensus-annotated-mut-freq.jsonl.gz`

#### What release are you using?

v11 at the moment, but this discussion is intended to be about what we do for future releases

#### Put your question or report your issue here.

We link to PedcBio through a combination of cancer study, case list (aka case set), and gene. The case list is the important linker between OpenPedCan and PedcBio, since its a curated list of samples that belong to some group, ex: `openpedcan_v11_gmkf_neuroblastoma`. In v11, as we added panel data, it was originally included in the "All Cohorts" case list, and when it was later changed to exclude panel data from all cohorts, there's no good way from the OpenPedCan side to create a URL for a different subset of samples and hard and time consuming to reload those sample lists on the PedcBio side. So for the future we want to figure out ways to make this easier

The current issues are:

- Case sets are a burden to create and load both in hands on time to manually curate and put them in PedcBio and in compute time (ex: recently took Miguel like 3 hours to load a handful of samples)
- As we increase the number of caselists, the load time for the study increases, so we won’t be able to keep adding infinite lists to make links so specialized. For example, one way around our panel issue would be to include `experimental_strategy` in the case lists, although that would increase the number of lists by three times.
- Although the same samples are in PedcBio as OpenPedCan, the IDs are slightly different due to how PedcBio treats subject IDs and biospecimen IDs differently than OpenPedCan so making case lists is not totally straightforward

Potential solutions:

- Could create a module in OpenPedCan-analysis to generate the case lists by sample IDs so there's better communication with and it's easier for PedcBio devs and gives us more control over what we want in the case lists

@jharenza is there anything else you'd like to add in?

**Comment by chinwallaa** [comment]
@migbro @logstar not sure if relevant here, but there is also the issue where cbioportal uses a different ensemble version (gene names) to what OpenPedCan uses.

**Comment by chinwallaa** [comment]
@migbro -sorry didnt mean to imply changes to the cbio side -  question is whether we need an additional filter/mapping to conform with the cBio side when we link out? similar to filtering the tables for when we deliver to FNL for OT based on the  reference versions OT is using

**Comment by kelseykeith** [comment]
@migbro Sorry didn't mean to imply we were asking for any changes now! The point of this discussion is supposed to be how to minimize that in the future. As far as I know, we're not planning on making any changes until early next year with v12

@chinwallaa There's nothing in the `snv-frequencies` module or anywhere else at the moment that matches up gene names as far as I know so that may be something we want to consider updating in the module in the next round. I think Jo Lynne mainly wanted to have a discussion about case lists though

**Comment by jharenza** [comment]
Closing for now. If needed, we can reopen later.
