### ISSUE TITLE
Create DW dbt tables for OT histologies mapping files

### ISSUE THREAD

**Issue by ewafula** [PediatricOpenTargets/ticket-tracker#445]
#### What are the scientific goals of the analysis?
Create data warehouse dbt tables for OT histologies mapping files 

#### What methods do you plan to use to accomplish the scientific goals?
 _`Code snippets included for creating mapping files from the OpenPedCan histologies.tsv 
`_
1. Create dbt table for the `CNS` mapping file 
```
readr::read_tsv("OpenPedCan-analysis/data/histologies.tsv") %>% 
  dplyr::filter(!is.na(CNS_region), sample_type == "Tumor") %>%
  dplyr::select(CNS_region, primary_site) %>%  
  dplyr::distinct() %>% 
  dplyr::arrange(CNS_region) %>%
  readr::write_csv("CNS_primary_site_match.csv")
```

2. Create dbt table for the `pathology diagnosis` mapping file 
```
readr::read_tsv("OpenPedCan-analysis/data/histologies.tsv") %>% 
  dplyr::select(pathology_diagnosis, broad_histology, short_histology) %>% 
  dplyr::filter(pathology_diagnosis != "Other" & 
                  pathology_diagnosis != "Wilms tumor") %>% 
  dplyr::arrange(pathology_diagnosis) %>% 
  dplyr::distinct() %>% 
  tidyr::drop_na() %>% 
  readr::write_csv("pathology_diagnosis_mapping.csv")
```
3. Create dbt table for the `pathology free text diagnosis` mapping file 
```
readr::read_tsv("OpenPedCan-analysis/data/histologies.tsv") %>%
  dplyr::select(pathology_free_text_diagnosis, broad_histology, 
                short_histology) %>% 
  dplyr::mutate(pathology_free_text_diagnosis = case_when(
    pathology_free_text_diagnosis == 
      "/residual pilocytic astrocytoma with kiaa1549- braf fusion, who grade i" ~ 
      "recurrent/residual pilocytic astrocytoma with kiaa1549- braf fusion, who grade i", 
    TRUE ~ pathology_free_text_diagnosis)) %>% 
  dplyr::mutate(short_histology = case_when(
    short_histology == "Embryonal tumor" ~ "Ependymoma", 
    short_histology == "Acute Lymphoblastic Leukemia" ~ "ALL", 
    TRUE ~ short_histology)) %>% 
  dplyr::arrange(pathology_free_text_diagnosis) %>% 
  dplyr::distinct() %>% 
  dplyr::drop_na() %>% 
  readr::write_csv("pathology_free_text_diagnosis_mapping.csv")
```
4. Create a `data/` directory with the [histologies-qc](https://github.com/d3b-center/histologies-qc) repo where the OT team can submit PRs for updated mapping files to be converted to dbt tables and upload the data warehouse by the D3b bix-dev team. Alternatively, create a new repo similar to the [d3b-dbt-study-transforms](https://github.com/d3b-center/d3b-dbt-study-transforms) repo where OT team currently submits PRs for updated cohort base histologies files to be transformed dbt tables and upload the data warehouse. 

#### What input data are required for this analysis?
v11 OpenPedCan `histologies.tsv`

#### How long do you expect is needed to complete the analysis? Will it be a multi-step analysis?
?

#### Who will complete the analysis (please add a GitHub handle here if relevant)?
@HuangXiaoyan0106 

#### What relevant scientific literature relates to this analysis?
NA

**Comment by ewafula** [comment]
@aadamk,  I forgot to copy you on this ticket.  Any additional suggestions?
Cc @jharenza

**Comment by aadamk** [comment]
thanks @ewafula 
is there a plan to include GTEx mappings here as well, or are those already in the warehouse?

**Comment by jharenza** [comment]
Hi @aadamk we have a [PR](https://github.com/d3b-center/d3b-dbt-study-transforms/pull/23) in for Nick to add them to the WH histologies view, so not in yet

**Comment by jharenza** [comment]
@ewafula can you create the tables and put them here or maybe put the code in either d3b codes or in the qc-histologies repo with the tables as output - @baileyckelly will put the tables in for us.

**Comment by ewafula** [comment]
Sure. Will do.

**Comment by ewafula** [comment]
@jharenza,  @baileyckelly, mapping files upload here on the ticket:
[pathology_free_text_diagnosis_mapping.tsv.gz](https://github.com/PediatricOpenTargets/ticket-tracker/files/9942665/pathology_free_text_diagnosis_mapping.tsv.gz)
[pathology_diagnosis_mapping.tsv.gz](https://github.com/PediatricOpenTargets/ticket-tracker/files/9942666/pathology_diagnosis_mapping.tsv.gz)
[CNS_primary_site_match.tsv.gz](https://github.com/PediatricOpenTargets/ticket-tracker/files/9942667/CNS_primary_site_match.tsv.gz)

**Comment by jharenza** [comment]
@HuangXiaoyan0106 can you add these tables in the `histologies_workflows` schema? cc @yuankunzhu
