### ISSUE TITLE
Obtain ploidy for GMKF NBL samples for CNV analysis

### ISSUE THREAD

**Issue by jharenza** [PediatricOpenTargets/ticket-tracker#45]
#### What data file(s) does this issue pertain to?
`histologies.tsv`

#### What release are you using?

v5

#### Put your question or report your issue here.
We will need to add ploidy into the histologies file for use in the consensus CNV module. For this ticket, please gather ploidy by BS_ID and add here.

**Comment by jharenza** [comment]
cc @yuankunzhu

**Comment by zhangb1** [comment]
[Maris_tumor_ploidy_visible.txt](https://github.com/PediatricOpenTargets/ticket-tracker/files/6702843/Maris_tumor_ploidy_visible.txt)

@jharenza  I listed the tumor ploidy for Maris data here: there is a BS_ID and ploidy in column 3 and 4.

let me know any questions

**Comment by jharenza** [comment]
Perfect, thank you!
