### ISSUE TITLE
Update mutational-signatures analysis module

### ISSUE THREAD

**Issue by rjcorb** [PediatricOpenTargets/ticket-tracker#453]
#### What analysis module should be updated and why?

The [mutational-signatures analysis module](https://github.com/PediatricOpenTargets/OpenPedCan-analysis/tree/dev/analyses/mutational-signatures) should be updated to include the same analysis scripts as are included in the [mutational-signature OpenPBTA-analysis module](https://github.com/AlexsLemonade/OpenPBTA-analysis/tree/master/analyses/mutational-signatures). 

#### What changes need to be made? Please provide enough detail for another participant to make the update.

The following R scripts from he OpenPBTA-analysis mutational-signatures module should be added to the OpenPedCan analysis module: 
- `04-analyze_de_novo.Rmd`
- `05-fit_cns_signatures.R`
- `06-compare_cns_exposures.Rmd`
- `07-plot_cns_fit.Rmd`
- `08-explore_hypermutators.Rmd`

#### What input data should be used? Which data were used in the version being updated?

- Consensus SNV caller files

#### When do you expect the revised analysis will be completed?

1 week

#### Who will complete the updated analysis?

@rjcorb

**Comment by jharenza** [comment]
closed with https://github.com/PediatricOpenTargets/ticket-tracker/issues/322
