### ISSUE TITLE
Create a CAVATICA OPC methylation-summary module app

### ISSUE THREAD

**Issue by ewafula** [PediatricOpenTargets/ticket-tracker#456]
# ✨

#### [Required] Is this a new tool/workflow?
- Yes

#### Provide software links and `dockerPull` location if applicable
- the methylation-summary module scripts and documentation here:
   - https://github.com/PediatricOpenTargets/OpenPedCan-analysis/tree/update-methyl-summary/analyses/methylation-summary
- needs to wait until after [PR #278](https://github.com/PediatricOpenTargets/OpenPedCan-analysis/pull/278) has been approved and merged. 

#### Add reference files and test input locations if applicable
- all parameters, inputs, outputs, and software dependencies  described in the [methylation-summary module README](https://github.com/PediatricOpenTargets/OpenPedCan-analysis/blob/update-methyl-summary/analyses/methylation-summary/README.md)
- all the module scripts include command-line options to enable easy implementation in CAVATICA

#### [Optional] How long do you think this work will take?
- For OPC v12 data release

#### [Optional] Who will complete this work?
- D3b bix-dev team

**Comment by sickler-alex** [comment]
Are the v12 data for this ready or should I just test the workflow with the v11 data, once I'm ready to start testing?

**Comment by jharenza** [comment]
You can work with v11 - @zhangb1 will be processing the v12 data soon

**Comment by sickler-alex** [comment]
Where will this be run? @yuankunzhu seems to think that this will be included in the monthly process which is run by an Airflow DAG. If that's the case, then we can just use the shell script that already exists to run this module. Do we need to run this on Cavatica or as a cwl workflow?

**Comment by sickler-alex** [comment]
Separate from my question above, I built a docker for this module to run it within the workflow since the current OPC docker is using an our of date R version. Once it's ready, where should it stay? I have the Dockerfile in the module and I uploaded the docker image to my docker hub so I can test it on Cavatica. The docker image will have to move to SBG's hosted docker repo since you can only download a docker image a certain number of times before you need a paid dockerhub account.

**Comment by ewafula** [comment]
@sickler-alex, hold to this until when [ticket #478](https://github.com/PediatricOpenTargets/ticket-tracker/issues/478) is completed. These changes are needed for v12   MTP methylation tables. 

I will update the module on your [PR #307](https://github.com/PediatricOpenTargets/OpenPedCan-analysis/pull/307) branch to avoid multiple merges.

**Comment by jharenza** [comment]
This is no longer needed.
