### ISSUE TITLE
Updated OPC documentation and data release note

### ISSUE THREAD

**Issue by ewafula** [PediatricOpenTargets/ticket-tracker#458]
#### What analysis module should be updated and why?
Update OpenPedCan [documentation](https://github.com/PediatricOpenTargets/documentation) and [release notes](https://github.com/PediatricOpenTargets/OpenPedCan-analysis/blob/4fb04fe60754b90da3c241dbb8b727c3722487cc/doc/release-notes.md) for MTP v1.1 release. 

#### What changes need to be made? Please provide enough detail for another participant to make the update.

- update the documentation repo to reflect the v11.1 data? We'll use this as the catch-all link when sourcing OpenPedCan throughout MTP.
- create release notes for v11

#### What input data should be used? Which data were used in the version being updated?
- Current OpenPedCan v11  data release 
-  Need to include a note stating `DGD DNA` samples are not included in MTP v1.1 SNV mutation frequencies tables

#### When do you expect the revised analysis will be completed?
1/2 days

#### Who will complete the updated analysis?
@kelseykeith

**Comment by kelseykeith** [comment]
Closed with https://github.com/PediatricOpenTargets/documentation/pull/8
