### ISSUE TITLE
Proposed Analysis: Create metadata table

### ISSUE THREAD

**Issue by jharenza** [PediatricOpenTargets/ticket-tracker#459]
#### What are the scientific goals of the analysis?
Create Table S1 for future manuscript to contain the histologies file along with a README

#### What methods do you plan to use to accomplish the scientific goals?
Using similar code as here, create a readme for the histologies file and output the table: https://github.com/AlexsLemonade/OpenPBTA-analysis/blob/master/tables/output_tables.Rmd

#### What input data are required for this analysis?
histologies.tsv

#### How long do you expect is needed to complete the analysis? Will it be a multi-step analysis?
<1 day

#### Who will complete the analysis (please add a GitHub handle here if relevant)?
@adilahiri 

#### What relevant scientific literature relates to this analysis?
NA

**Comment by adilahiri** [comment]
Hello @jharenza or @ewafula 
Just wanted to clarify a few queries 

1. Is this table going to be similar to the current [TableS1-histologies.xlsx](https://github.com/AlexsLemonade/OpenPBTA-analysis/blob/master/tables/results/TableS1-histologies.xlsx) but excluding the tab for CNS_region_definitions ?

2. Where will the code and resulting table files will be deposited ? 

Thank you.

**Comment by jharenza** [comment]
We can make a `tables` directory in the root of the repo, similar to OpenPBTA. For now, I think just adding the README and the histology tab of the excel will be perfect. If we want to add more tabs later for the paper, can do so later! There are just a few columns new from OpenPBTA, so want to be sure we add/cross check with what we have here. Thanks!
