### ISSUE TITLE
 v12 DESeq2 RNA-Seq tumor-normal(GTEx) analysis

### ISSUE THREAD

**Issue by ewafula** [PediatricOpenTargets/ticket-tracker#461]
#### What are the scientific goals of the analysis?
- DESeq2 OpenPedCan RNA-Seq tumor-normal(GTex) analysis 
- required for non-batch corrected RNA-Seq DE analysis API plotting 
- Should be performed following reprocessing of TARGET and GMKF (NBL Maris FY16) RNA-Seq datasets to Gencode v39 for OPenPedCan v12 data release [ticket #428](https://github.com/PediatricOpenTargets/ticket-tracker/issues/428)

#### What methods do you plan to use to accomplish the scientific goals?
Run the v12 release expression counts matrix through the OpenPedCan DESeq2 CAVATICA pipeline 

#### What input data are required for this analysis?
Re-harmonized v12 data release gene expression counts data matrix 
- `gene-counts-rsem-expected_count-collapsed.rds` 

#### How long do you expect is needed to complete the analysis? Will it be a multi-step analysis?
?

#### Who will complete the analysis (please add a GitHub handle here if relevant)?
bix-ops team

#### What relevant scientific literature relates to this analysis?
NA

**Comment by ewafula** [comment]
@zhangb1, DESeq2 analysis needs to be performed on cancer using @sangeetashukla DESeq2 module workflow on CAVATICA.  @sangeetashukla, please provide @zhangb1 details on how this needs to be performed.

**Comment by zhangb1** [comment]
For the v12 files, I imported to the project folder : https://cavatica.sbgenomics.com/u/shuklas1/tumor-normal-differential-expression/files/#q?path=v12

@sangeetashukla  let me know those inputs are good for running the workflow or not

**Comment by zhangb1** [comment]
Below these two files are missing in the v12 folder

```
independent-specimens.rnaseq.primary.tsv
independent-specimens.rnaseq.primary.eachcohort.tsv
```

But I saw some similar files in the v12, which two I should use for the input?

```
independent-specimens.rnaseq.primary-plus-pre-release.tsv
independent-specimens.rnaseq.primary-pre-release.tsv
independent-specimens.rnaseq.relapse-pre-release.tsv
independent-specimens.rnaseqpanel.primary-plus.eachcohort.tsv
independent-specimens.rnaseqpanel.primary-plus.tsv
independent-specimens.rnaseqpanel.primary.eachcohort.tsv
independent-specimens.rnaseqpanel.primary.tsv
independent-specimens.rnaseqpanel.relapse.eachcohort.tsv
independent-specimens.rnaseqpanel.relapse.tsv
```
@ewafula @sangeetashukla ?

**Comment by ewafula** [comment]
@sangeetashukla, can you help with instructions run the workflow similar to your previous DESEq2 runs?

**Comment by zhangb1** [comment]
```
0441ecdf2c9ea16bcbdcc3450d2bee64  gene-counts-rsem-expected_count-collapsed-deseq.jsonl
ac60c047074aab066a676e31ee6f2b4e  gene-counts-rsem-expected_count-collapsed-deseq.tsv
```
the expression results are in the v12 folder, md5 get updated , @ewafula @sangeetashukla

**Comment by ewafula** [comment]
Thank you, @Bo and @sangeetashukla, for working on this.

@afarrel and @logstar, can you please review the v12 DESeq results available on s3 when you can?

Cc @chinwallaa

**Comment by jharenza** [comment]
This has been completed on the HPC by @sangeetashukla
