### ISSUE TITLE
Update dev documentation

### ISSUE THREAD

**Issue by kelseykeith** [PediatricOpenTargets/ticket-tracker#462]
#### What analysis module should be updated and why?

MTP [documentation](https://github.com/PediatricOpenTargets/documentation) dev branch should be updated with some requested text and code changes to the sample count code and to merge back changes made to the main branch when updating for MTP release v1.1.

#### What changes need to be made? Please provide enough detail for another participant to make the update.

- Changes made during review for the MTP release v1.1 need to be merged back to the dev branch.
- Requested text changes to the documentation README
  - Need a sustainable way to reference previous versions of the documentation. Current suggestions are linking both to the previous version and the folder where previous versions live or having a table of previous versions.
  - Add equation instead of or in addition to the text description of the frequency calculation.
- @jharenza requested code changes to the sample count code https://github.com/PediatricOpenTargets/documentation/pull/8#discussion_r1036646711
  - Move variables to the beginning of the line to align with OpedPedCan code style
  - Make the tables in the Rmd interactive
  - Change "Number of Biospecimens" to "Number of Tumors" in the dataset count table in the README

#### What input data should be used? Which data were used in the version being updated?

OpenPedCan-analysis submodule pinned to the (at the time of ticket writing) current v1.1 release

#### When do you expect the revised analysis will be completed?

Revisions shouldn't take more than 1 day

#### Who will complete the updated analysis?

@kelseykeith

**Comment by kelseykeith** [comment]
This has not been completed, re-opening

**Comment by ewafula** [comment]
Thought you already complete documentation for MTP v1.1 😃

**Comment by kelseykeith** [comment]
Nope, this is a separate ticket! For fixing things that weren't urgent for the v1.1 update

**Comment by ewafula** [comment]
👍
