### ISSUE TITLE
Updated  v12 data release notes

### ISSUE THREAD

**Issue by ewafula** [PediatricOpenTargets/ticket-tracker#463]
#### What analysis module should be updated and why?
Updated OpenPedCan [data release notes](https://github.com/PediatricOpenTargets/OpenPedCan-analysis/blob/dev/doc/release-notes.md)

#### What changes need to be made? Please provide enough detail for another participant to make the update.
progressively  keep updating the v12 OpenPedCan data release notes 

#### What input data should be used? Which data were used in the version being updated?
NA

#### When do you expect the revised analysis will be completed?
With the v12 data release

#### Who will complete the updated analysis?
@ewafula

**Comment by jharenza** [comment]
Closed with https://github.com/PediatricOpenTargets/OpenPedCan-analysis/pull/321
