### ISSUE TITLE
add 'signature.tools.lib' package to Dockerfile

### ISSUE THREAD

**Issue by rjcorb** [PediatricOpenTargets/ticket-tracker#464]
The `signature.tools.lib` R package needs to be added to the Dockerfile to run adult CNS mutational signature analysis in the [mutational-signatures analysis module](https://github.com/PediatricOpenTargets/OpenPedCan-analysis/tree/dev/analyses/mutational-signatures). 

Will be completed by @rjcorb.

**Comment by jharenza** [comment]
closed with https://github.com/PediatricOpenTargets/OpenPedCan-analysis/pull/295
