### ISSUE TITLE
Create list of PBTA and TARGET BS_ids for v12 release

### ISSUE THREAD

**Issue by jharenza** [PediatricOpenTargets/ticket-tracker#475]
@bmennis can you create a list of all TARGET BS_IDs which will be contained in the v12 release, based on the gencode RNA-Seq harmonization and DNA annotations? 

@zhangb1 can you create a list of all BS_IDs we will include for samples which were harmonized for PBTA X01, "oligo", chordoma foundation, new DGD MAF, HOPE non-Penn samples which have been harmonized to date?

**Comment by zhangb1** [comment]
> @zhangb1 can you create a list of all BS_IDs we will include for samples which were harmonized for PBTA X01, "oligo", chordoma foundation, new DGD MAF, HOPE non-Penn samples which have been harmonized to date?

@jharenza  should I list all the BS ID, like Normal only or Tumor only also?

**Comment by jharenza** [comment]
Yes, all that are ready to be released! Thanks!

**Comment by zhangb1** [comment]
[chordoma_foundation_BS_ID.txt](https://github.com/PediatricOpenTargets/ticket-tracker/files/10347417/chordoma_foundation_BS_ID.txt)
[DGD_maf_BS_ID.txt](https://github.com/PediatricOpenTargets/ticket-tracker/files/10347418/DGD_maf_BS_ID.txt)
[oligo_BS_ID.txt](https://github.com/PediatricOpenTargets/ticket-tracker/files/10347419/oligo_BS_ID.txt)
[PBTA_X01_BS_ID.txt](https://github.com/PediatricOpenTargets/ticket-tracker/files/10347420/PBTA_X01_BS_ID.txt)

@jharenza  please see the files here,  project-hope data is tricky now, some the results are removed from the NCI bukcet, they are not recovered..... I may need to address that later

**Comment by jharenza** [comment]
@bmennis Can you provide a list of all TARGET bs_ids for v12, or was everything TARGET v11 included in the re-harm/re-ann? If the latter, not needed. Thanks!

**Comment by jharenza** [comment]
> [chordoma_foundation_BS_ID.txt](https://github.com/PediatricOpenTargets/ticket-tracker/files/10347417/chordoma_foundation_BS_ID.txt) [DGD_maf_BS_ID.txt](https://github.com/PediatricOpenTargets/ticket-tracker/files/10347418/DGD_maf_BS_ID.txt) [oligo_BS_ID.txt](https://github.com/PediatricOpenTargets/ticket-tracker/files/10347419/oligo_BS_ID.txt) [PBTA_X01_BS_ID.txt](https://github.com/PediatricOpenTargets/ticket-tracker/files/10347420/PBTA_X01_BS_ID.txt)
> 
> @jharenza please see the files here, project-hope data is tricky now, some the results are removed from the NCI bukcet, they are not recovered..... I may need to address that later

@zhangb1 it looks like this X01 only has WGS. Do you have the bs_ids for RNA-Seq X01?

**Comment by zhangb1** [comment]
@jharenza  are we sharing the ploya based stranded RNAseq samples?  Those are from Broad ploya based stranded RNAseq  , will be resequenced in the future.

**Comment by jharenza** [comment]
Ye sharing polyA now then stranded later

**Comment by zhangb1** [comment]
[PBTA_X01_RNAseq_BS_ID.txt](https://github.com/PediatricOpenTargets/ticket-tracker/files/10361265/PBTA_X01_RNAseq_BS_ID.txt)

@jharenza  this is the RNAseq data we harmonized from Broad this batch

**Comment by bmennis** [comment]
> @bmennis Can you provide a list of all TARGET bs_ids for v12, or was everything TARGET v11 included in the re-harm/re-ann? If the latter, not needed. Thanks!

@jharenza the TARGET v12 IDs match the v11 IDs, we re harmonized based off of that list of IDs
