### ISSUE TITLE
[Discussion]: Methylation MTP tables

### ISSUE THREAD

**Issue by ewafula** [PediatricOpenTargets/ticket-tracker#478]
#### What are the scientific goals of the analysis?

 Create condensed methylation analysis tables for either display or available for download on the MTP portal. 

#### What methods do you plan to use to accomplish the scientific goals?
- Create a condensed version of the current probe-level methylation summary tables from to gene/isoform-level by using either medians  or averages of the summary values (beta and tpm) per disease in each cohort
 - @chinwallaa, suggests that we discuss this issue, considering the methylation analyses tables are too large and will become even additional methylation array data comes in. 

Current file sizes for v11 data release:
 ```
[wafulae@reslnvvhpc0104 methylation-summary]$ ls -lhrt results
total 47G
-rwxrwx---. 1 wafulae opentargets  37M Jan  5 16:58 methyl-probe-annotations.tsv.gz
-rwxrwx---. 1 wafulae opentargets 1.4G Jan  5 18:38 methyl-probe-beta-quantiles.tsv.gz
-rwxrwx---. 1 wafulae opentargets 287M Jan  5 19:00 gene-methyl-probe-beta-tpm-correlations.tsv.gz
-rwxrwx---. 1 wafulae opentargets 2.2G Jan  5 23:06 isoform-methyl-probe-beta-tpm-correlations.tsv.gz
-rwxrwx---. 1 wafulae opentargets  25M Jan  6 11:01 methyl-tpm-transcript-representation.tsv.gz
-rwxrwx---. 1 wafulae opentargets 6.8G Jan  6 11:34 gene-methyl-beta-values-summary.rds
-rwxrwx---. 1 wafulae opentargets 1.7G Jan  6 11:34 gene-methyl-beta-values-summary.tsv.gz
-rwxrwx---. 1 wafulae opentargets  40G Jan  6 14:26 isoform-methyl-beta-values-summary.rds
-rwxrwx---. 1 wafulae opentargets 3.9G Jan  6 14:28 isoform-methyl-beta-values-summary.tsv.gz
-rwxrwx---. 1 wafulae opentargets 2.1G Jan  6 15:13 gene-methyl-beta-values-summary.jsonl.gz
-rwxrwx---. 1 wafulae opentargets 4.3G Jan  6 18:01 isoform-methyl-beta-values-summary.jsonl.gz
```

#### What input data are required for this analysis?
- gene-methyl-beta-values-summary.tsv
- isoform-methyl-beta-values-summary.tsv

**Comment by afarrel** [comment]
[Methylation_Summary_Table_design.xlsx](https://github.com/PediatricOpenTargets/ticket-tracker/files/10583563/Methylation_Summary_Table_design.xlsx)
Hi @ewafula. I think if we add two columns do the current summary tables, this can be used for the MTP tables. The tables would have to be an API call on the evidence page. The API call will call a disease and a gene and a subset of the table can be retrieved and displayed on MTP. The two additional columns will include the gene features of the transcript (promoter/5'UTR/exons/intros/3'UTR/3' downstream) and also the transcript expression. The table should be sorted firstly by transcripts with the highest representation (expression). Within each transcript, the probes should be shorted from promoter region to 3' downstream region. This would make it easier for a user to make sense of the data. The xlsx table has a mock table with just a few lines to give you an idea. Also, `targetFromSourceId` can be labled `Ensembl_ID`, `diseaseFromSourceMappedId`can be renamed also. Let's discuss alternatives.

**Comment by ewafula** [comment]
@afarrel, I am assuming the suggested update to the `methylation-summary` module will only need to extend the isoform summary table (`isoform-methyl-beta-values-summary.tsv.gz`) to include the `Gene_Feature` and `Median_Transcript_Expression`. The gene summary table (`gene-methyl-beta-values-summary.tsv.gz`) does not to be extended. 

A few comments and questions: 

1). For the gene region feature column (`Gene_Feature`) describing the CpG position, I think it would be prudent to only include CpG feature annotations associated with the probe/position that are in the Illumina Infinium probe manifest. In the last `methylation-summary` module update, we include all annotated GENECODE v39 locus transcripts for API plotting purposes even if they were not identified as the methylated transcripts in the array probe manifest.  These transcripts not  included in the array probe manifest can be set to `NA` the `Gene_Feature` column. Otherwise, if annotate all transcripts in the summary table, including the unmethylated,  it will require a bit more work (maybe another module?) to transform CpG coordinates from GRCh37 (arrays) to GRCh38 (GENECODE v39), then finding the corresponding standard gene features. 

Here are the CpG gene region features in the array probe manifest with some description gleaned from literature:
- TSS1500 = 200–1500 bases upstream of the transcriptional start site (TSS)
- TSS200 = 0–200 bases upstream of TSS
- 5′UTR =  between the TSS and the ATG start site
- 3'UTR =  between stop codon and poly-A tail
- 1stExon = first exon of the gene
- ExonBnd = exon boundary 

`Body`, which is the region between ATG start site and stop codon previously in 450k manifest is no longer used in the 850k (EPIC) for the same probes (see attached probe feature mapping file)
```
read_csv("infinium-methylationepic-v-1-0-b5-manifest-file.csv.gz",
           skip = 7, guess_max = 10000) %>% 
  select(GencodeCompV12_Group) %>% 
  separate_rows(GencodeCompV12_Group, sep = ";", convert = FALSE) %>% 
  pull() %>%
  unique()
[1] NA        "TSS200"  "TSS1500" "5'UTR"   "3'UTR"   "1stExon" "ExonBnd"
```
[updated_cpg_annot_mapping_in_epic_arrays.tsv.zip](https://github.com/PediatricOpenTargets/ticket-tracker/files/10613890/updated_cpg_annot_mapping_in_epic_arrays.tsv.zip)


2) Since we don't have sample IDs in the transcripts summary table, median transcript expression will need to be the representative median TPM of cancer group samples for patients with both Methylation and RNA-Seq data in a cohort. Cancer groups whose patients have no RNA-Seq data will be set to NA.  

3) Shouldn't the sorting be done when retrieving from the database on smaller chunks by gene?  I tried sorting on multiple columns within the module as you suggested. The module is implemented to analyze data by cancer group and already takes along time to run. Sorting as you suggested increases run times.

4) Prior v10, we had columns labeled  `Ensembl_ID` and `EFO` for the current `targetFromSourceId` and `diseaseFromSourceMappedId` columns in summary tables respectively. We were are asked to change the label by FNL to to match the implementation on the  MTP portal. 

5)  On average, except approximately 88 (upper end) and 6 (lower end) to will be retrieved for 850k and 450k arrays types respectively ( example with `H3-3A` and  `MYCN` genes symbols) . [See this ticket #197](https://github.com/PediatricOpenTargets/ticket-tracker/issues/197)
```
> read_rds("isoform-methyl-beta-values-summary.rds") %>% 
             filter(Disease == "High-grade glioma/astrocytoma", Dataset == "PBTA", Gene_symbol == "H3-3A")
# A tibble: 88 x 17
   Gene_symbol targetFr~1 trans~2 Dataset Disease disea~3 MONDO RNA_Co~4 Trans~5
   <chr>       <chr>      <chr>   <chr>   <chr>   <chr>   <chr>    <dbl>   <dbl>
 1 H3-3A       ENSG00000~ ENST00~ PBTA    High-g~ MONDO_~ MOND~ -2.87e-1      NA
 2 H3-3A       ENSG00000~ ENST00~ PBTA    High-g~ MONDO_~ MOND~ -1.73e-1      NA
 3 H3-3A       ENSG00000~ ENST00~ PBTA    High-g~ MONDO_~ MOND~ -3.65e-2      NA
 4 H3-3A       ENSG00000~ ENST00~ PBTA    High-g~ MONDO_~ MOND~  2.08e-1      NA
 5 H3-3A       ENSG00000~ ENST00~ PBTA    High-g~ MONDO_~ MOND~ -1.01e-1      NA
 6 H3-3A       ENSG00000~ ENST00~ PBTA    High-g~ MONDO_~ MOND~  2.31e-2      NA
 7 H3-3A       ENSG00000~ ENST00~ PBTA    High-g~ MONDO_~ MOND~  1.85e-1      NA
 8 H3-3A       ENSG00000~ ENST00~ PBTA    High-g~ MONDO_~ MOND~  3.47e-1      NA
 9 H3-3A       ENSG00000~ ENST00~ PBTA    High-g~ MONDO_~ MOND~ -9.52e-2      NA
10 H3-3A       ENSG00000~ ENST00~ PBTA    High-g~ MONDO_~ MOND~  9.40e-4      NA
> 
> read_rds("isoform-methyl-beta-values-summary.rds") %>% 
             filter(Disease == "Neuroblastoma", Dataset == "TARGET", Gene_symbol == "MYCN")
# A tibble: 6 x 17
  Gene_s~1 targe~2 trans~3 Dataset Disease disea~4 MONDO RNA_C~5 Trans~6 Probe~7
  <chr>    <chr>   <chr>   <chr>   <chr>   <chr>   <chr>   <dbl>   <dbl> <chr>  
1 MYCN     ENSG00~ ENST00~ TARGET  Neurob~ EFO_00~ MOND~ -0.0188    35.6 cg1962~
2 MYCN     ENSG00~ ENST00~ TARGET  Neurob~ EFO_00~ MOND~ -0.0160    64.4 cg1962~
3 MYCN     ENSG00~ ENST00~ TARGET  Neurob~ EFO_00~ MOND~ -0.433     64.4 cg0460~
4 MYCN     ENSG00~ ENST00~ TARGET  Neurob~ EFO_00~ MOND~ -0.387     35.6 cg0460~
5 MYCN     ENSG00~ ENST00~ TARGET  Neurob~ EFO_00~ MOND~  0.0613    64.4 cg2507~
6 MYCN     ENSG00~ ENST00~ TARGET  Neurob~ EFO_00~ MOND~  0.0688    35.6 cg2507~
```
6). Won't it better to have the methylation summary tables loaded in the MTP database considering we will still have to provide them with the tables for QC as we do with the TPM expression tables used for API plotting?

@jharenza, @chinwallaa, @logstar and @taylordm,  please chime in before we come to a final decision. Can discuss tomorrow during OT catch meeting.
