### ISSUE TITLE
Cancer group in histologies file needs update

### ISSUE THREAD

**Issue by jharenza** [PediatricOpenTargets/ticket-tracker#48]
#### What data file(s) does this issue pertain to?
histologies.tsv

#### What release are you using?

V5

#### Put your question or report your issue here.
- Two samples are annotated as "Anaplastic" - have to backtrack and update the code for these.
- @kgaonkar6 should we make all other dx of DIPG --> DMG for harm dx, even if not subtyped? Right now, this puts them into two groups so i think it makes sense to update this in openPBTA to be one

**Comment by jharenza** [comment]
The code for this per [this comment](https://github.com/PediatricOpenTargets/ticket-tracker/issues/24#issuecomment-849163143) was:
```
v19_2 <- v19 %>%
  dplyr::mutate(cancer_group = str_extract(harmonized_diagnosis, "[^,]*")) %>%
  dplyr::mutate(cancer_group = str_extract(cancer_group, "[^(]*")) %>%
  dplyr::mutate(cancer_group = case_when(cancer_group == "High-grade glioma/astrocytoma " ~ "High-grade glioma/astrocytoma", 
                                         cancer_group == "Low-grade glioma/astrocytoma " ~ "Low-grade glioma/astrocytoma", 
                                         cancer_group == "Dysembryoplastic neuroepithelial tumor " ~ "Dysembryoplastic neuroepithelial tumor",
                                         cancer_group == "Brainstem glioma- Diffuse intrinsic pontine glioma" ~ "Diffuse intrinsic pontine glioma",
                                         cancer_group == "Atypical Teratoid Rhabdoid Tumor " ~ "Atypical Teratoid Rhabdoid Tumor",
                                         TRUE ~ as.character(cancer_group))) %>%
  filter(experimental_strategy == "RNA-Seq")
```

Selecting up to the parentheses does not work for the `Anaplastic (malignant) meningioma` samples which became `Anaplastic`. These should be `Meningioma`.

**Comment by kgaonkar6** [comment]
hmm are these lines necessary in the case_when() we are assigning the same values ?
```
case_when(cancer_group == "High-grade glioma/astrocytoma " ~ "High-grade glioma/astrocytoma", 
                                         cancer_group == "Low-grade glioma/astrocytoma " ~ "Low-grade glioma/astrocytoma", 
                                         cancer_group == "Dysembryoplastic neuroepithelial tumor " ~ "Dysembryoplastic neuroepithelial tumor",
.....

)
```

**Comment by jharenza** [comment]
Those were only to get rid of trailing spacing - there is probably an easier way :)

**Comment by kgaonkar6** [comment]
ah I see that now! I did add a logic to remove the space at the end

**Comment by jharenza** [comment]
@kgaonkar6 I also noticed a few more things we should update in this field:
- Remove `Benign tumor` and `Dysplasia/Gliosis` from `cancer_group`
- Instead of Adamantinomatous Craniopharyngioma, we should this together with Craniopharyngioma as Craniopharyngioma more broadly.  Same with `Atypical Meningioma` --> `Meningioma

**Comment by jharenza** [comment]
- Update `Neurofibroma/Plexiform;Other` to `Neurofibroma/Plexiform`
- Update `Non-germinomatous germ cell tumor;Teratoma` to `Teratoma`
- Update `Meningothelial meningioma` to `Meningioma`
- Update `Embryonal Tumor with Multilayered Rosettes` to `Embryonal tumor with multilayer rosettes`  - 7316-2577 looks to need to go through embryonal subtyping in OpenPBTA just FYI
- Remove `Other`
- _Possibly_ Update Metastatic secondary tumors;Neuroblastoma to `Neuroblastoma` ** 

** for this one, let me just check some path reports to make sure the region is extracranial - it is listed as NOS in the histologies fiel

**Comment by jharenza** [comment]
>@kgaonkar6 should we make all other dx of DIPG --> DMG for harm dx, even if not subtyped? Right now, this puts them into two groups so i think it makes sense to update this in openPBTA to be one

For this, can you remove that logic and keep the DIPG?

**Comment by kgaonkar6** [comment]
ok keeping those as "Brainstem glioma- Diffuse intrinsic pontine glioma"

**Comment by jharenza** [comment]
can you also make the change: 

`Kidney Wilms Tumor` in TARGET `broad_histology` and `cancer_group` ---> `Wilms Tumor`

**Comment by jharenza** [comment]
> ok keeping those as "Brainstem glioma- Diffuse intrinsic pontine glioma"

sorry, can you shorten to `Diffuse intrinsic pontine glioma`

**Comment by kgaonkar6** [comment]
is cancer_group=="Germinoma;Teratoma" ok?

**Comment by jharenza** [comment]
>is cancer_group=="Germinoma;Teratoma" ok?

yeah - I don't want to preferentially choose there and that wouldn't be in our analyses anyway with n < 5

>Update Embryonal Tumor with Multilayered Rosettes to Embryonal tumor with multilayer rosettes - 7316-2577 looks to need to go through embryonal subtyping in OpenPBTA just FYI

Looks like this one was missed

**Comment by kgaonkar6** [comment]
thanks! 7316-2577 is now updated to Embryonal tumor with multilayer rosettes

**Comment by jharenza** [comment]
added with [PR 34](https://github.com/PediatricOpenTargets/OpenPedCan-analysis/pull/34)
