### ISSUE TITLE
Create merged rMATs matrix for v13 release

### ISSUE THREAD

**Issue by jharenza** [PediatricOpenTargets/ticket-tracker#480]
Create rMATs matrix for v12 release. Let's call it `splice-events-rmats.tsv.gz`

cc @naqvia @ewafula @chinwallaa

**Comment by zhangb1** [comment]
example result from @bmennis  : https://cavatica.sbgenomics.com/u/kfdrc-harmonization/sd-bhjxbdqk-rnaseq-analysis-gencode-v39/files/63c09afb3db2cd6efbfbc248/

**Comment by jharenza** [comment]
> example result from @bmennis  : https://cavatica.sbgenomics.com/u/kfdrc-harmonization/sd-bhjxbdqk-rnaseq-analysis-gencode-v39/files/63c09afb3db2cd6efbfbc248/

@naqvia can you check this file is appropriate for release

**Comment by zhangb1** [comment]
https://cavatica.sbgenomics.com/u/kfdrc-harmonization/sd-bhjxbdqk-x01-rnaseq-analysis/tasks/76e5a42b-31ff-4401-b67e-4dbd6f516a41/
example for the rmats results , need to merge, ` .filtered.A3SS.MATS.JC.txt  , .filtered.A5SS.MATS.JC.txt , .filtered.MXE.MATS.JC.txt  , .filtered.RI.MATS.JC.txt  ,  .filtered.SE.MATS.JC.txt `

**Comment by naqvia** [comment]
This merged file is a subset of samples that are specific to Project Hope (cc @bmennis ). But the format and output is correct (although for exon coordinates it has decimal points-- `.0`-- which is not needed). And each file above that @zhangb1 listed is what we would need to merge.

**Comment by jharenza** [comment]
@bmennis can you update the decimal point issue in the script? Is this an output issue?

**Comment by bmennis** [comment]
Im not entirely sure why it is converting the exon positions to floats, possibly because of the filtering calculations in the merge script? I dont think the outputs from rMATS have them

**Comment by jharenza** [comment]
@bmennis I thinkthis is a non-issue - I didn't see them but I think it was however ammar opened the file

**Comment by bmennis** [comment]
I mean I wouldn't be surprised if there is an error, im really not great with pandas haha. But im definitely happy to fix this so we have it right

**Comment by naqvia** [comment]
I think it should be fine. It might be more related to my terminal and settings locally. I'll see if I can figure it out!

**Comment by HuangXiaoyan0106** [comment]
@zhangb1 @jharenza  I developed the cwl workflow to merge rMATs results, here is the result for v12 release:
https://cavatica.sbgenomics.com/u/d3b-bixu-ops/monthly-release-analysis/tasks/c03c8e55-0c71-4a79-b244-ff169d18e41f
Please let me know if I can be of any assistance.

**Comment by zhangb1** [comment]
@HuangXiaoyan0106  Thanks !

**Comment by zhangb1** [comment]
close this ticket
