### ISSUE TITLE
Create bixu-generated fields for v12 release

### ISSUE THREAD

**Issue by jharenza** [PediatricOpenTargets/ticket-tracker#481]
#### What data file(s) does this issue pertain to?
v12 base histologies

#### Put your question or report your issue here.
Create the bixu-generated fields - tumor fraction, germline sex estimate, etc for the v12 release.

@HuangXiaoyan0106 can you add it to this PR: https://github.com/d3b-center/histologies-qc/pull/1

**Comment by jharenza** [comment]
cc @ewafula

**Comment by HuangXiaoyan0106** [comment]
> #### What data file(s) does this issue pertain to?
> v12 base histologies
> 
> #### Put your question or report your issue here.
> Create the bixu-generated fields - tumor fraction, germline sex estimate, etc for the v12 release.
> 
> @HuangXiaoyan0106 can you add it to this PR: [d3b-center/histologies-qc#1](https://github.com/d3b-center/histologies-qc/pull/1)

Hi @jharenza, I have done the monthly release on 1/5/2023 and generated the latest histology file. You can check it in the [Cavatica delivery project ](https://cavatica.sbgenomics.com/u/d3b-bixu-ops/monthly-release-data/files/63b6ce5c9668d812ed2fdca7/)or S3 bucket(`d3b-bixu/d3b_bix_data_merge_release/tumor-board-release/2023/20230105_release/20230105_release_histologies_ops.csv`). 
Is this enough for v12?

**Comment by jharenza** [comment]
@HuangXiaoyan0106 we will check- it seems we were missing many samples from pbta histologies file last week so we can check. @ewafula can you take a look? @zhangb1 can you add @ewafula to this cavatica project?

**Comment by zhangb1** [comment]
bix field  histology file updated in the cavatica  :  https://cavatica.sbgenomics.com/u/zhangb1/temp-ot-v12-release/files/63da9bbcb315f57f1c3b7bc8/

**Comment by jharenza** [comment]
Thanks, @zhangb1 - looks like X01 is all set - we are still missing 537 germline sex estimate for GMKF NBL - these were in v11, so they had been run, just looks like they need to be captured 
[missing_germline_sex_estimate.csv](https://github.com/PediatricOpenTargets/ticket-tracker/files/10559915/missing_germline_sex_estimate.csv)

**Comment by jharenza** [comment]
Stand by - I see some RNA-Seq in that file..

**Comment by jharenza** [comment]
[missing_germline_sex_estimate.csv](https://github.com/PediatricOpenTargets/ticket-tracker/files/10559957/missing_germline_sex_estimate.csv)

Use this please

**Comment by zhangb1** [comment]
> [missing_germline_sex_estimate.csv](https://github.com/PediatricOpenTargets/ticket-tracker/files/10559957/missing_germline_sex_estimate.csv)
> 
> Use this please

These are all Tumors? we only have the gender estimation on Germline samples...   @HuangXiaoyan0106

**Comment by jharenza** [comment]
OK thanks - this must have been a mistake having been annotated in v11! feel free to close!

**Comment by zhangb1** [comment]
We will apply the participant ID as key to cover the Tumor/Normal WGS and RNAseq  `germline_sex_estimate` field

**Comment by zhangb1** [comment]
updated histology file : https://cavatica.sbgenomics.com/u/zhangb1/temp-ot-v12-release/files/63dbc5ad122b6e29c16cceb6/

**Comment by jharenza** [comment]
all good now, thanks
