### ISSUE TITLE
[Investigate] why CN consensus module is taking 4 hours with GA

### ISSUE THREAD

**Issue by jharenza** [PediatricOpenTargets/ticket-tracker#482]
Example log: https://github.com/PediatricOpenTargets/OpenPedCan-analysis/actions/runs/3861943317/jobs/6583834313

@devbyaccident @ewafula

**Comment by devbyaccident** [comment]
Looking through the github actions logs, there's no obvious long polls. Is this an increase with no code changes? Was there a previous run that took less time? This could just be running 35240 tasks in the same job...

**Comment by devbyaccident** [comment]
Job logs here: [6583834313_logs.txt.zip](https://github.com/PediatricOpenTargets/ticket-tracker/files/10374104/6583834313_logs.txt.zip)

**Comment by jharenza** [comment]
> 35240 tasks 

Can you explain this? There was a recent update to use a new algorithm in this module and I don't know if this is when it happened because it didn't phase me then - @ewafula can you pull that PR and note it here so @devbyaccident can investigate. It should have been a simple replace one algorithm with another so not sure...

**Comment by devbyaccident** [comment]
> Can you explain this?

Let me start by saying I'm not familiar with this module, but in the logs for the *Run Analysis* step in that job, it looks like it's putting together 35240 tasks of different types. If there's a previous run with less I can compare it to, that might help in understanding why, but that's what it looks like at first glance.

<img width="393" alt="image" src="https://user-images.githubusercontent.com/12488263/211368700-5348db42-da55-464c-8cb6-1b5bbca4fcc7.png">

**Comment by ewafula** [comment]
@jharenza and @devbyaccident, here is the PR that updated the module from mantsv to GATK

https://github.com/PediatricOpenTargets/OpenPedCan-analysis/pull/207

**Comment by jharenza** [comment]
OK, even though logs expired, the [entirety of that GA run was 2 h 42 m](https://github.com/PediatricOpenTargets/OpenPedCan-analysis/actions/runs/3221883543) so it was not the code update for that PR that did it.

**Comment by jharenza** [comment]
This was solved when we created new CI files and used testing data instead of local input data! https://github.com/PediatricOpenTargets/OpenPedCan-analysis/pull/310
