### ISSUE TITLE
 [Investigate] Incorrect subtypes

### ISSUE THREAD

**Issue by sickler-alex** [PediatricOpenTargets/ticket-tracker#489]
# 🆘

#### [Required] Before completing the questionnaire below, please describe your issue in a couple of sentences

In OT V11, `7316-2632` was subtyped as `LGG, CDKN2A/B` which requires a CNV gain in either CDKN2A or CDKN2B. But, when looking at the raw data, the sample actually has a gain in CDKN2A. Should the subtyping rules be updated or is there something else going on?

#### [Required] How would you most generally describe your issue? 
- [ ] Workflow 
- [X] Data
- [ ] Documentation 

#### [Required] Which pipeline or pipelines relate to the issue? 
- [ ] Alignment and HaplotypeCaller
- [ ] HaplotypeCaller
- [ ] Joint Genotyping
- [ ] RNAseq
- [ ] Somatic Variant
- [X] Other (please provide link): OT and toolkit

#### [Required for Workflow Issues] Please select all that apply to your Workflow related issue:
- [ ] Cost
- [ ] Failure
- [ ] Run time
- [ ] Other (describe below)

#### [Required for Data Issues] Please select all that apply to your Data related issue:
- [ ] Empty Workflow Outputs 
- [X] Incorrect Workflow Outputs
- [X] Unexpected Workflow Outputs
- [ ] Other (describe below)

#### [Required for Documentation Issues] Please select all that apply to your Documentation related issue:
- [ ] Incorrect
- [ ] Misleading
- [ ] Missing or Unclear
- [ ] Other (describe below)

**Comment by sickler-alex** [comment]
Looking at the subtyping results, it looks like `7316-3065` and `7316-934` also have this issue.

**Comment by jharenza** [comment]
v12 subtypes for these:
```r
> v12 %>%
+   filter(sample_id %in% c("7316-2632", "7316-3065", "7316-934"),
+          !is.na(pathology_diagnosis)) %>%
+   select(sample_id, molecular_subtype, molecular_subtype_methyl) %>%
+   unique()
# A tibble: 4 × 3
  sample_id molecular_subtype     molecular_subtype_methyl
  <chr>     <chr>                 <chr>                   
1 7316-3065 LGG, To be classified NA                      
2 7316-934  LGG, BRAF V600E       NA                      
3 7316-2632 LGG, FGFR             NA                      
4 7316-3065 LGG, RTK              NA 
```

I think the CN file used for v11 was not accurate for these, as you saw.
