### ISSUE TITLE
v12 WGS germline sex estimate 

### ISSUE THREAD

**Issue by ewafula** [PediatricOpenTargets/ticket-tracker#492]
#### What are the scientific goals of the analysis?
Perform analysis for  v12 WGS samples missing  germline sex estimate

#### What methods do you plan to use to accomplish the scientific goals?
bix-ops germline sex estimate pipeline 

#### What input data are required for this analysis?
- v12 sample IDs listed in the attached file, excluding [previously estimated GMKF samples](https://github.com/d3b-center/d3b-dbt-study-transforms/pull/33) but not coded current adapt base histologies. 
-  v12 sample IDs requiring germline sex estimate  determined in histologies files available in the [histologies-qc repo PR](https://github.com/d3b-center/histologies-qc/pull/1):
```
> v11_gsex_estimate <- read_tsv("histologies/previous_histologies.tsv") %>% 
  filter(experimental_strategy == "WGS", 
         germline_sex_estimate %in% c("Female", "Male")) %>% 
  pull(Kids_First_Biospecimen_ID)

> read_tsv("output/2023-01-18_histologies-base.tsv") %>% 
  filter(experimental_strategy == "WGS", 
         !germline_sex_estimate %in% c("Female", "Male"), 
         !Kids_First_Biospecimen_ID %in% v11_gsex_estimate) %>% 
  pull(Kids_First_Biospecimen_ID) %>% 
  write_lines("~/Downloads/v12_wgs_missing_sex_estimate.txt")
```
[v12_wgs_missing_sex_estimate.tsv.zip](https://github.com/PediatricOpenTargets/ticket-tracker/files/10451639/v12_wgs_missing_sex_estimate.tsv.zip)

-  Sample IDs listed on the following attached chordoma WGS sample, currently not in the base adapt histologies, will also require germline sex estimate:

[chordoma_wgs_to_inlcude.txt](https://github.com/PediatricOpenTargets/ticket-tracker/files/10451329/chordoma_wgs_to_inlcude.txt)

#### How long do you expect is needed to complete the analysis? Will it be a multi-step analysis?
For v12 histologies 

#### Who will complete the analysis (please add a GitHub handle here if relevant)?
bix-ops

Cc @jharenza

**Comment by zhangb1** [comment]
@ewafula  for the wgs BS IDs, can you also list the cohorts in the BSID list, only BS ID will be hard for us to track where are the samples from.  Thank you!

**Comment by ewafula** [comment]
> @ewafula for the wgs BS IDs, can you also list the cohorts in the BSID list, only BS ID will be hard for us to track where are the samples from. Thank you!

@zhangb1, updated with OpenPedCan cohorts. Linked to the ticket above.

**Comment by HuangXiaoyan0106** [comment]
@zhangb1 There are 5168 sample IDs listed in `v12_wgs_missing_sex_estimate.tsv`, but only 135 samples have xy ratio files in the master genomics manifest, so I checked the original cram files, but only 1115 samples were recorded(4053 are missing).
1. [1115_v12_wgs_sex_cram.csv](https://github.com/PediatricOpenTargets/ticket-tracker/files/10534482/1115_v12_wgs_missing_sex_cram.csv)
2. [4053_missing_ids_in_master.txt](https://github.com/PediatricOpenTargets/ticket-tracker/files/10534499/4053_missing_ids_in_master.txt)

All samples listed in `chordoma_wgs_to_inlcude.txt`, I have found cram files.
[chordoma_v12_cram.csv](https://github.com/PediatricOpenTargets/ticket-tracker/files/10534610/chordoma_v12_cram.csv)

**Comment by zhangb1** [comment]
@jharenza @ewafula 

Just checked the missing sex ratio files for the 4053 ids ..4032 are from CBTN X01 Tumor or Normal ,  21 are Chordoma Tumor

We don't have the sex ratio file for CBTN X01 ,since the source files are cram file from Broad, we consider the cram as harmonized file, we didn't do the gender estimation in the cram to gvcf pipeline.  they are no sex estimate for those Normal samples.

**Comment by zhangb1** [comment]
We will run the CBTN X01 Normal samples gender estimate .....

**Comment by jharenza** [comment]
thank you!

**Comment by zhangb1** [comment]
ticket created. : https://github.com/d3b-center/bixu-tracker/issues/1784

but for now, I will run the tool for the CBTN X01 germline samples..... for the future ,we need to have that in the public workflow

**Comment by zhangb1** [comment]
related to the ticket https://github.com/PediatricOpenTargets/ticket-tracker/issues/481

close this one
