### ISSUE TITLE
Updated analysis: Driver gene list needs to be updated

### ISSUE THREAD

**Issue by komalsrathi** [PediatricOpenTargets/ticket-tracker#494]
#### What analysis module should be updated and why?

`oncoprint-landscape`

#### What changes need to be made? Please provide enough detail for another participant to make the update.

Driver gene lists here: https://github.com/PediatricOpenTargets/OpenPedCan-analysis/tree/dev/analyses/oncoprint-landscape/driver-lists (as well as any other gene lists that are being used in the repo) will need an update with the new Gencode version v39, as some important gene symbols have changed in this version. Here are some genes from the `brain-goi-list-long.txt` file:

```
"H3F3A" <- "H3-3A"
"HIST1H3A" <- "H3C1"
"HIST1H3B" <- "H3C2"
"HIST1H3C" <- "H3C3"
"C11ORF70" <- "CFAP300"
"C11ORF95" <- "ZFTA"
"LRB1B" <- "LRP1B"
"CXORF67" <- "EZHIP"
"UTX" <- "KDM6A" 
```

#### What input data should be used? Which data were used in the version being updated?

Gencode v39 GTF

#### When do you expect the revised analysis will be completed?

N/A

#### Who will complete the updated analysis?

@jharenza will inform

**Comment by jharenza** [comment]
@komalsrathi would you be able to submit a PR for this - only updating the list, but not running the module? We can get it through for you since it is not run in github actions

**Comment by komalsrathi** [comment]
Sure - will do.

**Comment by jharenza** [comment]
Thanks so much! When doing, can you also mark the new lists with "gencode_v39" appended - working on multiple projects and we might need old symbols for a bit longer. Thanks!
