### ISSUE TITLE
Transfer TARGET RNAseq/WES/WGS fastq files to CAVATICA

### ISSUE THREAD

**Issue by afarrel** [PediatricOpenTargets/ticket-tracker#5]
#### What data file(s) does this issue pertain to?

- [**Receice Data paths and manifests** ] @yuankunzhu  - get data paths and manifests from @afarrel and @ewafula  
- [**Tranfer Data**] transfer TARGET fastq files from Diskin folders on isilon to CAVATICA.

[ **Files are located**]:

-  **RNA:**
/mnt/isilon/diskin_lab/TARGET_RNA/fastq/

- **WES:**
/mnt/isilon/dbgap/prj_1812/TARGET-Exome/fastq/
/mnt/isilon/diskin_lab/TARGET_WXS/dbGap/fastq/

#### Who is performing this task.
@yuankunzhu

**Comment by jharenza** [comment]
closing this since we will pull directly from CGC
