### ISSUE TITLE
split generate-analysis-files.sh

### ISSUE THREAD

**Issue by jharenza** [PediatricOpenTargets/ticket-tracker#500]
We need to split https://github.com/PediatricOpenTargets/OpenPedCan-analysis/blob/dev/scripts/generate-analysis-files.sh into `generate-analysis-files.sh` and `run-for-subtyping.sh`. For the release, we might also want to renumber these or make a readme to avoid confusion.

1. @zhangb1  team generates raw data matrices
2. QC on those files is run - where is this script @ewafula - I recall you made this notebook
3. run `generate-analysis-files.sh` and start PR 1/N, changing the download data script to v12 bucket folder
4. run each line of `run-for-subtyping.sh` as a separate PR stacked on 1
5. Once histology files is generated at the end of these PRs, run `create-subset-files.sh`
6. Start merging PRs backwards to make sure they pass all checks
7. Create data release PR including data release notes before final merge
8. Post merge of data release, run `generate-mtp-tables.sh`

Does this sound accurate @ewafula ?

For this issue, @ewafula can you take care of splitting `generate-analysis-files.sh`?

**Comment by ewafula** [comment]
@jharenza, previously this was split up into two scripts, generating analysis and subtyping files separately. But you asked me to combine them into one script, the current script that does both. Why are we reverting back? Seet the ticket close ticket below:
https://github.com/PediatricOpenTargets/ticket-tracker/issues/402

**Comment by ewafula** [comment]
In response to #2, here the data release QC module:
https://github.com/PediatricOpenTargets/OpenPedCan-analysis/tree/dev/analyses/data-pre-release-qc

**Comment by jharenza** [comment]
> @jharenza, previously this was split up into two scripts, generating analysis and subtyping files separately. But you asked me to combine them into one script, the current script that does both. Why are we reverting back? Seet the ticket close ticket below: #402

I think I was thinking that we would be running this just to compare to the toolkit but I think we are pretty far away from relying on toolkit here since we will continue dev, and I anticipate bringing DGD and methylation into each module during release, so each module will require updates for v12

**Comment by jharenza** [comment]
Sorry, we probably should have completed the integration of DGD + methyl long before this but alas, here we are
