### ISSUE TITLE
Proposed Analysis: Calculate TPM/z-score/SD/quantile summary statistics within each cancer group and cohort

### ISSUE THREAD

**Issue by logstar** [PediatricOpenTargets/ticket-tracker#51]
#### What are the scientific goals of the analysis?

Within each cancer group and cohort, calculate TPM means, standard deviations, z-scores, and ranks.

#### What methods do you plan to use to accomplish the scientific goals?

For each `cancer_group`, select one of the following two sets of samples:

- Samples from all `cohort`s, e.g. CBTN, GMKF, and PNOC.
- Samples from each individual `cohort`.

If >= 5 samples are selected, generate the following summary statistics:

- TPM means of each gene across all selected samples, and denote this vector as `mean_TPM_vector`.
- TPM standard deviations of each gene across all selected samples.
- z-scores of each gene across all genes, computed as `z_score_vector = (mean_TPM_vector - mean(mean_TPM_vector)) / sd(mean_TPM_vector)`.
- Ranks of mean TPM of each gene across all selected samples, which takes one of the following four values: `Highest expressed 25%`, `Expression between upper quartile and median`, `Expression between median and lower quartile`, and `Lowest expressed 25%`. If multiple genes have the same mean TPM value, their tied rank is the lowest rank, in order to be conservative on the description of their expression levels.

Combine each type of the summary statistics vectors into a table, with rows as genes, and columns as `cancer_group_cohort`.

**Method update**:

Generate tables to list the number of samples in each set of selected samples.

Use Ensembl ENSG IDs as gene names.

Generate z-scores across all cancer groups. Denote the (n_genes, n_cancer_groups) mean TPM matrix as `mean_TPM_matrix`. Compute z-scores across all cancer groups as `z_score_matrix = (mean_TPM_matrix - rowMeans(mean_TPM_matrix)) / rowSD(mean_TPM_matrix)`.

#### What input data are required for this analysis?

- `gene-expression-rsem-tpm-collapsed.rds`
- `histologies.tsv`

#### How long do you expect is needed to complete the analysis? Will it be a multi-step analysis?

1-2 days.

This will not be a multi-step analysis.

#### Who will complete the analysis (please add a GitHub handle here if relevant)?

@logstar 

#### To discuss:

@jharenza If you have any suggestions or updates, feel free to let me know.

**Comment by jharenza** [comment]
To clarify the z-scores:

For within cancer group, we would do below as noted above:
>z-scores of each gene across all genes, computed as z_score_vector = (mean_TPM_vector - mean(mean_TPM_vector)) / sd(mean_TPM_vector).

But when doing across cancers, we will z-score by gene (row).

**Comment by jharenza** [comment]
@logstar please combine `CBTN` and `PNOC` into one cohort, `PBTA` for this analysis

**Comment by logstar** [comment]
@jharenza Thank you for the comments. I will combine CBTN and PNOC into one cohort PBTA for this analysis.

Do we need z-scores or quantiles across all cancers? I remember there is only one z-score and one quantile in the JSON record. If necessary, I will update this ticket and the PR to generate z-scores and quantiles across all cancers as well.

**Comment by jharenza** [comment]
>Do we need z-scores or quantiles across all cancers? I remember there is only one z-score and one quantile in the JSON record. If necessary, I will update this ticket and the PR to generate z-scores and quantiles across all cancers as well.

Yes, this would be per every gene, z-score across cancers - I think those JSON files were just mock ups and we can make any JSON files we would like- but will confirm tomorrow on the call if that is useful or if TPM is enough.

**Comment by logstar** [comment]
> > Do we need z-scores or quantiles across all cancers? I remember there is only one z-score and one quantile in the JSON record. If necessary, I will update this ticket and the PR to generate z-scores and quantiles across all cancers as well.
> 
> Yes, this would be per every gene, z-score across cancers - I think those JSON files were just mock ups and we can make any JSON files we would like- but will confirm tomorrow on the call if that is useful or if TPM is enough.

Got it. Thank you for the quick reply. I will update the issue, module, and PR to include the z-scores across all cancers.

**Comment by logstar** [comment]
<https://github.com/PediatricOpenTargets/OpenPedCan-analysis/pull/27> merged.

Will open new ticket and PR for extracting table annotation code into a standalone module.
