### ISSUE TITLE
Updated filter-mtp-tables module

### ISSUE THREAD

**Issue by ewafula** [PediatricOpenTargets/ticket-tracker#511]
#### What analysis module should be updated and why?
Update [filter-mtp-tables](https://github.com/PediatricOpenTargets/OpenPedCan-analysis/tree/dev/analyses/filter-mtp-tables) module to utilize targets and disease mapping files from the `mtp-annotations` module 

#### What changes need to be made? Please provide enough detail for another participant to make the update.
0). Update `01-filter-mtp-tables-for-current-gencode.Rmd` script 
1). Utilize `analyses/mtp-annotations/results/mtp-targets-mapping.tsv.gz` and `analyses/mtp-annotations/run-mtp-annotations.sh` to filter `Ensembl IDs` and update `EFO/MONDO` respectively in MTP tables.  
2). Include MTP gene-level and isoform-level methylation summary tables from the [methylation-summary](https://github.com/PediatricOpenTargets/OpenPedCan-analysis/tree/dev/analyses/methylation-summary) module
3). Inlcude upcoming DESeq long table
4). Remove `02-filter-mtp-tables-misc-updates.R` script - no longer needed from v12 onwards 
5). Exclude `input/MTP_v11_InvalidENSG_20220831.txt` - no longer needed from v12 onwards 

#### What input data should be used? Which data were used in the version being updated?
MTP tables described in the [filter-mtp-tables](https://github.com/PediatricOpenTargets/OpenPedCan-analysis/tree/dev/analyses/filter-mtp-tables)  and methylation summary tables

#### When do you expect the revised analysis will be completed?
This sprint 

#### Who will complete the updated analysis?
@atlas4213

**Comment by jharenza** [comment]
closed with https://github.com/PediatricOpenTargets/OpenPedCan-analysis/pull/349
