### ISSUE TITLE
Targeted capture bed file for TARGET

### ISSUE THREAD

**Issue by kgaonkar6** [PediatricOpenTargets/ticket-tracker#52]
#### What data file(s) does this issue pertain to?
We have paired tumor and normal targeted-capture samples we will need a bed file to run WF 

Sample distribution:
```
  experimental_strategy sample_type     n
  <chr>                 <chr>       <int>
1 Targeted-Capture      Normal        499
2 Targeted-Capture      Tumor         499
```

#### What release are you using?

v5

#### Put your question or report your issue here.
Once we have the TARGET bed file please check if the bed is hg19 we will need to map to hg38 to reprocess the data.

**Comment by jharenza** [comment]
This BED file can be found here: https://target-data.nci.nih.gov/Public/NBL/targeted_capture_sequencing/DESIGN/

**Comment by jharenza** [comment]
Assigning to @bmennis cc @yuankunzhu

**Comment by zhangb1** [comment]
@jharenza  do you know how to query the target DNA samples in cavatica data browser ? 

![image](https://user-images.githubusercontent.com/14929845/123097474-2b819a80-d3fe-11eb-8927-59d5a56a74c9.png)
I only can see WXS in the query , no capture region . how can I get those samples?

**Comment by jharenza** [comment]
@zhangb1 it seems like it is not in the GDC, so not showing in CAVATICA. We are going to upload from isilon anyway.

**Comment by kgaonkar6** [comment]
Will the associated bed file also be uploaded from isilon?

**Comment by jharenza** [comment]
> Will the associated bed file also be uploaded from isilon?

No, I posted the link above in [this comment](https://github.com/PediatricOpenTargets/ticket-tracker/issues/52#issuecomment-866180775)

**Comment by yuankunzhu** [comment]
@jharenza @kgaonkar6 where can we find the panel BED files?

**Comment by jharenza** [comment]
@zhangb1 panel bed file https://target-data.nci.nih.gov/Public/NBL/targeted_capture_sequencing/DESIGN/TARGET_AML_NBL_WT_SeqVal79_attempt06_AllTracks_hg19_hugo.bed.txt

**Comment by jharenza** [comment]
this data has been processed - closing
