### ISSUE TITLE
Update gene_match module for v12 data release

### ISSUE THREAD

**Issue by ewafula** [PediatricOpenTargets/ticket-tracker#525]
#### What analysis module should be updated and why?
[gene_match module](https://github.com/PediatricOpenTargets/OpenPedCan-analysis/tree/dev/analyses/gene_match/input)

#### What changes need to be made? Please provide enough detail for another participant to make the update.
Update module using new versions of input files 

#### What input data should be used? Which data were used in the version being updated?
New input files:
- Use `PMTL_v3.1.tsv` in place of `PMTL_v1.1.tsv`
   -  [PMTL_v3.1.tsv.zip](https://github.com/PediatricOpenTargets/ticket-tracker/files/10972183/PMTL_v3.1.tsv.zip)

- Use `OpenPedCan-v12-ensg-hugo-pmtl-mapping.tsv`  in place of `open_ped_can_v7_ensg-hugo-rmtl-mapping.tsv`
   - **Note:** column `pmtl` replaces `rmtl`
   - [OpenPedCan-v12-ensg-hugo-pmtl-mapping.tsv.zip](https://github.com/PediatricOpenTargets/ticket-tracker/files/10972188/OpenPedCan-v12-ensg-hugo-pmtl-mapping.tsv.zip)

#### When do you expect the revised analysis will be completed?
1 day

**Note:**  
- please check out  `v12-post-release` ([PR #340](https://github.com/PediatricOpenTargets/OpenPedCan-analysis/pull/340)) and create your PR branch off this branch  
- submit your PR to the `v12-post-release` branch ([PR #340](https://github.com/PediatricOpenTargets/OpenPedCan-analysis/pull/340))

#### Who will complete the updated analysis?
@sangeetashukla

**Comment by ewafula** [comment]
**Moving the comment here from the associated [PR # 341](https://github.com/PediatricOpenTargets/OpenPedCan-analysis/pull/341)**

@zhangb1,  @jharenza, and @chinwallaa, diffs in gene symbols between `snv consensus maf` and gene `ensg-hugo-pmtl-mapping.tsv` produced by this module (`gene_match`) are mostly regulatory elements. They are represented mostly by their ENSG IDs in Gencode. But in the `snv consensus maf`, these regulatory gene symbols (`Hugo_symbol` column ) are mostly represented by either `ENST or  ENSR IDs`. For this reason, it seems they are ignored in the downstream modules that utilize the svn consensus maf file.  I wanted to make sure I bring this to your attention in case you want to change course in the future to recode the `Hugo_symbol` column in the `snv consensus maf` using the appropriate Gencode gene symbol representation. 

[04-qc-ensg-hugo-pmtl-mapping.nb.html.zip](https://github.com/PediatricOpenTargets/ticket-tracker/files/11042880/04-qc-ensg-hugo-pmtl-mapping.nb.html.zip)

**Comment by jharenza** [comment]
Closed with https://github.com/PediatricOpenTargets/OpenPedCan-analysis/pull/321
