### ISSUE TITLE
Updated efo-mondo-mapping module for v12 data release

### ISSUE THREAD

**Issue by ewafula** [PediatricOpenTargets/ticket-tracker#526]
#### What analysis module should be updated and why?
[efo-mondo-mapping](https://github.com/PediatricOpenTargets/OpenPedCan-analysis/tree/dev/analyses/efo-mondo-mapping)

#### What changes need to be made? Please provide enough detail for another participant to make the update.
Update EFO, MONDO, and NCIT codes for v12 cancer groups

#### What input data should be used? Which data were used in the version being updated?
Use the updated v12 [efo-mondo-map-prefill.tsv](https://github.com/PediatricOpenTargets/OpenPedCan-analysis/blob/v12-integrate/analyses/efo-mondo-mapping/results/efo-mondo-map-prefill.tsv) files on the [PR #336](https://github.com/PediatricOpenTargets/OpenPedCan-analysis/pull/336)  

#### When do you expect the revised analysis will be completed?
1 day

**Note:**  
- please check out  `v12-post-release` ([PR #340](https://github.com/PediatricOpenTargets/OpenPedCan-analysis/pull/340)) and create your PR branch off this branch  
- submit your PR to the `v12-post-release` branch ([PR #340](https://github.com/PediatricOpenTargets/OpenPedCan-analysis/pull/340))

#### Who will complete the updated analysis?
@sangeetashukla

**Comment by ewafula** [comment]
**Moving this comment from @sangeetashukla on the PR  here on the ticket**
@jharenza @chinwallaa @ewafula 
Final summary of changes that need reviewing before merging into dev:

As of now, the list of cancer_groups in the `results/efo-mondo-map.tsv` in this branch matches the v12 `histologies.tsv`. As per that list, below are the notes. 

`Diffuse hemispheric glioma NA NA NA` - No codes were found, and need to be added manually.

`Epstein-Barr virus-related tumor MONDO_0017342 MONDO_0017342 NA` - NCIT code is pending.

`Extraventricular neurocytoma EFO_1000856 MONDO_0016727 NCIT_C92555` - EFO code needs review.

`Glial-neuronal tumor	NA	NA	NA` - No codes were found, and need to be added manually.

`Mesenchymal tumor EFO_1000473 MONDO_0003512 NCIT_C7059` - needs review because description for each of the codes is not necessarily the same.

`Other EFO_0030051 GO_0051707 NCIT_C17649` - needs review since this is not specific at all.

`Perineuroma NA NA NA` - was added but is missing all codes, therefore needs review.

`Pheochromocytoma and Paraganglioma	EFO_0020005	MONDO_0035540	NA` - NCIT code is pending.

`SEGA	NA	NA	NA` - was added but is missing all codes, therefore needs review.

`High-grade glioma` and `Low-grade glioma` need additional review since `High-grade glioma/astrocytoma` and `Low-grade glioma/astrocytoma` are also included, although the codes are different.

`T Acute Lymphoblastic Leukemia/Lymphoma EFO_0000209 MONDO_0004963 NCIT_C3183 EFO_1001936 MONDO_0003537 NCIT_C8694` The codes need to be re-visited. Alternatives are suggested here based on the automated search results captured in `results/efo-mondo-map-prefill-auto.tsv`

`Uterine Corpus Endometrial Carcinoma EFO_0007532 MONDO_0000553 NCIT_C159413 EFO_1000238 MONDO_0000553 NCIT_C159413` - EFO code seems to have changed, needs review.

**Comment by ewafula** [comment]
@sangeetashukla, 

SEGA seems to have an NCIT code here:
https://www.ebi.ac.uk/ols/ontologies/ncit/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FNCIT_C3696

Perineuroma has MONDO code here:
https://monarchinitiative.org/disease/MONDO:0019404

**Comment by jharenza** [comment]
Hi @sangeetashukla. See my comments below. cc @ewafula 

```
Diffuse hemispheric glioma NA NA NA - No codes were found, and need to be added manually. - this is a new entity. use MONDO:0016680 for now
Epstein-Barr virus-related tumor MONDO_0017342 MONDO_0017342 NA - NCIT code is pending. - OK
Extraventricular neurocytoma EFO_1000856 MONDO_0016727 NCIT_C92555 - EFO code needs review. - MONDO_0016727 and NCIT_C92555 correct. EFO not correct
Glial-neuronal tumor	NA	NA	NA - No codes were found, and need to be added manually. - NCIT_C4747
Mesenchymal tumor EFO_1000473 MONDO_0003512 NCIT_C7059 - needs review because description for each of the codes is not necessarily the same. - NCIT:C7059 seems best here
Other EFO_0030051 GO_0051707 NCIT_C17649 - needs review since this is not specific at all. - this should be removed totally, will update PR prior to this
Perineuroma NA NA NA - was added but is missing all codes, therefore needs review. - MONDO:0019404
Pheochromocytoma and Paraganglioma	EFO_0020005	MONDO_0035540	NA - NCIT code is pending. - OK to be blank NCIT
SEGA	NA	NA	NA - was added but is missing all codes, therefore needs review. - NCIT:C3696 and will update PR to use long name
High-grade glioma and Low-grade glioma need additional review since High-grade glioma/astrocytoma and Low-grade glioma/astrocytoma are also included, although the codes are different. 
T Acute Lymphoblastic Leukemia/Lymphoma EFO_0000209 MONDO_0004963 NCIT_C3183 EFO_1001936 MONDO_0003537 NCIT_C8694 The codes need to be re-visited. Alternatives are suggested here based on the automated search results captured in results/efo-mondo-map-prefill-auto.tsv - use these: EFO_0000209 MONDO_0004963 NCIT_C3183
Uterine Corpus Endometrial Carcinoma EFO_0007532 MONDO_0000553 NCIT_C159413 EFO_1000238 MONDO_0000553 NCIT_C159413 - EFO code seems to have changed, needs review. - http://purl.obolibrary.org/obo/NCIT_C159413 this seems to be nothing. Use EFO_0007532 MONDO_0000553
```

**Comment by sangeetashukla** [comment]
> Hi @sangeetashukla. See my comments below. cc @ewafula
> 
> ```
> Diffuse hemispheric glioma NA NA NA - No codes were found, and need to be added manually. - this is a new entity. use MONDO:0016680 for now
> Epstein-Barr virus-related tumor MONDO_0017342 MONDO_0017342 NA - NCIT code is pending. - OK
> Extraventricular neurocytoma EFO_1000856 MONDO_0016727 NCIT_C92555 - EFO code needs review. - MONDO_0016727 and NCIT_C92555 correct. EFO not correct
> Glial-neuronal tumor	NA	NA	NA - No codes were found, and need to be added manually. - NCIT_C4747
> Mesenchymal tumor EFO_1000473 MONDO_0003512 NCIT_C7059 - needs review because description for each of the codes is not necessarily the same. - NCIT:C7059 seems best here
> Other EFO_0030051 GO_0051707 NCIT_C17649 - needs review since this is not specific at all. - this should be removed totally, will update PR prior to this
> Perineuroma NA NA NA - was added but is missing all codes, therefore needs review. - MONDO:0019404
> Pheochromocytoma and Paraganglioma	EFO_0020005	MONDO_0035540	NA - NCIT code is pending. - OK to be blank NCIT
> SEGA	NA	NA	NA - was added but is missing all codes, therefore needs review. - NCIT:C3696 and will update PR to use long name
> High-grade glioma and Low-grade glioma need additional review since High-grade glioma/astrocytoma and Low-grade glioma/astrocytoma are also included, although the codes are different. 
> T Acute Lymphoblastic Leukemia/Lymphoma EFO_0000209 MONDO_0004963 NCIT_C3183 EFO_1001936 MONDO_0003537 NCIT_C8694 The codes need to be re-visited. Alternatives are suggested here based on the automated search results captured in results/efo-mondo-map-prefill-auto.tsv - use these: EFO_0000209 MONDO_0004963 NCIT_C3183
> Uterine Corpus Endometrial Carcinoma EFO_0007532 MONDO_0000553 NCIT_C159413 EFO_1000238 MONDO_0000553 NCIT_C159413 - EFO code seems to have changed, needs review. - http://purl.obolibrary.org/obo/NCIT_C159413 this seems to be nothing. Use EFO_0007532 MONDO_0000553
> ```

Thank you @jharenza 
I will review your comments and update the mapping file.

**Comment by sangeetashukla** [comment]
@ewafula The older PR attached to the issue has been merged. I will create a new PR with the efo-mondo-map.tsv updated.

**Comment by ewafula** [comment]
Sure, @sangeetashukla. Create a v12-efo-mondo branch off the v12-post-release PR branch as you did before.

**Comment by jharenza** [comment]
Closed with https://github.com/PediatricOpenTargets/OpenPedCan-analysis/pull/321
