### ISSUE TITLE
update cnv-frequencies tables for v12 

### ISSUE THREAD

**Issue by ewafula** [PediatricOpenTargets/ticket-tracker#527]
#### What analysis module should be updated and why?
Update [cnv-frequencies](https://github.com/PediatricOpenTargets/OpenPedCan-analysis/tree/dev/analyses/cnv-frequencies) module

#### What changes need to be made? Please provide enough detail for another participant to make the update.
- checkout the branch for [PR #340](https://github.com/PediatricOpenTargets/OpenPedCan-analysis/pull/340) and create branch off it for this update.  The `download-data.sh`  bash script in this branch is already updated for v12 data downloads
   - `git checkout -b v12-post-release origin/v12-post-release`
   - `git branch v12-cnv-freq`

- change `datatypeId` column value for the output  tables from `somatic_mutation` to `pediatric_cancer`
- rerun the module using v12 data release files 
-  submit your PR to the `v12-post-release`  branch
- output files are likely to be larger than the maximum limit allowed on GitHub. Include a .gitignore in the `results/` directory

#### What input data should be used? Which data were used in the version being updated?
- module input data files are described in the README and already set in the wrapper bash script. 

#### When do you expect the revised analysis will be completed?
1/2 day

#### Who will complete the updated analysis?
@zzgeng

**Comment by jharenza** [comment]
closed with https://github.com/PediatricOpenTargets/OpenPedCan-analysis/pull/345
