### ISSUE TITLE
update snv-frequencies tables for v12 

### ISSUE THREAD

**Issue by ewafula** [PediatricOpenTargets/ticket-tracker#529]
#### What analysis module should be updated and why?
Update [snv-frequencies](https://github.com/PediatricOpenTargets/OpenPedCan-analysis/tree/dev/analyses/snv-frequencies) module

#### What changes need to be made? Please provide enough detail for another participant to make the update.
- checkout the branch for [PR #340](https://github.com/PediatricOpenTargets/OpenPedCan-analysis/pull/340) and create branch off it for this update.  The `download-data.sh`  bash script in this branch is already updated for v12 data downloads
   - `git checkout -b v12-post-release origin/v12-post-release`
   - `git branch v12-snv-freq`

- change `datatypeId` column value for the output  tables from `somatic_mutation` to `pediatric_cancer`
- include  add `HGVSg` column in the result tables as described in [ticket # 313](https://github.com/PediatricOpenTargets/ticket-tracker/issues/315)
- rerun the module using v12 data release files 
-  submit your PR to the `v12-post-release`  branch
- output files are likely to be larger than the maximum limit allowed on GitHub. Include a .gitignore in the `results/` directory
-  Updating PedcbioPortal URL links is not required for these preliminary tables until when [ticket # 509](https://github.com/PediatricOpenTargets/ticket-tracker/issues/509) has been completed

#### What input data should be used? Which data were used in the version being updated?
- module input data files are described in the README and already set in the wrapper bash script. 

#### When do you expect the revised analysis will be completed?
1 day

#### Who will complete the updated analysis?
@kelseykeith

**Comment by jharenza** [comment]
closed with https://github.com/PediatricOpenTargets/OpenPedCan-analysis/pull/346
