### ISSUE TITLE
WXS bed file for TARGET 

### ISSUE THREAD

**Issue by kgaonkar6** [PediatricOpenTargets/ticket-tracker#53]
#### What data file(s) does this issue pertain to?
We have paired tumor and normal targeted-capture samples we will need a bed file to run WF

Sample distribution:
```
  experimental_strategy sample_type     n
  <chr>                 <chr>       <int>
1 WXS                   Normal        659
2 WXS                   Tumor         699
```

#### What release are you using?

v5

#### Put your question or report your issue here.
Once we have the TARGET bed file please check if the bed is hg19 we will need to map to hg38 to reprocess the data.

**Comment by jharenza** [comment]
Assigning to @bmennis cc @yuankunzhu

**Comment by yuankunzhu** [comment]
did some initial investigation, and notes on [g-slide](https://docs.google.com/presentation/d/1HXlhsZi64tLkIpBbxs0BkFsGN_BSip5TlzWgSJCCEzg/edit#slide=id.ge25f85e018_0_30)

basically we have:

using v5, we have 1358 TARGET WXS samples and query them in GDC, we have
- 1308 are WXS, among them:
  - 1151 have no capture kit information, recorded as “None”
  - the rest 157 are all with kit Custom V2 Exome Bait, 48 RXN X 16 tubes which is hg19 based
- 17 are Genotyping Array → no capture kit info
- 3 are WGS → no capture kit info
- 30 have no record → those are actually not sequenced

**Comment by kgaonkar6** [comment]
looping in @ewafula @afarrel to confirm/provide additional information regarding capture kit

**Comment by afarrel** [comment]
[SeqCap_EZ_Exome_v2.bed.zip](https://github.com/PediatricOpenTargets/ticket-tracker/files/6728923/SeqCap_EZ_Exome_v2.bed.zip)
Here is the Bed file for AML WXS.

**Comment by jharenza** [comment]
> [SeqCap_EZ_Exome_v2.bed.zip](https://github.com/PediatricOpenTargets/ticket-tracker/files/6728923/SeqCap_EZ_Exome_v2.bed.zip)
> Here is the Bed file for AML WXS.

@zhangb1 @yuankunzhu ^

**Comment by zhangb1** [comment]
> [SeqCap_EZ_Exome_v2.bed.zip](https://github.com/PediatricOpenTargets/ticket-tracker/files/6728923/SeqCap_EZ_Exome_v2.bed.zip)
> Here is the Bed file for AML WXS.

@afarrel @jharenza  are they HG19 or 38,  do you know?

**Comment by ewafula** [comment]
@yuankunzhu @zhangb1, here are both the updated WXS capture kits bed file manifest and the bed files for the TARGET cancer types. Most of the kits utilized target regions from both hg19 and GRCh37 but don't provide definitive info which coordinates were used in their respective bed files. For the TARGET project,  raw reads for AML and NBL for each capture library were aligned to `GRCh37-lite` and `GRCh37/HG19_Broad_variant` respectively.  cc @jharenza, @afarrel,  @chinwallaa , @kgaonkar6 

Can't attach the bed files.  Will upload on slack. https://opentargetspediatrics.slack.com/archives/C021N2D56DB/p1625114498299200?thread_ts=1624885379.266600&cid=C021N2D56DB

[target_WXS_capture_kits_bed_file_manifest.tsv.zip](https://github.com/PediatricOpenTargets/ticket-tracker/files/6745440/target_WXS_capture_kits_bed_file_manifest.tsv.zip)

**Comment by kgaonkar6** [comment]
Closing , please reopen if needed.
