### ISSUE TITLE
update rna-seq-expression-summary-stats tables for v12 

### ISSUE THREAD

**Issue by ewafula** [PediatricOpenTargets/ticket-tracker#530]
#### What analysis module should be updated and why?
Update [rna-seq-expression-summary-stats](https://github.com/PediatricOpenTargets/OpenPedCan-analysis/tree/dev/analyses/rna-seq-expression-summary-stats) module

#### What changes need to be made? Please provide enough detail for another participant to make the update.
- checkout the branch for [PR #340](https://github.com/PediatricOpenTargets/OpenPedCan-analysis/pull/340) and create branch off it for this update.  The `download-data.sh`  bash script in this branch is already updated for v12 data downloads
   - `git checkout -b v12-post-release origin/v12-post-release`
   - `git branch v12-tpm`

- update the module to include the TCGA TPM gene expression matrix. You need to read in both `gene-expression-rsem-tpm-collapsed.rds` and `tcga-gene-expression-rsem-tpm-collapsed.rds` matrices then merge them into a single dataframe to be analyzed together. Note that there are 26 genes in the OPC matrix that are not in the TCGA matrix. When merging, only keep the common genes between the matrices so that way we are on level a playing ground with what expression is being measured for gene across all samples.
```
> opc <- read_rds("gene-expression-rsem-tpm-collapsed.rds") %>% rownames()
> tcga <- read_rds("tcga-gene-expression-rsem-tpm-collapsed.rds") %>% rownames()
> setdiff(opc, tcga)
 [1] "SNORA16A"       "TBCE"           "ANAPC1P2"       "PDE11A"        
 [5] "PRICKLE2-AS1"   "CCDC39"         "MATR3"          "POLR2J4"       
 [9] "SPDYE11"        "POLR2J3"        "KBTBD11-OT1"    "PINX1"         
[13] "RMRP"           "ZNF883"         "BMS1P4"         "ITFG2-AS1"     
[17] "SFTA3"          "GABARAPL3"      "SNORA50A"       "SLFN12L"       
[21] "SIGLEC5"        "MKKS"           "ACTL10"         "DUXAP8"        
[25] "ARMCX5-GPRASP2" "U6"            
> setdiff(tcga, opc)
character(0)
````

- rerun the module using v12 data release files 
-  submit your PR to the `v12-post-release`  branch
- output files will likely be larger than the maximum limit on GitHub. Include a .gitignore in the `results/` directory

#### What input data should be used? Which data were used in the version being updated?
- module input data files are described in the README and already set in the wrapper bash script. 

#### When do you expect the revised analysis will be completed?
1 day

#### Who will complete the updated analysis?
@sangeetashukla

**Comment by jharenza** [comment]
Closed with https://github.com/PediatricOpenTargets/OpenPedCan-analysis/pull/347
