### ISSUE TITLE
Update debian sources list (possible issue)

### ISSUE THREAD

**Issue by jharenza** [PediatricOpenTargets/ticket-tracker#534]
Cross-posting from OpenPBTA:
https://github.com/AlexsLemonade/OpenPBTA-analysis/pull/1745

>Looks like Debian finally pulled the plug on Debian 9 (Stretch) so now we have to deal with that. This is a first attempt, but it is failing locally when trying to build java, so we'll see.

**Comment by jashapiro** [comment]
For this project, a far better solution will be to update the docker image to a more recent version of R/rocker. That may require updates in other places, but it will be important to do this anyway, as the current versions rely on MRAN, which will shut down soon.

This will also allow the use of more modern packages which may speed or improve other analyses.

I would probably recommend updating to R 4.2.3, which is one version before the current release. This will mean that the rocker image will still use a frozen repository, but it will use a [Posit Public Package Manager](https://packagemanager.posit.co/) snapshot, as described: https://github.com/rocker-org/rocker-versioned2

**Comment by jharenza** [comment]
Ah, we did discuss updating the R/rocker version after v12 which is in process. We did remove the reliance on MRAN to use R package manager, per [your suggestion](https://github.com/AlexsLemonade/OpenPBTA-analysis/issues/1250#issuecomment-1074330529) over in OpenPBTA, so ✔️ for one thing!

**Comment by jharenza** [comment]
Closed with https://github.com/PediatricOpenTargets/OpenPedCan-analysis/pull/321
