### ISSUE TITLE
Copy v12 OPC files into CAVATICA project

### ISSUE THREAD

**Issue by jharenza** [PediatricOpenTargets/ticket-tracker#535]
Copy v12 files into https://cavatica.sbgenomics.com/u/cavatica/opentarget

post-v12 release

**Comment by jharenza** [comment]
Hi @zhangb1 v12 has been released! Can you work on this when you get a chance? Thanks!

**Comment by zhangb1** [comment]
```
https://cavatica.sbgenomics.com/u/cavatica/opentarget/files/#q?path=v12
```

v12 in the opentarget project now.
