### ISSUE TITLE
Update to R version 4.2.3 in docker image 

### ISSUE THREAD

**Issue by jharenza** [PediatricOpenTargets/ticket-tracker#537]
Suggested [here](https://github.com/PediatricOpenTargets/ticket-tracker/issues/534#issuecomment-1520995059) by @jashapiro was to update the R version in our docker image, which will also likely entail updates to module functions.

Also suggested in #515 is to add vroom for quicker loading of large files.

**Comment by jharenza** [comment]
Will also need to update the freeze date for R packages, as currently using 2019: https://github.com/PediatricOpenTargets/OpenPedCan-analysis/blob/8862448c8be13d78dab9691657a54d773d2c426f/Dockerfile#L9-L10

Possibly might need to change the package manager, per above comment.

**Comment by jashapiro** [comment]
When you update to an R4.x image, you should be able to delete that line completely. This line was likely added to deal with the MRAN  instability. In more recent rocker images, the CRAN mirror will already be set to an RSPM freeze date that corresponds to the release date of the _next_ version of R. See https://github.com/rocker-org/rocker-versioned2.

**Comment by jharenza** [comment]
awesome, thank you @jashapiro !
