### ISSUE TITLE
update cancer_group for BS_ETC8R0TD

### ISSUE THREAD

**Issue by komalsrathi** [PediatricOpenTargets/ticket-tracker#54]
#### What data file(s) does this issue pertain to?

histologies.tsv

#### What release are you using?

v5

#### Put your question or report your issue here.

BS_ETC8R0TD `cancer_group` should be Neuroblastoma, right now it is `NA`:

  Kids_First_Biospecimen_ID cohort cancer_group
1:               BS_ETC8R0TD   GMKF         <NA>

**Comment by komalsrathi** [comment]
@ewafula from [slack](https://opentargetspediatrics.slack.com/archives/C021N2D56DB/p1624389569256700), should we close this?

**Comment by ewafula** [comment]
@komalsrathi, close because the issue was previously addressed and closed after Sharon and John asked to include GMKF samples with "Unknown" in some dx columns.
