### ISSUE TITLE
Updated analysis: Refactoring molecular-subtyping-ATRT module

### ISSUE THREAD

**Issue by zzgeng** [PediatricOpenTargets/ticket-tracker#541]
#### What analysis module should be updated and why?
Update molecular-subtyping-ATRT module to include a script to generate JSON file for sample selection. 

#### What changes need to be made? Please provide enough detail for another participant to make the update.
Add a script to generate JSON file for sample selection. 

#### What input data should be used? Which data were used in the version being updated?
input: histologies_base.tsv (v12)

**Comment by jharenza** [comment]
closed with https://github.com/PediatricOpenTargets/OpenPedCan-analysis/pull/359
