### ISSUE TITLE
Updated analysis: Refactoring molecular-subtyping-neurocytoma module

### ISSUE THREAD

**Issue by zzgeng** [PediatricOpenTargets/ticket-tracker#546]
#### What analysis module should be updated and why?
Update molecular-subtyping-neurocytoma module to include a script to generate JSON file for sample selection. Make sure the format of output files in this module is consistent with other molecular subtyping modules.

#### What changes need to be made? Please provide enough detail for another participant to make the update.
Add a script to generate JSON file for sample selection.

#### What input data should be used? Which data were used in the version being updated?
histologies_base.tsv (v12)

**Comment by jharenza** [comment]
closed with https://github.com/PediatricOpenTargets/OpenPedCan-analysis/pull/365
