### ISSUE TITLE
The difference of variant call files for DNA sample between v11 and v12 release

### ISSUE THREAD

**Issue by zzgeng** [PediatricOpenTargets/ticket-tracker#549]
#### What data file(s) does this issue pertain to? 
variant-level-snv-consensus-annotated-mut-freq.tsv.gz from v11 and v12
https://github.com/PediatricOpenTargets/OpenPedCan-analysis/blob/dev/analyses/hotspots-detection/input/hotspots_database/hotspot_database_2017_snv.tsv

#### What release are you using?

v11 and v12

#### Put your question or report your issue here.
Compare between v11 and v12 release, if there is anything off in protein change (HGVSp_short), transcripts, etc.

**Comment by jharenza** [comment]
@zzgeng can you take [this](https://cavatica.sbgenomics.com/u/zhangb1/opentagret-4-callers-vcf-temp-holder/files/645eb287bc2e1056deb7a040/) MAF, which was the [original hg19 hotspot VCF](https://github.com/taylor-lab/hotspots/blob/master/publication_hotspots.vcf) lifted over from hg19 to hg38 and then annotated and identify what differences in protein location change by gene from [this hotspot TSV file](https://github.com/PediatricOpenTargets/OpenPedCan-analysis/blob/dev/analyses/hotspots-detection/input/hotspots_database/hotspot_database_2017_snv.tsv) we have been using? We know BRAF protein location will differ, but I think we need to use _this_ as our new comparison. You can use [this](https://cavatica.sbgenomics.com/u/zhangb1/opentagret-4-callers-vcf-temp-holder/files/645eaf970fb693681b09a56a/) hotspot file with gene symbols lifted.

**Comment by jharenza** [comment]
@migbro has been working on this over in [bixu-tracker](https://github.com/d3b-center/bixu-tracker/issues/1903).
