### ISSUE TITLE
Proposed Analysis: AML subtyping

### ISSUE THREAD

**Issue by kgaonkar6** [PediatricOpenTargets/ticket-tracker#55]
#### What are the scientific goals of the analysis?
From email discussion with Dr. Sarah Tasian, we have the following information that we should use to subtype AML.

>I have included our pediatric AML risk classification from our current COG phase 3 clinical trial (AAML1831) and how we are stratifying patients by underlying genetic alterations in case helpful. An earlier version of this clinical protocol table is included in a review paper attached if you need a reference. Please note that ‘RAM phenotype’ is a flow cytometry designation (CD56++ and dim for CD45/CD38/HLA-DR) and usually aligns with the CBFA2T3-GLIS2 fusion in AMKL.
‘Low risk’ AML: RUNX1-RUNXT1 from t(8;21), CBFB-MYH11 from inv(16), CEBPA point mutations, NPM1 point mutations
‘High risk’ AML: classically monosomy 7, monosomy 5/5q-, and FLT3-ITD, but now with many others
Lesions that are not clearly prognostic fall into an intermediate category, and we use end-induction measurable residual disease (MRD) to refine risk stratification and allocate to transplant in first remission or not.

![image](https://user-images.githubusercontent.com/34580719/122997265-d00dc900-d379-11eb-8c4c-15d17c4041a1.png)

![image](https://user-images.githubusercontent.com/34580719/122997275-d308b980-d379-11eb-94af-54b1db1fb750.png)

![image](https://user-images.githubusercontent.com/34580719/122997288-d603aa00-d379-11eb-9dbb-19a15f21fab8.png)

#### What methods do you plan to use to accomplish the scientific goals?

🚨 This is a draft
 @jharenza  will update/add information
We will use fusion calls to subtype the samples the subtypes for now

- AML, low risk
RUNX1-RUNXT1 from t(8;21)
CBFB-MYH11 from inv(16), 

- AML, high risk 
FLT3-ITD
MLLT10-any partner
CBFA2T3-GLIS2 (RAM phenotype)

- AML, medium risk 
TBD all/subset alterations in the figures above

#### What input data are required for this analysis?
fusion-putative-oncogenic.tsv

#### How long do you expect is needed to complete the analysis? Will it be a multi-step analysis?
2-3 days

#### Who will complete the analysis (please add a GitHub handle here if relevant)?
@kgaonkar6

**Comment by jharenza** [comment]
Adding to this [data dictionary](https://docs.google.com/spreadsheets/d/1_KyfeZNsepIxSU0Nzw5Mi8mk1PiKCWlSBjatw0AECQ0/edit#gid=1553670248) prepared by Sam V and discussed with Sarah T  to the ticket. I also sent an email to Sarah today asking if she would like us to use the below designations or the high/med/low risk designations as above. If using above, they won't match NCIT IDs, so we will have to figure out how to best do that part.

| inv(16)(p13q22)                            | NCIT:C36373   |
|--------------------------------------------|---------------|
| t(16;16)(p13.1;q22)                        | NCIT:C27759   |
| t(15;17)(q24;q21)                          | NCIT:C27758   |
| t(9;11)(p22;q23) / MLL-MLLT3(AF9)          | NCIT:C36370   |
| t(10;11)(p12;q23) / MLL-MLLT10(AF10)       | NCIT:C132102  |
| t(10;11)(p11.2;q23)                        | NCIT:C168758  |
| t(1;11)(q21;q23) / MLL-MLLT11(AF1Q)        | NCIT:C168759  |
| t(4;11)(q21;q23) / MLL-MLLT2(AF4)          | NCIT:C36365   |
| t(6;11)(q27;q23) / MLL-MLLT4(AF6)          | NCIT:C36610   |
| t(6;9)(p23;q34) DEK/NUP214                 | NCIT:C36532   |
| t(11;19)(q23;p13) / (MLL-ENL)/(MLL-ELL)    | NCIT:C168764  |
| t(11;19)(q23;p13.1) / (MLL-ELL)            | NCIT:C36371   |
| t(11;19)(q23;p13.3) / (MLL-ENL)            | NCIT:C36372   |
| MLL Other Partner                          | NCIT:C36517   |
| t(11;17)(AF17)                             | NCIT:C168760  |
| t(8;16)MOZ/CBP                             | NCIT:C167194  |
| Monosomy 7                                 | NCIT:C36411   |
| Monosomy 5                                 | NCIT:C36523   |
| Trisomy 8                                  | NCIT:C36396   |
| der.12p                                    | NCIT:C173542  |
| t(2;12)                                    | NCIT:C173543  |
| t(5;11)(q35;p15) / NSD1/NUP98              | NCIT:C131503  |
| t(7;12)(q36;p13) / HLXB9(MNX1)/ETV6(TEL)   | NCIT:C122689  |
| t(9;22)(q34;q11.2) / ABL/BCR               | NCIT:C13271   |
| inv(3)(q21.3;q26.2)                        | NCIT:C36407   |
| t(3;3)(q21;q26.2)                          | NCIT:C36406   |
| t(3;12)(q23;p12.3) / ETV6/EVI1             | NCIT:C168766  |
| del(5q)(5q31-q32)                          | NCIT:C168769  |
| t(1;22)(RBM15-MKL1)                        | NCIT:C36417   |
| del(13q)(13q14-21)                         | NCIT:C168770  |
| del(17p)                                   | NCIT:C36499   |
| MLL Rearrangement                          | NCIT:C122623  |
| Non-KMT2A MLLT10                           | NCIT:C168771  |
| inv(16)(p13.3q24.3) / CBFA2T3-GLIS2        | NCIT:C167195  |
| t(11;15)(p15;q35) / NUP98/JARID1A          | NCITC131505   |
| t(16;21)(q24;q22) / RUNX1-CBFA2T3          | NCIT:C168773  |
| t(3;5)(q25;q34) / NPM1/MLF1                | NCIT:C36415   |
| t(16;21)(p11;q22) / FUS/ERG                | NCIT:C36616   |
| NPM1 Mutation                              | NCIT:C82429   |
| Monoallelic CEBPA Gene Mutation            | NCIT:C168774  |
| Biallelic CEBPA Gene Mutation              | NCIT:C157569  |
| CEBPA Gene Mutation                        | NCIT:C38372   |
| FLT3 Internal Tandem Duplication           | NCIT:C67494   |
| FLT3 Tyrosine Kinase Domain Point Mutation | NCIT:C67495   |
| WT1 Mutation                               | NCIT:C146726  |
| CKIT Mutation - Ex17                       | NCIT:C116396  |
| CKIT Mutation - Ex8                        | NCIT:C128660  |
| CKIT Mutation - Unspecified                | NCIT:C39712   |
| GATA1 Mutation                             | NCIT:C82340   |
| RUNX1 Mutation                             | NCIT:C38362   |
| PTPN11 Mutation                            | NCIT:C82612   |
| N-RAS Mutation                             | NCIT:C41381   |
| K-RAS Mutation                             | NCIT:C41361   |
| Other                                      | NCIT:C17649   |
| Unknown                                    | NCIT:C17998   |
| Not Reported                               | NCIT:C43234   |

**Comment by kgaonkar6** [comment]
Just wanted to verify the nomenclature, since I don't think we have use cytogenetic terms before for subtyping.

`del(5q)(5q31-q32)` http://atlasgeneticsoncology.org/Anomalies/del5qID1092.html deletion anywhere in chr5 q or chr 5q31-32 

`inv(16)(p13q22)`  http://atlasgeneticsoncology.org/Anomalies/inv16ID1036.html which I believe denotes a inversion chr16 in p13 and q22

`t(9;22)(q34;q11.2) / ABL/BCR` http://atlasgeneticsoncology.org/Anomalies/t0922ALLID1024.html, denotes a translocation and chr 9 q34 and chr22q11.2 AND OR a fusion of ABL-BCR 

`der.12p` ?

**Comment by jharenza** [comment]
Oh yes - I have a new email from Sarah and still have to compile this - we will not search fro these, but rather include in the subtype itself. Have to think about how we want to do this.
