### ISSUE TITLE
Updated analysis: missing NBL samples in histologies file

### ISSUE THREAD

**Issue by zzgeng** [PediatricOpenTargets/ticket-tracker#550]
#### What analysis module should be updated and why?
molecular-subtyping-pathology
molecular-subtyping-NBL

#### What changes need to be made? Please provide enough detail for another participant to make the update.
Check the script to make sure include all NBL samples.

#### What input data should be used? Which data were used in the version being updated?
histologies.tsv
[neuroblastoma_molecular_subtypes.tsv](https://github.com/PediatricOpenTargets/OpenPedCan-analysis/blob/dev/analyses/molecular-subtyping-NBL/results/neuroblastoma_molecular_subtypes.tsv)

#### When do you expect the revised analysis will be completed?
Next week

**Comment by jharenza** [comment]
completed with https://github.com/PediatricOpenTargets/OpenPedCan-analysis/pull/367
