### ISSUE TITLE
Missing germline sex estimate in ops csv

### ISSUE THREAD

**Issue by jharenza** [PediatricOpenTargets/ticket-tracker#552]
#### What data file(s) does this issue pertain to?
https://github.com/d3b-center/histologies-qc/blob/main/histologies/20230310_release_histologies_ops.csv

#### What release are you using?

v12 OPC

#### Put your question or report your issue here.
[missing_germline_sex.csv](https://github.com/PediatricOpenTargets/ticket-tracker/files/11480085/missing_germline_sex.csv)

**Comment by zhangb1** [comment]
@HuangXiaoyan0106  can you check this?

**Comment by jharenza** [comment]
[missing_germline_sex.csv](https://github.com/PediatricOpenTargets/ticket-tracker/files/11483071/missing_germline_sex.csv)
Current update ^ using the file in https://cavatica.sbgenomics.com/u/d3b-bixu-ops/monthly-release-data/files/#q?path=20230515_release (cc @HuangXiaoyan0106 @zhangb1 @aadamk)

**Comment by HuangXiaoyan0106** [comment]
> [missing_germline_sex.csv](https://github.com/PediatricOpenTargets/ticket-tracker/files/11483071/missing_germline_sex.csv)
> Current update ^ using the file in https://cavatica.sbgenomics.com/u/d3b-bixu-ops/monthly-release-data/files/#q?path=20230515_release (cc @HuangXiaoyan0106 @zhangb1 @aadamk)

I checked them and none of them are on the master genomics manifest. cc @zhangb1

**Comment by HuangXiaoyan0106** [comment]
Hi @jharenza, here is the new histology file with the missing gender added based on the extra Hope manifest provided by @zhangb1 
https://cavatica.sbgenomics.com/u/d3b-bixu-ops/monthly-release-data/files/64644258301b36722425cfbe/

**Comment by jharenza** [comment]
thanks so much @HuangXiaoyan0106 - is it possible in the future to name this file without a date and extra text? That way we do not have to change the filename everytime we generate a histologies file for a data release? Wondering if maybe you can have a "current" folder or something where that filename is always the same and the dated ones are archived elsewhere? Not sure if this would work for you?

**Comment by HuangXiaoyan0106** [comment]
@jharenza Currently, we do not have this function. But I can mark this on my to-do list, I need to think about the whole process of Airflow. If this feature is implemented, I will let you know.

**Comment by jharenza** [comment]
thanks, just putting it out there! also, looks like the file is good, will close.
