### ISSUE TITLE
Updated documentation: analysis README out of date

### ISSUE THREAD

**Issue by jharenza** [PediatricOpenTargets/ticket-tracker#554]
#### What analysis module should be updated and why?
README for analysis modules needs to be updated

#### What changes need to be made? Please provide enough detail for another participant to make the update.
1. Changing over to use GENCODE v39 from v29, VEP 105 where needed
2. Make sure all modules are up to date with respect to whether they are being used in OPC, what the outputs are, etc.

#### What input data should be used? Which data were used in the version being updated?
NA

#### When do you expect the revised analysis will be completed?
next sprint

**Comment by atlas4213** [comment]
@jharenza When it comes to whether or not the module is being used in OPC, how exactly would I verify that?

**Comment by jharenza** [comment]
> @jharenza When it comes to whether or not the module is being used in OPC, how exactly would I verify that?

Thanks for checking- you can typically go by the last time it was run (if it was not run in a few years, then we haven't yet adapted it. if you see some commits from our team and not ALSF, then it has been used here).

**Comment by atlas4213** [comment]
@jharenza Also am I changing all references to which gencode version we are using to 39 or only the ones that say gencode 29?

**Comment by atlas4213** [comment]
> @jharenza Also am I changing all references to which gencode version we are using to 39 or only the ones that say gencode 29?

Nevermind. I see in the code that the version is v39 so I will update it.

**Comment by atlas4213** [comment]
@jharenza Okay, I have gone through and made changes for the gencode versions as well as checking for the readme to tell the input and outputs. I see that there are some modules that have been marked as deprecated but when it comes to knowing that the modules are not in use any more, is there any particular way for me to check that? Also when it comes to the formatting of the readme's do we want them to all have the same format or just to be sure that the desired sections are included? Lastly for the few modules that do not have readme's should I inform the people that wrote the module or just make a note of it?

**Comment by jharenza** [comment]
Hi @atlas4213!

>some modules that have been marked as deprecated but when it comes to knowing that the modules are not in use any more, is there any particular way for me to check that?

For this, if they are marked, then they are definitely not being used. Some are leftover from OpenPBTA, some are deprecated here. Are there any you are questioning? The deprecated modules should not have had any recent commits (last few years).

>Also when it comes to the formatting of the readme's do we want them to all have the same format or just to be sure that the desired sections are included? 

The only part of this ticket is to format the main README in the analysis folder. So no need to worry about formatting analysis module READMES.

>Lastly for the few modules that do not have readme's should I inform the people that wrote the module or just make a note of it?

If you see any missing, please make separate tickets for each and we can assign as needed. Thanks!

**Comment by atlas4213** [comment]
> Hi @atlas4213!
> 
> > some modules that have been marked as deprecated but when it comes to knowing that the modules are not in use any more, is there any particular way for me to check that?
> 
> For this, if they are marked, then they are definitely not being used. Some are leftover from OpenPBTA, some are deprecated here. Are there any you are questioning? The deprecated modules should not have had any recent commits (last few years).
> 
> > Also when it comes to the formatting of the readme's do we want them to all have the same format or just to be sure that the desired sections are included?
> 
> The only part of this ticket is to format the main README in the analysis folder. So no need to worry about formatting analysis module READMES.
> 
> > Lastly for the few modules that do not have readme's should I inform the people that wrote the module or just make a note of it?
> 
> If you see any missing, please make separate tickets for each and we can assign as needed. Thanks!

Okay, no problem. How exactly do I go about making a separate ticket?

**Comment by jharenza** [comment]
You can create tickets here: https://github.com/PediatricOpenTargets/ticket-tracker/issues - I suggest using "updated analysis" template. Thanks!

**Comment by jharenza** [comment]
closed with https://github.com/PediatricOpenTargets/OpenPedCan-analysis/pull/383
