### ISSUE TITLE
 Rerun all of the modules with the new docker image

### ISSUE THREAD

**Issue by ewafula** [PediatricOpenTargets/ticket-tracker#556]
#### What analysis module should be updated and why?
 Rerun all of the modules with the new docker image. 

#### What changes need to be made? Please provide enough detail for another participant to make the update.
- update any module that fails or has warnings as a result of deprecated R or Python functions as a result of newer packages/modules

#### What input data should be used? Which data were used in the version being updated?
Respective module inputs

#### When do you expect the revised analysis will be completed?
Starting the in  second half of this sprint 

#### Who will complete the updated analysis?
@ewafula

**Comment by jharenza** [comment]
closed with https://github.com/PediatricOpenTargets/OpenPedCan-analysis/pull/372
