### ISSUE TITLE
Remove sample not-consented from methyl matrices

### ISSUE THREAD

**Issue by ewafula** [PediatricOpenTargets/ticket-tracker#559]
#### What are the scientific goals of the analysis?
Remove Kids_First_Biospecimen_ID `BS_XA1T7CAX` which is not consented from methyl matrices.

#### What methods do you plan to use to accomplish the scientific goals?
Exclude form methyl matrices

#### What input data are required for this analysis?
- methyl-beta-values.rds
- methyl-cn-values.rds
- methyl-m-values.rds

#### How long do you expect is needed to complete the analysis? Will it be a multi-step analysis?
1 day

#### Who will complete the analysis (please add a GitHub handle here if relevant)?
@ewafula 

#### What relevant scientific literature relates to this analysis?
NA

**Comment by jharenza** [comment]
Also remove for aliquot id mixup/uncertainty: 

```
BS_7J80611F
BS_PYYQTG34
```

@ewafula this is ready to be worked on

**Comment by jharenza** [comment]
@ewafula I got more clarity from NIH on this - we will keep BS_7J80611F and BS_PYYQTG34.

**Comment by ewafula** [comment]
@jharenza. This is done — updated matrices and `methy-md5sum.txt` uploaded to the v13 folder on the s3 bucket.
