### ISSUE TITLE
Add ENSG to Hugo Symbol map file to v6

### ISSUE THREAD

**Issue by jharenza** [PediatricOpenTargets/ticket-tracker#56]
#### What data file(s) does this issue pertain to?
RSEM files contain Hugo Symbols, but OT needs ENSG IDs

#### What release are you using?

v5

#### Put your question or report your issue here.
Map file in slack [here](https://opentargetspediatrics.slack.com/archives/C021Y7H1X8U/p1624396310190400) since I cannot paste a TSV in github 🤯

**Comment by jharenza** [comment]
@kgaonkar6 please retain only those ENSG ids which were collapsed for this

**Comment by kgaonkar6** [comment]
Ah I missed the comment above. These are currently all ENSG ids ( without the numbers after "." ) so there will be multiple per gene.  I can do a quick update.

**Comment by jharenza** [comment]
added with [PR 34](https://github.com/PediatricOpenTargets/OpenPedCan-analysis/pull/34)
