### ISSUE TITLE
Update workflow scripts associated with the data release analysis process

### ISSUE THREAD

**Issue by ewafula** [PediatricOpenTargets/ticket-tracker#561]
#### What analysis module should be updated and why?
- Include  copy number consensus in `scripts/generate-analysis-files.sh`
- clean up `scripts/run-for-subtyping.sh` 

#### What changes need to be made? Please provide enough detail for another participant to make the update.
- update `generate-analysis-files.sh` to  include generate cnv consensus file
- clean up `run-for-subtyping.sh` to match the current molecular subtyping process that also  includes generating additional release files -  `full histologies file` and `independent sample lists`
- log execution runtimes for all modules included in the `generate-analysis-files.sh` and  `run-for-subtyping.sh`  workflow scripts to include  time estimates in the repo README

#### What input data should be used? Which data were used in the version being updated?
pre-release data files 

#### When do you expect the revised analysis will be completed?
1/2 day

#### Who will complete the updated analysis?
@ewafula

**Comment by jharenza** [comment]
completed with https://github.com/PediatricOpenTargets/OpenPedCan-analysis/pull/380
