### ISSUE TITLE
v6 data release

### ISSUE THREAD

**Issue by jharenza** [PediatricOpenTargets/ticket-tracker#57]
#### What data file(s) does this issue pertain to?
starting a list of what needs to go into v6

### merged CNV files - 
- [x] #44 
- [x] #77 
- [x] #81 

#80 removed ,to be released with TARGET WXS in a future release

### update histologies file per 
- [x] #43 
- [x]  #46 
- [x]  #54 
- [x]  #48 
- [x]  #79
- [x] https://github.com/AlexsLemonade/OpenPBTA-analysis/issues/1108
- [x] #61 
- [x] #62 
- [x] @ewafula added 661 additional RNA samples (some sequenced twice labelled with, sample_id suffix *1 and *2) and two additional  Kidney Wilms tumor WXS samples for TARGET cohort

### Add gene mapping files 

- [x] #56  
- [x] #78 
- [x] #84 

#85 removed, will be added in v7 

#### What release are you using?

v5

**Comment by kgaonkar6** [comment]
Should we add the independent-sample lists to the release as well?

**Comment by jharenza** [comment]
eh, i think the relative paths should be OK, as long as we keep those up to date? I put in a change request per #37 and they may change if we remove some samples from histologies.tsv, so it may be hard to keep up with them in release.

**Comment by jharenza** [comment]
added with [PR 34](https://github.com/PediatricOpenTargets/OpenPedCan-analysis/pull/34)

**Comment by jharenza** [comment]
added with [PR 34](https://github.com/PediatricOpenTargets/OpenPedCan-analysis/pull/34)
