### ISSUE TITLE
Proposed Analysis: Calculate z-scores within and between all cancer groups and GTEX normals

### ISSUE THREAD

**Issue by afarrel** [PediatricOpenTargets/ticket-tracker#6]
#### Objective:

Create a module to generate z-scores and quantiles within/between all cancers <s>`broad_histology`</s> `cancer_group`

#### What changes need to be made? Please provide enough detail for another participant to make the update.
NOTE: This will require a batch-corrected merged TPM file containing all cancer samples as well as a batch-corrected merged TPM file containing all cancer + GTEX samples, which should be done and released prior to merging this analysis.

1. Remove  tumor-associated `Normal` samples from analysis.
2. Calculate gene x histology z-scores across the full tumor dataset.
3. Annotate quantiles.
4. Within each <s>`broad_histology`</s> `cancer_group`, calculate z-scores per gene.
5. Annotate quantiles.
6. Calculate gene x histology z-scores across the full tumor + GTEX dataset.
7. Annotate quantiles.

_Expected output_ 
Matrices: 
1. gene x histology z-scores across all cancers
2. gene x histology quantiles across all cancers 
3. gene x histology z-scores within `cancer_group`
4. gene x histology quantiles within `cancer_group`
5. gene x histology/GTEX tissue z-scores across all cancers
6. gene x histology/GTEX tissue quantiles across all cancers

#### Who will work/consult on this:

@sangeetashukla or @logstar 

#### To discuss:
>a batch-corrected merged TPM file containing all cancer samples as well as a batch-corrected merged TPM file containing all cancer + GTEX samples

Should we provide two corrected matrices or one large corrected matrix?  cc @aadamk and @taylordm

**Comment by logstar** [comment]
@jharenza @afarrel Thank you for the analysis description. I understand this analysis, but I have a few questions about how to exactly implement the analysis.

While I am waiting for the batch corrected cancer + GTEX TPM matrix, I will use OpenPedCan-analysis v4 release contains `gtex_target_tcga-gene-counts-rsem-expected_count-collapsed.rds` as test data for creating this analysis module.

In steps 2, 3, 6 and 7, should I take the mean TPM for each gene across all samples in each broad histology, and then use the TPM means to compute z-scores and quantiles? Is it ok to create the following 11 quantiles 0.0, 0.1, 0.2, ..., 1.0? Is the result expected to be like the following table?

geneID    | histology1 | histology2 | ...
------|------------|------------|----
gene1 | 0.1        | -0.5       | ...
gene2 | 0.3        | -0.7       | ...
... | ...        | ...       | ...

In steps 4 and 5, should I use the gene TPM of all samples within a histology to z-scores and quantiles? Is the result expected to be like the following table?

geneID    | sample1 | sample2 | ...
------|------------|------------|----
gene1 | 0.2        | -0.1       | ...
gene2 | 0.9        | -0.6       | ...
... | ...        | ...       | ...

**Comment by jharenza** [comment]
Hi @logstar! Thanks for asking.

I just noticed that I had `broad_histology` up there, but I actually created `cancer_group` for this purpose. So, let's use that column.

In addition, it looks like we have TCGA `broad_histology`/`cancer_group` too narrow, which we can fix later, so for this, please just subset TARGET and GTEX.

>In steps 2, 3, 6 and 7, should I take the mean TPM for each gene across all samples in each broad histology, and then use the TPM means to compute z-scores and quantiles?

For the z-scoring, I think you can follow what @kgaonkar6 had done for comparing expression to GTEX when we did fusion gene expression analysis [here](https://github.com/AlexsLemonade/OpenPBTA-analysis/blob/master/analyses/fusion_filtering/03-Calc-zscore-annotate.R).

>Is it ok to create the following 11 quantiles 0.0, 0.1, 0.2, ..., 1.0? Is the result expected to be like the following table?

For quantiles, @taylordm only wanted the four quantiles, and I think what she wanted was basically whether that genes' z-score fell into one of 4 _quartiles_: 0.0-0.25, 0.25-0.5, 0.5-0.75, and 0.75-1.0. So for this, maybe you can just annotate as one of the below (stole from wiki :)). @taylordm correct me if I am wrong/any preference here?


Quart | Output QUARTILE Value
-- | --
0 | Minimum value
1 | Lower Quartile (25th percentile)
2 | Median
3 | Upper Quartile (75th percentile)
4 | Maximum value

p | Output QUARTILE Value
-- | --
0 | Minimum value
0.25 | Lower Quartile (25th percentile)
0.5 | Median
0.75 | Upper Quartile (75th percentile)
1 | Maximum value

<br class="Apple-interchange-newline">

>In steps 4 and 5, should I use the gene TPM of all samples within a histology to z-scores and quantiles? 

Yes

Those tables look fine to me, one matrix of z-scores and one matrix of quantiles

**Comment by logstar** [comment]
@jharenza Thank you for the detailed reply. I will work on this analysis accordingly.

**Comment by logstar** [comment]
@jharenza thank you for the reference to the fusion filtering analysis.

I wonder if this analysis needs to use all normal GTEX sample means and standard deviations for computing z-scores, like the fusion filtering analysis. In the following code from `fusion_filtering/03-Calc-zscore-annotate.R#L115-L121`, the overall means of normal samples are subtracted from the disease samples, and the disease samples are divided by the overall standard deviations of normal samples.

```R
  #normData mean and sd
  normData_means <- rowMeans(normData, na.rm = TRUE)
  normData_sd <- apply(normData, 1, sd, na.rm = TRUE)
  # subtract mean
  expressionMatrixzscored <- sweep(expressionMatrixMatched, 1, normData_means, FUN = "-")
  # divide by SD remove NAs and Inf values from zscore for genes with 0 in normData
  expressionMatrixzscored <- sweep(expressionMatrixzscored, 1,normData_sd, FUN = "/") %>% mutate(GeneSymbol=rownames(.)) %>% na_if(Inf) %>% na.omit()
```

In `fusion_filtering/03-Calc-zscore-annotate.R`, z-scores are only computed for each individual sample, if I understand correctly. Therefore, I am still wondering if I should use `cancer_group` means to compute z-scores and quantiles for each individual `cancer_group`, like the following:

1. For each `cancer_group` and each gene, compute the mean TPM across all samples within the `cancer_group`. This generates a new gene x `cancer_group` matrix of TPM means, which will be refered as `cancer_group_tpm_mean_matrix` in the following steps.
2. `cancer_group_tpm_mean_matrix <- log2(cancer_group_tpm_mean_matrix + 1)`. This transformation is used in `fusion_filtering/03-Calc-zscore-annotate.R`.
3. If we do not need to use normal sample means or standard deviations, compute z-scores as `(cancer_group_tpm_mean_matrix - rowMeans(cancer_group_tpm_mean_matrix)) / rowStandardDeviation(cancer_group_tpm_mean_matrix)`, which generates a new gene x `cancer_group` z-score matrix. If we need to use normal sample means or standard deviations, compute z-scores as `(cancer_group_tpm_mean_matrix - rowMeans(normal_sample_tpm_matrix)) / rowStandardDeviation(normal_sample_tpm_matrix)`.
4. Compute quantiles as `rowQuantile(cancer_group_tpm_mean_matrix, p = c(0, 0.25, 0.5, 0.75, 1))`, which generates a new gene x `cancer_group_p` matrix like the following:

geneID | cancer_group1_quantile_p0 | cancer_group1_quantile_p25 | cancer_group1_quantile_p50 | cancer_group1_quantile_p75 | cancer_group1_quantile_p100 | cancer_group2_quantile_p0 | cancer_group2_quantile_p25 | ...
-------|------------------|-------------------|-------------------|-------------------|------------------|------------------|-------------------|----
gene1  | 94.8             | 5.6               | 63.3              | 99.2              | 26.4             | 8.9              | 12.5              | ...
gene2  | 50.1             | 64.9              | 14.7              | 88.4              | 25.6             | 96.4             | 2.1               | ...
gene3  | 76.2             | 64.9              | 35.2              | 26.9              | 89.              | 90.5             | 38.               | ...
...    | ...              | ...               | ...               | ...               | ...              | ...              | ...               | ...

For individual sample z-scores and quantiles, use the same procedure without the first step of taking means.

**Comment by jharenza** [comment]
> * For each `cancer_group` and each gene, compute the mean TPM across all samples within the `cancer_group`. This generates a new gene x `cancer_group` matrix of TPM means, which will be refered as `cancer_group_tpm_mean_matrix` in the following steps.

Hi @logstar this sounds great. Just a note - we need to remove all sample-level analysis, so we will essentially do two analyses:
1. across `cancer_group`s
2. across each `cancer_group` and normals (`gtex_group`) (separate z-score matrix for each `cancer_group`) - does that make sense?. This one may expand to a 3rd analysis using `gtex_subgroup`. I had this written earlier as all cancers and normals, but I think it makes more sense to do them separately.

**Comment by logstar** [comment]
Thank you for the detailed reply @jharenza .

I will work on the updated analyses using the upcoming v5 release data. I will generate the following results for each analysis:

> 1. across `cancer_group`s

- One gene x `cancer_group` z-score matrix that includes all `cancer_groups`. Compute gene-wise z-scores with `(cancer_group_tpm_mean_matrix - rowMeans(cancer_group_tpm_mean_matrix)) / rowStandardDeviation(cancer_group_tpm_mean_matrix)`.
- One gene x `cancer_group_quantile` quantile matrix that includes all `cancer_groups`.

> 2. across each `cancer_group` and normals (`gtex_group`) (separate z-score matrix for each `cancer_group`) - does that make sense?. This one may expand to a 3rd analysis using `gtex_subgroup`. I had this written earlier as all cancers and normals, but I think it makes more sense to do them separately.

- For each `cancer_group`:
  - One gene x `cancer/gtex_group` z-score matrix that includes one `cancer_group` and all `gtex_group`s. Compute gene-wise z-score with `(cancer_gtex_group_tpm_mean_matrix - rowMeans(cancer_gtex_group_tpm_mean_matrix)) / rowStandardDeviation(cancer_gtex_group_tpm_mean_matrix)`.
  - One gene x `cancer/gtex_group_quantile` quantile matrix that includes one `cancer_group` and all `gtex_group`s.

To further clarify the z-score computation procedure:

- I will compute gene-wise z-scores for each gene x `cancer/gtex_group` mean TPM matrix with `(tpm_mean_matrix - rowMeans(tpm_mean_matrix)) / rowStandardDeviation(tpm_mean_matrix)`.
- This procedure is different from `fusion_filtering/03-Calc-zscore-annotate.R`, which is referred in the comment <https://github.com/PediatricOpenTargets/ticket-tracker/issues/6#issuecomment-853259474>.
- In `fusion_filtering/03-Calc-zscore-annotate.R`, z-scores are computed using two TPM matrices, `cancer_sample_tpm_matrix` and `normal_sample_tpm_matrix`, with `(cancer_sample_tpm_matrix - rowMeans(normal_sample_tpm_matrix)) / rowStandardDeviation(normal_sample_tpm_matrix)`

If you have any questions, feel free to let me know.

**Comment by jharenza** [comment]
closing in favor of the cleaner ticket #51
