### ISSUE TITLE
histologies.tsv tumor_descriptor update 

### ISSUE THREAD

**Issue by kgaonkar6** [PediatricOpenTargets/ticket-tracker#61]
#### What data file(s) does this issue pertain to?
histologies.tsv needs an update to harmonize to use "Camel Case" naming convention such as first letter of each word is capitalized. That will also fix `Recurrent tumor` and `Recurrent Tumor`

```
> as.data.frame(table(v5$tumor_descriptor))
                              Var1  Freq
1                Initial CNS Tumor  1518
2                 Metastatic tumor   396
3                    Primary tumor 12869
4                      Progressive   301
5  Progressive Disease Post-Mortem    13
6                       Recurrence   136
7                  Recurrent tumor   161
8                  Recurrent Tumor    44
9                Second Malignancy    37
10                     Unavailable     2
```

#### What release are you using?

v5

**Comment by jharenza** [comment]
@kgaonkar6 we should also harmonize all of these to the CBTN terms

```Recurrence
Recurrent tumor
Recurrent Tumor
```

to `Recurrence`

**Comment by jharenza** [comment]
added with [PR 34](https://github.com/PediatricOpenTargets/OpenPedCan-analysis/pull/34)
