### ISSUE TITLE
histologies.tsv experimental_strategy update

### ISSUE THREAD

**Issue by kgaonkar6** [PediatricOpenTargets/ticket-tracker#62]
#### What data file(s) does this issue pertain to?
histologies.tsv
![image](https://user-images.githubusercontent.com/34580719/123152890-183cf200-d433-11eb-97cd-2ed663fb65fa.png)

#### What release are you using?

v5

#### Put your question or report your issue here.
PBTA has panel has experimental_strategy == “Targeted Sequencing” should we update the TARGET panel experimental_strategy as well to have it harmonized?

**Comment by jharenza** [comment]
added with [PR 34](https://github.com/PediatricOpenTargets/OpenPedCan-analysis/pull/34)
