### ISSUE TITLE
Proposed Analysis: Test data for OpenTarget CI

### ISSUE THREAD

**Issue by kgaonkar6** [PediatricOpenTargets/ticket-tracker#63]
#### What are the scientific goals of the analysis?
To set up test data for CI

#### What methods do you plan to use to accomplish the scientific goals?
Create a subset of samples that can test all modules being added to the OpenPedCan repo

#### What input data are required for this analysis?
snv-consensus-plus-hotspots.maf.tsv.gz
fusion-arriba.tsv.gz
fusion-starfusion.tsv.gz
gene-counts-rsem-expected_count-collapsed.rds
gene-expression-rsem-tpm-collapsed.rds
histologies.tsv
cnv-cnvkit.tsv.gz
cnv-controlfreec.tsv.gz

#### How long do you expect is needed to complete the analysis? Will it be a multi-step analysis?
TBD

#### Who will complete the analysis (please add a GitHub handle here if relevant)?
@kgaonkar6

**Comment by jharenza** [comment]
For normals, select from `gtex_group == Brain & Adrenal Gland`

**Comment by jharenza** [comment]
Should have >5 samples per `cancer_group`

**Comment by jharenza** [comment]
I created a folder here: s3://kf-openaccess-us-east-1-prd-pbta/open-targets/testing/

**Comment by jharenza** [comment]
Code to subset files: https://github.com/AlexsLemonade/OpenPBTA-analysis/tree/master/analyses/create-subset-files @runjin326

**Comment by jharenza** [comment]
This will probably be @runjin326 to generate the data while @devbyaccident works on GA

**Comment by jharenza** [comment]
Closing this - will make a fresh ticket with more details
