### ISSUE TITLE
Proposed Analysis: Annotate SNV table of mutation frequencies

### ISSUE THREAD

**Issue by jharenza** [PediatricOpenTargets/ticket-tracker#64]
#### What are the scientific goals of the analysis?
Annotate the SNV TSV table of mutation frequencies per cohort+cancer group+primary/relapse as will be created in #8 for conversion to JSON format.

#### What methods do you plan to use to accomplish the scientific goals?
Annotate the table with headings as below:
[OT_SomaticTables_SNV_CNV.xlsx](https://github.com/PediatricOpenTargets/ticket-tracker/files/6711008/OT_SomaticTables_SNV_CNV.xlsx)

Much of this can be achieved by leveraging MAF fields corresponding to the exact variant calls. For ClinVar, we may need to download a version of the database.

Update June 30th
- [ ] Instead of COSMIC frequency, annotate as COSMIC mutation census with tier from CosmicMutantExportCensus.tsv​
- [x] #82 
- [x] #83 
- [x] add RMTL (Y/N)

#### What input data are required for this analysis?
```
snv-consensus-plus-hotspots.maf.tsv.gz
```

#### How long do you expect is needed to complete the analysis? Will it be a multi-step analysis?
2-3 days

#### Who will complete the analysis (please add a GitHub handle here if relevant)?
@logstar ?

**Comment by logstar** [comment]
Hi @jharenza . Thank you for the analysis description.

I have a few questions about how to generate the columns in the "Example Somatic Mutation Table" sheet of [OT_SomaticTables_SNV_CNV.xlsx](https://github.com/PediatricOpenTargets/ticket-tracker/files/6711008/OT_SomaticTables_SNV_CNV.xlsx).

- To generate `Frequency in Overall Dataset` (example value "4.17%"), should I use all samples, or all `independent-primary-plus` samples, or other set of samples in a `cancer_group`/`cancer_group_cohort`?
- To generate `Mutations/Total Samples` ( example value ".1/24"), should I aggregate all variants of the corresponding gene and divide by "Total Samples"? Similarly, for "Total Samples", should I use all samples, or all `independent-primary-plus` samples, or other set of samples in a `cancer_group`/`cancer_group_cohort`?
- To generate `Identifer hg38 (See ClinVar ex)` (example value "10_102599545_G_A"), should I concatenate `Chromosome`, `Start_Position`, `End_Position`, `Reference_Allele`, and `Tumor_Seq_Allele2` with "_"? I briefly went over [ClinVar identifier documentation](https://www.ncbi.nlm.nih.gov/clinvar/docs/identifiers/) and several examples, but I could not find any identifier exactly like "10_102599545_G_A".
- To generate the following columns, do we have mapping tables available? If not, I will download them from their corresponding databases.
  - `Protein Identifier/Name`
  - `Protein Refseq ID`
  - `Predicted Mutation Impact Score`
  - `Overall COSMIC frequency`
  - `OncoKB cancer gene`
  - `OncoKB oncogene/TS gene`
- To generate `Hotspot`, should I use the the `HotSpotAllele` column in the MAF file?

I will work on the frequencies first.

**Comment by jharenza** [comment]
Hi @logstar 

Let's tackle `cancer_group_cohort` first.

>- To generate `Frequency in Overall Dataset` (example value "4.17%"), should I use all samples, or all `independent-primary-plus` samples, or other set of samples in a `cancer_group`/`cancer_group_cohort`?
>- To generate `Mutations/Total Samples` ( example value ".1/24"), should I aggregate all variants of the corresponding gene and divide by "Total Samples"? Similarly, for "Total Samples", should I use all samples, or all `independent-primary-plus` samples, or other set of samples in a `cancer_group`/`cancer_group_cohort`?

Ah, good question. I hadn't recalled this field, but the way we would create this is within `cancer_group_cohort`, identify the unique variants per patient (right now, they are at a sample level, but you could pull out BS_IDs and the mutation metadata, then merge it with the PT_IDs, drop the BS_IDs and unique them to get patient-level variant calls. This would be the data that goes into `Frequency in Overall Dataset` and I think instead of `Mutations/Total Samples`, we should make this column two columns: `Total mutations` and `Total patients in dataset`, otherwise, it looks like it would just be the fraction that corresponds to the percent.

Then, the `independent-primary` will be used for `Frequency in primary tumors` and `independent-relapse` will be used for `Frequency in relapse tumors`. That being said, I think we need another four columns for `Total primary tumors mutated` and `Total primary tumors in dataset` `Total relapse tumors mutated` and `Total relapse tumors in dataset`.  Let me update the excel file, too.

>- To generate `Identifer hg38 (See ClinVar ex)` (example value "10_102599545_G_A"), should I concatenate `Chromosome`, `Start_Position`, `End_Position`, `Reference_Allele`, and `Tumor_Seq_Allele2` with "_"? I briefly went over [ClinVar identifier documentation](https://www.ncbi.nlm.nih.gov/clinvar/docs/identifiers/) and several examples, but I could not find any identifier exactly like "10_102599545_G_A".

I think you have this almost right; there would be no end position in the above identifier.

>- To generate the following columns, do we have mapping tables available? If not, I will download them from their corresponding databases.
  - `Protein Identifier/Name`
  - `Protein Refseq ID`
  - `Predicted Mutation Impact Score`
  - `Overall COSMIC frequency`
  - `OncoKB cancer gene`
  - `OncoKB oncogene/TS gene`

Yes, let me update the excel file- give me a few min.

>- To generate `Hotspot`, should I use the the `HotSpotAllele` column in the MAF file?

yes

**Comment by logstar** [comment]
@jharenza Thank you for the detailed reply.

I will work on `cancer_group_cohort` first.

I agree it is more informative to have the revised columns.

If I understand correctly, `Frequency in Overall Dataset` = `Total mutations` / `Total patients in dataset`. The `Total mutations` is the number of patients that has the corresponding variant of the row.

**Comment by jharenza** [comment]
>If I understand correctly, Frequency in Overall Dataset = Total mutations / Total patients in dataset. The Total mutations is the number of patients that has the corresponding variant of the row.

yes, where total mutations is total N of that specific mutation in the dataset

**Comment by logstar** [comment]
> > If I understand correctly, Frequency in Overall Dataset = Total mutations / Total patients in dataset. The Total mutations is the number of patients that has the corresponding variant of the row.
> 
> yes, where total mutations is total N of that specific mutation in the dataset

Got it. Thank you for the quick reply. I will work on the analysis accordingly.

**Comment by kgaonkar6** [comment]
Just wanted to make a note from the June 30th call (feel free to update/edit)
- [ ] Instead of COSMIC frequency, annotate as COSMIC mutation census with tier from CosmicMutantExportCensus.tsv​

**Comment by logstar** [comment]
Thank you for the notes.

I wonder where I can get the CosmicMutantExportCensus.tsv​ and RMTL table for annotation. Are they going to be available in future data releases?

**Comment by kgaonkar6** [comment]
RMTL will be (soon) provided in v6 
CosmicMutantExportCensus.tsv​ ( Originally from https://cancer.sanger.ac.uk/census or a reusable version of the file with the info) will also be provided in v6

**Comment by logstar** [comment]
> RMTL will be (soon) provided in v6
> CosmicMutantExportCensus.tsv​ ( Originally from https://cancer.sanger.ac.uk/census or a reusable version of the file with the info) will also be provided in v6

Got it. Thank you for the quick reply.

**Comment by jharenza** [comment]
I am having problems downloading the CosmicMutantExportCensus.tsv​ file - I cannot access via the Qiagen website as they suggest, so I submitted an email asking for help there. So, for now, proceed without this annotation.

**Comment by logstar** [comment]
@jharenza Is the following unfinished task included in the `Gene_type` annotation? The "COSMIC genes" are listed as a data source for the `genelistreference.txt` at <https://github.com/PediatricOpenTargets/OpenPedCan-analysis/tree/dev/analyses/fusion_filtering>.

> Instead of COSMIC frequency, annotate as COSMIC mutation census with tier from CosmicMutantExportCensus.tsv​

If not, I could add the required annotation for the v7 annotator and `snv-frequencies` module updates.

**Comment by jharenza** [comment]
No, this was to use the COSMIC mutation evidence rather than the genes. I never heard back from them, so we can add it as a future ticket and enhancement if we hear back.

**Comment by logstar** [comment]
> No, this was to use the COSMIC mutation evidence rather than the genes. I never heard back from them, so we can add it as a future ticket and enhancement if we hear back.

Got it. I think we could leave this ticket open as a reference.

I will also submit two tickets for adding COSMIC mutation evidence to snv-frequencies and annotator, label them with blocked, and refer to this issue.

**Comment by runjin326** [comment]
Closing with [PR45 ](https://github.com/PediatricOpenTargets/OpenPedCan-analysis/pull/45) merged.
