### ISSUE TITLE
Proposed Analysis: Create CNV frequencies file

### ISSUE THREAD

**Issue by jharenza** [PediatricOpenTargets/ticket-tracker#66]
#### What are the scientific goals of the analysis?
Create one file of CNV frequencies per `cohort+cancer_group` for primary and relapse/recurrent tumors, and one file per `cancer_group` for primary and relapse/recurrent tumors. To do this, use the independent specimen files.

#### What methods do you plan to use to accomplish the scientific goals?
This will be performed on a per gene level and we will capture gene amplifications, gains, low-level deletions, and deep deletions.
The table below is a mock-up table of what we would like to do. This ticket will serve the purpose of gathering CNV frequencies, annotating the genes/cancer groups, and ticket #69 will serve to convert to JSONL. Please use the table below as a guide:
[OT_SomaticTables_SNV_CNV.xlsx](https://github.com/PediatricOpenTargets/ticket-tracker/files/6711066/OT_SomaticTables_SNV_CNV.xlsx)

#### What input data are required for this analysis?
consensus cnv files<s>, yet to be released but will come in #57 </s>

#### How long do you expect is needed to complete the analysis? Will it be a multi-step analysis?
2-3 days

#### Who will complete the analysis (please add a GitHub handle here if relevant)?
TBD

**Comment by jharenza** [comment]
@ewafula the most recent CNV table should be this one: https://nih.box.com/s/ftqr2kobvb6anv24ganhows4qhe51a29

**Comment by runjin326** [comment]
Closing with [PR52](https://github.com/PediatricOpenTargets/OpenPedCan-analysis/pull/52) merged.
