### ISSUE TITLE
Proposed Analysis: Convert tpm/z-score/quantile files to JSON

### ISSUE THREAD

**Issue by jharenza** [PediatricOpenTargets/ticket-tracker#67]
#### What are the scientific goals of the analysis?
Convert the files produced in #51 to JSON for load to OT portal.

#### What methods do you plan to use to accomplish the scientific goals?
JSON conversion within the [data-ingestion repository?](https://github.com/PediatricOpenTargets/data-ingestion)

#### What input data are required for this analysis?
Files produced from #51 (PR [27](https://github.com/PediatricOpenTargets/OpenPedCan-analysis/pull/27))

#### How long do you expect is needed to complete the analysis? Will it be a multi-step analysis?
?

#### Who will complete the analysis (please add a GitHub handle here if relevant)?
@ewafula @sangeetashukla @afarrel or @taylordm 

#### What relevant scientific literature relates to this analysis?
NA

Should we put these files in S3?

**Comment by logstar** [comment]
JSON file created in the merged PR <https://github.com/PediatricOpenTargets/OpenPedCan-analysis/pull/27>.
