### ISSUE TITLE
Proposed Analysis: Create JSON files for CNV tables

### ISSUE THREAD

**Issue by jharenza** [PediatricOpenTargets/ticket-tracker#68]
#### What are the scientific goals of the analysis?
Convert the files produced in #66  to JSONL for load to OT portal.

#### What methods do you plan to use to accomplish the scientific goals?
possibly pandas as per https://stackoverflow.com/questions/51775175/pandas-dataframe-to-jsonl-json-lines-conversion

#### What input data are required for this analysis?
Files produced from #66 (PR TBD)

#### How long do you expect is needed to complete the analysis? Will it be a multi-step analysis?
?

#### Who will complete the analysis (please add a GitHub handle here if relevant)?
@ewafula @sangeetashukla @afarrel or @taylordm 

#### What relevant scientific literature relates to this analysis?
NA

Should we put these files in S3?

**Comment by runjin326** [comment]
Closing with [PR52](https://github.com/PediatricOpenTargets/OpenPedCan-analysis/pull/52) merged
