### ISSUE TITLE
Proposed Analysis: Create JSON files for SNV tables

### ISSUE THREAD

**Issue by jharenza** [PediatricOpenTargets/ticket-tracker#69]
#### What are the scientific goals of the analysis?
Convert the files produced in #64  to JSON for load to OT portal.

#### What methods do you plan to use to accomplish the scientific goals?
JSON conversion within the [data-ingestion repository?](https://github.com/PediatricOpenTargets/data-ingestion)

#### What input data are required for this analysis?
Files produced from #64  (PR TBD)

#### How long do you expect is needed to complete the analysis? Will it be a multi-step analysis?
?

#### Who will complete the analysis (please add a GitHub handle here if relevant)?
@ewafula @sangeetashukla @afarrel or @taylordm 

#### What relevant scientific literature relates to this analysis?
NA

Should we put these files in S3?

**Comment by runjin326** [comment]
Closing with [PR66 ](https://github.com/PediatricOpenTargets/ticket-tracker/issues/66) merged.
