### ISSUE TITLE
Proposed Analysis: Create JSON files for fusion tables

### ISSUE THREAD

**Issue by jharenza** [PediatricOpenTargets/ticket-tracker#72]
#### What are the scientific goals of the analysis?
Convert the files produced in #71  to JSON for load to OT portal.

#### What methods do you plan to use to accomplish the scientific goals?
JSON conversion within the [data-ingestion repository?](https://github.com/PediatricOpenTargets/data-ingestion)

Update from June 30th
- [ ] Add RTML
- [ ] Add ENSG ids for each gene
- [ ] Unique row per partner for each gene

#### What input data are required for this analysis?
Files produced from #71   (PR TBD)

#### How long do you expect is needed to complete the analysis? Will it be a multi-step analysis?
?

#### Who will complete the analysis (please add a GitHub handle here if relevant)?
@ewafula @sangeetashukla @afarrel or @taylordm 

#### What relevant scientific literature relates to this analysis?
NA

Should we put these files in S3?

**Comment by kgaonkar6** [comment]
From Jun 30th meeting fusions will have the above update:
- [ ] Add RTML
- [ ] Add ENSG ids

**Comment by jharenza** [comment]
closed with https://github.com/PediatricOpenTargets/OpenPedCan-analysis/pull/49
