### ISSUE TITLE
Updated analysis: independent-samples to modify secondary to relapse/recurrent/progressive only

### ISSUE THREAD

**Issue by jharenza** [PediatricOpenTargets/ticket-tracker#75]
#### What analysis module should be updated and why?
independent-samples

#### What changes need to be made? Please provide enough detail for another participant to make the update.
For the secondary tumors, I realize we want this to be specific to progression or relapse, so I advocate changing the name of the output to be `relapse` and include `tumor_descriptor` listed below:

```
Progressive
Progressive Disease Post-Mortem
Recurrence
Recurrent tumor
Recurrent Tumor
```

within this code:

https://github.com/PediatricOpenTargets/OpenPedCan-analysis/blob/0b5099f94038e12a7e1d98cc65b0801bca8ded63/analyses/independent-samples/independent-samples.R#L48-L51

Once #57 is released, those recurrent tumors should be harmonized and we can probably update this again.

#### What input data should be used? Which data were used in the version being updated?
histologies file

#### When do you expect the revised analysis will be completed?
~1 day

#### Who will complete the updated analysis?
@runjin326

**Comment by jharenza** [comment]
In addition to this, we also want an RNA primary only list as well as a relapse list:

Primary RNA-Seq specimens matching WGS/WXS/Panel independent sample_ids plus "relapse" only-RNA-Seq `independent-specimens.rnaseq.primary.tsv`

Relapse RNA-Seq specimens matching WGS/WXS/Panel independent sample_ids plus "relapse" only-RNA-Seq `independent-specimens.rnaseq.relapse.tsv`

**Comment by runjin326** [comment]
Quick question, did we add more WXS+Panel specimens in V5 release? I am getting more independent samples than v4. Just want to make sure.
`998 WGS primary specimens
167 WGS relapse specimens
1126 WGS specimens (including non-primary)
1734 WGS+WXS+Panel primary specimens
172 WGS+WXS+Panel relapse specimens
1864 WGS+WXS+Panel specimens (including non-primary)`

**Comment by jharenza** [comment]
> Quick question, did we add more WXS+Panel specimens in V5 release? I am getting more independent samples than v4. Just want to make sure.

yes!

**Comment by jharenza** [comment]
completed with [PR 30](https://github.com/PediatricOpenTargets/OpenPedCan-analysis/pull/30)
