### ISSUE TITLE
Add EFO/Mondo cancer mapping file to v6

### ISSUE THREAD

**Issue by jharenza** [PediatricOpenTargets/ticket-tracker#78]
#### What data file(s) does this issue pertain to?
We need a EFO/Mondo cancer mapping file for JSON conversions

#### What release are you using?

v5

#### Put your question or report your issue here.
@afarrel created an EFO/MONDO mapping file for PBTA/GMKF NBL, and will add TARGET cancers

**Comment by afarrel** [comment]
[Histologies_EFO_MONDO_Progress_Codes_Only_V2.txt](https://github.com/PediatricOpenTargets/ticket-tracker/files/6730934/Histologies_EFO_MONDO_Progress_Codes_Only_V2.txt)
[Histologies_EFO_MONDO_Progress_V2.txt](https://github.com/PediatricOpenTargets/ticket-tracker/files/6730935/Histologies_EFO_MONDO_Progress_V2.txt)
@jharenza I added the TARGET EFO/MONDO codes here.

**Comment by jharenza** [comment]
Thank you!

**Comment by jharenza** [comment]
just added this file, with a few edits here: `s3://kf-openaccess-us-east-1-prd-pbta/open-targets/6/efo-mondo-map.tsv`

**Comment by kgaonkar6** [comment]
hmm the file in s3://kf-openaccess-us-east-1-prd-pbta/open-targets/**v**6/efo-mondo-map.tsv errored out with the md5um above.
Can you check and let me know? When I added the md5sum to the download checks it failed.

```
efo-mondo-map.tsv: FAILED
ensg-hugo-rmtl-v1-mapping.tsv: FAILED
```

**Comment by jharenza** [comment]
fixed - i had the path wrong

**Comment by jharenza** [comment]
added with [PR 34](https://github.com/PediatricOpenTargets/OpenPedCan-analysis/pull/34)
