### ISSUE TITLE
Update CBTN+PNOC to PBTA histologies.tsv

### ISSUE THREAD

**Issue by kgaonkar6** [PediatricOpenTargets/ticket-tracker#79]
#### What data file(s) does this issue pertain to?
histologies.tsv

#### What release are you using?

v5

#### Put your question or report your issue here.
Update the cohort to PBTA

**Comment by jharenza** [comment]
added with [PR 34](https://github.com/PediatricOpenTargets/OpenPedCan-analysis/pull/34)
