### ISSUE TITLE
Add WXS to cnv files update

### ISSUE THREAD

**Issue by kgaonkar6** [PediatricOpenTargets/ticket-tracker#80]
#### What data file(s) does this issue pertain to?
Add WXS cnv calls to cnvkit and controlfreec files

#### What release are you using?

v6

#### Put your question or report your issue here.

**Gathering WXS samples**
```
histology_wxs <- histology %>% filter(experimental_strategy != "WGS",
                                      experimental_strategy != "RNA-Seq",
                                      sample_type !="Normal")
```

 It seems both cnvkit and controlfreec didn't historically have WXS calls can we add them now since we will be using those calls for OpenTarget

``` 
table(cnvkit$ID %in% histology_wxs$Kids_First_Biospecimen_ID)
 FALSE 
2084011 

 
 table(controlfreec$Kids_First_Biospecimen_ID %in% histology_wxs$Kids_First_Biospecimen_ID)
 FALSE 
1652450 
```

**Comment by kgaonkar6** [comment]
@zhangb1 not sure if you already noticed the ticket, I've  just updated the ticket to include WXS update as well.

**Comment by kgaonkar6** [comment]
@yuankunzhu @jharenza, did we plan to have bix-ops merge WXS cnvkit calls for this v6 release? 
OR will we add this data in a future release when the WXS cnv data is registered/harmonized? 

The required WXS samples are 
`cohort==PNOC & experimental_strategy=="WXS"`
s3://kf-openaccess-us-east-1-prd-pbta/open-targets/v5/histologies.tsv

The updated cnvkit seg file (with the fixed GMKF tumor ids are now in v6 )
s3://kf-openaccess-us-east-1-prd-pbta/open-targets/v6/cnv-cnvkit.seg.gz

**Comment by jharenza** [comment]
WXS will be later once harmonized

**Comment by jharenza** [comment]
we can add them with the rest of TARGET WXS later

**Comment by zhangb1** [comment]
@jharenza @kgaonkar6  I missed this discussion.

Seems we need to add  WXS  cnvkit and control-freeC from PNOC003 to the v7 ?  how about panel, I remember PNOC003-05 has a panel data.

**Comment by jharenza** [comment]
> how about panel

No, I don't think so - did you run CNV on the panel? I don't think it will be very accurate, so we are going to stick to WXS only.

**Comment by zhangb1** [comment]
> > how about panel
> 
> No, I don't think so - did you run CNV on the panel? I don't think it will be very accurate, so we are going to stick to WXS only.

but for the TARGET samples , should we merge the panel data (I saw that in the ticket)?  we ran the CNV in panel too, but yeah you are right ,the results maybe need to be revalued .

**Comment by jharenza** [comment]
merge panel only for SNVs, I would suggest

**Comment by zhangb1** [comment]
This should be fixed in the v7 release

**Comment by jharenza** [comment]
closing with [PR 61](https://github.com/PediatricOpenTargets/OpenPedCan-analysis/pull/61)
