### ISSUE TITLE
cnv-cnvkit.tsv.gz GMKF ids check

### ISSUE THREAD

**Issue by kgaonkar6** [PediatricOpenTargets/ticket-tracker#81]
#### What data file(s) does this issue pertain to?
histologies.tsv

#### What release are you using?

v5

#### Put your question or report your issue here.
@zhangb1  can we check if the GMKF ids are assigned the correctly? 
While checking for a new cnvkit file released for v6 it seems the IDs used in the cnvkit are `experimental_strategy=="Normal".

```
> histology[which(histology$Kids_First_Biospecimen_ID %in% cnvkit$ID),c("cohort","sample_type","experimental_strategy")] %>% unique()
# A tibble: 3 x 3
  cohort sample_type experimental_strategy
  <chr>  <chr>       <chr>                
1 CBTN   Tumor       WGS                  
2 PNOC   Tumor       WGS                  
3 GMKF   Normal      WGS  
```

**Comment by yuankunzhu** [comment]
@zhangb1 is OOO today, but I did a quick check on Biospecimen IDs in the v6 cnv-cnvkit.tsv.gz file, those are all `Tumor` in Data Service. Maybe we didn't put the right sample_type in the histologies file?

```bash
aws s3 cp s3://kf-openaccess-us-east-1-prd-pbta/open-targets/v6/cnv-cnvkit.tsv.gz .


$ zcat cnv-cnvkit.tsv.gz | sed 1d | cut -f1 | head -10000 | sort -u \
  | while read i; do kfapi bs $i | jq .results.source_text_tissue_type; done
"Tumor"
"Tumor"
"Tumor"
"Tumor"
"Tumor"
"Tumor"
"Tumor"
"Tumor"
"Tumor"
```

**Comment by kgaonkar6** [comment]
Thanks for looking into this! I'll check with the team to verify the histology file. 

I'd done a quick check for a few samples which say are sample_type == "Normal" , maybe I misunderstood?
cnvkit$ID %>% unique() %>% tail(2)
[1] "BS_Y2DE021S" "BS_NVAYK43V"

https://kf-api-dataservice.kidsfirstdrc.org/biospecimens/BS_Y2DE021S
https://kf-api-dataservice.kidsfirstdrc.org/biospecimens/BS_NVAYK43V

**Comment by zhangb1** [comment]
Sorry @kgaonkar6  , I accidentally add the Normal BS ID to the seg file for Maris. because the Maris data was using the old pipeline, there is no seg file in cavatica project. 

here is the match from the normal  to the  tumor. Sorry about that
[Maris_tumor_normal_matched_list.txt](https://github.com/PediatricOpenTargets/ticket-tracker/files/6737787/Maris_tumor_normal_matched_list.txt)

**Comment by kgaonkar6** [comment]
Thanks @zhangb1 I'll update the cnvkit files on s3

**Comment by kgaonkar6** [comment]
This is fixed , thanks!

**Comment by kgaonkar6** [comment]
Opening the corrected cnvkit seg file is not in s3

**Comment by runjin326** [comment]
Close with PR89 (https://github.com/PediatricOpenTargets/OpenPedCan-analysis/pull/89)
