### ISSUE TITLE
Proposed Analysis: add oncoKB annotation to consensus MAF

### ISSUE THREAD

**Issue by jharenza** [PediatricOpenTargets/ticket-tracker#82]
#### What are the scientific goals of the analysis?
Add oncoKB annotation to consensus MAF

#### What methods do you plan to use to accomplish the scientific goals?
Use the annotator here: https://github.com/oncokb/oncokb-annotator

@kgaonkar6 has run this on annotated MAFs before - even though it suggests using VCF as input, maybe we can use MAF. 

#### What input data are required for this analysis?
Consensus MAF

#### How long do you expect is needed to complete the analysis? Will it be a multi-step analysis?
1-2 days

#### Who will complete the analysis (please add a GitHub handle here if relevant)?
@logstar ?

#### What relevant scientific literature relates to this analysis?
NA

**Comment by logstar** [comment]
Updates on the progress. I applied for the oncoKB API access at <https://www.oncokb.org/apiAccess> yesterday. I am waiting for their approval, which might take one or two days. After getting the API access, I will work on annotating the consensus MAF and update the [merged SNV frequency table](https://github.com/PediatricOpenTargets/OpenPedCan-analysis/pull/45).

**Comment by jharenza** [comment]
thanks for the update @logstar ! We may have to rethink this module and pull it into the d3b harmonization workflow since there is an api access issue, but keep us posted. In the meantime, let's keep working on the SNV frequency table (as you are) and try to get a mock JSON file (even if a sample) for next Wednesday if possible.

**Comment by logstar** [comment]
> thanks for the update @logstar ! We may have to rethink this module and pull it into the d3b harmonization workflow since there is an api access issue, but keep us posted. In the meantime, let's keep working on the SNV frequency table (as you are) and try to get a mock JSON file for this table (even if a sample) for next Wednesday if possible.

I will keep you posted on adding the oncoKB annotation.

Thank you for the heads-up on JSON file deadline. I just remembered there was a discussion on Monday that we want analysis modules to create JSON objects and store them somewhere. I will use `jsonlite::write_json(result_tibble, 'result.json')` for converting the result tables to JSON.

**Comment by logstar** [comment]
Closed with PR <https://github.com/PediatricOpenTargets/OpenPedCan-analysis/pull/45> merged.
