### ISSUE TITLE
Updated analysis: add pedcbio links to SNV tables

### ISSUE THREAD

**Issue by jharenza** [PediatricOpenTargets/ticket-tracker#83]
#### What analysis module should be updated and why?
Module being created in #64 

#### What changes need to be made? Please provide enough detail for another participant to make the update.
Add pedcbio links in columns by row for visualization of the cohort by gene cc @taylordm and possibly to discuss at 8 am on Wednesday for input from John, Sharon, and Sarah.

#### What input data should be used? Which data were used in the version being updated?
the main url: https://pedcbioportal.kidsfirstdrc.org/study/summary?id=ped_opentargets_2021 plus appending gene IDs

Some ideas:

**oncoprint** `(*results/oncoprint*studyID*geneID)`
https://pedcbioportal.kidsfirstdrc.org/results/oncoprint?cancer_study_list=ped_opentargets_2021&tab_index=tab_visualize&case_set_id=ped_opentargets_2021_all&Action=Submit&gene_list=H3F3A

**lollipop** `(*results/mutations*studyID*geneID)`
https://pedcbioportal.kidsfirstdrc.org/results/mutations?cancer_study_list=ped_opentargets_2021&tab_index=tab_visualize&case_set_id=ped_opentargets_2021_all&Action=Submit&gene_list=H3F3A

#### When do you expect the revised analysis will be completed?
1-2 days after #64 

#### Who will complete the updated analysis?
@logstar

**Comment by logstar** [comment]
Thank you for the analysis description. The plot URLs work great!

I just have a few questions on how to implement this analysis.

- Should I use `case_set_id=ped_opentargets_2021_all` for all genes?
- How to check if a gene symbol is available in `https://pedcbioportal.kidsfirstdrc.org/study/summary?id=ped_opentargets_2021`? I am planning to put a blank `''` at genes that are not available. I can download data from the `Mutated Genes`, `Fusion Genes`, and `CNA Genes` and take a unique union of all symbols, but I wonder if this is the correct way.

**Comment by jharenza** [comment]
>Should I use case_set_id=ped_opentargets_2021_all for all genes?

This will be specific to each cohort+cancer_group. Here is a sample link below, where the values of cohort and histology change based on the values in cohort and cancer_group (aka HISTOLOGY) in pedcbio. Sorry for not including that!

https://pedcbioportal.kidsfirstdrc.org/study/summary?id=ped_opentargets_2021#filterJson={"clinicalDataFilters":[{"attributeId":"COHORT","values":[{"value":"PBTA"}]},{"attributeId":"HISTOLOGY","values":[{"value":"Low-grade glioma/astrocytoma"}]}],"studyIds":["ped_opentargets_2021"]}

>How to check if a gene symbol is available in https://pedcbioportal.kidsfirstdrc.org/study/summary?id=ped_opentargets_2021? I am planning to put a blank '' at genes that are not available. I can download data from the Mutated Genes, Fusion Genes, and CNA Genes and take a unique union of all symbols, but I wonder if this is the correct way.

@allisonheath @migbro or @kalletlak - can you answer this question? is there a file/api to the list of gene IDs that pedcbio uses?

**Comment by logstar** [comment]
Thank you for the clarification @jharenza .

Regarding the oncoprint URL for each (`cancer_group`, `cohort`) combination, I wonder if we could define `case_set_id`s, which is used in the following URL, to represent different (`cancer_group`, `cohort`) combinations, e.g. `case_set_id=ped_opentargets_2021_low_grade_glioma_astrocytoma_pbta` and `case_set_id=ped_opentargets_2021_ medulloblastoma_pbta`.

> **oncoprint** `(*results/oncoprint*studyID*geneID)`
> https://pedcbioportal.kidsfirstdrc.org/results/oncoprint?cancer_study_list=ped_opentargets_2021&tab_index=tab_visualize&case_set_id=ped_opentargets_2021_all&Action=Submit&gene_list=H3F3A

cc: @allisonheath

**Comment by kalletlak** [comment]
`case_set_id` is predefined property, which are defined in study data files while importing. Also it is used when there are filters applied.

If there are any filters in study page and trying to query genes from then all the information(cohort, cancer group, and gene) will be transformed to a session if there are lot of filtered samples

Regarding data availability for genes -> it would be different for each profile. For mutation and fusion/sv, you could use `Mutated Genes` and `Fusion Genes` tables. But `CNA genes` it includes only `AMP` and `HOMDEL` (2 and -2). If it is just one gene then I prefer to query for results and see if there are any alterations for it. But if you want all genes then I prefer to check in the data files.

**Comment by logstar** [comment]
Thank you for the quick reply @kalletlak .

> `case_set_id` is predefined property, which are defined in study data files while importing. Also it is used when there are filters applied.
> 
> If there are any filters in study page and trying to query genes from then all the information(cohort, cancer group, and gene) will be transformed to a session if there are lot of filtered samples

I wonder what would you suggest if we want to generate oncoprint and lollipop plot URLs for each histology, each cohort, and each gene. I assume getting all session IDs for all histology and cohort combinations would not be a good way, so I was thinking if we could request the maintainer of pedcbioportal kids first data to add `case_set_id`s to the data.

> Regarding data availability for genes -> it would be different for each profile. For mutation and fusion/sv, you could use `Mutated Genes` and `Fusion Genes` tables. But `CNA genes` it includes only `AMP` and `HOMDEL` (2 and -2). If it is just one gene then I prefer to query for results and see if there are any alterations for it. But if you want all genes then I prefer to check in the data files.

After checking some testing URLs, I think we might not need to check data availability for genes, if you could confirm that any valid gene symbol can be linked to a plot, even though the gene is not included in the Mutated/Fusion/CNA genes tabs. For example, `MT-CO1` URL <https://pedcbioportal.kidsfirstdrc.org/results/oncoprint?cancer_study_list=ped_opentargets_2021&tab_index=tab_visualize&case_set_id=ped_opentargets_2021_all&Action=Submit&gene_list=MT-CO1> , but it is not in any Mutated/Fusion/CNA genes tab.

Previously, we want to prevent dead links being inserted into our tables, assuming that a URL would be a dead link if the gene symbol is not included in the dataset.

**Comment by kalletlak** [comment]
1. True, adding case set(sample list) for each histology/cohort would be ideal. BTW, how many would it be? Also if you could come up with those sample lists then we could update the study
@migbro what do you think?

2. Yes, it will work for any valid gene(genes that are present in the pedcbioportal database) irrespective of data availability.

**Comment by migbro** [comment]
>     1. True, adding case set(sample list) for each histology/cohort would be ideal. BTW, how many would it be? Also if you could come up with those sample lists then we could update the study
>        @migbro what do you think?
> 
>     2. Yes, it will work for any valid gene(genes that are present in the pedcbioportal database) irrespective of data availability.

Hmm, case lists like this: https://docs.cbioportal.org/5.1-data-loading/data-loading/file-formats#case-lists? Can custom ones be made? That does seem to make sense. As for missing genes, especially the `MT` genes, if they are important, should we create a faux panel? If we do that, will we need to list all genes, or will a combo of what is in cBio and in this "panel" work?

**Comment by kalletlak** [comment]
yes - for case lists.

for missing genes - we can only query genes that are present in cbio database.

**Comment by migbro** [comment]
Right, but genes can be added, right? Like they did for panels for Project Genie? Or is that just to make an exception to not filter out things like nonsense mutations, synonymous, etc?

**Comment by kalletlak** [comment]
yes, we could definitely add genes. Genes in panels are also validated against genes in the database

**Comment by logstar** [comment]
> 1. True, adding case set(sample list) for each histology/cohort would be ideal. BTW, how many would it be? Also if you could come up with those sample lists then we could update the study

Probably 64  case sets. The dataset has 64 different histologies and 1 cohort `PBTA`.

>    @migbro what do you think?
> 2. Yes, it will work for any valid gene(genes that are present in the pedcbioportal database) irrespective of data availability.

Good to know. Then, we might not need to check gene availability, if all gene symbols we have are present in cbio database. What do you think @jharenza ? Do we need to check exactly, or we could assume that cbio gene symbol set is comprehensive?

**Comment by logstar** [comment]
Regarding the sample lists, I wonder if I could share an R script, so you can adapt it into your code base to generate those case sets.

I could attach the script and results here, but it would be difficult to maintain if there is any updates on the dataset.

**Comment by logstar** [comment]
@kalletlak Attached files are as following. Delete the `.txt` suffix in the filenames to get the correct filename. GitHub does not support attachments with `.tsv` or `.R` suffix.

- [`ped_opentargets_2021_clinical_data.tsv.txt`](https://github.com/PediatricOpenTargets/ticket-tracker/files/6779064/ped_opentargets_2021_clinical_data.tsv.txt): clinical data table downloaded from <https://pedcbioportal.kidsfirstdrc.org/study/summary?id=ped_opentargets_2021>
- [`ped_opentargets_2021_histology_cohort_case_set_id_list.tsv.txt`](https://github.com/PediatricOpenTargets/ticket-tracker/files/6779065/ped_opentargets_2021_histology_cohort_case_set_id_list.tsv.txt): case set table of 63 `case_set_id`s, which has the following columns:
  - `HISTOLOGY`: from clinical data tsv
  - `case_set_id`: converted from HISTOLOGY and COHORT by concatenating with `'___'`, replacing non-alphanum characters to `'_'`, and transforming to lower case
  - `n_samples`: number of samples in the case set
  - `sample_ids`: a `','` separated list of the clinical data "Sample ID" column values that are included in the case set. Assuming that there is no `','` in "Sample ID" values, `sample_ids` can be converted to a list of "Sample ID" values by splitting on `','`
- [`get_histology_cohort_case_set_ids.R.txt`](https://github.com/PediatricOpenTargets/ticket-tracker/files/6779063/get_histology_cohort_case_set_ids.R.txt): R script that takes `ped_opentargets_2021_clinical_data.tsv` to generate `ped_opentargets_2021_histology_cohort_case_set_id_list.tsv`

**Comment by kalletlak** [comment]
Thanks @logstar. @migbro would it be easy to update study based on above information?

**Comment by jharenza** [comment]
@kalletlak thanks for the feedback, but this project is going to have constant updates and I am not sure we can get to a place for real-time pedcbio updates like this. Are you saying we have no option for creating a URL for say:

Open targets study, medulloblastoma, CTNNB1 gene, oncoprint using those keywords? The links will always be random alphanumeric?

**Comment by jharenza** [comment]
hey @kalletlak maybe this will help - we would essentially like to combine this selection:
```
https://pedcbioportal.kidsfirstdrc.org/study/summary?id=ped_opentargets_2021#filterJson={"clinicalDataFilters":[{"attributeId":"HISTOLOGY","values":[{"value":"Medulloblastoma"}]},{"attributeId":"COHORT","values":[{"value":"PBTA"}]}],"studyIds":["ped_opentargets_2021"]}
```
with this oncoprint

```
https://pedcbioportal.kidsfirstdrc.org/results/oncoprint?case_set_id=all&gene_list=CTNNB1&cancer_study_list=ped_opentargets_2021
```

How can we create a URL for the oncoprint using the selection above without creating many `case_set_id` lists?

**Comment by kalletlak** [comment]
@jharenza there is no other way. But we could pass sample ids if they are minimum(depends on url size). Example

https://pedcbioportal.kidsfirstdrc.org/results?cancer_study_list=ped_opentargets_2021&tab_index=tab_visualize&case_ids=ped_opentargets_2021%3A7316-100%2Bped_opentargets_2021%3A7316-101_68282&Action=Submit&gene_list=CTNNB1

where case ids are provided as list of `<study_id>:<sample_id>` joined by `+`

**Comment by jharenza** [comment]
😢  - thanks @kalletlak - i just filed #93 for this

**Comment by kalletlak** [comment]
@logstar example to post data to cbio https://gist.githubusercontent.com/kalletlak/7f31a5f704d26a2bd0a27c7c347f1c3a/raw/866419a728de1dc9fc67a21852a2b45c19f41843/post_to_cbio

**Comment by logstar** [comment]
> @logstar example to post data to cbio https://gist.githubusercontent.com/kalletlak/7f31a5f704d26a2bd0a27c7c347f1c3a/raw/866419a728de1dc9fc67a21852a2b45c19f41843/post_to_cbio

@kalletlak Thank you.

Saw your message on slack as well. I was thinking about how to use the javascript function to implement this link-out. I have no experience with this type of programming.

I was wondering if you have any suggestions on how to implement this on the future PedOT website.

I imagine that someone that develop the backend of the website needs to program a pedcbio icon button to allow executing a similar function like your example. On my end, I would need to provide a list of `case_id`s for each button.

**Comment by kalletlak** [comment]
@logstar yes, it need to be done at PedOT website.

**Comment by logstar** [comment]
Closed with PR <https://github.com/PediatricOpenTargets/OpenPedCan-analysis/pull/45> merged.
