### ISSUE TITLE
Create Table with Uberon codes for GTEx Subgroups

### ISSUE THREAD

**Issue by afarrel** [PediatricOpenTargets/ticket-tracker#85]
#### What data file(s) does this issue pertain to?
GTEx data that will be used in Differential expression tables, etc

#### What release are you using?

This will be included in v6

#### Put your question or report your issue here.
Please create a table that match UBERON code to the GTEx subgroup tissues.

#### When should this be done.
~ 1 Week.

**Comment by sangeetashukla** [comment]
@afarrel @jharenza 
I have updated the excel below with the Uberon codes for the tissues and subgroups listed, as best as I could find via [this link](https://www.ebi.ac.uk/ols/ontologies/uberon) 

In cases where I am not sure of the most suitable code, I have added potential options in the Notes column which need to be reviewed. Would one of you please take a look?

[Uberon_codes_for_GTEX.xlsx](https://github.com/PediatricOpenTargets/ticket-tracker/files/6780434/Uberon_codes_for_GTEX.xlsx)

**Comment by afarrel** [comment]
[Uberon-map.xlsx](https://github.com/PediatricOpenTargets/ticket-tracker/files/6816236/Uberon-map.xlsx)

Here is a table comparing GTEX descriptions with UBERON codes and UBERON descriptions.

**Comment by jharenza** [comment]
Since v8 gtex lists "whole blood" subgroup and "whole blood" group as UBERON_0013756, which is mapped to venous blood, we are changing this nomenclature to "blood". "Whole blood" maps to  UBERON_0000178. I will submit an issue on their portal.

Also collapsing the cerebellums here as noted in #106

**Comment by jharenza** [comment]
these are now in s3 v7 folder cc @kgaonkar6

**Comment by jharenza** [comment]
Update from GTEX portal:

>If you look at this link definition, in the Term Relations Box, you'll note that they are equivalent terms.
https://www.ebi.ac.uk/ols/ontologies/uberon/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FUBERON_0013756
Thanks,
Kristin

**Comment by jharenza** [comment]
closing with [PR 61](https://github.com/PediatricOpenTargets/OpenPedCan-analysis/pull/61)
