### ISSUE TITLE
Redo "Brain_FPKM_hg38_matrix.txt.zip" with new gtex file

### ISSUE THREAD

**Issue by kgaonkar6** [PediatricOpenTargets/ticket-tracker#87]
#### What data file(s) does this issue pertain to?
Add a param to select gtex_group to bash script so that we can create subsets for
Regenerate a Brain GTEx file using tpm file and filter for samples using samples where gtex_group=="Brain"

#### What release are you using?

v6

**Comment by runjin326** [comment]
@kgaonkar6, the `00-normal-matrix-generation.R` script [here](https://github.com/PediatricOpenTargets/OpenPedCan-analysis/commit/3d7b046777de827c80b03f7e1322058a974b14da) should be able to generate one for brain. I used the code to generate the matrix as rds before but it was too big to upload to GitHub. Let me know if you want me to do this.

**Comment by kgaonkar6** [comment]
Thanks @runjin326 ! Closing this since https://github.com/PediatricOpenTargets/OpenPedCan-analysis/pull/46 is merged
