### ISSUE TITLE
Proposed Analysis: Run KF Pipelines on TARGET RNA

### ISSUE THREAD

**Issue by afarrel** [PediatricOpenTargets/ticket-tracker#9]
#### What are the scientific goals of the analysis?
Prepare TARGET RNA and WES <s>and WGS</s> data for ingestion into Open Targets Platform

#### What methods do you plan to use to accomplish the scientific goals?
Kids First pipelines on Cavatica

#### What input data are required for this analysis?
all TARGET RNA 

#### Who will complete the analysis (please add a GitHub handle here if relevant)?
@zhangb1 

Updating this ticket to reflect RNA only

**Comment by jharenza** [comment]
@zhangb1 TARGET AML will be highest priority here, so as to get the fusion calls for a subtyping module.

**Comment by zhangb1** [comment]
> @zhangb1 TARGET AML will be highest priority here, so as to get the fusion calls for a subtyping module.

We are still waiting for the manifest clear up right?

**Comment by jharenza** [comment]
Yes, will followup with @afarrel and Sharon today

**Comment by jharenza** [comment]
@zhangb1 and @yuankunzhu Can you use [this query](https://portal.gdc.cancer.gov/repository?facetTab=files&filters=%7B%22op%22%3A%22and%22%2C%22content%22%3A%5B%7B%22op%22%3A%22in%22%2C%22content%22%3A%7B%22field%22%3A%22cases.project.program.name%22%2C%22value%22%3A%5B%22TARGET%22%5D%7D%7D%2C%7B%22op%22%3A%22in%22%2C%22content%22%3A%7B%22field%22%3A%22files.analysis.workflow_type%22%2C%22value%22%3A%5B%22STAR%202-Pass%22%2C%22STAR%202-Pass%20Genome%22%5D%7D%7D%2C%7B%22op%22%3A%22in%22%2C%22content%22%3A%7B%22field%22%3A%22files.data_format%22%2C%22value%22%3A%5B%22bam%22%5D%7D%7D%2C%7B%22op%22%3A%22in%22%2C%22content%22%3A%7B%22field%22%3A%22files.experimental_strategy%22%2C%22value%22%3A%5B%22RNA-Seq%22%5D%7D%7D%5D%7D&searchTableTab=files) to pull the samples from GDC - it looks like AML is not labeled as `STAR 2 pass Genome` but rather `STAR 2` pass, so they were missing. Then, if you can pull a manifest of `aliquot_id`, we can compare with Sharon and in the meantime, I think we should process all of these samples. 

CAUTION: these are not all 100 bp reads, so the workflow may have to be modified based on read lengths. Some are 50, 75, 100.

**Comment by yuankunzhu** [comment]
just added those `STAR 2 PASS` BAMs to the this project: https://cavatica.sbgenomics.com/u/d3b-bixu-ops/open-target-target-rnaseq/files/#q?label_id=STAR%202-Pass

@jharenza do you have a manifest of the read lengths for those samples?

**Comment by jharenza** [comment]
> just added those `STAR 2 PASS` BAMs to the this project: https://cavatica.sbgenomics.com/u/d3b-bixu-ops/open-target-target-rnaseq/files/#q?label_id=STAR%202-Pass
> 
> 
> 
> @jharenza do you have a manifest of the read lengths for those samples?

Sorry I never posted this here. This box folder (https://upenn.box.com/s/huohekyxkp1xqgljcz3b3qpw2daw1zh2) has multi qc files for the RNA-Seq and you can extract read lengths from them @zhangb1. 

Please us the manifest in the OT v4 folder to select neuroblastoma and AML histology samples for the first run: s3://kf-openaccess-us-east-1-prd-pbta/open-targets/v4/

@yuankunzhu and @zhangb1 now that the billing group is created, do you need anything else from us?

**Comment by zhangb1** [comment]
> > just added those `STAR 2 PASS` BAMs to the this project: https://cavatica.sbgenomics.com/u/d3b-bixu-ops/open-target-target-rnaseq/files/#q?label_id=STAR%202-Pass
> > @jharenza do you have a manifest of the read lengths for those samples?
> 
> Sorry I never posted this here. This box folder (https://upenn.box.com/s/huohekyxkp1xqgljcz3b3qpw2daw1zh2) has multi qc files for the RNA-Seq and you can extract read lengths from them @zhangb1.
> 
> Please us the histologies.tsv file in the OT v4 folder to select neuroblastoma and AML histology samples for the first run: s3://kf-openaccess-us-east-1-prd-pbta/open-targets/v4/
> 
> @yuankunzhu and @zhangb1 now that the billing group is created, do you need anything else from us?

I need to check the difference between the histology samples vs the samples Yuankun imported from GDC... 
Not sure how many overlaps...I can do later today.  We only process will process the overlap samples? @jharenza  just to confirm...

**Comment by jharenza** [comment]
Yes

**Comment by zhangb1** [comment]
checking the histology file in OT v4 folder 

the overlaps are 1208 samples.  will start running the samples with these 1208 first

![image](https://user-images.githubusercontent.com/14929845/121737888-78dd3e00-cac7-11eb-8764-18a378c15e9e.png)

**Comment by zhangb1** [comment]
after talk to @yuankunzhu  and @migbro  seems the read length won't effect the results too much 

see the answer from the author here : 

https://github.com/alexdobin/STAR/issues/1094#issuecomment-738117601 

I will start a test run see how it goes.

**Comment by jharenza** [comment]
Oh, good to know!

**Comment by zhangb1** [comment]
ran one sample. has been completed here:

https://cavatica.sbgenomics.com/u/d3b-bixu-ops/open-target-target-rnaseq/tasks/4c86e0b5-9995-4046-b185-89951e367db5/

I will use the stranded and unstranded information to submit the tasks will draft all the tasks by today.

**Comment by jharenza** [comment]
Nice, that sample has a known `CBFB-MYH11` fusion and it comes up in the results. 👍

**Comment by zhangb1** [comment]
@jharenza  just found an issue about the stranded and unstranded :

I used the file in the box, called `PanTARGET_Samples_MetaData_11419.txt` to check the strandness info

but seems some of the samples have the replicates  , and the strandness information are different,

like TARGET-20-PAPWIU-09A-03R ,  TARGET-20-PAPWIU-09A-03R_1 is unstranded and TARGET-20-PAPWIU-09A-03R_2 is stranded. 

The one we used in cavatica won't tell us which replicate it belongs to.  Not sure you have the information?

**Comment by ewafula** [comment]
Here is a file with rna-seq library types.

[tcga_library_type.tsv.gz](https://github.com/PediatricOpenTargets/ticket-tracker/files/6650598/tcga_library_type.tsv.gz)

**Comment by zhangb1** [comment]
> Here is a file with rna-seq library types.
> 
> [tcga_library_type.tsv.gz](https://github.com/PediatricOpenTargets/ticket-tracker/files/6650598/tcga_library_type.tsv.gz)

Hi eric, there are 262 samples with the `NA` and only poly-A in the RNA_library, does it mean we don't know the types?

**Comment by ewafula** [comment]
> > Here is a file with rna-seq library types.
> > [tcga_library_type.tsv.gz](https://github.com/PediatricOpenTargets/ticket-tracker/files/6650598/tcga_library_type.tsv.gz)
> 
> Hi eric, there are 262 samples with the `NA` and only poly-A in the RNA_library, does it mean we don't know the types?

@zhangb1, sorry for bungling the file name. It was supposed to be `target_library_type.tsv` not `tcga_library_type.tsv`. The samples with `"NA"` were sequenced at `Hudson Alpha seq_center` and the library type is unknown based on the data manifest from obtained from TARGET by @afarrel.  `poly-A == polyA unstranded`, `poly-A stranded == polyA stranded`, and `stranded == total RNA (ribo-minus)`.  I am following @jharenza instructions for the nomenclature used for `pbta-histologies.txt`.

**Comment by zhangb1** [comment]
> > > Here is a file with rna-seq library types.
> > > [tcga_library_type.tsv.gz](https://github.com/PediatricOpenTargets/ticket-tracker/files/6650598/tcga_library_type.tsv.gz)
> > 
> > 
> > Hi eric, there are 262 samples with the `NA` and only poly-A in the RNA_library, does it mean we don't know the types?
> 
> @zhangb1, sorry for bungling the file name. It was supposed to be `target_library_type.tsv` not `tcga_library_type.tsv`. The samples with `"NA"` were sequenced at `Hudson Alpha seq_center` and the library type is unknown based on the data manifest from obtained from TARGET by @afarrel. `poly-A == polyA unstranded`, `poly-A stranded == polyA stranded`, and `stranded == total RNA (ribo-minus)`. I am following @jharenza instructions for the nomenclature used for `pbta-histologies.txt`.

Thank you @ewafula ,   @jharenza  any ideas about those NA samples?

**Comment by zhangb1** [comment]
@jharenza  just follow up this, for those strandness NA samples do we need to run our own tools to decide the strandness?

**Comment by jharenza** [comment]
We need to run our own thanks

**Comment by zhangb1** [comment]
We are facing the connect issue on cavatica to the target data now. I emailed SBG support team last Thursday.  We can't process the target data.  

Also Michelle from SBG noticed the issue too.  tried to run the data this morning , but the issue still has NOT been solved.

**Comment by jharenza** [comment]
@zhangb1 @yuankunzhu @HuangXiaoyan0106 - looks like we now have TARGET NBL and AML access so we can proceed with that RNA-Seq harmonization via linking from the GDC. I suggest using [v6 histologies file](s3://kf-openaccess-us-east-1-prd-pbta/open-targets/v6/histologies.tsv) for sample overlap.

**Comment by zhangb1** [comment]
> @zhangb1 @yuankunzhu @HuangXiaoyan0106 - looks like we now all TARGET access, so we can proceed with that RNA-Seq harmonization via linking from the GDC. I suggest using v6 histologies file: s3://kf-openaccess-us-east-1-prd-pbta/open-targets/v6/histologies.tsv for sample overlap.

@jharenza OKay. We are not NOT using the data which uploaded from the CHOP server ?  just to confirm.

**Comment by jharenza** [comment]
Correct - no need now for the RNA!

**Comment by zhangb1** [comment]
@jharenza  just checked all the query data from data browser and compare to the v6 histology file:

![image](https://user-images.githubusercontent.com/14929845/124791674-45e96700-df1a-11eb-9a54-cb588b9a6bbc.png)

there are 1329 overlaps, we will go to process those samples.  cc @bmennis

**Comment by jharenza** [comment]
ok great, sounds good - thank you! can you provide the overlap IDs here?

**Comment by zhangb1** [comment]
[overlap_samples.txt](https://github.com/PediatricOpenTargets/ticket-tracker/files/6779519/overlap_samples.txt)
 The overlap samples

**Comment by bmennis** [comment]
I am working on running the RNAseq workflow for the TARGET samples in the RNAseq project. I am using the v6 histologies file to inform for drafting tasks as to the stranded information for each sample. It looks like for the samples there are 4 different types of strandedness in the histologies file including:
```
stranded
poly-A
poly-A stranded
NA
```

I ran the tool infer experiment in the project on two samples from each type to get an idea on if the strandedness for the samples in those types are reverse, forward or unstranded which are entered into our workflow as rf-stranded, fr-stranded, and default respectively. It looks like the stranded samples are reverse, the poly-A are unstranded, poly-A stranded are reverse, and the NA are also reverse.

I was a bit surprised at the results from the NA samples so I decided to run all of the NA information samples through the tool. There were 130 samples ran, all with reverse stranded results except 4 samples which appear to be unstranded and the results are here:
```
Aliquot ID                      Reads1 Fraction  Reads2 Fraction
TARGET-15-SJMPAL011912-09A-01R  0.3896  0.5927
TARGET-15-SJMPAL011913-09A-01R  0.4137  0.5560
TARGET-15-SJMPAL022667-09A-01R  0.3668  0.5957
TARGET-15-SJMPAL011914-09A-01R  0.3501  0.6139
```

I will draft up all NA samples as revserve or rf-stranded except these 4 samples which I will draft as default.

**Comment by jharenza** [comment]
thanks @bmennis - can you also create a table of these results by the aliquot ID and we can update the histologies file accordingly in #92  cc @kgaonkar6

**Comment by bmennis** [comment]
RNAseq analysis of the TARGET samples is complete with metadata patched to the outputs. For reference the files can be found in the Cavatica project here:
https://cavatica.sbgenomics.com/u/d3b-bixu-ops/open-target-target-rnaseq/files/#q

**Comment by zhangb1** [comment]
this should be consider as done ,close the ticket
