### ISSUE TITLE
Updated analysis: Create R Shiny demo for TPM plots

### ISSUE THREAD

**Issue by jharenza** [PediatricOpenTargets/ticket-tracker#90]
#### What analysis module should be updated and why?
TPM plots per #38 

#### What changes need to be made? Please provide enough detail for another participant to make the update.
Create a Shiny app to visualize TPM plots 

#### What input data should be used? Which data were used in the version being updated?
same as in #38

#### When do you expect the revised analysis will be completed?
For demo Monday 7/12

#### Who will complete the updated analysis?
@komalsrathi

**Comment by komalsrathi** [comment]
App link: https://reslndbhidam01.research.chop.edu/OpenPedCan-exprs/ requires VPN.

**Comment by jharenza** [comment]
Repo: https://github.com/PediatricOpenTargets/OpenPedCan-exprs-shinyapp
