### ISSUE TITLE
data release v7

### ISSUE THREAD

**Issue by jharenza** [PediatricOpenTargets/ticket-tracker#92]
#### What data file(s) does this issue pertain to?
List of updates for v7

#### What release are you using?

v6

##### Update data files
- [x] #100 
- [x] Merge Consensus annotated CNV + CNVKit annotated WXS only samples as a new data file
- [x] Merge seg files cnv-consensus.seg.gz + cnv-cnvkit.seg.gz as new data file
- [x] #102
- [x] #101
- [x] #126 
- [x] Merge GTEx TPM and expected_count to PBTA+GMKF+TARGET merged files 
- [x] #88 
- [x] #117 
- [ ] <s>#116 </s> save for v8
- [x] #125 

##### Update histologies.tsv add PR with updates in https://github.com/d3b-center/D3b-codes
- [x] #85
- [x] #104 
- [x] #106
- [x] #109 
- [x] #121 
- [x] We should remove all TARGET RNA samples not included within the GDC overlap per [this ticket]
(https://github.com/PediatricOpenTargets/ticket-tracker/issues/9#issuecomment-875852665) so that we aren't inadvertently choosing independent samples which are not in our sequencing files.
- [x] Generate md5sum

**Comment by kgaonkar6** [comment]
For [transcriptomic-dimension-reduction](https://github.com/AlexsLemonade/OpenPBTA-analysis/blob/master/analyses/transcriptomic-dimension-reduction/01-dimension-reduction.sh)  we will need the following files should we add this to v7?

```
gene-expression-rsem-fpkm.rds
gene-expression-kallisto.rds
```

**Comment by jharenza** [comment]
> For [transcriptomic-dimension-reduction](https://github.com/AlexsLemonade/OpenPBTA-analysis/blob/master/analyses/transcriptomic-dimension-reduction/01-dimension-reduction.sh) we will need the following files should we add this to v7? Or should we just do tpm only?
> 
> ```
> gene-expression-rsem-fpkm.rds
> gene-expression-kallisto.rds
> ```

is this only for the BRAF mutant clustering of HGGs to determine LGG status? If so, I think we can maybe omit that code for the subtyping?

**Comment by kgaonkar6** [comment]
It's only for the BRAF mutant clustering, I'm ok to remove it from subtyping 👍

**Comment by jharenza** [comment]
I updated the release notes for the EFO/MONDO and uberon files, so you can update based on what is uploaded now to s3.

**Comment by jharenza** [comment]
closing with [PR 61](https://github.com/PediatricOpenTargets/OpenPedCan-analysis/pull/61)
