### ISSUE TITLE
Updated analysis: fusion-summary for OT subtyping

### ISSUE THREAD

**Issue by kgaonkar6** [PediatricOpenTargets/ticket-tracker#94]
#### What analysis module should be updated and why?
Update the `fusion-summary` using the latest `fusion-putative-oncogenic.tsv` and `histologies.tsv`

#### What changes need to be made? Please provide enough detail for another participant to make the update.

- Change each occurrence of`pbta-fusion-putative-oncogenic.tsv` to `fusion-putative-oncogenic.tsv` 
- Change each occurrence of`pbta-histologies.tsv` to `histologies.tsv` 

#### What input data should be used? Which data were used in the version being updated?
v6
fusion-putative-oncogenic.tsv
histologies.tsv

#### When do you expect the revised analysis will be completed?
1 day

**Comment by jharenza** [comment]
closed with https://github.com/PediatricOpenTargets/OpenPedCan-analysis/pull/79
