### ISSUE TITLE
Updated analysis: tp53_nf1_score for OT subtyping

### ISSUE THREAD

**Issue by kgaonkar6** [PediatricOpenTargets/ticket-tracker#97]
#### What analysis module should be updated and why?
Update `tp53_nf1_score` to use OT filename updates. 

#### What changes need to be made? Please provide enough detail for another participant to make the update.
 - Replace occurrence of `pbta-snv-consensus-mutation.maf.tsv.gz` to `snv-consensus-plus-hotspots.maf.tsv.gz` .
 - Currently the scripts are run separately for `pbta-gene-expression-rsem-fpkm-collapsed.stranded.rds` and `pbta-gene-expression-rsem-fpkm-collapsed.polya.rds` please use the `gene-expression-rsem-tpm-collapsed.rds` file and be sure to subset the rds files to use Kids_First_Biospecimen_ID that belong to `PBTA` and `GMKF` cohorts within the code. 
 - Change each occurrence of`pbta-histologies.tsv` to `histologies.tsv

#### What input data should be used? Which data were used in the version being updated?
v6
snv-consensus-plus-hotspots.maf.tsv.gz
gene-expression-rsem-tpm-collapsed.rds

#### When do you expect the revised analysis will be completed?
2-3 days

**Comment by runjin326** [comment]
@kgaonkar6, just want to clarify, for this module update, do we just want to update classifier scores file (e.g., `pbta-gene-expression-rsem-fpkm-collapsed.polya_classifier_scores.tsv`) to be cohort specific (i.e., make it to `gene-expression-rsem-fpkm-collapsed.GMKF_classifier_scores.tsv`) or do we want to update all files? (e.g., `loss_overlap_domains_tp53.tsv`, `TP53_NF1_snv_alteration.tsv` etc.)

**Comment by kgaonkar6** [comment]
We are not doing cohort level analysis here so we don't need to rename the files as *GMKF* etc.

But the rnaseq input files will change from `pbta-gene-expression-rsem-fpkm-collapsed.stranded.rds` and `pbta-gene-expression-rsem-fpkm-collapsed.polya.rds to `gene-expression-rsem-tpm-collapsed.rds`

Additionally,
- Kids_First_Biospecimen_ID that belong to PBTA and GMKF cohorts within the code, or maybe a generic logic to not include GTEX samples would be more generalizable.
- I do think however that polya and stranded rnaseq need to be separated while applying classifier in `01-apply-classifier.py` since the distribution of gene expression in stranded and polya , what do you think?

**Comment by runjin326** [comment]
That makes sense! So what you meant for subsetting for GMKF and PBTA is just to make sure not to include GTEx files right? And yes I agree with separating polyA and stranded since they would likely have different profiles.

**Comment by runjin326** [comment]
Closing with PR84( https://github.com/PediatricOpenTargets/OpenPedCan-analysis/pull/84 ) and PR94(https://github.com/PediatricOpenTargets/OpenPedCan-analysis/pull/94) merged
