### ISSUE TITLE
Create a Cavatica workflow to process DESeq

### ISSUE THREAD

**Issue by sangeetashukla** [PediatricOpenTargets/ticket-tracker#99]
#### What analysis module should be updated and why?
Use the DESeq module and convert that into a Cavatica workflow so that DESeq analysis can be performed using Cavatica instead of the cluster.

#### What changes need to be made? Please provide enough detail for another participant to make the update.

- Use the existing R code and encapsulate it in a Cavatica app
- Include instructions in module README to enable user to access module scripts and publish a Cavatica app for data analysis

#### What input data should be used? Which data were used in the version being updated?
histology.tsv, collapsed gene counts, uberon codes and EFO MONDO codes should be used as input

#### When do you expect the revised analysis will be completed?
2 weeks

#### Who will complete the updated analysis?
@sangeetashukla @yuankunzhu @zhangb1

**Comment by jharenza** [comment]
@sangeetashukla and @afarrel - the cavatica project for release data has been made and I will add you now since it is not yet public: https://github.com/PediatricOpenTargets/ticket-tracker/issues/127#issuecomment-886898179

**Comment by sangeetashukla** [comment]
[This](https://cavatica.sbgenomics.com/u/shuklas1/deseq-trial1/apps/#q?archived=false) is the link to the app on Cavatica
I am working with @migbro  to make a few updates to it to enable it to run

**Comment by migbro** [comment]
1) Replicate hist i and gtex i slurm array submission (from @afarrel ) as a scatter tool in cavatica - expression tool or simple shell - save output as array of int?
2) Update cavatica tool to pull R script from git instead, then run - @sickler-alex can help here. Scatter in input hist and gtex array
3) Tool to collate results

**Comment by sangeetashukla** [comment]
Tested the app to work with v10 data
Added a step to convert the merged TSV results into RDS

Note: The TSV to RDS conversion step kills the job with no error message, possibly indicating that the resource allocation may need to be changed. I have reached out to Cavatica Support team regarding this.
Will update the ticket as I hear from them.

**Comment by sangeetashukla** [comment]
Functional Cavatica workflow for conducting differential expression analysis of tumor and normal tissues is available [here](https://cavatica.sbgenomics.com/u/shuklas1/tumor-normal-differential-expression/).
This project contains a workflow app with multiple tools, each of which replicate the task performed in the [tumor-normal-differential-expression module](https://github.com/sangeetashukla/OpenPedCan-analysis/tree/create-tn-deseq/analyses) in the repo.

The app generates three output files, .tsv, .jsonl, and .rds; which contain the results of expression analysis for all combinations of cancer group and tissue histology.

**Comment by sangeetashukla** [comment]
@afarrel @chinwallaa Here is the link to the Cavatica project for DESeq wowkflow where I have also included a brief write-up. Please go through the write-up and feel free to play with the workflow and share any feedback.
